// SPDX-License-Identifier: Apache-2.0
package store

import (
	"bytes"
	"context"
	"database/sql"
	"embed"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/delinoio/oss/cmds/delidev-cli/internal/domain"
)

// These are fixed historical schemas, never generated by the test under test.
//
//go:embed testdata/schema/*.sql
var historicalSchemas embed.FS

// historicalSchema places the test's seeded records into a frozen historical
// schema. It discovers common columns, so future tables never require edits to
// old tests or expanding lists of DROP statements. This is test-only conversion;
// production migrations must never infer an unknown layout this way.
func historicalSchema(db *sql.DB, version string) (sql.Result, error) {
	raw, err := historicalSchemas.ReadFile("testdata/schema/" + version + ".sql")
	if err != nil {
		return nil, err
	}
	ctx := context.Background()
	conn, err := db.Conn(ctx)
	if err != nil {
		return nil, err
	}
	defer conn.Close()
	if _, err = conn.ExecContext(ctx, "PRAGMA foreign_keys=OFF"); err != nil {
		return nil, err
	}
	defer conn.ExecContext(ctx, "PRAGMA foreign_keys=ON")
	tx, err := conn.BeginTx(ctx, nil)
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()
	names := func(query string) ([]string, error) {
		rows, err := tx.QueryContext(ctx, query)
		if err != nil {
			return nil, err
		}
		defer rows.Close()
		var result []string
		for rows.Next() {
			var name string
			if err = rows.Scan(&name); err != nil {
				return nil, err
			}
			result = append(result, name)
		}
		return result, rows.Err()
	}
	quote := func(s string) string { return `"` + strings.ReplaceAll(s, `"`, `""`) + `"` }
	tables, err := names(`SELECT name FROM pragma_table_list WHERE schema='main' AND type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name`)
	if err != nil {
		return nil, err
	}
	saved := map[string][]string{}
	for _, table := range tables {
		columns, err := names(`SELECT name FROM pragma_table_info('` + strings.ReplaceAll(table, "'", "''") + `')`)
		if err != nil {
			return nil, err
		}
		saved[table] = columns
		if _, err = tx.ExecContext(ctx, `CREATE TEMP TABLE `+quote("retained_"+table)+` AS SELECT * FROM main.`+quote(table)); err != nil {
			return nil, err
		}
		// These frozen schemas predate native accounting. Retained user records
		// must not carry a future layout marker into a reconstructed old fixture.
		if table == "metadata" {
			if _, err = tx.ExecContext(ctx, "DELETE FROM temp.retained_metadata WHERE key IN ('native_accounting_layout','subscription_identity_layout','subscription_notification_layout','account_oauth_layout','provider_presets_layout','account_oauth_credentials_layout')"); err != nil {
				return nil, err
			}
		}
	}
	// Remove triggers first, then virtual tables (which own shadow tables), then
	// ordinary tables. All recreation below comes from the historical SQL file.
	for _, kind := range []string{"trigger", "view"} {
		objects, err := names("SELECT name FROM sqlite_master WHERE type='" + kind + "' AND name NOT LIKE 'sqlite_%'")
		if err != nil {
			return nil, err
		}
		for _, name := range objects {
			if _, err = tx.ExecContext(ctx, "DROP "+kind+" "+quote(name)); err != nil {
				return nil, err
			}
		}
	}
	virtual, err := names(`SELECT name FROM pragma_table_list WHERE schema='main' AND type='virtual'`)
	if err != nil {
		return nil, err
	}
	for _, table := range append(virtual, tables...) {
		if _, err = tx.ExecContext(ctx, `DROP TABLE `+quote(table)); err != nil {
			return nil, err
		}
	}
	if _, err = tx.ExecContext(ctx, string(raw)); err != nil {
		return nil, err
	}
	current, err := names(`SELECT name FROM pragma_table_list WHERE schema='main' AND type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name`)
	if err != nil {
		return nil, err
	}
	for _, table := range current {
		prior, ok := saved[table]
		if !ok {
			continue
		}
		columns, err := names(`SELECT name FROM pragma_table_info('` + strings.ReplaceAll(table, "'", "''") + `')`)
		if err != nil {
			return nil, err
		}
		var common []string
		for _, col := range columns {
			for _, old := range prior {
				if col == old {
					common = append(common, quote(col))
					break
				}
			}
		}
		if len(common) == 0 {
			continue
		}
		projection := strings.Join(common, ",")
		if table == "metadata" && (version == "025" || version == "026" || version == "027") {
			if _, err = tx.ExecContext(ctx, "DELETE FROM main.metadata WHERE key<>'native_accounting_layout'"); err != nil {
				return nil, err
			}
		}
		if _, err = tx.ExecContext(ctx, `INSERT INTO main.`+quote(table)+` (`+projection+`) SELECT `+projection+` FROM temp.`+quote("retained_"+table)); err != nil {
			return nil, fmt.Errorf("restore fixture table %s: %w", table, err)
		}
	}
	for _, table := range tables {
		if _, err = tx.ExecContext(ctx, `DROP TABLE temp.`+quote("retained_"+table)); err != nil {
			return nil, err
		}
	}
	return nil, tx.Commit()
}

// Frozen historical schemas remain recovery evidence, never upgrade inputs.
func TestFrozenHistoricalSchemasRejectWithoutChangingOriginalFiles(t *testing.T) {
	entries, err := historicalSchemas.ReadDir("testdata/schema")
	if err != nil {
		t.Fatal(err)
	}
	for _, entry := range entries {
		t.Run(entry.Name(), func(t *testing.T) {
			root := t.TempDir()
			if err := os.Chmod(root, 0700); err != nil {
				t.Fatal(err)
			}
			path := filepath.Join(root, "state.sqlite")
			db, err := sql.Open("sqlite", path)
			if err != nil {
				t.Fatal(err)
			}
			raw, err := historicalSchemas.ReadFile("testdata/schema/" + entry.Name())
			if err != nil {
				t.Fatal(err)
			}
			if _, err = db.Exec(string(raw)); err != nil {
				t.Fatal(err)
			}
			if err = db.Close(); err != nil {
				t.Fatal(err)
			}
			if err = os.Chmod(path, 0600); err != nil {
				t.Fatal(err)
			}
			before, err := os.ReadFile(path)
			if err != nil {
				t.Fatal(err)
			}
			for range 2 {
				opened, err := Open(context.Background(), root)
				if err == nil {
					opened.Close()
					t.Fatal("historical schema adopted")
				}
				if domain.SafeError(err).Code != domain.RecoveryRequired {
					t.Fatal(err)
				}
				after, err := os.ReadFile(path)
				if err != nil || !bytes.Equal(before, after) {
					t.Fatal("original bytes changed", err)
				}
				for _, suffix := range []string{"-wal", "-shm", "-journal"} {
					if _, err = os.Lstat(path + suffix); !os.IsNotExist(err) {
						t.Fatal("sidecar created", suffix, err)
					}
				}
			}
		})
	}
}
