[package]
name = "materialized_artifact"
version = "0.0.0"
edition.workspace = true
license = "MIT"
publish = false
rust-version.workspace = true

[dependencies]
materialized_artifact_macros = { workspace = true }
tempfile = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[lints]
workspace = true

[lib]
doctest = false
test = false
