// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: devhud/v1/account.proto

package devhudv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountState int32

const (
	AccountState_ACCOUNT_STATE_UNSPECIFIED      AccountState = 0
	AccountState_ACCOUNT_STATE_ACTIVE           AccountState = 1
	AccountState_ACCOUNT_STATE_PENDING_DELETION AccountState = 2
)

// Enum value maps for AccountState.
var (
	AccountState_name = map[int32]string{
		0: "ACCOUNT_STATE_UNSPECIFIED",
		1: "ACCOUNT_STATE_ACTIVE",
		2: "ACCOUNT_STATE_PENDING_DELETION",
	}
	AccountState_value = map[string]int32{
		"ACCOUNT_STATE_UNSPECIFIED":      0,
		"ACCOUNT_STATE_ACTIVE":           1,
		"ACCOUNT_STATE_PENDING_DELETION": 2,
	}
)

func (x AccountState) Enum() *AccountState {
	p := new(AccountState)
	*p = x
	return p
}

func (x AccountState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountState) Descriptor() protoreflect.EnumDescriptor {
	return file_devhud_v1_account_proto_enumTypes[0].Descriptor()
}

func (AccountState) Type() protoreflect.EnumType {
	return &file_devhud_v1_account_proto_enumTypes[0]
}

func (x AccountState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountState.Descriptor instead.
func (AccountState) EnumDescriptor() ([]byte, []int) {
	return file_devhud_v1_account_proto_rawDescGZIP(), []int{0}
}

type AccountPreconditionReason int32

const (
	AccountPreconditionReason_ACCOUNT_PRECONDITION_REASON_UNSPECIFIED             AccountPreconditionReason = 0
	AccountPreconditionReason_ACCOUNT_PRECONDITION_REASON_NOT_PENDING_DELETION    AccountPreconditionReason = 1
	AccountPreconditionReason_ACCOUNT_PRECONDITION_REASON_RECOVERY_WINDOW_EXPIRED AccountPreconditionReason = 2
	AccountPreconditionReason_ACCOUNT_PRECONDITION_REASON_PURGE_CLAIMED           AccountPreconditionReason = 3
)

// Enum value maps for AccountPreconditionReason.
var (
	AccountPreconditionReason_name = map[int32]string{
		0: "ACCOUNT_PRECONDITION_REASON_UNSPECIFIED",
		1: "ACCOUNT_PRECONDITION_REASON_NOT_PENDING_DELETION",
		2: "ACCOUNT_PRECONDITION_REASON_RECOVERY_WINDOW_EXPIRED",
		3: "ACCOUNT_PRECONDITION_REASON_PURGE_CLAIMED",
	}
	AccountPreconditionReason_value = map[string]int32{
		"ACCOUNT_PRECONDITION_REASON_UNSPECIFIED":             0,
		"ACCOUNT_PRECONDITION_REASON_NOT_PENDING_DELETION":    1,
		"ACCOUNT_PRECONDITION_REASON_RECOVERY_WINDOW_EXPIRED": 2,
		"ACCOUNT_PRECONDITION_REASON_PURGE_CLAIMED":           3,
	}
)

func (x AccountPreconditionReason) Enum() *AccountPreconditionReason {
	p := new(AccountPreconditionReason)
	*p = x
	return p
}

func (x AccountPreconditionReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountPreconditionReason) Descriptor() protoreflect.EnumDescriptor {
	return file_devhud_v1_account_proto_enumTypes[1].Descriptor()
}

func (AccountPreconditionReason) Type() protoreflect.EnumType {
	return &file_devhud_v1_account_proto_enumTypes[1]
}

func (x AccountPreconditionReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountPreconditionReason.Descriptor instead.
func (AccountPreconditionReason) EnumDescriptor() ([]byte, []int) {
	return file_devhud_v1_account_proto_rawDescGZIP(), []int{1}
}

type AccountPreconditionDetail struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Reason        AccountPreconditionReason `protobuf:"varint,1,opt,name=reason,proto3,enum=devhud.v1.AccountPreconditionReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountPreconditionDetail) Reset() {
	*x = AccountPreconditionDetail{}
	mi := &file_devhud_v1_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountPreconditionDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountPreconditionDetail) ProtoMessage() {}

func (x *AccountPreconditionDetail) ProtoReflect() protoreflect.Message {
	mi := &file_devhud_v1_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountPreconditionDetail.ProtoReflect.Descriptor instead.
func (*AccountPreconditionDetail) Descriptor() ([]byte, []int) {
	return file_devhud_v1_account_proto_rawDescGZIP(), []int{0}
}

func (x *AccountPreconditionDetail) GetReason() AccountPreconditionReason {
	if x != nil {
		return x.Reason
	}
	return AccountPreconditionReason_ACCOUNT_PRECONDITION_REASON_UNSPECIFIED
}

type Account struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	UserId                  *UuidV7                `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LogtoSubject            string                 `protobuf:"bytes,2,opt,name=logto_subject,json=logtoSubject,proto3" json:"logto_subject,omitempty"`
	DisplayName             string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Email                   string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	State                   AccountState           `protobuf:"varint,5,opt,name=state,proto3,enum=devhud.v1.AccountState" json:"state,omitempty"`
	AdministrativelyBlocked bool                   `protobuf:"varint,6,opt,name=administratively_blocked,json=administrativelyBlocked,proto3" json:"administratively_blocked,omitempty"`
	CreatedAt               *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DeletionRequestedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=deletion_requested_at,json=deletionRequestedAt,proto3" json:"deletion_requested_at,omitempty"`
	RecoverableUntil        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=recoverable_until,json=recoverableUntil,proto3" json:"recoverable_until,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_devhud_v1_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_devhud_v1_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_devhud_v1_account_proto_rawDescGZIP(), []int{1}
}

func (x *Account) GetUserId() *UuidV7 {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *Account) GetLogtoSubject() string {
	if x != nil {
		return x.LogtoSubject
	}
	return ""
}

func (x *Account) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Account) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Account) GetState() AccountState {
	if x != nil {
		return x.State
	}
	return AccountState_ACCOUNT_STATE_UNSPECIFIED
}

func (x *Account) GetAdministrativelyBlocked() bool {
	if x != nil {
		return x.AdministrativelyBlocked
	}
	return false
}

func (x *Account) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Account) GetDeletionRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletionRequestedAt
	}
	return nil
}

func (x *Account) GetRecoverableUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.RecoverableUntil
	}
	return nil
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_devhud_v1_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devhud_v1_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_devhud_v1_account_proto_rawDescGZIP(), []int{2}
}

type GetAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_devhud_v1_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devhud_v1_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_devhud_v1_account_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type DeleteAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountRequest) Reset() {
	*x = DeleteAccountRequest{}
	mi := &file_devhud_v1_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRequest) ProtoMessage() {}

func (x *DeleteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devhud_v1_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return file_devhud_v1_account_proto_rawDescGZIP(), []int{4}
}

type DeleteAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountResponse) Reset() {
	*x = DeleteAccountResponse{}
	mi := &file_devhud_v1_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountResponse) ProtoMessage() {}

func (x *DeleteAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devhud_v1_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return file_devhud_v1_account_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type RestoreAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreAccountRequest) Reset() {
	*x = RestoreAccountRequest{}
	mi := &file_devhud_v1_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreAccountRequest) ProtoMessage() {}

func (x *RestoreAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devhud_v1_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreAccountRequest.ProtoReflect.Descriptor instead.
func (*RestoreAccountRequest) Descriptor() ([]byte, []int) {
	return file_devhud_v1_account_proto_rawDescGZIP(), []int{6}
}

type RestoreAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreAccountResponse) Reset() {
	*x = RestoreAccountResponse{}
	mi := &file_devhud_v1_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreAccountResponse) ProtoMessage() {}

func (x *RestoreAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devhud_v1_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreAccountResponse.ProtoReflect.Descriptor instead.
func (*RestoreAccountResponse) Descriptor() ([]byte, []int) {
	return file_devhud_v1_account_proto_rawDescGZIP(), []int{7}
}

func (x *RestoreAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

var File_devhud_v1_account_proto protoreflect.FileDescriptor

const file_devhud_v1_account_proto_rawDesc = "" +
	"\n" +
	"\x17devhud/v1/account.proto\x12\tdevhud.v1\x1a\x16devhud/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"Y\n" +
	"\x19AccountPreconditionDetail\x12<\n" +
	"\x06reason\x18\x01 \x01(\x0e2$.devhud.v1.AccountPreconditionReasonR\x06reason\"\xd1\x03\n" +
	"\aAccount\x12*\n" +
	"\auser_id\x18\x01 \x01(\v2\x11.devhud.v1.UuidV7R\x06userId\x12#\n" +
	"\rlogto_subject\x18\x02 \x01(\tR\flogtoSubject\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12-\n" +
	"\x05state\x18\x05 \x01(\x0e2\x17.devhud.v1.AccountStateR\x05state\x129\n" +
	"\x18administratively_blocked\x18\x06 \x01(\bR\x17administrativelyBlocked\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12N\n" +
	"\x15deletion_requested_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x13deletionRequestedAt\x12G\n" +
	"\x11recoverable_until\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x10recoverableUntil\"\x13\n" +
	"\x11GetAccountRequest\"B\n" +
	"\x12GetAccountResponse\x12,\n" +
	"\aaccount\x18\x01 \x01(\v2\x12.devhud.v1.AccountR\aaccount\"\x16\n" +
	"\x14DeleteAccountRequest\"E\n" +
	"\x15DeleteAccountResponse\x12,\n" +
	"\aaccount\x18\x01 \x01(\v2\x12.devhud.v1.AccountR\aaccount\"\x17\n" +
	"\x15RestoreAccountRequest\"F\n" +
	"\x16RestoreAccountResponse\x12,\n" +
	"\aaccount\x18\x01 \x01(\v2\x12.devhud.v1.AccountR\aaccount*k\n" +
	"\fAccountState\x12\x1d\n" +
	"\x19ACCOUNT_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ACCOUNT_STATE_ACTIVE\x10\x01\x12\"\n" +
	"\x1eACCOUNT_STATE_PENDING_DELETION\x10\x02*\xe6\x01\n" +
	"\x19AccountPreconditionReason\x12+\n" +
	"'ACCOUNT_PRECONDITION_REASON_UNSPECIFIED\x10\x00\x124\n" +
	"0ACCOUNT_PRECONDITION_REASON_NOT_PENDING_DELETION\x10\x01\x127\n" +
	"3ACCOUNT_PRECONDITION_REASON_RECOVERY_WINDOW_EXPIRED\x10\x02\x12-\n" +
	")ACCOUNT_PRECONDITION_REASON_PURGE_CLAIMED\x10\x032\x86\x02\n" +
	"\x0eAccountService\x12I\n" +
	"\n" +
	"GetAccount\x12\x1c.devhud.v1.GetAccountRequest\x1a\x1d.devhud.v1.GetAccountResponse\x12R\n" +
	"\rDeleteAccount\x12\x1f.devhud.v1.DeleteAccountRequest\x1a .devhud.v1.DeleteAccountResponse\x12U\n" +
	"\x0eRestoreAccount\x12 .devhud.v1.RestoreAccountRequest\x1a!.devhud.v1.RestoreAccountResponseB3Z1github.com/delinoio/oss/protos/devhud/v1;devhudv1b\x06proto3"

var (
	file_devhud_v1_account_proto_rawDescOnce sync.Once
	file_devhud_v1_account_proto_rawDescData []byte
)

func file_devhud_v1_account_proto_rawDescGZIP() []byte {
	file_devhud_v1_account_proto_rawDescOnce.Do(func() {
		file_devhud_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_devhud_v1_account_proto_rawDesc), len(file_devhud_v1_account_proto_rawDesc)))
	})
	return file_devhud_v1_account_proto_rawDescData
}

var file_devhud_v1_account_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_devhud_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_devhud_v1_account_proto_goTypes = []any{
	(AccountState)(0),                 // 0: devhud.v1.AccountState
	(AccountPreconditionReason)(0),    // 1: devhud.v1.AccountPreconditionReason
	(*AccountPreconditionDetail)(nil), // 2: devhud.v1.AccountPreconditionDetail
	(*Account)(nil),                   // 3: devhud.v1.Account
	(*GetAccountRequest)(nil),         // 4: devhud.v1.GetAccountRequest
	(*GetAccountResponse)(nil),        // 5: devhud.v1.GetAccountResponse
	(*DeleteAccountRequest)(nil),      // 6: devhud.v1.DeleteAccountRequest
	(*DeleteAccountResponse)(nil),     // 7: devhud.v1.DeleteAccountResponse
	(*RestoreAccountRequest)(nil),     // 8: devhud.v1.RestoreAccountRequest
	(*RestoreAccountResponse)(nil),    // 9: devhud.v1.RestoreAccountResponse
	(*UuidV7)(nil),                    // 10: devhud.v1.UuidV7
	(*timestamppb.Timestamp)(nil),     // 11: google.protobuf.Timestamp
}
var file_devhud_v1_account_proto_depIdxs = []int32{
	1,  // 0: devhud.v1.AccountPreconditionDetail.reason:type_name -> devhud.v1.AccountPreconditionReason
	10, // 1: devhud.v1.Account.user_id:type_name -> devhud.v1.UuidV7
	0,  // 2: devhud.v1.Account.state:type_name -> devhud.v1.AccountState
	11, // 3: devhud.v1.Account.created_at:type_name -> google.protobuf.Timestamp
	11, // 4: devhud.v1.Account.deletion_requested_at:type_name -> google.protobuf.Timestamp
	11, // 5: devhud.v1.Account.recoverable_until:type_name -> google.protobuf.Timestamp
	3,  // 6: devhud.v1.GetAccountResponse.account:type_name -> devhud.v1.Account
	3,  // 7: devhud.v1.DeleteAccountResponse.account:type_name -> devhud.v1.Account
	3,  // 8: devhud.v1.RestoreAccountResponse.account:type_name -> devhud.v1.Account
	4,  // 9: devhud.v1.AccountService.GetAccount:input_type -> devhud.v1.GetAccountRequest
	6,  // 10: devhud.v1.AccountService.DeleteAccount:input_type -> devhud.v1.DeleteAccountRequest
	8,  // 11: devhud.v1.AccountService.RestoreAccount:input_type -> devhud.v1.RestoreAccountRequest
	5,  // 12: devhud.v1.AccountService.GetAccount:output_type -> devhud.v1.GetAccountResponse
	7,  // 13: devhud.v1.AccountService.DeleteAccount:output_type -> devhud.v1.DeleteAccountResponse
	9,  // 14: devhud.v1.AccountService.RestoreAccount:output_type -> devhud.v1.RestoreAccountResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_devhud_v1_account_proto_init() }
func file_devhud_v1_account_proto_init() {
	if File_devhud_v1_account_proto != nil {
		return
	}
	file_devhud_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_devhud_v1_account_proto_rawDesc), len(file_devhud_v1_account_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_devhud_v1_account_proto_goTypes,
		DependencyIndexes: file_devhud_v1_account_proto_depIdxs,
		EnumInfos:         file_devhud_v1_account_proto_enumTypes,
		MessageInfos:      file_devhud_v1_account_proto_msgTypes,
	}.Build()
	File_devhud_v1_account_proto = out.File
	file_devhud_v1_account_proto_goTypes = nil
	file_devhud_v1_account_proto_depIdxs = nil
}
