[package]
name = "clibox"
version = "0.2.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Delino"]
description = "A native CLI distributed through native packages and npm"
readme = "README.md"
repository = "https://github.com/delinoio/oss"
publish = false

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
clibox-config = { path = "../clibox-config" }
clibox-system = { path = "../clibox-system" }
clibox-transform = { path = "../clibox-transform" }
clibox-wait = { path = "../clibox-wait" }

[dev-dependencies]
base64 = "0.22.1"
clibox-system = { path = "../clibox-system", features = ["test"] }
sha2 = "0.10"
rustls = { version = "0.23.36", default-features = false, features = ["ring", "std", "tls12"] }
serde_json = "1.0.149"
tempfile = "3.25.0"
socket2 = "0.6.2"
rcgen = "0.14"

[target.'cfg(unix)'.dev-dependencies]
libc = "0.2.182"

[target.'cfg(windows)'.dev-dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_System_Console", "Win32_System_Threading", "Win32_Storage_FileSystem", "Win32_Security", "Win32_Security_Authorization"] }
