// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deletion.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAccountDevices = `-- name: DeleteAccountDevices :exec
DELETE FROM deck_device_registrations
WHERE account_id = $1
`

func (q *Queries) DeleteAccountDevices(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccountDevices, accountID)
	return err
}

const deleteDeckAccount = `-- name: DeleteDeckAccount :exec
DELETE FROM deck_accounts WHERE account_id = $1
`

func (q *Queries) DeleteDeckAccount(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeckAccount, accountID)
	return err
}

const deleteOrganizationConnection = `-- name: DeleteOrganizationConnection :exec
DELETE FROM deck_connections
WHERE owner_scope = 2 AND owner_id = $1
`

func (q *Queries) DeleteOrganizationConnection(ctx context.Context, organizationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganizationConnection, organizationID)
	return err
}

const deleteOrganizationFeatureData = `-- name: DeleteOrganizationFeatureData :exec
DELETE FROM deck_views
WHERE owner_scope = 2 AND owner_organization_id = $1
`

func (q *Queries) DeleteOrganizationFeatureData(ctx context.Context, organizationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganizationFeatureData, organizationID)
	return err
}

const deleteOrganizationMemberships = `-- name: DeleteOrganizationMemberships :exec
DELETE FROM deck_organization_memberships
WHERE organization_id = $1
`

func (q *Queries) DeleteOrganizationMemberships(ctx context.Context, organizationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganizationMemberships, organizationID)
	return err
}

const deleteOrganizationTeamMemberships = `-- name: DeleteOrganizationTeamMemberships :exec
DELETE FROM deck_team_memberships
WHERE organization_id = $1
`

func (q *Queries) DeleteOrganizationTeamMemberships(ctx context.Context, organizationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganizationTeamMemberships, organizationID)
	return err
}

const deletePersonalConnection = `-- name: DeletePersonalConnection :exec
DELETE FROM deck_connections
WHERE owner_scope = 1 AND owner_id = $1
`

func (q *Queries) DeletePersonalConnection(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePersonalConnection, accountID)
	return err
}

const deletePersonalFeatureData = `-- name: DeletePersonalFeatureData :exec
DELETE FROM deck_views
WHERE owner_scope = 1 AND owner_account_id = $1
`

func (q *Queries) DeletePersonalFeatureData(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePersonalFeatureData, accountID)
	return err
}

const deleteViewCreateIdempotencyByOwnerHash = `-- name: DeleteViewCreateIdempotencyByOwnerHash :exec
DELETE FROM deck_view_create_idempotency
WHERE owner_hash = $1
`

func (q *Queries) DeleteViewCreateIdempotencyByOwnerHash(ctx context.Context, ownerHash []byte) error {
	_, err := q.db.Exec(ctx, deleteViewCreateIdempotencyByOwnerHash, ownerHash)
	return err
}

const getDeletionJobByReplayKey = `-- name: GetDeletionJobByReplayKey :one
SELECT deletion_job_id, replay_key, target_hash, trigger, state, accepted_at, completed_at FROM deck_deletion_jobs
WHERE replay_key = $1
`

func (q *Queries) GetDeletionJobByReplayKey(ctx context.Context, replayKey pgtype.UUID) (DeckDeletionJob, error) {
	row := q.db.QueryRow(ctx, getDeletionJobByReplayKey, replayKey)
	var i DeckDeletionJob
	err := row.Scan(
		&i.DeletionJobID,
		&i.ReplayKey,
		&i.TargetHash,
		&i.Trigger,
		&i.State,
		&i.AcceptedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertDeletionJob = `-- name: InsertDeletionJob :one
INSERT INTO deck_deletion_jobs (
    deletion_job_id, replay_key, target_hash, trigger, state,
    accepted_at, completed_at
) VALUES (
    $1, $2,
    $3, $4, 3,
    $5, $5
)
RETURNING deletion_job_id, replay_key, target_hash, trigger, state, accepted_at, completed_at
`

type InsertDeletionJobParams struct {
	DeletionJobID pgtype.UUID
	ReplayKey     pgtype.UUID
	TargetHash    []byte
	Trigger       int16
	AcceptedAt    pgtype.Timestamptz
}

func (q *Queries) InsertDeletionJob(ctx context.Context, arg InsertDeletionJobParams) (DeckDeletionJob, error) {
	row := q.db.QueryRow(ctx, insertDeletionJob,
		arg.DeletionJobID,
		arg.ReplayKey,
		arg.TargetHash,
		arg.Trigger,
		arg.AcceptedAt,
	)
	var i DeckDeletionJob
	err := row.Scan(
		&i.DeletionJobID,
		&i.ReplayKey,
		&i.TargetHash,
		&i.Trigger,
		&i.State,
		&i.AcceptedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertOwnerTombstone = `-- name: InsertOwnerTombstone :exec
INSERT INTO deck_owner_tombstones (target_hash, accepted_at)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertOwnerTombstoneParams struct {
	TargetHash []byte
	AcceptedAt pgtype.Timestamptz
}

func (q *Queries) InsertOwnerTombstone(ctx context.Context, arg InsertOwnerTombstoneParams) error {
	_, err := q.db.Exec(ctx, insertOwnerTombstone, arg.TargetHash, arg.AcceptedAt)
	return err
}

const listDeviceRegistrationsForUpdate = `-- name: ListDeviceRegistrationsForUpdate :many
SELECT registration_id, device_id, account_id, platform, display_name_ciphertext, push_ciphertext, detailed_notification_text_enabled, shortcuts_ciphertext, widgets_ciphertext, grant_verifier, revision, lease_expires_at, created_at, updated_at
FROM deck_device_registrations
ORDER BY registration_id
FOR UPDATE
`

func (q *Queries) ListDeviceRegistrationsForUpdate(ctx context.Context) ([]DeckDeviceRegistration, error) {
	rows, err := q.db.Query(ctx, listDeviceRegistrationsForUpdate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeckDeviceRegistration{}
	for rows.Next() {
		var i DeckDeviceRegistration
		if err := rows.Scan(
			&i.RegistrationID,
			&i.DeviceID,
			&i.AccountID,
			&i.Platform,
			&i.DisplayNameCiphertext,
			&i.PushCiphertext,
			&i.DetailedNotificationTextEnabled,
			&i.ShortcutsCiphertext,
			&i.WidgetsCiphertext,
			&i.GrantVerifier,
			&i.Revision,
			&i.LeaseExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationViewIDsForUpdate = `-- name: ListOrganizationViewIDsForUpdate :many
SELECT view_id
FROM deck_views
WHERE owner_scope = 2 AND owner_organization_id = $1
ORDER BY view_id
FOR UPDATE
`

func (q *Queries) ListOrganizationViewIDsForUpdate(ctx context.Context, organizationID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listOrganizationViewIDsForUpdate, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var view_id pgtype.UUID
		if err := rows.Scan(&view_id); err != nil {
			return nil, err
		}
		items = append(items, view_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeviceViewStateAfterDeletion = `-- name: UpdateDeviceViewStateAfterDeletion :exec
UPDATE deck_device_registrations
SET shortcuts_ciphertext = $1,
    widgets_ciphertext = $2,
    revision = revision + 1,
    updated_at = $3
WHERE registration_id = $4
  AND revision = $5
`

type UpdateDeviceViewStateAfterDeletionParams struct {
	ShortcutsCiphertext []byte
	WidgetsCiphertext   []byte
	UpdatedAt           pgtype.Timestamptz
	RegistrationID      pgtype.UUID
	ExpectedRevision    int64
}

func (q *Queries) UpdateDeviceViewStateAfterDeletion(ctx context.Context, arg UpdateDeviceViewStateAfterDeletionParams) error {
	_, err := q.db.Exec(ctx, updateDeviceViewStateAfterDeletion,
		arg.ShortcutsCiphertext,
		arg.WidgetsCiphertext,
		arg.UpdatedAt,
		arg.RegistrationID,
		arg.ExpectedRevision,
	)
	return err
}
