// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDeviceByRegistrationAndAccount = `-- name: DeleteDeviceByRegistrationAndAccount :execrows
DELETE FROM deck_device_registrations
WHERE registration_id = $1
  AND account_id = $2
`

type DeleteDeviceByRegistrationAndAccountParams struct {
	RegistrationID pgtype.UUID
	AccountID      pgtype.UUID
}

func (q *Queries) DeleteDeviceByRegistrationAndAccount(ctx context.Context, arg DeleteDeviceByRegistrationAndAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeviceByRegistrationAndAccount, arg.RegistrationID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDeviceByRegistrationAndGrant = `-- name: DeleteDeviceByRegistrationAndGrant :execrows
DELETE FROM deck_device_registrations AS registration
WHERE registration.registration_id = $1
  AND registration.lease_expires_at > $2
  AND (
      registration.grant_verifier = $3
      OR EXISTS (
          SELECT 1
          FROM deck_device_registration_idempotency AS replay
          WHERE replay.registration_id = registration.registration_id
            AND replay.grant_verifier = $3
            AND replay.lease_expires_at > $2
      )
  )
`

type DeleteDeviceByRegistrationAndGrantParams struct {
	RegistrationID pgtype.UUID
	Now            pgtype.Timestamptz
	GrantVerifier  []byte
}

func (q *Queries) DeleteDeviceByRegistrationAndGrant(ctx context.Context, arg DeleteDeviceByRegistrationAndGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeviceByRegistrationAndGrant, arg.RegistrationID, arg.Now, arg.GrantVerifier)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredDeviceByID = `-- name: DeleteExpiredDeviceByID :exec
DELETE FROM deck_device_registrations
WHERE device_id = $1
  AND lease_expires_at <= $2
`

type DeleteExpiredDeviceByIDParams struct {
	DeviceID pgtype.UUID
	Now      pgtype.Timestamptz
}

func (q *Queries) DeleteExpiredDeviceByID(ctx context.Context, arg DeleteExpiredDeviceByIDParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredDeviceByID, arg.DeviceID, arg.Now)
	return err
}

const deleteExpiredDeviceIdempotency = `-- name: DeleteExpiredDeviceIdempotency :exec
DELETE FROM deck_device_registration_idempotency
WHERE lease_expires_at <= $1
`

func (q *Queries) DeleteExpiredDeviceIdempotency(ctx context.Context, now pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteExpiredDeviceIdempotency, now)
	return err
}

const getDeviceByAccountAndID = `-- name: GetDeviceByAccountAndID :one
SELECT registration_id, device_id, account_id, platform, display_name_ciphertext, push_ciphertext, detailed_notification_text_enabled, shortcuts_ciphertext, widgets_ciphertext, grant_verifier, revision, lease_expires_at, created_at, updated_at FROM deck_device_registrations
WHERE account_id = $1 AND device_id = $2
`

type GetDeviceByAccountAndIDParams struct {
	AccountID pgtype.UUID
	DeviceID  pgtype.UUID
}

func (q *Queries) GetDeviceByAccountAndID(ctx context.Context, arg GetDeviceByAccountAndIDParams) (DeckDeviceRegistration, error) {
	row := q.db.QueryRow(ctx, getDeviceByAccountAndID, arg.AccountID, arg.DeviceID)
	var i DeckDeviceRegistration
	err := row.Scan(
		&i.RegistrationID,
		&i.DeviceID,
		&i.AccountID,
		&i.Platform,
		&i.DisplayNameCiphertext,
		&i.PushCiphertext,
		&i.DetailedNotificationTextEnabled,
		&i.ShortcutsCiphertext,
		&i.WidgetsCiphertext,
		&i.GrantVerifier,
		&i.Revision,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceByGrantVerifier = `-- name: GetDeviceByGrantVerifier :one
SELECT registration_id, device_id, account_id, platform, display_name_ciphertext, push_ciphertext, detailed_notification_text_enabled, shortcuts_ciphertext, widgets_ciphertext, grant_verifier, revision, lease_expires_at, created_at, updated_at FROM deck_device_registrations
WHERE grant_verifier = $1
`

func (q *Queries) GetDeviceByGrantVerifier(ctx context.Context, grantVerifier []byte) (DeckDeviceRegistration, error) {
	row := q.db.QueryRow(ctx, getDeviceByGrantVerifier, grantVerifier)
	var i DeckDeviceRegistration
	err := row.Scan(
		&i.RegistrationID,
		&i.DeviceID,
		&i.AccountID,
		&i.Platform,
		&i.DisplayNameCiphertext,
		&i.PushCiphertext,
		&i.DetailedNotificationTextEnabled,
		&i.ShortcutsCiphertext,
		&i.WidgetsCiphertext,
		&i.GrantVerifier,
		&i.Revision,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT registration_id, device_id, account_id, platform, display_name_ciphertext, push_ciphertext, detailed_notification_text_enabled, shortcuts_ciphertext, widgets_ciphertext, grant_verifier, revision, lease_expires_at, created_at, updated_at FROM deck_device_registrations
WHERE device_id = $1
`

func (q *Queries) GetDeviceByID(ctx context.Context, deviceID pgtype.UUID) (DeckDeviceRegistration, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, deviceID)
	var i DeckDeviceRegistration
	err := row.Scan(
		&i.RegistrationID,
		&i.DeviceID,
		&i.AccountID,
		&i.Platform,
		&i.DisplayNameCiphertext,
		&i.PushCiphertext,
		&i.DetailedNotificationTextEnabled,
		&i.ShortcutsCiphertext,
		&i.WidgetsCiphertext,
		&i.GrantVerifier,
		&i.Revision,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceByRegistration = `-- name: GetDeviceByRegistration :one
SELECT registration_id, device_id, account_id, platform, display_name_ciphertext, push_ciphertext, detailed_notification_text_enabled, shortcuts_ciphertext, widgets_ciphertext, grant_verifier, revision, lease_expires_at, created_at, updated_at FROM deck_device_registrations
WHERE registration_id = $1
`

func (q *Queries) GetDeviceByRegistration(ctx context.Context, registrationID pgtype.UUID) (DeckDeviceRegistration, error) {
	row := q.db.QueryRow(ctx, getDeviceByRegistration, registrationID)
	var i DeckDeviceRegistration
	err := row.Scan(
		&i.RegistrationID,
		&i.DeviceID,
		&i.AccountID,
		&i.Platform,
		&i.DisplayNameCiphertext,
		&i.PushCiphertext,
		&i.DetailedNotificationTextEnabled,
		&i.ShortcutsCiphertext,
		&i.WidgetsCiphertext,
		&i.GrantVerifier,
		&i.Revision,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRegisterDeviceIdempotency = `-- name: GetRegisterDeviceIdempotency :one
SELECT account_id, idempotency_key, request_digest, registration_id,
       grant_replay_ciphertext, grant_verifier, response_ciphertext,
       lease_expires_at, created_at
FROM deck_device_registration_idempotency
WHERE account_id = $1
  AND idempotency_key = $2
`

type GetRegisterDeviceIdempotencyParams struct {
	AccountID      pgtype.UUID
	IdempotencyKey pgtype.UUID
}

func (q *Queries) GetRegisterDeviceIdempotency(ctx context.Context, arg GetRegisterDeviceIdempotencyParams) (DeckDeviceRegistrationIdempotency, error) {
	row := q.db.QueryRow(ctx, getRegisterDeviceIdempotency, arg.AccountID, arg.IdempotencyKey)
	var i DeckDeviceRegistrationIdempotency
	err := row.Scan(
		&i.AccountID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.RegistrationID,
		&i.GrantReplayCiphertext,
		&i.GrantVerifier,
		&i.ResponseCiphertext,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getViewNotificationPreference = `-- name: GetViewNotificationPreference :one
SELECT registration_id, view_id, preference_ciphertext, revision, updated_at FROM deck_view_notification_preferences
WHERE registration_id = $1
  AND view_id = $2
`

type GetViewNotificationPreferenceParams struct {
	RegistrationID pgtype.UUID
	ViewID         pgtype.UUID
}

func (q *Queries) GetViewNotificationPreference(ctx context.Context, arg GetViewNotificationPreferenceParams) (DeckViewNotificationPreference, error) {
	row := q.db.QueryRow(ctx, getViewNotificationPreference, arg.RegistrationID, arg.ViewID)
	var i DeckViewNotificationPreference
	err := row.Scan(
		&i.RegistrationID,
		&i.ViewID,
		&i.PreferenceCiphertext,
		&i.Revision,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDevice = `-- name: InsertDevice :one
INSERT INTO deck_device_registrations (
    registration_id, device_id, account_id, platform,
    display_name_ciphertext, push_ciphertext,
    detailed_notification_text_enabled, shortcuts_ciphertext,
    widgets_ciphertext, grant_verifier, revision, lease_expires_at,
    created_at, updated_at
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7,
    $8, $9,
    $10, 1, $11,
    $12, $13
)
RETURNING registration_id, device_id, account_id, platform, display_name_ciphertext, push_ciphertext, detailed_notification_text_enabled, shortcuts_ciphertext, widgets_ciphertext, grant_verifier, revision, lease_expires_at, created_at, updated_at
`

type InsertDeviceParams struct {
	RegistrationID                  pgtype.UUID
	DeviceID                        pgtype.UUID
	AccountID                       pgtype.UUID
	Platform                        int16
	DisplayNameCiphertext           []byte
	PushCiphertext                  []byte
	DetailedNotificationTextEnabled bool
	ShortcutsCiphertext             []byte
	WidgetsCiphertext               []byte
	GrantVerifier                   []byte
	LeaseExpiresAt                  pgtype.Timestamptz
	CreatedAt                       pgtype.Timestamptz
	UpdatedAt                       pgtype.Timestamptz
}

func (q *Queries) InsertDevice(ctx context.Context, arg InsertDeviceParams) (DeckDeviceRegistration, error) {
	row := q.db.QueryRow(ctx, insertDevice,
		arg.RegistrationID,
		arg.DeviceID,
		arg.AccountID,
		arg.Platform,
		arg.DisplayNameCiphertext,
		arg.PushCiphertext,
		arg.DetailedNotificationTextEnabled,
		arg.ShortcutsCiphertext,
		arg.WidgetsCiphertext,
		arg.GrantVerifier,
		arg.LeaseExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i DeckDeviceRegistration
	err := row.Scan(
		&i.RegistrationID,
		&i.DeviceID,
		&i.AccountID,
		&i.Platform,
		&i.DisplayNameCiphertext,
		&i.PushCiphertext,
		&i.DetailedNotificationTextEnabled,
		&i.ShortcutsCiphertext,
		&i.WidgetsCiphertext,
		&i.GrantVerifier,
		&i.Revision,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRegisterDeviceIdempotency = `-- name: InsertRegisterDeviceIdempotency :exec
INSERT INTO deck_device_registration_idempotency (
    account_id, idempotency_key, request_digest, registration_id,
    grant_replay_ciphertext, grant_verifier, response_ciphertext,
    lease_expires_at
) VALUES (
    $1, $2,
    $3, $4,
    $5, $6,
    $7, $8
)
`

type InsertRegisterDeviceIdempotencyParams struct {
	AccountID             pgtype.UUID
	IdempotencyKey        pgtype.UUID
	RequestDigest         []byte
	RegistrationID        pgtype.UUID
	GrantReplayCiphertext []byte
	GrantVerifier         []byte
	ResponseCiphertext    []byte
	LeaseExpiresAt        pgtype.Timestamptz
}

func (q *Queries) InsertRegisterDeviceIdempotency(ctx context.Context, arg InsertRegisterDeviceIdempotencyParams) error {
	_, err := q.db.Exec(ctx, insertRegisterDeviceIdempotency,
		arg.AccountID,
		arg.IdempotencyKey,
		arg.RequestDigest,
		arg.RegistrationID,
		arg.GrantReplayCiphertext,
		arg.GrantVerifier,
		arg.ResponseCiphertext,
		arg.LeaseExpiresAt,
	)
	return err
}

const renewDevice = `-- name: RenewDevice :one
UPDATE deck_device_registrations
SET platform = $1,
    display_name_ciphertext = $2,
    push_ciphertext = $3,
    detailed_notification_text_enabled = $4,
    shortcuts_ciphertext = $5,
    widgets_ciphertext = $6,
    grant_verifier = $7,
    lease_expires_at = $8,
    revision = revision + 1,
    updated_at = $9
WHERE registration_id = $10
  AND revision = $11
RETURNING registration_id, device_id, account_id, platform, display_name_ciphertext, push_ciphertext, detailed_notification_text_enabled, shortcuts_ciphertext, widgets_ciphertext, grant_verifier, revision, lease_expires_at, created_at, updated_at
`

type RenewDeviceParams struct {
	Platform                        int16
	DisplayNameCiphertext           []byte
	PushCiphertext                  []byte
	DetailedNotificationTextEnabled bool
	ShortcutsCiphertext             []byte
	WidgetsCiphertext               []byte
	GrantVerifier                   []byte
	LeaseExpiresAt                  pgtype.Timestamptz
	UpdatedAt                       pgtype.Timestamptz
	RegistrationID                  pgtype.UUID
	ExpectedRevision                int64
}

func (q *Queries) RenewDevice(ctx context.Context, arg RenewDeviceParams) (DeckDeviceRegistration, error) {
	row := q.db.QueryRow(ctx, renewDevice,
		arg.Platform,
		arg.DisplayNameCiphertext,
		arg.PushCiphertext,
		arg.DetailedNotificationTextEnabled,
		arg.ShortcutsCiphertext,
		arg.WidgetsCiphertext,
		arg.GrantVerifier,
		arg.LeaseExpiresAt,
		arg.UpdatedAt,
		arg.RegistrationID,
		arg.ExpectedRevision,
	)
	var i DeckDeviceRegistration
	err := row.Scan(
		&i.RegistrationID,
		&i.DeviceID,
		&i.AccountID,
		&i.Platform,
		&i.DisplayNameCiphertext,
		&i.PushCiphertext,
		&i.DetailedNotificationTextEnabled,
		&i.ShortcutsCiphertext,
		&i.WidgetsCiphertext,
		&i.GrantVerifier,
		&i.Revision,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDevice = `-- name: UpdateDevice :one
UPDATE deck_device_registrations
SET display_name_ciphertext = $1,
    push_ciphertext = $2,
    detailed_notification_text_enabled = $3,
    shortcuts_ciphertext = $4,
    widgets_ciphertext = $5,
    revision = revision + 1,
    updated_at = $6
WHERE registration_id = $7
  AND account_id = $8
  AND revision = $9
RETURNING registration_id, device_id, account_id, platform, display_name_ciphertext, push_ciphertext, detailed_notification_text_enabled, shortcuts_ciphertext, widgets_ciphertext, grant_verifier, revision, lease_expires_at, created_at, updated_at
`

type UpdateDeviceParams struct {
	DisplayNameCiphertext           []byte
	PushCiphertext                  []byte
	DetailedNotificationTextEnabled bool
	ShortcutsCiphertext             []byte
	WidgetsCiphertext               []byte
	UpdatedAt                       pgtype.Timestamptz
	RegistrationID                  pgtype.UUID
	AccountID                       pgtype.UUID
	ExpectedRevision                int64
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (DeckDeviceRegistration, error) {
	row := q.db.QueryRow(ctx, updateDevice,
		arg.DisplayNameCiphertext,
		arg.PushCiphertext,
		arg.DetailedNotificationTextEnabled,
		arg.ShortcutsCiphertext,
		arg.WidgetsCiphertext,
		arg.UpdatedAt,
		arg.RegistrationID,
		arg.AccountID,
		arg.ExpectedRevision,
	)
	var i DeckDeviceRegistration
	err := row.Scan(
		&i.RegistrationID,
		&i.DeviceID,
		&i.AccountID,
		&i.Platform,
		&i.DisplayNameCiphertext,
		&i.PushCiphertext,
		&i.DetailedNotificationTextEnabled,
		&i.ShortcutsCiphertext,
		&i.WidgetsCiphertext,
		&i.GrantVerifier,
		&i.Revision,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertViewNotificationPreference = `-- name: UpsertViewNotificationPreference :one
INSERT INTO deck_view_notification_preferences (
    registration_id, view_id, preference_ciphertext, revision, updated_at
) VALUES (
    $1, $2,
    $3, 1, $4
)
ON CONFLICT (registration_id, view_id) DO UPDATE
SET preference_ciphertext = EXCLUDED.preference_ciphertext,
    revision = deck_view_notification_preferences.revision + 1,
    updated_at = EXCLUDED.updated_at
WHERE deck_view_notification_preferences.revision = $5
RETURNING registration_id, view_id, preference_ciphertext, revision, updated_at
`

type UpsertViewNotificationPreferenceParams struct {
	RegistrationID       pgtype.UUID
	ViewID               pgtype.UUID
	PreferenceCiphertext []byte
	UpdatedAt            pgtype.Timestamptz
	ExpectedRevision     int64
}

func (q *Queries) UpsertViewNotificationPreference(ctx context.Context, arg UpsertViewNotificationPreferenceParams) (DeckViewNotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertViewNotificationPreference,
		arg.RegistrationID,
		arg.ViewID,
		arg.PreferenceCiphertext,
		arg.UpdatedAt,
		arg.ExpectedRevision,
	)
	var i DeckViewNotificationPreference
	err := row.Scan(
		&i.RegistrationID,
		&i.ViewID,
		&i.PreferenceCiphertext,
		&i.Revision,
		&i.UpdatedAt,
	)
	return i, err
}
