// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const canManageOrganizationForGitHubCallback = `-- name: CanManageOrganizationForGitHubCallback :one
SELECT EXISTS (
    SELECT 1
    FROM deck_organization_memberships
    WHERE organization_id = $1
      AND account_id = $2
      AND active
      AND role >= 2
)::boolean
`

type CanManageOrganizationForGitHubCallbackParams struct {
	OrganizationID pgtype.UUID
	AccountID      pgtype.UUID
}

func (q *Queries) CanManageOrganizationForGitHubCallback(ctx context.Context, arg CanManageOrganizationForGitHubCallbackParams) (bool, error) {
	row := q.db.QueryRow(ctx, canManageOrganizationForGitHubCallback, arg.OrganizationID, arg.AccountID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const canUseOrganizationForGitHubCallback = `-- name: CanUseOrganizationForGitHubCallback :one
SELECT EXISTS (
    SELECT 1
    FROM deck_organization_memberships
    WHERE organization_id = $1
      AND account_id = $2
      AND active
)::boolean
`

type CanUseOrganizationForGitHubCallbackParams struct {
	OrganizationID pgtype.UUID
	AccountID      pgtype.UUID
}

func (q *Queries) CanUseOrganizationForGitHubCallback(ctx context.Context, arg CanUseOrganizationForGitHubCallbackParams) (bool, error) {
	row := q.db.QueryRow(ctx, canUseOrganizationForGitHubCallback, arg.OrganizationID, arg.AccountID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteConsumedGitHubCallbackState = `-- name: DeleteConsumedGitHubCallbackState :one
DELETE FROM deck_github_callback_states
WHERE state_hash = $1
  AND owner_scope = $2
  AND owner_id = $3
  AND account_id = $4
  AND consumed_at IS NOT NULL
RETURNING state_hash
`

type DeleteConsumedGitHubCallbackStateParams struct {
	StateHash  []byte
	OwnerScope int16
	OwnerID    pgtype.UUID
	AccountID  pgtype.UUID
}

func (q *Queries) DeleteConsumedGitHubCallbackState(ctx context.Context, arg DeleteConsumedGitHubCallbackStateParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, deleteConsumedGitHubCallbackState,
		arg.StateHash,
		arg.OwnerScope,
		arg.OwnerID,
		arg.AccountID,
	)
	var state_hash []byte
	err := row.Scan(&state_hash)
	return state_hash, err
}

const deleteExpiredGitHubCallbackStates = `-- name: DeleteExpiredGitHubCallbackStates :exec
DELETE FROM deck_github_callback_states
WHERE expires_at <= $1
`

func (q *Queries) DeleteExpiredGitHubCallbackStates(ctx context.Context, expiredAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteExpiredGitHubCallbackStates, expiredAt)
	return err
}

const deleteGitHubCallbackState = `-- name: DeleteGitHubCallbackState :exec
DELETE FROM deck_github_callback_states
WHERE state_hash = $1
`

func (q *Queries) DeleteGitHubCallbackState(ctx context.Context, stateHash []byte) error {
	_, err := q.db.Exec(ctx, deleteGitHubCallbackState, stateHash)
	return err
}

const deleteGitHubCallbackStatesByOwner = `-- name: DeleteGitHubCallbackStatesByOwner :exec
DELETE FROM deck_github_callback_states
WHERE owner_scope = $1
  AND owner_id = $2
`

type DeleteGitHubCallbackStatesByOwnerParams struct {
	OwnerScope int16
	OwnerID    pgtype.UUID
}

func (q *Queries) DeleteGitHubCallbackStatesByOwner(ctx context.Context, arg DeleteGitHubCallbackStatesByOwnerParams) error {
	_, err := q.db.Exec(ctx, deleteGitHubCallbackStatesByOwner, arg.OwnerScope, arg.OwnerID)
	return err
}

const deleteGitHubConnectionCredentials = `-- name: DeleteGitHubConnectionCredentials :exec
DELETE FROM deck_github_user_credentials
WHERE connection_id = $1
`

func (q *Queries) DeleteGitHubConnectionCredentials(ctx context.Context, connectionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGitHubConnectionCredentials, connectionID)
	return err
}

const deleteGitHubUserCredentialsByAccount = `-- name: DeleteGitHubUserCredentialsByAccount :exec
DELETE FROM deck_github_user_credentials
WHERE account_id = $1
`

func (q *Queries) DeleteGitHubUserCredentialsByAccount(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGitHubUserCredentialsByAccount, accountID)
	return err
}

const deleteGitHubUserCredentialsByGitHubUser = `-- name: DeleteGitHubUserCredentialsByGitHubUser :exec
DELETE FROM deck_github_user_credentials
WHERE github_user_id = $1
`

func (q *Queries) DeleteGitHubUserCredentialsByGitHubUser(ctx context.Context, githubUserID int64) error {
	_, err := q.db.Exec(ctx, deleteGitHubUserCredentialsByGitHubUser, githubUserID)
	return err
}

const deleteOwnerNotificationEvents = `-- name: DeleteOwnerNotificationEvents :exec
DELETE FROM deck_notification_events
WHERE view_id IN (
    SELECT view_id FROM deck_views
    WHERE ($1::smallint = 1
            AND owner_scope = 1 AND owner_account_id = $2)
       OR ($1::smallint = 2
            AND owner_scope = 2 AND owner_organization_id = $2)
)
`

type DeleteOwnerNotificationEventsParams struct {
	OwnerScope int16
	OwnerID    pgtype.UUID
}

func (q *Queries) DeleteOwnerNotificationEvents(ctx context.Context, arg DeleteOwnerNotificationEventsParams) error {
	_, err := q.db.Exec(ctx, deleteOwnerNotificationEvents, arg.OwnerScope, arg.OwnerID)
	return err
}

const deleteOwnerNotificationState = `-- name: DeleteOwnerNotificationState :exec
DELETE FROM deck_view_notification_preferences
WHERE view_id IN (
    SELECT view_id FROM deck_views
    WHERE ($1::smallint = 1
            AND owner_scope = 1 AND owner_account_id = $2)
       OR ($1::smallint = 2
            AND owner_scope = 2 AND owner_organization_id = $2)
)
`

type DeleteOwnerNotificationStateParams struct {
	OwnerScope int16
	OwnerID    pgtype.UUID
}

func (q *Queries) DeleteOwnerNotificationState(ctx context.Context, arg DeleteOwnerNotificationStateParams) error {
	_, err := q.db.Exec(ctx, deleteOwnerNotificationState, arg.OwnerScope, arg.OwnerID)
	return err
}

const disconnectGitHubConnection = `-- name: DisconnectGitHubConnection :one
UPDATE deck_connections
SET state = $1,
    github_installation_id = NULL,
    github_account_id = NULL,
    github_account_kind = NULL,
    github_account_login_ciphertext = NULL,
    github_metadata_permission = NULL,
    github_contents_permission = NULL,
    github_pull_requests_permission = NULL,
    github_checks_permission = NULL,
    github_members_permission = NULL,
    revision = revision + 1,
    updated_at = $2
WHERE connection_id = $3
  AND revision = $4
RETURNING connection_id, owner_scope, owner_id, state, revision, created_at, updated_at, github_installation_id, github_account_id, github_account_kind, github_account_login_ciphertext, github_metadata_permission, github_contents_permission, github_pull_requests_permission, github_checks_permission, github_members_permission
`

type DisconnectGitHubConnectionParams struct {
	ConnectionState  int16
	UpdatedAt        pgtype.Timestamptz
	ConnectionID     pgtype.UUID
	ExpectedRevision int64
}

func (q *Queries) DisconnectGitHubConnection(ctx context.Context, arg DisconnectGitHubConnectionParams) (DeckConnection, error) {
	row := q.db.QueryRow(ctx, disconnectGitHubConnection,
		arg.ConnectionState,
		arg.UpdatedAt,
		arg.ConnectionID,
		arg.ExpectedRevision,
	)
	var i DeckConnection
	err := row.Scan(
		&i.ConnectionID,
		&i.OwnerScope,
		&i.OwnerID,
		&i.State,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubInstallationID,
		&i.GithubAccountID,
		&i.GithubAccountKind,
		&i.GithubAccountLoginCiphertext,
		&i.GithubMetadataPermission,
		&i.GithubContentsPermission,
		&i.GithubPullRequestsPermission,
		&i.GithubChecksPermission,
		&i.GithubMembersPermission,
	)
	return i, err
}

const getGitHubCallbackStateForUpdate = `-- name: GetGitHubCallbackStateForUpdate :one
SELECT state_hash, owner_scope, owner_id, account_id, state_ciphertext, expires_at, consumed_at, created_at
FROM deck_github_callback_states
WHERE state_hash = $1
FOR UPDATE
`

func (q *Queries) GetGitHubCallbackStateForUpdate(ctx context.Context, stateHash []byte) (DeckGithubCallbackState, error) {
	row := q.db.QueryRow(ctx, getGitHubCallbackStateForUpdate, stateHash)
	var i DeckGithubCallbackState
	err := row.Scan(
		&i.StateHash,
		&i.OwnerScope,
		&i.OwnerID,
		&i.AccountID,
		&i.StateCiphertext,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getGitHubConnectionByIDForUpdate = `-- name: GetGitHubConnectionByIDForUpdate :one
SELECT connection_id, owner_scope, owner_id, state, revision, created_at, updated_at, github_installation_id, github_account_id, github_account_kind, github_account_login_ciphertext, github_metadata_permission, github_contents_permission, github_pull_requests_permission, github_checks_permission, github_members_permission
FROM deck_connections
WHERE connection_id = $1
FOR UPDATE
`

func (q *Queries) GetGitHubConnectionByIDForUpdate(ctx context.Context, connectionID pgtype.UUID) (DeckConnection, error) {
	row := q.db.QueryRow(ctx, getGitHubConnectionByIDForUpdate, connectionID)
	var i DeckConnection
	err := row.Scan(
		&i.ConnectionID,
		&i.OwnerScope,
		&i.OwnerID,
		&i.State,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubInstallationID,
		&i.GithubAccountID,
		&i.GithubAccountKind,
		&i.GithubAccountLoginCiphertext,
		&i.GithubMetadataPermission,
		&i.GithubContentsPermission,
		&i.GithubPullRequestsPermission,
		&i.GithubChecksPermission,
		&i.GithubMembersPermission,
	)
	return i, err
}

const getGitHubConnectionByInstallationForUpdate = `-- name: GetGitHubConnectionByInstallationForUpdate :one
SELECT connection_id, owner_scope, owner_id, state, revision, created_at, updated_at, github_installation_id, github_account_id, github_account_kind, github_account_login_ciphertext, github_metadata_permission, github_contents_permission, github_pull_requests_permission, github_checks_permission, github_members_permission
FROM deck_connections
WHERE github_installation_id = $1
FOR UPDATE
`

func (q *Queries) GetGitHubConnectionByInstallationForUpdate(ctx context.Context, githubInstallationID pgtype.Int8) (DeckConnection, error) {
	row := q.db.QueryRow(ctx, getGitHubConnectionByInstallationForUpdate, githubInstallationID)
	var i DeckConnection
	err := row.Scan(
		&i.ConnectionID,
		&i.OwnerScope,
		&i.OwnerID,
		&i.State,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubInstallationID,
		&i.GithubAccountID,
		&i.GithubAccountKind,
		&i.GithubAccountLoginCiphertext,
		&i.GithubMetadataPermission,
		&i.GithubContentsPermission,
		&i.GithubPullRequestsPermission,
		&i.GithubChecksPermission,
		&i.GithubMembersPermission,
	)
	return i, err
}

const getGitHubConnectionByOwner = `-- name: GetGitHubConnectionByOwner :one
SELECT connection_id, owner_scope, owner_id, state, revision, created_at, updated_at, github_installation_id, github_account_id, github_account_kind, github_account_login_ciphertext, github_metadata_permission, github_contents_permission, github_pull_requests_permission, github_checks_permission, github_members_permission
FROM deck_connections
WHERE owner_scope = $1
  AND owner_id = $2
`

type GetGitHubConnectionByOwnerParams struct {
	OwnerScope int16
	OwnerID    pgtype.UUID
}

func (q *Queries) GetGitHubConnectionByOwner(ctx context.Context, arg GetGitHubConnectionByOwnerParams) (DeckConnection, error) {
	row := q.db.QueryRow(ctx, getGitHubConnectionByOwner, arg.OwnerScope, arg.OwnerID)
	var i DeckConnection
	err := row.Scan(
		&i.ConnectionID,
		&i.OwnerScope,
		&i.OwnerID,
		&i.State,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubInstallationID,
		&i.GithubAccountID,
		&i.GithubAccountKind,
		&i.GithubAccountLoginCiphertext,
		&i.GithubMetadataPermission,
		&i.GithubContentsPermission,
		&i.GithubPullRequestsPermission,
		&i.GithubChecksPermission,
		&i.GithubMembersPermission,
	)
	return i, err
}

const getGitHubConnectionByOwnerForUpdate = `-- name: GetGitHubConnectionByOwnerForUpdate :one
SELECT connection_id, owner_scope, owner_id, state, revision, created_at, updated_at, github_installation_id, github_account_id, github_account_kind, github_account_login_ciphertext, github_metadata_permission, github_contents_permission, github_pull_requests_permission, github_checks_permission, github_members_permission
FROM deck_connections
WHERE owner_scope = $1
  AND owner_id = $2
FOR UPDATE
`

type GetGitHubConnectionByOwnerForUpdateParams struct {
	OwnerScope int16
	OwnerID    pgtype.UUID
}

func (q *Queries) GetGitHubConnectionByOwnerForUpdate(ctx context.Context, arg GetGitHubConnectionByOwnerForUpdateParams) (DeckConnection, error) {
	row := q.db.QueryRow(ctx, getGitHubConnectionByOwnerForUpdate, arg.OwnerScope, arg.OwnerID)
	var i DeckConnection
	err := row.Scan(
		&i.ConnectionID,
		&i.OwnerScope,
		&i.OwnerID,
		&i.State,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubInstallationID,
		&i.GithubAccountID,
		&i.GithubAccountKind,
		&i.GithubAccountLoginCiphertext,
		&i.GithubMetadataPermission,
		&i.GithubContentsPermission,
		&i.GithubPullRequestsPermission,
		&i.GithubChecksPermission,
		&i.GithubMembersPermission,
	)
	return i, err
}

const getGitHubUserCredential = `-- name: GetGitHubUserCredential :one
SELECT connection_id, account_id, github_user_id, wrapping_key_id, user_access_token_ciphertext, user_refresh_token_ciphertext, user_access_token_expires_at, user_refresh_token_expires_at, updated_at
FROM deck_github_user_credentials
WHERE connection_id = $1
  AND account_id = $2
`

type GetGitHubUserCredentialParams struct {
	ConnectionID pgtype.UUID
	AccountID    pgtype.UUID
}

func (q *Queries) GetGitHubUserCredential(ctx context.Context, arg GetGitHubUserCredentialParams) (DeckGithubUserCredential, error) {
	row := q.db.QueryRow(ctx, getGitHubUserCredential, arg.ConnectionID, arg.AccountID)
	var i DeckGithubUserCredential
	err := row.Scan(
		&i.ConnectionID,
		&i.AccountID,
		&i.GithubUserID,
		&i.WrappingKeyID,
		&i.UserAccessTokenCiphertext,
		&i.UserRefreshTokenCiphertext,
		&i.UserAccessTokenExpiresAt,
		&i.UserRefreshTokenExpiresAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGitHubWebhookDelivery = `-- name: GetGitHubWebhookDelivery :one
SELECT delivery_id, event_type, action_type, installation_id, github_user_id, payload_hash, processed_at
FROM deck_github_webhook_deliveries
WHERE delivery_id = $1
`

func (q *Queries) GetGitHubWebhookDelivery(ctx context.Context, deliveryID string) (DeckGithubWebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getGitHubWebhookDelivery, deliveryID)
	var i DeckGithubWebhookDelivery
	err := row.Scan(
		&i.DeliveryID,
		&i.EventType,
		&i.ActionType,
		&i.InstallationID,
		&i.GithubUserID,
		&i.PayloadHash,
		&i.ProcessedAt,
	)
	return i, err
}

const insertGitHubCallbackState = `-- name: InsertGitHubCallbackState :exec
INSERT INTO deck_github_callback_states (
    state_hash, owner_scope, owner_id, account_id, state_ciphertext, expires_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
`

type InsertGitHubCallbackStateParams struct {
	StateHash       []byte
	OwnerScope      int16
	OwnerID         pgtype.UUID
	AccountID       pgtype.UUID
	StateCiphertext []byte
	ExpiresAt       pgtype.Timestamptz
}

func (q *Queries) InsertGitHubCallbackState(ctx context.Context, arg InsertGitHubCallbackStateParams) error {
	_, err := q.db.Exec(ctx, insertGitHubCallbackState,
		arg.StateHash,
		arg.OwnerScope,
		arg.OwnerID,
		arg.AccountID,
		arg.StateCiphertext,
		arg.ExpiresAt,
	)
	return err
}

const insertGitHubConnection = `-- name: InsertGitHubConnection :one
INSERT INTO deck_connections (
    connection_id, owner_scope, owner_id, state,
    github_installation_id, github_account_id, github_account_kind,
    github_account_login_ciphertext, github_metadata_permission,
    github_contents_permission,
    github_pull_requests_permission, github_checks_permission,
    github_members_permission, revision, created_at, updated_at
) VALUES (
    $1, $2, $3, 3,
    $4, $5,
    $6, $7,
    $8, $9,
    $10,
    $11, $12, 1,
    $13, $14
)
RETURNING connection_id, owner_scope, owner_id, state, revision, created_at, updated_at, github_installation_id, github_account_id, github_account_kind, github_account_login_ciphertext, github_metadata_permission, github_contents_permission, github_pull_requests_permission, github_checks_permission, github_members_permission
`

type InsertGitHubConnectionParams struct {
	ConnectionID                 pgtype.UUID
	OwnerScope                   int16
	OwnerID                      pgtype.UUID
	GithubInstallationID         pgtype.Int8
	GithubAccountID              pgtype.Int8
	GithubAccountKind            pgtype.Int2
	GithubAccountLoginCiphertext []byte
	GithubMetadataPermission     pgtype.Int2
	GithubContentsPermission     pgtype.Int2
	GithubPullRequestsPermission pgtype.Int2
	GithubChecksPermission       pgtype.Int2
	GithubMembersPermission      pgtype.Int2
	CreatedAt                    pgtype.Timestamptz
	UpdatedAt                    pgtype.Timestamptz
}

func (q *Queries) InsertGitHubConnection(ctx context.Context, arg InsertGitHubConnectionParams) (DeckConnection, error) {
	row := q.db.QueryRow(ctx, insertGitHubConnection,
		arg.ConnectionID,
		arg.OwnerScope,
		arg.OwnerID,
		arg.GithubInstallationID,
		arg.GithubAccountID,
		arg.GithubAccountKind,
		arg.GithubAccountLoginCiphertext,
		arg.GithubMetadataPermission,
		arg.GithubContentsPermission,
		arg.GithubPullRequestsPermission,
		arg.GithubChecksPermission,
		arg.GithubMembersPermission,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i DeckConnection
	err := row.Scan(
		&i.ConnectionID,
		&i.OwnerScope,
		&i.OwnerID,
		&i.State,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubInstallationID,
		&i.GithubAccountID,
		&i.GithubAccountKind,
		&i.GithubAccountLoginCiphertext,
		&i.GithubMetadataPermission,
		&i.GithubContentsPermission,
		&i.GithubPullRequestsPermission,
		&i.GithubChecksPermission,
		&i.GithubMembersPermission,
	)
	return i, err
}

const insertGitHubWebhookDelivery = `-- name: InsertGitHubWebhookDelivery :exec
INSERT INTO deck_github_webhook_deliveries (
    delivery_id, event_type, action_type, installation_id, github_user_id,
    payload_hash, processed_at
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7
)
`

type InsertGitHubWebhookDeliveryParams struct {
	DeliveryID     string
	EventType      int16
	ActionType     int16
	InstallationID int64
	GithubUserID   int64
	PayloadHash    []byte
	ProcessedAt    pgtype.Timestamptz
}

func (q *Queries) InsertGitHubWebhookDelivery(ctx context.Context, arg InsertGitHubWebhookDeliveryParams) error {
	_, err := q.db.Exec(ctx, insertGitHubWebhookDelivery,
		arg.DeliveryID,
		arg.EventType,
		arg.ActionType,
		arg.InstallationID,
		arg.GithubUserID,
		arg.PayloadHash,
		arg.ProcessedAt,
	)
	return err
}

const listGitHubUserCredentialsForRewrap = `-- name: ListGitHubUserCredentialsForRewrap :many
SELECT connection_id, account_id, github_user_id, wrapping_key_id, user_access_token_ciphertext, user_refresh_token_ciphertext, user_access_token_expires_at, user_refresh_token_expires_at, updated_at
FROM deck_github_user_credentials
ORDER BY connection_id, account_id
FOR UPDATE
`

func (q *Queries) ListGitHubUserCredentialsForRewrap(ctx context.Context) ([]DeckGithubUserCredential, error) {
	rows, err := q.db.Query(ctx, listGitHubUserCredentialsForRewrap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeckGithubUserCredential{}
	for rows.Next() {
		var i DeckGithubUserCredential
		if err := rows.Scan(
			&i.ConnectionID,
			&i.AccountID,
			&i.GithubUserID,
			&i.WrappingKeyID,
			&i.UserAccessTokenCiphertext,
			&i.UserRefreshTokenCiphertext,
			&i.UserAccessTokenExpiresAt,
			&i.UserRefreshTokenExpiresAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnerViewsForProviderCleanup = `-- name: ListOwnerViewsForProviderCleanup :many
SELECT view_id
FROM deck_views
WHERE ($1::smallint = 1
        AND owner_scope = 1 AND owner_account_id = $2)
   OR ($1::smallint = 2
        AND owner_scope = 2 AND owner_organization_id = $2)
ORDER BY view_id
FOR UPDATE
`

type ListOwnerViewsForProviderCleanupParams struct {
	OwnerScope int16
	OwnerID    pgtype.UUID
}

func (q *Queries) ListOwnerViewsForProviderCleanup(ctx context.Context, arg ListOwnerViewsForProviderCleanupParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listOwnerViewsForProviderCleanup, arg.OwnerScope, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var view_id pgtype.UUID
		if err := rows.Scan(&view_id); err != nil {
			return nil, err
		}
		items = append(items, view_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGitHubCallbackStateConsumed = `-- name: MarkGitHubCallbackStateConsumed :exec
UPDATE deck_github_callback_states
SET consumed_at = $1
WHERE state_hash = $2
  AND consumed_at IS NULL
`

type MarkGitHubCallbackStateConsumedParams struct {
	ConsumedAt pgtype.Timestamptz
	StateHash  []byte
}

func (q *Queries) MarkGitHubCallbackStateConsumed(ctx context.Context, arg MarkGitHubCallbackStateConsumedParams) error {
	_, err := q.db.Exec(ctx, markGitHubCallbackStateConsumed, arg.ConsumedAt, arg.StateHash)
	return err
}

const markOwnerViewsConnected = `-- name: MarkOwnerViewsConnected :exec
UPDATE deck_views
SET connection_state = 3,
    revision = revision + 1,
    updated_at = $1
WHERE (
    ($2::smallint = 1
        AND owner_scope = 1 AND owner_account_id = $3)
    OR ($2::smallint = 2
        AND owner_scope = 2 AND owner_organization_id = $3)
)
  AND connection_state <> 3
`

type MarkOwnerViewsConnectedParams struct {
	UpdatedAt  pgtype.Timestamptz
	OwnerScope int16
	OwnerID    pgtype.UUID
}

func (q *Queries) MarkOwnerViewsConnected(ctx context.Context, arg MarkOwnerViewsConnectedParams) error {
	_, err := q.db.Exec(ctx, markOwnerViewsConnected, arg.UpdatedAt, arg.OwnerScope, arg.OwnerID)
	return err
}

const markOwnerViewsDisconnected = `-- name: MarkOwnerViewsDisconnected :exec
UPDATE deck_views
SET connection_state = 1,
    revision = revision + 1,
    updated_at = $1
WHERE (
    ($2::smallint = 1
        AND owner_scope = 1 AND owner_account_id = $3)
    OR ($2::smallint = 2
        AND owner_scope = 2 AND owner_organization_id = $3)
)
  AND connection_state <> 1
`

type MarkOwnerViewsDisconnectedParams struct {
	UpdatedAt  pgtype.Timestamptz
	OwnerScope int16
	OwnerID    pgtype.UUID
}

func (q *Queries) MarkOwnerViewsDisconnected(ctx context.Context, arg MarkOwnerViewsDisconnectedParams) error {
	_, err := q.db.Exec(ctx, markOwnerViewsDisconnected, arg.UpdatedAt, arg.OwnerScope, arg.OwnerID)
	return err
}

const reconnectGitHubConnection = `-- name: ReconnectGitHubConnection :one
UPDATE deck_connections
SET state = 3,
    github_installation_id = $1,
    github_account_id = $2,
    github_account_kind = $3,
    github_account_login_ciphertext = $4,
    github_metadata_permission = $5,
    github_contents_permission = $6,
    github_pull_requests_permission = $7,
    github_checks_permission = $8,
    github_members_permission = $9,
    revision = revision + 1,
    updated_at = $10
WHERE connection_id = $11
RETURNING connection_id, owner_scope, owner_id, state, revision, created_at, updated_at, github_installation_id, github_account_id, github_account_kind, github_account_login_ciphertext, github_metadata_permission, github_contents_permission, github_pull_requests_permission, github_checks_permission, github_members_permission
`

type ReconnectGitHubConnectionParams struct {
	GithubInstallationID         pgtype.Int8
	GithubAccountID              pgtype.Int8
	GithubAccountKind            pgtype.Int2
	GithubAccountLoginCiphertext []byte
	GithubMetadataPermission     pgtype.Int2
	GithubContentsPermission     pgtype.Int2
	GithubPullRequestsPermission pgtype.Int2
	GithubChecksPermission       pgtype.Int2
	GithubMembersPermission      pgtype.Int2
	UpdatedAt                    pgtype.Timestamptz
	ConnectionID                 pgtype.UUID
}

func (q *Queries) ReconnectGitHubConnection(ctx context.Context, arg ReconnectGitHubConnectionParams) (DeckConnection, error) {
	row := q.db.QueryRow(ctx, reconnectGitHubConnection,
		arg.GithubInstallationID,
		arg.GithubAccountID,
		arg.GithubAccountKind,
		arg.GithubAccountLoginCiphertext,
		arg.GithubMetadataPermission,
		arg.GithubContentsPermission,
		arg.GithubPullRequestsPermission,
		arg.GithubChecksPermission,
		arg.GithubMembersPermission,
		arg.UpdatedAt,
		arg.ConnectionID,
	)
	var i DeckConnection
	err := row.Scan(
		&i.ConnectionID,
		&i.OwnerScope,
		&i.OwnerID,
		&i.State,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubInstallationID,
		&i.GithubAccountID,
		&i.GithubAccountKind,
		&i.GithubAccountLoginCiphertext,
		&i.GithubMetadataPermission,
		&i.GithubContentsPermission,
		&i.GithubPullRequestsPermission,
		&i.GithubChecksPermission,
		&i.GithubMembersPermission,
	)
	return i, err
}

const requireGitHubReauthentication = `-- name: RequireGitHubReauthentication :one
UPDATE deck_connections
SET state = 4,
    revision = revision + 1,
    updated_at = $1
WHERE connection_id = $2
  AND revision = $3
RETURNING connection_id, owner_scope, owner_id, state, revision, created_at, updated_at, github_installation_id, github_account_id, github_account_kind, github_account_login_ciphertext, github_metadata_permission, github_contents_permission, github_pull_requests_permission, github_checks_permission, github_members_permission
`

type RequireGitHubReauthenticationParams struct {
	UpdatedAt        pgtype.Timestamptz
	ConnectionID     pgtype.UUID
	ExpectedRevision int64
}

func (q *Queries) RequireGitHubReauthentication(ctx context.Context, arg RequireGitHubReauthenticationParams) (DeckConnection, error) {
	row := q.db.QueryRow(ctx, requireGitHubReauthentication, arg.UpdatedAt, arg.ConnectionID, arg.ExpectedRevision)
	var i DeckConnection
	err := row.Scan(
		&i.ConnectionID,
		&i.OwnerScope,
		&i.OwnerID,
		&i.State,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubInstallationID,
		&i.GithubAccountID,
		&i.GithubAccountKind,
		&i.GithubAccountLoginCiphertext,
		&i.GithubMetadataPermission,
		&i.GithubContentsPermission,
		&i.GithubPullRequestsPermission,
		&i.GithubChecksPermission,
		&i.GithubMembersPermission,
	)
	return i, err
}

const rewrapGitHubUserCredential = `-- name: RewrapGitHubUserCredential :exec
UPDATE deck_github_user_credentials
SET wrapping_key_id = $1,
    user_access_token_ciphertext = $2,
    user_refresh_token_ciphertext = $3
WHERE connection_id = $4
  AND account_id = $5
`

type RewrapGitHubUserCredentialParams struct {
	WrappingKeyID              string
	UserAccessTokenCiphertext  []byte
	UserRefreshTokenCiphertext []byte
	ConnectionID               pgtype.UUID
	AccountID                  pgtype.UUID
}

func (q *Queries) RewrapGitHubUserCredential(ctx context.Context, arg RewrapGitHubUserCredentialParams) error {
	_, err := q.db.Exec(ctx, rewrapGitHubUserCredential,
		arg.WrappingKeyID,
		arg.UserAccessTokenCiphertext,
		arg.UserRefreshTokenCiphertext,
		arg.ConnectionID,
		arg.AccountID,
	)
	return err
}

const updateGitHubInstallationPermissions = `-- name: UpdateGitHubInstallationPermissions :one
UPDATE deck_connections
SET github_metadata_permission = $1,
    github_contents_permission = $2,
    github_pull_requests_permission = $3,
    github_checks_permission = $4,
    github_members_permission = $5,
    revision = revision + 1,
    updated_at = $6
WHERE connection_id = $7
  AND revision = $8
RETURNING connection_id, owner_scope, owner_id, state, revision, created_at, updated_at, github_installation_id, github_account_id, github_account_kind, github_account_login_ciphertext, github_metadata_permission, github_contents_permission, github_pull_requests_permission, github_checks_permission, github_members_permission
`

type UpdateGitHubInstallationPermissionsParams struct {
	GithubMetadataPermission     pgtype.Int2
	GithubContentsPermission     pgtype.Int2
	GithubPullRequestsPermission pgtype.Int2
	GithubChecksPermission       pgtype.Int2
	GithubMembersPermission      pgtype.Int2
	UpdatedAt                    pgtype.Timestamptz
	ConnectionID                 pgtype.UUID
	ExpectedRevision             int64
}

func (q *Queries) UpdateGitHubInstallationPermissions(ctx context.Context, arg UpdateGitHubInstallationPermissionsParams) (DeckConnection, error) {
	row := q.db.QueryRow(ctx, updateGitHubInstallationPermissions,
		arg.GithubMetadataPermission,
		arg.GithubContentsPermission,
		arg.GithubPullRequestsPermission,
		arg.GithubChecksPermission,
		arg.GithubMembersPermission,
		arg.UpdatedAt,
		arg.ConnectionID,
		arg.ExpectedRevision,
	)
	var i DeckConnection
	err := row.Scan(
		&i.ConnectionID,
		&i.OwnerScope,
		&i.OwnerID,
		&i.State,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubInstallationID,
		&i.GithubAccountID,
		&i.GithubAccountKind,
		&i.GithubAccountLoginCiphertext,
		&i.GithubMetadataPermission,
		&i.GithubContentsPermission,
		&i.GithubPullRequestsPermission,
		&i.GithubChecksPermission,
		&i.GithubMembersPermission,
	)
	return i, err
}

const updateGitHubUserCredentials = `-- name: UpdateGitHubUserCredentials :exec
UPDATE deck_github_user_credentials
SET wrapping_key_id = $1,
    user_access_token_ciphertext = $2,
    user_refresh_token_ciphertext = $3,
    user_access_token_expires_at = $4,
    user_refresh_token_expires_at = $5,
    updated_at = $6
WHERE account_id = $7
  AND github_user_id = $8
`

type UpdateGitHubUserCredentialsParams struct {
	WrappingKeyID              string
	UserAccessTokenCiphertext  []byte
	UserRefreshTokenCiphertext []byte
	UserAccessTokenExpiresAt   pgtype.Timestamptz
	UserRefreshTokenExpiresAt  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
	AccountID                  pgtype.UUID
	GithubUserID               int64
}

func (q *Queries) UpdateGitHubUserCredentials(ctx context.Context, arg UpdateGitHubUserCredentialsParams) error {
	_, err := q.db.Exec(ctx, updateGitHubUserCredentials,
		arg.WrappingKeyID,
		arg.UserAccessTokenCiphertext,
		arg.UserRefreshTokenCiphertext,
		arg.UserAccessTokenExpiresAt,
		arg.UserRefreshTokenExpiresAt,
		arg.UpdatedAt,
		arg.AccountID,
		arg.GithubUserID,
	)
	return err
}

const upsertGitHubUserCredential = `-- name: UpsertGitHubUserCredential :exec
INSERT INTO deck_github_user_credentials (
    connection_id, account_id, github_user_id, wrapping_key_id,
    user_access_token_ciphertext, user_refresh_token_ciphertext,
    user_access_token_expires_at,
    user_refresh_token_expires_at, updated_at
) VALUES (
    $1, $2, $3,
    $4,
    $5,
    $6,
    $7,
    $8, $9
)
ON CONFLICT (connection_id, account_id) DO UPDATE
SET github_user_id = EXCLUDED.github_user_id,
    wrapping_key_id = EXCLUDED.wrapping_key_id,
    user_access_token_ciphertext = EXCLUDED.user_access_token_ciphertext,
    user_refresh_token_ciphertext = EXCLUDED.user_refresh_token_ciphertext,
    user_access_token_expires_at = EXCLUDED.user_access_token_expires_at,
    user_refresh_token_expires_at = EXCLUDED.user_refresh_token_expires_at,
    updated_at = EXCLUDED.updated_at
`

type UpsertGitHubUserCredentialParams struct {
	ConnectionID               pgtype.UUID
	AccountID                  pgtype.UUID
	GithubUserID               int64
	WrappingKeyID              string
	UserAccessTokenCiphertext  []byte
	UserRefreshTokenCiphertext []byte
	UserAccessTokenExpiresAt   pgtype.Timestamptz
	UserRefreshTokenExpiresAt  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
}

func (q *Queries) UpsertGitHubUserCredential(ctx context.Context, arg UpsertGitHubUserCredentialParams) error {
	_, err := q.db.Exec(ctx, upsertGitHubUserCredential,
		arg.ConnectionID,
		arg.AccountID,
		arg.GithubUserID,
		arg.WrappingKeyID,
		arg.UserAccessTokenCiphertext,
		arg.UserRefreshTokenCiphertext,
		arg.UserAccessTokenExpiresAt,
		arg.UserRefreshTokenExpiresAt,
		arg.UpdatedAt,
	)
	return err
}
