// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountOrganizationViews(ctx context.Context, ownerOrganizationID pgtype.UUID) (int32, error)
	CountPersonalViews(ctx context.Context, ownerAccountID pgtype.UUID) (int32, error)
	DeactivateOrganizationMembershipsForAccount(ctx context.Context, accountID pgtype.UUID) error
	DeactivateTeamMembershipsForAccount(ctx context.Context, accountID pgtype.UUID) error
	DeleteAccountDevices(ctx context.Context, accountID pgtype.UUID) error
	DeleteDeckAccount(ctx context.Context, accountID pgtype.UUID) error
	DeleteDeviceByRegistrationAndAccount(ctx context.Context, arg DeleteDeviceByRegistrationAndAccountParams) (int64, error)
	DeleteDeviceByRegistrationAndGrant(ctx context.Context, arg DeleteDeviceByRegistrationAndGrantParams) (int64, error)
	DeleteExpiredDeviceByID(ctx context.Context, arg DeleteExpiredDeviceByIDParams) error
	DeleteExpiredDeviceIdempotency(ctx context.Context, now pgtype.Timestamptz) error
	DeleteOrganizationConnection(ctx context.Context, organizationID pgtype.UUID) error
	DeleteOrganizationFeatureData(ctx context.Context, organizationID pgtype.UUID) error
	DeleteOrganizationMemberships(ctx context.Context, organizationID pgtype.UUID) error
	DeleteOrganizationTeamMemberships(ctx context.Context, organizationID pgtype.UUID) error
	DeletePersonalConnection(ctx context.Context, accountID pgtype.UUID) error
	DeletePersonalFeatureData(ctx context.Context, accountID pgtype.UUID) error
	DeleteView(ctx context.Context, arg DeleteViewParams) (int64, error)
	DeleteViewCreateIdempotencyByOwnerHash(ctx context.Context, ownerHash []byte) error
	DeleteViewSnapshotState(ctx context.Context, arg DeleteViewSnapshotStateParams) error
	DeleteViewSnapshots(ctx context.Context, arg DeleteViewSnapshotsParams) error
	EnsureOwnerLock(ctx context.Context, ownerHash []byte) error
	GetCreateViewIdempotency(ctx context.Context, arg GetCreateViewIdempotencyParams) (DeckViewCreateIdempotency, error)
	GetDeckAccountBySubject(ctx context.Context, logtoSubject string) (DeckAccount, error)
	GetDeletionJobByReplayKey(ctx context.Context, replayKey pgtype.UUID) (DeckDeletionJob, error)
	GetDeviceByAccountAndID(ctx context.Context, arg GetDeviceByAccountAndIDParams) (DeckDeviceRegistration, error)
	GetDeviceByGrantVerifier(ctx context.Context, grantVerifier []byte) (DeckDeviceRegistration, error)
	GetDeviceByID(ctx context.Context, deviceID pgtype.UUID) (DeckDeviceRegistration, error)
	GetDeviceByRegistration(ctx context.Context, registrationID pgtype.UUID) (DeckDeviceRegistration, error)
	GetRegisterDeviceIdempotency(ctx context.Context, arg GetRegisterDeviceIdempotencyParams) (DeckDeviceRegistrationIdempotency, error)
	GetView(ctx context.Context, viewID pgtype.UUID) (DeckView, error)
	GetViewNotificationPreference(ctx context.Context, arg GetViewNotificationPreferenceParams) (DeckViewNotificationPreference, error)
	GetViewSnapshotState(ctx context.Context, arg GetViewSnapshotStateParams) (DeckPullRequestSnapshotState, error)
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error
	InsertCreateViewIdempotency(ctx context.Context, arg InsertCreateViewIdempotencyParams) error
	InsertDeletionJob(ctx context.Context, arg InsertDeletionJobParams) (DeckDeletionJob, error)
	InsertDevice(ctx context.Context, arg InsertDeviceParams) (DeckDeviceRegistration, error)
	InsertOwnerTombstone(ctx context.Context, arg InsertOwnerTombstoneParams) error
	InsertRegisterDeviceIdempotency(ctx context.Context, arg InsertRegisterDeviceIdempotencyParams) error
	InsertView(ctx context.Context, arg InsertViewParams) (DeckView, error)
	InsertViewSnapshot(ctx context.Context, arg InsertViewSnapshotParams) error
	IsOwnerTombstoned(ctx context.Context, targetHash []byte) (bool, error)
	ListDeviceRegistrationsForUpdate(ctx context.Context) ([]DeckDeviceRegistration, error)
	ListOrganizationMembershipsForAccount(ctx context.Context, accountID pgtype.UUID) ([]ListOrganizationMembershipsForAccountRow, error)
	ListOrganizationViewIDsForUpdate(ctx context.Context, organizationID pgtype.UUID) ([]pgtype.UUID, error)
	ListOrganizationViews(ctx context.Context, arg ListOrganizationViewsParams) ([]DeckView, error)
	ListPersonalViews(ctx context.Context, arg ListPersonalViewsParams) ([]DeckView, error)
	ListTeamMembershipsForAccount(ctx context.Context, accountID pgtype.UUID) ([]ListTeamMembershipsForAccountRow, error)
	ListViewSnapshots(ctx context.Context, arg ListViewSnapshotsParams) ([]DeckPullRequestSnapshot, error)
	LockOwner(ctx context.Context, ownerHash []byte) ([]byte, error)
	Ping(ctx context.Context) (int32, error)
	RenewDevice(ctx context.Context, arg RenewDeviceParams) (DeckDeviceRegistration, error)
	UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (DeckDeviceRegistration, error)
	UpdateDeviceViewStateAfterDeletion(ctx context.Context, arg UpdateDeviceViewStateAfterDeletionParams) error
	UpdateView(ctx context.Context, arg UpdateViewParams) (DeckView, error)
	UpdateViewSnapshotState(ctx context.Context, arg UpdateViewSnapshotStateParams) error
	UpsertDeckAccount(ctx context.Context, arg UpsertDeckAccountParams) error
	UpsertOrganizationMembership(ctx context.Context, arg UpsertOrganizationMembershipParams) error
	UpsertTeamMembership(ctx context.Context, arg UpsertTeamMembershipParams) error
	UpsertViewNotificationPreference(ctx context.Context, arg UpsertViewNotificationPreferenceParams) (DeckViewNotificationPreference, error)
}

var _ Querier = (*Queries)(nil)
