use std::{
    collections::{BTreeSet, HashSet},
    fs,
    io::Read,
    path::{Component, Path, PathBuf},
};

use pnp::{Manifest, PackageDependency, PackageInformation, PackageLocator, Resolution};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use sha2::{Digest, Sha256};

use crate::diagnostic::{manifest_error, Code, Error, Result};

const MAX_MANIFEST: u64 = 64 * 1024 * 1024;

pub fn digest(bytes: &[u8]) -> String {
    format!("{:x}", Sha256::digest(bytes))
}

pub fn normalize(path: &Path) -> PathBuf {
    let mut result = PathBuf::new();
    for part in path.components() {
        match part {
            Component::CurDir => {}
            Component::ParentDir => {
                result.pop();
            }
            _ => result.push(part),
        }
    }
    result
}

pub fn select(project: Option<&Path>, cwd: &Path) -> Result<PathBuf> {
    if let Some(project) = project {
        let path = normalize(&cwd.join(project));
        let path = if path.is_dir() {
            path.join(".pnp.cjs")
        } else {
            path
        };
        if path.file_name().is_some_and(|n| n == ".pnp.cjs") && path.is_file() {
            return Ok(path);
        }
    } else {
        for parent in cwd.ancestors() {
            let path = parent.join(".pnp.cjs");
            match fs::symlink_metadata(&path) {
                Ok(_) => return Ok(path),
                Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
                Err(_) => return Err(manifest_error()),
            }
        }
    }
    Err(Error::new(
        Code::PnportManifestMissing,
        "No .pnp.cjs found; select an installed Yarn 4 project with --project.",
    ))
}

fn read_manifest(path: &Path) -> Result<Vec<u8>> {
    let mut bytes = Vec::new();
    fs::File::open(path)
        .map_err(|_| manifest_error())?
        .take(MAX_MANIFEST + 1)
        .read_to_end(&mut bytes)
        .map_err(|_| manifest_error())?;
    if bytes.len() as u64 > MAX_MANIFEST {
        return Err(manifest_error());
    }
    Ok(bytes)
}

/// Decode only Yarn's single-quoted data string. Never evaluate JavaScript.
fn inline_data(source: &str) -> Result<Option<String>> {
    let Some(offset) = source
        .match_indices("const RAW_RUNTIME_STATE")
        .find_map(|(offset, _)| {
            let line = source[..offset]
                .rsplit_once('\n')
                .map_or(&source[..offset], |(_, line)| line);
            line.trim()
                .is_empty()
                .then_some(offset + "const RAW_RUNTIME_STATE".len())
        })
    else {
        return Ok(None);
    };
    let start = source[offset..]
        .trim_start()
        .strip_prefix('=')
        .ok_or_else(manifest_error)?
        .trim_start();
    let Some(start) = start.strip_prefix('\'') else {
        return Err(manifest_error());
    };
    let mut chars = start.chars();
    let mut data = String::new();
    while let Some(c) = chars.next() {
        match c {
            '\'' => return Ok(Some(data)),
            '\\' => match chars.next().ok_or_else(manifest_error)? {
                '\\' => data.push('\\'),
                '\'' => data.push('\''),
                '\n' => {}
                '\r' => {
                    if chars.clone().next() == Some('\n') {
                        chars.next();
                    }
                }
                'n' => data.push('\n'),
                'r' => data.push('\r'),
                't' => data.push('\t'),
                _ => return Err(manifest_error()),
            },
            _ => data.push(c),
        }
    }
    Err(manifest_error())
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Input {
    pub path: PathBuf,
    pub sha256: String,
}
#[derive(Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Snapshot {
    pub schema_version: u32,
    pub manifest_path: PathBuf,
    pub data: Value,
    pub inputs: Vec<Input>,
}
pub struct Graph {
    pub snapshot: Snapshot,
    pub manifest: Manifest,
    pub identity: String,
    managed_locators: HashSet<PackageLocator>,
    location_ancestors: HashSet<PathBuf>,
}

impl Graph {
    pub fn load(path: &Path) -> Result<Self> {
        let path = fs::canonicalize(path).map_err(|_| manifest_error())?;
        let bytes = read_manifest(&path)?;
        let source = std::str::from_utf8(&bytes).map_err(|_| manifest_error())?;
        let mut inputs = vec![Input {
            path: path.clone(),
            sha256: digest(&bytes),
        }];
        let data = match inline_data(source)? {
            Some(data) => serde_json::from_str(&data).map_err(|_| manifest_error())?,
            None => {
                // Split loaders generated by Yarn read this exact sibling. A stale
                // data file must not override a malformed or unknown inline loader.
                if !source.lines().any(|line| {
                    line.trim()
                        == "const pnpDataFilepath = path.resolve(__dirname, \".pnp.data.json\");"
                }) {
                    return Err(manifest_error());
                }
                let data_path = path.with_file_name(".pnp.data.json");
                let bytes = read_manifest(&data_path)?;
                inputs.push(Input {
                    path: data_path,
                    sha256: digest(&bytes),
                });
                serde_json::from_slice(&bytes).map_err(|_| manifest_error())?
            }
        };
        Self::from_snapshot(Snapshot {
            schema_version: 1,
            manifest_path: path,
            data,
            inputs,
        })
    }

    pub fn from_snapshot(snapshot: Snapshot) -> Result<Self> {
        if snapshot.schema_version != 1 || !snapshot.manifest_path.is_absolute() {
            return Err(manifest_error());
        }
        validate_data(&snapshot.data)?;
        let mut manifest: Manifest =
            serde_json::from_value(snapshot.data.clone()).map_err(|_| manifest_error())?;
        validate_references(&manifest)?;
        pnp::init_pnp_manifest(&mut manifest, &snapshot.manifest_path);
        // pnp does not retain linkType. Index it once instead of rescanning the
        // JSON registry for every source-file syscall under the preload mutex.
        let mut managed_locators = HashSet::new();
        for record in snapshot.data["packageRegistryData"]
            .as_array()
            .ok_or_else(manifest_error)?
        {
            for entry in record[1].as_array().ok_or_else(manifest_error)? {
                if entry[1]["linkType"] == "HARD" {
                    managed_locators.insert(PackageLocator {
                        name: record[0].as_str().unwrap_or("").to_owned(),
                        reference: entry[0].as_str().unwrap_or("").to_owned(),
                    });
                }
            }
        }
        let location_ancestors = manifest
            .package_registry_data
            .values()
            .flat_map(|entries| entries.values())
            .flat_map(|package| {
                normalize(&package.package_location)
                    .ancestors()
                    .skip(1)
                    .map(Path::to_owned)
                    .collect::<Vec<_>>()
            })
            .collect();
        let identity = digest(&serde_json::to_vec(&snapshot).map_err(|_| manifest_error())?);
        tracing::debug!(action = "graph_loaded", graph = %identity, packages = manifest.package_registry_data.len());
        Ok(Self {
            snapshot,
            manifest,
            identity,
            managed_locators,
            location_ancestors,
        })
    }

    pub fn unchanged(&self) -> Result<()> {
        for input in &self.snapshot.inputs {
            if read_manifest(&input.path).map(|b| digest(&b)).ok().as_ref() != Some(&input.sha256) {
                return Err(Error::new(
                    Code::PnportGraphChanged,
                    "PnP data changed or disappeared; restart pnport to load a new snapshot.",
                ));
            }
        }
        Ok(())
    }

    pub fn resolve(&self, name: &str, issuer: &Path) -> Result<PathBuf> {
        match pnp::resolve_to_unqualified_via_manifest(&self.manifest, name, issuer) {
            Ok(Resolution::Resolved(path, sub)) => {
                Ok(sub.map_or(path.clone(), |sub| path.join(sub)))
            }
            _ => Err(Error::new(
                Code::PnportResolutionFailed,
                "The selected PnP graph does not provide this dependency for the issuer.",
            )),
        }
    }

    pub fn package(&self, issuer: &Path) -> Option<&PackageInformation> {
        let locator = pnp::find_locator(&self.manifest, issuer)?;
        self.manifest
            .package_registry_data
            .get(&locator.name)?
            .get(&locator.reference)
    }

    pub fn managed(&self, path: &Path) -> bool {
        let Some(locator) = pnp::find_locator(&self.manifest, path) else {
            return false;
        };
        self.managed_locators.contains(locator)
    }

    pub fn is_location_ancestor(&self, path: &Path) -> bool {
        self.location_ancestors.contains(path)
    }

    pub fn dependency_names(&self, issuer: &Path) -> Vec<String> {
        let Some(package) = self.package(issuer) else {
            return vec![];
        };
        let mut names: BTreeSet<_> = package.package_dependencies.keys().cloned().collect();
        if self.manifest.enable_top_level_fallback {
            names.extend(self.manifest.fallback_pool.keys().cloned());
        }
        names
            .into_iter()
            .filter(|name| self.resolve(name, issuer).is_ok())
            .collect()
    }

    pub fn check_conflicts(&self) -> Result<()> {
        for entries in self.manifest.package_registry_data.values() {
            for package in entries.values() {
                let path = &package.package_location;
                // ZIP-internal node_modules is package content, not a physical
                // project collision. Workspace/unplugged roots remain checked.
                if matches!(pnp::fs::VPath::from(path), Ok(pnp::fs::VPath::Native(_))) {
                    check_conflict(&path.join("node_modules"))?;
                }
            }
        }
        Ok(())
    }
}

pub fn check_conflict(path: &Path) -> Result<()> {
    match fs::symlink_metadata(path) {
        Ok(_) => Err(Error::new(
            Code::PnportFilesystemConflict,
            "A physical node_modules conflicts with the virtual view; move it yourself before \
             restarting.",
        )),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(_) => Err(Error::new(
            Code::PnportFilesystemConflict,
            "Cannot establish whether a physical node_modules conflicts with the virtual view.",
        )),
    }
}

fn name_valid(name: &str) -> bool {
    let parts: Vec<_> = name.split('/').collect();
    let safe =
        |p: &&str| !p.is_empty() && !matches!(*p, "." | "..") && !p.contains(['\\', ':', '\0']);
    (parts.len() == 1 && !name.starts_with('@')
        || parts.len() == 2 && parts[0].starts_with('@') && parts[0].len() > 1)
        && parts.iter().all(safe)
}

fn validate_data(data: &Value) -> Result<()> {
    let registry = data
        .get("packageRegistryData")
        .and_then(Value::as_array)
        .ok_or_else(manifest_error)?;
    let mut names = BTreeSet::new();
    for record in registry {
        let record = record
            .as_array()
            .filter(|v| v.len() == 2)
            .ok_or_else(manifest_error)?;
        if !record[0].is_null() && !record[0].as_str().is_some_and(name_valid) {
            return Err(manifest_error());
        }
        if !names.insert(record[0].to_string()) {
            return Err(manifest_error());
        }
        let mut refs = BTreeSet::new();
        for entry in record[1].as_array().ok_or_else(manifest_error)? {
            let entry = entry
                .as_array()
                .filter(|v| v.len() == 2)
                .ok_or_else(manifest_error)?;
            if !refs.insert(entry[0].to_string()) {
                return Err(manifest_error());
            }
            let info = &entry[1];
            if !info
                .get("packageLocation")
                .and_then(Value::as_str)
                .is_some_and(|s| !s.is_empty() && !s.contains('\0'))
            {
                return Err(manifest_error());
            }
            let mut deps = BTreeSet::new();
            for dep in info
                .get("packageDependencies")
                .and_then(Value::as_array)
                .ok_or_else(manifest_error)?
            {
                let dep = dep
                    .as_array()
                    .filter(|v| v.len() == 2)
                    .ok_or_else(manifest_error)?;
                let name = dep[0]
                    .as_str()
                    .filter(|s| name_valid(s))
                    .ok_or_else(manifest_error)?;
                if !deps.insert(name) {
                    return Err(manifest_error());
                }
            }
        }
    }
    Ok(())
}

fn validate_references(manifest: &Manifest) -> Result<()> {
    let get = |locator: &PackageLocator| {
        manifest
            .package_registry_data
            .get(&locator.name)
            .and_then(|refs| refs.get(&locator.reference))
    };
    if get(&PackageLocator::default()).is_none() {
        return Err(manifest_error());
    }
    for root in &manifest.dependency_tree_roots {
        if get(root).is_none() {
            return Err(manifest_error());
        }
    }
    for (name, dep) in manifest
        .package_registry_data
        .values()
        .flat_map(|entries| entries.values())
        .flat_map(|pkg| pkg.package_dependencies.iter())
        .chain(manifest.fallback_pool.iter())
    {
        let locator = match dep {
            Some(PackageDependency::Reference(reference)) => PackageLocator {
                name: name.clone(),
                reference: reference.clone(),
            },
            Some(PackageDependency::Alias(name, reference)) => PackageLocator {
                name: name.clone(),
                reference: reference.clone(),
            },
            None => continue,
        };
        if !name_valid(&locator.name) || get(&locator).is_none() {
            return Err(manifest_error());
        }
    }
    Ok(())
}
