import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import yaml from "js-yaml";

test("Workflow keeps credentials, OIDC and actual signing out of every dry-run job", () => {
  const workflow = yaml.load(readFileSync(new URL("../../.github/workflows/release-runmoor.yml", import.meta.url), "utf8"));
  assert.deepEqual(workflow.permissions, { contents: "read" });
  assert.equal(workflow.on.workflow_dispatch.inputs.dry_run.default, true);
  assert.deepEqual(workflow.on.push.tags, ["runmoor@v*"]);
  for (const [name, job] of Object.entries(workflow.jobs)) {
    if (name === "publish" || name === "homebrew") continue;
    assert.equal(job.permissions?.["id-token"], undefined);
    assert.doesNotMatch(JSON.stringify(job), /secrets\.|cosign|sign-blob|action-gh-release/u);
  }
  const publish = workflow.jobs.publish;
  assert.equal(publish.if, "needs.plan.outputs.mode == 'publish'");
  assert.deepEqual(publish.permissions, { contents: "write", "id-token": "write" });
  const reuseStep = publish.steps.find((step) => step.name === "Inspect and reuse existing stable draft");
  assert.match(reuseStep.run, /checkPublication\(plan, request\)/u);
  assert.match(reuseStep.run, /assetManifest\(draftDirectory, true\)/u);
  assert.match(reuseStep.run, /verify\(draftDirectory, true, \{identity\}\)/u);
  const preflightStep = publish.steps.find((step) => step.name === "Revalidate release identity before draft upload");
  const preflight = preflightStep.run;
  assert.match(preflight, /checkPublication\(plan, githubRequest/u);
  assert.match(preflight, /RUNMOOR_RELEASE_ID/u);
  const signStep = publish.steps.find((step) => step.name === "Sign exact artifacts with Sigstore");
  const sign = signStep.run;
  assert.equal(signStep.if, "env.RUNMOOR_REUSE_DRAFT != 'true'");
  assert.match(sign, /--signed true --identity "https:\/\/github.com\/\$\{GITHUB_WORKFLOW_REF\}"/u);
  const verifier = readFileSync(new URL("../release/runmoor.mjs", import.meta.url), "utf8");
  assert.match(verifier, /"verify-blob", "--bundle"/u);
  assert.match(verifier, /"--certificate-oidc-issuer", "https:\/\/token.actions.githubusercontent.com"/u);
  const release = publish.steps.find((step) => step.uses?.startsWith("softprops/"));
  assert.equal(release.id, "release-draft");
  assert.equal(release.if, "env.RUNMOOR_REUSE_DRAFT != 'true'");
  assert.equal(release.with.draft, true);
  assert.equal(release.with.prerelease, false);
  assert.equal(release.with.overwrite_files, false);
  assert.equal(release.with.body_path, "scripts/release/runmoor-release-notes.md");
  const pinStep = publish.steps.find((step) => step.name === "Pin stable release draft");
  assert.equal(pinStep.env.CREATED_RELEASE_ID, "${{ steps.release-draft.outputs.id }}");
  assert.match(pinStep.run, /checkPublication\(plan, githubRequest\(process.env.GH_TOKEN\), undefined, releaseId\)/u);
  assert.match(pinStep.run, /existingId !== createdId/u);
  const finalVerificationStep = publish.steps.find((step) => step.name === "Download and verify complete stable release draft");
  assert.match(finalVerificationStep.run, /assetManifest\(draftDirectory, true\)/u);
  assert.match(finalVerificationStep.run, /verify\(draftDirectory, true, \{identity\}\)/u);
  const publishStable = publish.steps.find((step) => step.name === "Publish stable release");
  assert.match(publishStable.run, /publishDraft\(plan, githubRequest/u);
  assert.match(publishStable.run, /releaseId: Number\(process.env.RUNMOOR_RELEASE_ID\)/u);
  assert.match(publishStable.run, /runmoor-verified-assets\.json/u);
  assert.match(finalVerificationStep.run, /checkPublication\(plan, request, downloaded, releaseId\)/u);
  assert.ok(finalVerificationStep.run.indexOf("verify(draftDirectory, true, {identity})") < finalVerificationStep.run.indexOf("writeFileSync(path.join(process.env.RUNNER_TEMP"));
  assert.match(reuseStep.run, /RUNMOOR_RELEASE_ID=\$\{release.id\}/u);
  assert.match(reuseStep.run, /checkPublication\(plan, request, downloaded, release.id\)/u);
  assert.equal(publishStable.env.GH_TOKEN, "${{ github.token }}");
  assert.equal(publishStable.env.RUNMOOR_RELEASE_NOTES, "scripts/release/runmoor-release-notes.md");
  assert.match(readFileSync(new URL("../release/runmoor-release-notes.md", import.meta.url), "utf8"), /Live GitHub repository\/organization and App\/PAT compatibility and real Tart execution have not been certified\./u);
  assert.ok(publish.steps.indexOf(reuseStep) < publish.steps.indexOf(signStep));
  assert.ok(publish.steps.indexOf(signStep) < publish.steps.indexOf(preflightStep));
  assert.ok(publish.steps.indexOf(preflightStep) < publish.steps.indexOf(release));
  assert.ok(publish.steps.indexOf(release) < publish.steps.indexOf(pinStep));
  assert.ok(publish.steps.indexOf(pinStep) < publish.steps.indexOf(finalVerificationStep));
  assert.ok(publish.steps.indexOf(finalVerificationStep) < publish.steps.indexOf(publishStable));
  assert.ok(publish.steps.indexOf(release) < publish.steps.indexOf(publishStable));
});

test("Runmoor Homebrew verifies and installs before obtaining tap-only publication credentials", () => {
  const release = yaml.load(readFileSync(new URL("../../.github/workflows/release-runmoor.yml", import.meta.url), "utf8"));
  const call = release.jobs.homebrew;
  assert.deepEqual(call.needs, ["plan", "publish"]);
  assert.equal(call.if, "needs.plan.outputs.mode == 'publish'");
  assert.equal(call.uses, "./.github/workflows/release-runmoor-homebrew.yml");
  assert.equal(call.with.dry_run, false);
  assert.deepEqual(call.permissions, { contents: "read" });
  assert.match(JSON.stringify(release.jobs.package), /runmoor-homebrew\.mjs render/u);
  const workflow = yaml.load(readFileSync(new URL("../../.github/workflows/release-runmoor-homebrew.yml", import.meta.url), "utf8"));
  assert.deepEqual(workflow.permissions, { contents: "read" });
  assert.equal(workflow.on.workflow_dispatch.inputs.dry_run.default, true);
  assert.equal(workflow.on.workflow_call.inputs.dry_run.default, true);
  assert.equal(workflow.jobs.homebrew["runs-on"], "macos-15");
  assert.doesNotMatch(JSON.stringify(workflow), /id-token|sign-blob|action-gh-release/u);
  const steps = workflow.jobs.homebrew.steps;
  const validation = steps.findIndex((step) => step.name === "Validate Homebrew installation on Apple Silicon");
  const token = steps.findIndex((step) => step.id === "tap-bot");
  assert.ok(steps.findIndex((step) => step.name === "Validate publication context before credentials") < token);
  assert.ok(validation < token);
  assert.match(steps[validation].run, /brew install --formula/u);
  assert.match(steps[validation].run, /brew test/u);
  assert.match(steps[validation].run, /\$RELEASE_REVISION/u);
  assert.equal(steps[token].with.repositories, "homebrew-tap");
  assert.equal(steps[token].with["permission-contents"], "write");
  for (const step of steps.slice(token)) assert.equal(step.if, "${{ !inputs.dry_run }}");
  const publish = steps.find((step) => step.name === "Publish verified Homebrew Formula");
  assert.equal(publish.env.HOMEBREW_TAP_GH_TOKEN, "${{ steps.tap-bot.outputs.token }}");
  assert.match(steps.at(-1).run, /brew install delinoio\/tap\/runmoor/u);
});
