// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: identity.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGeneralTeam = `-- name: CreateGeneralTeam :one
INSERT INTO teams (id, organization_id, name, protected_general)
VALUES ($1, $2, 'General', true)
RETURNING id, organization_id, parent_team_id, name, protected_general, created_at, updated_at
`

type CreateGeneralTeamParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) CreateGeneralTeam(ctx context.Context, arg CreateGeneralTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createGeneralTeam, arg.ID, arg.OrganizationID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ParentTeamID,
		&i.Name,
		&i.ProtectedGeneral,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (id, name, slug)
VALUES ($1, $2, $3)
RETURNING id, name, slug, overage_limit_micros, deleted_at, created_at, updated_at
`

type CreateOrganizationParams struct {
	ID   pgtype.UUID
	Name string
	Slug string
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.ID, arg.Name, arg.Slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OverageLimitMicros,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganizationMembership = `-- name: CreateOrganizationMembership :one
INSERT INTO organization_memberships (organization_id, account_id, role)
VALUES (
    $1,
    $2,
    $3
)
RETURNING organization_id, account_id, role, created_at, updated_at
`

type CreateOrganizationMembershipParams struct {
	OrganizationID pgtype.UUID
	AccountID      pgtype.UUID
	Role           string
}

func (q *Queries) CreateOrganizationMembership(ctx context.Context, arg CreateOrganizationMembershipParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, createOrganizationMembership, arg.OrganizationID, arg.AccountID, arg.Role)
	var i OrganizationMembership
	err := row.Scan(
		&i.OrganizationID,
		&i.AccountID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPolarCustomer = `-- name: CreatePolarCustomer :one
INSERT INTO polar_customers (organization_id, polar_customer_id)
VALUES (
    $1::uuid,
    $2
)
RETURNING organization_id, polar_customer_id, created_at, updated_at
`

type CreatePolarCustomerParams struct {
	OrganizationID  pgtype.UUID
	PolarCustomerID string
}

func (q *Queries) CreatePolarCustomer(ctx context.Context, arg CreatePolarCustomerParams) (PolarCustomer, error) {
	row := q.db.QueryRow(ctx, createPolarCustomer, arg.OrganizationID, arg.PolarCustomerID)
	var i PolarCustomer
	err := row.Scan(
		&i.OrganizationID,
		&i.PolarCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTeamMembership = `-- name: CreateTeamMembership :one
INSERT INTO team_memberships (organization_id, team_id, account_id, role)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING organization_id, team_id, account_id, role, created_at, updated_at
`

type CreateTeamMembershipParams struct {
	OrganizationID pgtype.UUID
	TeamID         pgtype.UUID
	AccountID      pgtype.UUID
	Role           string
}

func (q *Queries) CreateTeamMembership(ctx context.Context, arg CreateTeamMembershipParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, createTeamMembership,
		arg.OrganizationID,
		arg.TeamID,
		arg.AccountID,
		arg.Role,
	)
	var i TeamMembership
	err := row.Scan(
		&i.OrganizationID,
		&i.TeamID,
		&i.AccountID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const currentOrganizationBalance = `-- name: CurrentOrganizationBalance :one
SELECT COALESCE((
    SELECT balance_after_micros
    FROM ledger_entries
    WHERE organization_id = $1
    ORDER BY created_at DESC, id DESC
    LIMIT 1
), 0)::bigint AS balance_micros
`

func (q *Queries) CurrentOrganizationBalance(ctx context.Context, organizationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, currentOrganizationBalance, organizationID)
	var balance_micros int64
	err := row.Scan(&balance_micros)
	return balance_micros, err
}

const deleteAccountMemberships = `-- name: DeleteAccountMemberships :execrows
DELETE FROM organization_memberships
WHERE account_id = $1
`

func (q *Queries) DeleteAccountMemberships(ctx context.Context, accountID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccountMemberships, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDisabledAccount = `-- name: DeleteDisabledAccount :execrows
DELETE FROM accounts
WHERE id = $1
  AND status = 'disabled'
`

func (q *Queries) DeleteDisabledAccount(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDisabledAccount, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOrganizationMembership = `-- name: DeleteOrganizationMembership :execrows
DELETE FROM organization_memberships
WHERE organization_id = $1
  AND account_id = $2
`

type DeleteOrganizationMembershipParams struct {
	OrganizationID pgtype.UUID
	AccountID      pgtype.UUID
}

func (q *Queries) DeleteOrganizationMembership(ctx context.Context, arg DeleteOrganizationMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrganizationMembership, arg.OrganizationID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOrganizationOperationalData = `-- name: DeleteOrganizationOperationalData :one
SELECT delete_organization_operational_data($1::uuid)
`

func (q *Queries) DeleteOrganizationOperationalData(ctx context.Context, organizationID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, deleteOrganizationOperationalData, organizationID)
	var delete_organization_operational_data bool
	err := row.Scan(&delete_organization_operational_data)
	return delete_organization_operational_data, err
}

const disableAndEraseAccount = `-- name: DisableAndEraseAccount :one
UPDATE accounts
SET display_name = '',
    status = 'disabled',
    updated_at = transaction_timestamp()
WHERE id = $1
  AND status = 'active'
RETURNING id, logto_subject, display_name, status, created_at, updated_at
`

func (q *Queries) DisableAndEraseAccount(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, disableAndEraseAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.LogtoSubject,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureAccount = `-- name: EnsureAccount :one
INSERT INTO accounts (id, logto_subject, display_name)
VALUES ($1, $2, $3)
ON CONFLICT (logto_subject) DO UPDATE
SET logto_subject = EXCLUDED.logto_subject
RETURNING id, logto_subject, display_name, status, created_at, updated_at
`

type EnsureAccountParams struct {
	ID           pgtype.UUID
	LogtoSubject string
	DisplayName  string
}

func (q *Queries) EnsureAccount(ctx context.Context, arg EnsureAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, ensureAccount, arg.ID, arg.LogtoSubject, arg.DisplayName)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.LogtoSubject,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const forfeitOrganizationCredit = `-- name: ForfeitOrganizationCredit :one
INSERT INTO ledger_entries (
    id,
    organization_id,
    entry_type,
    amount_micros,
    balance_after_micros,
    source_reference,
    actor_reference
) VALUES (
    $1,
    $2,
    'credit_forfeiture',
    -$3::bigint,
    0,
    $4,
    $5
)
RETURNING id, organization_id, billing_period_id, billing_period_starts_at_snapshot, billing_period_ends_at_snapshot, entry_type, amount_micros, balance_after_micros, reservation_id, usage_record_id, team_id_snapshot, team_name_snapshot, source_reference, actor_reference, created_at, retain_until
`

type ForfeitOrganizationCreditParams struct {
	ID              pgtype.UUID
	OrganizationID  pgtype.UUID
	AmountMicros    int64
	SourceReference string
	ActorReference  string
}

func (q *Queries) ForfeitOrganizationCredit(ctx context.Context, arg ForfeitOrganizationCreditParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, forfeitOrganizationCredit,
		arg.ID,
		arg.OrganizationID,
		arg.AmountMicros,
		arg.SourceReference,
		arg.ActorReference,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.BillingPeriodID,
		&i.BillingPeriodStartsAtSnapshot,
		&i.BillingPeriodEndsAtSnapshot,
		&i.EntryType,
		&i.AmountMicros,
		&i.BalanceAfterMicros,
		&i.ReservationID,
		&i.UsageRecordID,
		&i.TeamIDSnapshot,
		&i.TeamNameSnapshot,
		&i.SourceReference,
		&i.ActorReference,
		&i.CreatedAt,
		&i.RetainUntil,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, logto_subject, display_name, status, created_at, updated_at
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.LogtoSubject,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCancelablePolarSubscriptionForOrganization = `-- name: GetCancelablePolarSubscriptionForOrganization :one
SELECT polar_subscription_id
FROM subscriptions
WHERE organization_id = $1
  AND status IN ('pending', 'active', 'past_due')
ORDER BY
    CASE status
        WHEN 'active' THEN 0
        WHEN 'past_due' THEN 1
        ELSE 2
    END,
    created_at DESC
LIMIT 1
`

func (q *Queries) GetCancelablePolarSubscriptionForOrganization(ctx context.Context, organizationID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getCancelablePolarSubscriptionForOrganization, organizationID)
	var polar_subscription_id string
	err := row.Scan(&polar_subscription_id)
	return polar_subscription_id, err
}

const getDeletedAccountSubject = `-- name: GetDeletedAccountSubject :one
SELECT subject_digest, account_id, actor_reference, deleted_at, retain_until
FROM deleted_account_subjects
WHERE subject_digest = $1
`

func (q *Queries) GetDeletedAccountSubject(ctx context.Context, subjectDigest []byte) (DeletedAccountSubject, error) {
	row := q.db.QueryRow(ctx, getDeletedAccountSubject, subjectDigest)
	var i DeletedAccountSubject
	err := row.Scan(
		&i.SubjectDigest,
		&i.AccountID,
		&i.ActorReference,
		&i.DeletedAt,
		&i.RetainUntil,
	)
	return i, err
}

const getIdempotencyRecord = `-- name: GetIdempotencyRecord :one
SELECT id, caller_kind, caller_id, operation, idempotency_key, request_hash, response_payload, connect_code, created_at, expires_at
FROM idempotency_records
WHERE caller_kind = $1
  AND caller_id = $2
  AND operation = $3
  AND idempotency_key = $4
  AND expires_at > transaction_timestamp()
`

type GetIdempotencyRecordParams struct {
	CallerKind     string
	CallerID       string
	Operation      string
	IdempotencyKey string
}

func (q *Queries) GetIdempotencyRecord(ctx context.Context, arg GetIdempotencyRecordParams) (IdempotencyRecord, error) {
	row := q.db.QueryRow(ctx, getIdempotencyRecord,
		arg.CallerKind,
		arg.CallerID,
		arg.Operation,
		arg.IdempotencyKey,
	)
	var i IdempotencyRecord
	err := row.Scan(
		&i.ID,
		&i.CallerKind,
		&i.CallerID,
		&i.Operation,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ResponsePayload,
		&i.ConnectCode,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, slug, overage_limit_micros, deleted_at, created_at, updated_at
FROM organizations
WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OverageLimitMicros,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationForAccount = `-- name: GetOrganizationForAccount :one
SELECT organization.id, organization.name, organization.slug, organization.overage_limit_micros, organization.deleted_at, organization.created_at, organization.updated_at, membership.role AS caller_role
FROM organizations AS organization
JOIN organization_memberships AS membership
  ON membership.organization_id = organization.id
WHERE organization.id = $1
  AND membership.account_id = $2
  AND organization.deleted_at IS NULL
`

type GetOrganizationForAccountParams struct {
	OrganizationID pgtype.UUID
	AccountID      pgtype.UUID
}

type GetOrganizationForAccountRow struct {
	ID                 pgtype.UUID
	Name               string
	Slug               string
	OverageLimitMicros int64
	DeletedAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	CallerRole         string
}

func (q *Queries) GetOrganizationForAccount(ctx context.Context, arg GetOrganizationForAccountParams) (GetOrganizationForAccountRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationForAccount, arg.OrganizationID, arg.AccountID)
	var i GetOrganizationForAccountRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OverageLimitMicros,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CallerRole,
	)
	return i, err
}

const getOrganizationMember = `-- name: GetOrganizationMember :one
SELECT
    membership.organization_id,
    membership.account_id,
    account.display_name,
    membership.role,
    membership.created_at,
    membership.updated_at
FROM organization_memberships AS membership
JOIN accounts AS account ON account.id = membership.account_id
JOIN organizations AS organization
  ON organization.id = membership.organization_id
WHERE membership.organization_id = $1
  AND membership.account_id = $2
  AND account.status = 'active'
  AND organization.deleted_at IS NULL
`

type GetOrganizationMemberParams struct {
	OrganizationID pgtype.UUID
	AccountID      pgtype.UUID
}

type GetOrganizationMemberRow struct {
	OrganizationID pgtype.UUID
	AccountID      pgtype.UUID
	DisplayName    string
	Role           string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetOrganizationMember(ctx context.Context, arg GetOrganizationMemberParams) (GetOrganizationMemberRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationMember, arg.OrganizationID, arg.AccountID)
	var i GetOrganizationMemberRow
	err := row.Scan(
		&i.OrganizationID,
		&i.AccountID,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationMembership = `-- name: GetOrganizationMembership :one
SELECT membership.organization_id, membership.account_id, membership.role, membership.created_at, membership.updated_at
FROM organization_memberships AS membership
JOIN accounts AS account ON account.id = membership.account_id
JOIN organizations AS organization
  ON organization.id = membership.organization_id
WHERE membership.organization_id = $1
  AND membership.account_id = $2
  AND account.status = 'active'
  AND organization.deleted_at IS NULL
`

type GetOrganizationMembershipParams struct {
	OrganizationID pgtype.UUID
	AccountID      pgtype.UUID
}

func (q *Queries) GetOrganizationMembership(ctx context.Context, arg GetOrganizationMembershipParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, getOrganizationMembership, arg.OrganizationID, arg.AccountID)
	var i OrganizationMembership
	err := row.Scan(
		&i.OrganizationID,
		&i.AccountID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasAccountOrganization = `-- name: HasAccountOrganization :one
SELECT EXISTS (
    SELECT 1
    FROM organization_memberships AS membership
    JOIN organizations AS organization
      ON organization.id = membership.organization_id
    WHERE membership.account_id = $1
      AND organization.deleted_at IS NULL
)
`

func (q *Queries) HasAccountOrganization(ctx context.Context, accountID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasAccountOrganization, accountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertDeletedAccountSubject = `-- name: InsertDeletedAccountSubject :one
INSERT INTO deleted_account_subjects (
    subject_digest,
    account_id,
    actor_reference
) VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (subject_digest) DO NOTHING
RETURNING subject_digest, account_id, actor_reference, deleted_at, retain_until
`

type InsertDeletedAccountSubjectParams struct {
	SubjectDigest  []byte
	AccountID      pgtype.UUID
	ActorReference string
}

func (q *Queries) InsertDeletedAccountSubject(ctx context.Context, arg InsertDeletedAccountSubjectParams) (DeletedAccountSubject, error) {
	row := q.db.QueryRow(ctx, insertDeletedAccountSubject, arg.SubjectDigest, arg.AccountID, arg.ActorReference)
	var i DeletedAccountSubject
	err := row.Scan(
		&i.SubjectDigest,
		&i.AccountID,
		&i.ActorReference,
		&i.DeletedAt,
		&i.RetainUntil,
	)
	return i, err
}

const insertDeletionTombstone = `-- name: InsertDeletionTombstone :one
INSERT INTO deletion_tombstones (
    entity_type,
    entity_id,
    actor_reference
) VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (entity_type, entity_id) DO NOTHING
RETURNING entity_type, entity_id, actor_reference, deleted_at, retain_until
`

type InsertDeletionTombstoneParams struct {
	EntityType     string
	EntityID       pgtype.UUID
	ActorReference string
}

func (q *Queries) InsertDeletionTombstone(ctx context.Context, arg InsertDeletionTombstoneParams) (DeletionTombstone, error) {
	row := q.db.QueryRow(ctx, insertDeletionTombstone, arg.EntityType, arg.EntityID, arg.ActorReference)
	var i DeletionTombstone
	err := row.Scan(
		&i.EntityType,
		&i.EntityID,
		&i.ActorReference,
		&i.DeletedAt,
		&i.RetainUntil,
	)
	return i, err
}

const insertIdempotencyRecord = `-- name: InsertIdempotencyRecord :one
INSERT INTO idempotency_records (
    id,
    caller_kind,
    caller_id,
    operation,
    idempotency_key,
    request_hash,
    response_payload,
    connect_code,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    transaction_timestamp() + interval '24 hours'
)
RETURNING id, caller_kind, caller_id, operation, idempotency_key, request_hash, response_payload, connect_code, created_at, expires_at
`

type InsertIdempotencyRecordParams struct {
	ID              pgtype.UUID
	CallerKind      string
	CallerID        string
	Operation       string
	IdempotencyKey  string
	RequestHash     []byte
	ResponsePayload []byte
	ConnectCode     pgtype.Int4
}

func (q *Queries) InsertIdempotencyRecord(ctx context.Context, arg InsertIdempotencyRecordParams) (IdempotencyRecord, error) {
	row := q.db.QueryRow(ctx, insertIdempotencyRecord,
		arg.ID,
		arg.CallerKind,
		arg.CallerID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.ResponsePayload,
		arg.ConnectCode,
	)
	var i IdempotencyRecord
	err := row.Scan(
		&i.ID,
		&i.CallerKind,
		&i.CallerID,
		&i.Operation,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ResponsePayload,
		&i.ConnectCode,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listAccountOrganizations = `-- name: ListAccountOrganizations :many
SELECT
    organization.id,
    organization.name,
    organization.slug,
    membership.role
FROM organization_memberships AS membership
JOIN organizations AS organization
  ON organization.id = membership.organization_id
WHERE membership.account_id = $1
  AND organization.deleted_at IS NULL
ORDER BY organization.id
`

type ListAccountOrganizationsRow struct {
	ID   pgtype.UUID
	Name string
	Slug string
	Role string
}

func (q *Queries) ListAccountOrganizations(ctx context.Context, accountID pgtype.UUID) ([]ListAccountOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, listAccountOrganizations, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountOrganizationsRow{}
	for rows.Next() {
		var i ListAccountOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveReservationBlockersForAccount = `-- name: ListActiveReservationBlockersForAccount :many
SELECT DISTINCT
    organization.id,
    organization.name,
    team.id AS team_id,
    team.name AS team_name
FROM usage_reservations AS reservation
JOIN organizations AS organization
  ON organization.id = reservation.organization_id
JOIN teams AS team
  ON team.organization_id = reservation.organization_id
 AND team.id = reservation.team_id
WHERE reservation.account_id = $1
  AND reservation.status = 'held'
ORDER BY organization.id, team.id
`

type ListActiveReservationBlockersForAccountRow struct {
	ID       pgtype.UUID
	Name     string
	TeamID   pgtype.UUID
	TeamName string
}

func (q *Queries) ListActiveReservationBlockersForAccount(ctx context.Context, accountID pgtype.UUID) ([]ListActiveReservationBlockersForAccountRow, error) {
	rows, err := q.db.Query(ctx, listActiveReservationBlockersForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveReservationBlockersForAccountRow{}
	for rows.Next() {
		var i ListActiveReservationBlockersForAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TeamID,
			&i.TeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLastOwnerBlockers = `-- name: ListLastOwnerBlockers :many
SELECT organization.id, organization.name
FROM organizations AS organization
JOIN organization_memberships AS membership
  ON membership.organization_id = organization.id
WHERE membership.account_id = $1
  AND membership.role = 'owner'
  AND organization.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1
      FROM organization_memberships AS other_membership
      JOIN accounts AS other_account
        ON other_account.id = other_membership.account_id
      WHERE other_membership.organization_id = organization.id
        AND other_membership.role = 'owner'
        AND other_membership.account_id <> $1
        AND other_account.status = 'active'
  )
ORDER BY organization.id
`

type ListLastOwnerBlockersRow struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) ListLastOwnerBlockers(ctx context.Context, accountID pgtype.UUID) ([]ListLastOwnerBlockersRow, error) {
	rows, err := q.db.Query(ctx, listLastOwnerBlockers, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLastOwnerBlockersRow{}
	for rows.Next() {
		var i ListLastOwnerBlockersRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationMembers = `-- name: ListOrganizationMembers :many
SELECT
    membership.organization_id,
    membership.account_id,
    account.display_name,
    membership.role,
    membership.created_at,
    membership.updated_at
FROM organization_memberships AS membership
JOIN accounts AS account ON account.id = membership.account_id
JOIN organizations AS organization
  ON organization.id = membership.organization_id
WHERE membership.organization_id = $1
  AND membership.account_id > $2
  AND account.status = 'active'
  AND organization.deleted_at IS NULL
ORDER BY membership.account_id
LIMIT $3
`

type ListOrganizationMembersParams struct {
	OrganizationID pgtype.UUID
	AfterID        pgtype.UUID
	PageLimit      int32
}

type ListOrganizationMembersRow struct {
	OrganizationID pgtype.UUID
	AccountID      pgtype.UUID
	DisplayName    string
	Role           string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ListOrganizationMembers(ctx context.Context, arg ListOrganizationMembersParams) ([]ListOrganizationMembersRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationMembers, arg.OrganizationID, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationMembersRow{}
	for rows.Next() {
		var i ListOrganizationMembersRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.AccountID,
			&i.DisplayName,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsForAccount = `-- name: ListOrganizationsForAccount :many
SELECT organization.id, organization.name, organization.slug, organization.overage_limit_micros, organization.deleted_at, organization.created_at, organization.updated_at
FROM organizations AS organization
JOIN organization_memberships AS membership
  ON membership.organization_id = organization.id
WHERE membership.account_id = $1
  AND organization.deleted_at IS NULL
  AND organization.id > $2
ORDER BY organization.id
LIMIT $3
`

type ListOrganizationsForAccountParams struct {
	AccountID pgtype.UUID
	AfterID   pgtype.UUID
	PageLimit int32
}

func (q *Queries) ListOrganizationsForAccount(ctx context.Context, arg ListOrganizationsForAccountParams) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizationsForAccount, arg.AccountID, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.OverageLimitMicros,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAccountByLogtoSubject = `-- name: LockAccountByLogtoSubject :one
SELECT id, logto_subject, display_name, status, created_at, updated_at
FROM accounts
WHERE logto_subject = $1
FOR UPDATE
`

func (q *Queries) LockAccountByLogtoSubject(ctx context.Context, logtoSubject string) (Account, error) {
	row := q.db.QueryRow(ctx, lockAccountByLogtoSubject, logtoSubject)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.LogtoSubject,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockOwnedOrganizations = `-- name: LockOwnedOrganizations :many
SELECT organization.id
FROM organizations AS organization
JOIN organization_memberships AS membership
  ON membership.organization_id = organization.id
WHERE membership.account_id = $1
  AND membership.role = 'owner'
  AND organization.deleted_at IS NULL
ORDER BY organization.id
FOR UPDATE OF organization
`

func (q *Queries) LockOwnedOrganizations(ctx context.Context, accountID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, lockOwnedOrganizations, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrganizationDeleted = `-- name: MarkOrganizationDeleted :one
UPDATE organizations
SET deleted_at = transaction_timestamp(),
    updated_at = transaction_timestamp()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, name, slug, overage_limit_micros, deleted_at, created_at, updated_at
`

func (q *Queries) MarkOrganizationDeleted(ctx context.Context, id pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, markOrganizationDeleted, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OverageLimitMicros,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveOrganizationSlugForAccount = `-- name: ResolveOrganizationSlugForAccount :one
SELECT
    organization.id, organization.name, organization.slug, organization.overage_limit_micros, organization.deleted_at, organization.created_at, organization.updated_at,
    (organization.slug <> $1)::boolean AS matched_alias
FROM organization_slug_registry AS registry
JOIN organizations AS organization
  ON organization.id = registry.organization_id
JOIN organization_memberships AS membership
  ON membership.organization_id = organization.id
WHERE registry.slug = $1
  AND membership.account_id = $2
  AND organization.deleted_at IS NULL
`

type ResolveOrganizationSlugForAccountParams struct {
	Slug      string
	AccountID pgtype.UUID
}

type ResolveOrganizationSlugForAccountRow struct {
	ID                 pgtype.UUID
	Name               string
	Slug               string
	OverageLimitMicros int64
	DeletedAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	MatchedAlias       bool
}

func (q *Queries) ResolveOrganizationSlugForAccount(ctx context.Context, arg ResolveOrganizationSlugForAccountParams) (ResolveOrganizationSlugForAccountRow, error) {
	row := q.db.QueryRow(ctx, resolveOrganizationSlugForAccount, arg.Slug, arg.AccountID)
	var i ResolveOrganizationSlugForAccountRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OverageLimitMicros,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MatchedAlias,
	)
	return i, err
}

const updateAccountDisplayName = `-- name: UpdateAccountDisplayName :one
UPDATE accounts
SET display_name = $1,
    updated_at = transaction_timestamp()
WHERE id = $2
  AND status = 'active'
RETURNING id, logto_subject, display_name, status, created_at, updated_at
`

type UpdateAccountDisplayNameParams struct {
	DisplayName string
	ID          pgtype.UUID
}

func (q *Queries) UpdateAccountDisplayName(ctx context.Context, arg UpdateAccountDisplayNameParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountDisplayName, arg.DisplayName, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.LogtoSubject,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganizationMembershipRole = `-- name: UpdateOrganizationMembershipRole :one
UPDATE organization_memberships
SET role = $1,
    updated_at = transaction_timestamp()
WHERE organization_id = $2
  AND account_id = $3
RETURNING organization_id, account_id, role, created_at, updated_at
`

type UpdateOrganizationMembershipRoleParams struct {
	Role           string
	OrganizationID pgtype.UUID
	AccountID      pgtype.UUID
}

func (q *Queries) UpdateOrganizationMembershipRole(ctx context.Context, arg UpdateOrganizationMembershipRoleParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, updateOrganizationMembershipRole, arg.Role, arg.OrganizationID, arg.AccountID)
	var i OrganizationMembership
	err := row.Scan(
		&i.OrganizationID,
		&i.AccountID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganizationName = `-- name: UpdateOrganizationName :one
UPDATE organizations
SET name = $1,
    updated_at = transaction_timestamp()
WHERE id = $2
  AND deleted_at IS NULL
RETURNING id, name, slug, overage_limit_micros, deleted_at, created_at, updated_at
`

type UpdateOrganizationNameParams struct {
	Name string
	ID   pgtype.UUID
}

func (q *Queries) UpdateOrganizationName(ctx context.Context, arg UpdateOrganizationNameParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganizationName, arg.Name, arg.ID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OverageLimitMicros,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganizationSlug = `-- name: UpdateOrganizationSlug :one
UPDATE organizations
SET slug = $1,
    updated_at = transaction_timestamp()
WHERE id = $2
  AND deleted_at IS NULL
RETURNING id, name, slug, overage_limit_micros, deleted_at, created_at, updated_at
`

type UpdateOrganizationSlugParams struct {
	Slug string
	ID   pgtype.UUID
}

func (q *Queries) UpdateOrganizationSlug(ctx context.Context, arg UpdateOrganizationSlugParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganizationSlug, arg.Slug, arg.ID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OverageLimitMicros,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
