// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           pgtype.UUID
	LogtoSubject string
	DisplayName  string
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type AuditEvent struct {
	ID                pgtype.UUID
	OccurredAt        pgtype.Timestamptz
	EventType         string
	ActorReference    string
	OrganizationID    pgtype.UUID
	TeamID            pgtype.UUID
	ServiceIdentityID pgtype.UUID
	MeterID           pgtype.UUID
	ReservationID     pgtype.UUID
	Decision          string
	Result            string
	SafeErrorClass    pgtype.Text
	Metadata          []byte
}

type BillingPeriod struct {
	ID                 pgtype.UUID
	OrganizationID     pgtype.UUID
	SubscriptionID     pgtype.UUID
	StartsAt           pgtype.Timestamptz
	EndsAt             pgtype.Timestamptz
	OverageLimitMicros int64
	CreatedAt          pgtype.Timestamptz
}

type CatalogApp struct {
	ID          pgtype.UUID
	Slug        string
	Name        string
	Summary     string
	Description string
	IconUrl     string
	Enabled     bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type CatalogMeter struct {
	ID                    pgtype.UUID
	AppID                 pgtype.UUID
	MeterKey              string
	Name                  string
	Description           string
	UnitName              string
	UnitPrecision         int32
	ReservationTtlSeconds int64
	Enabled               bool
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type CatalogPriceVersion struct {
	ID               pgtype.UUID
	MeterID          pgtype.UUID
	UsdMicrosPerUnit int64
	EffectiveFrom    pgtype.Timestamptz
	EffectiveUntil   pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

type DeletionJob struct {
	ID             pgtype.UUID
	AccountID      pgtype.UUID
	OrganizationID pgtype.UUID
	JobType        string
	Status         string
	CreatedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	AttemptCount   int32
	NextAttemptAt  pgtype.Timestamptz
	DeadLetteredAt pgtype.Timestamptz
	SafeErrorClass pgtype.Text
}

type IdempotencyRecord struct {
	ID              pgtype.UUID
	CallerKind      string
	CallerID        string
	Operation       string
	IdempotencyKey  string
	RequestHash     []byte
	ResponsePayload []byte
	ConnectCode     pgtype.Int4
	CreatedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
}

type IntegrationOutbox struct {
	ID             pgtype.UUID
	Integration    string
	Operation      string
	AggregateType  string
	AggregateID    pgtype.UUID
	Payload        []byte
	CreatedAt      pgtype.Timestamptz
	DeliveredAt    pgtype.Timestamptz
	AttemptCount   int32
	NextAttemptAt  pgtype.Timestamptz
	DeadLetteredAt pgtype.Timestamptz
	SafeErrorClass pgtype.Text
}

type LedgerEntry struct {
	ID                 pgtype.UUID
	OrganizationID     pgtype.UUID
	BillingPeriodID    pgtype.UUID
	EntryType          string
	AmountMicros       int64
	BalanceAfterMicros int64
	ReservationID      pgtype.UUID
	UsageRecordID      pgtype.UUID
	TeamIDSnapshot     pgtype.UUID
	TeamNameSnapshot   pgtype.Text
	SourceReference    string
	ActorReference     string
	CreatedAt          pgtype.Timestamptz
}

type Organization struct {
	ID                 pgtype.UUID
	Name               string
	Slug               string
	OverageLimitMicros int64
	DeletedAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type OrganizationInvitation struct {
	ID                 pgtype.UUID
	OrganizationID     pgtype.UUID
	TokenHash          []byte
	OrganizationRole   string
	TargetTeamID       pgtype.UUID
	TeamRole           pgtype.Text
	CreatedByAccountID pgtype.UUID
	ExpiresAt          pgtype.Timestamptz
	RevokedAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
}

type OrganizationInvitationAcceptance struct {
	InvitationID pgtype.UUID
	AccountID    pgtype.UUID
	AcceptedAt   pgtype.Timestamptz
}

type OrganizationMembership struct {
	OrganizationID pgtype.UUID
	AccountID      pgtype.UUID
	Role           string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type OrganizationSlugAlias struct {
	Slug           string
	OrganizationID pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

type OrganizationSlugRegistry struct {
	Slug           string
	OrganizationID pgtype.UUID
}

type PolarCustomer struct {
	OrganizationID  pgtype.UUID
	PolarCustomerID string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type PolarMeterMapping struct {
	MeterID      pgtype.UUID
	PolarMeterID string
	CreatedAt    pgtype.Timestamptz
}

type ServiceIdentity struct {
	ID            pgtype.UUID
	LogtoClientID string
	Name          string
	Enabled       bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type ServiceMeterAllowlist struct {
	ServiceIdentityID pgtype.UUID
	MeterID           pgtype.UUID
	Enabled           bool
	CreatedAt         pgtype.Timestamptz
}

type Subscription struct {
	ID                    pgtype.UUID
	OrganizationID        pgtype.UUID
	PolarSubscriptionID   string
	Status                string
	CurrentPeriodStartsAt pgtype.Timestamptz
	CurrentPeriodEndsAt   pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type Team struct {
	ID               pgtype.UUID
	OrganizationID   pgtype.UUID
	ParentTeamID     pgtype.UUID
	Name             string
	ProtectedGeneral bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type TeamMembership struct {
	OrganizationID pgtype.UUID
	TeamID         pgtype.UUID
	AccountID      pgtype.UUID
	Role           string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type UsageRecord struct {
	ID                   pgtype.UUID
	ReservationID        pgtype.UUID
	OrganizationID       pgtype.UUID
	TeamID               pgtype.UUID
	TeamNameSnapshot     string
	MeterID              pgtype.UUID
	AccountID            pgtype.UUID
	ServiceIdentityID    pgtype.UUID
	CommittedUnits       int64
	TotalCostMicros      int64
	CreditAppliedMicros  int64
	OverageAppliedMicros int64
	CommittedAt          pgtype.Timestamptz
}

type UsageReservation struct {
	ID                      pgtype.UUID
	OrganizationID          pgtype.UUID
	TeamID                  pgtype.UUID
	TeamNameSnapshot        string
	MeterID                 pgtype.UUID
	PriceVersionID          pgtype.UUID
	AccountID               pgtype.UUID
	ServiceIdentityID       pgtype.UUID
	MaximumUnits            int64
	UsdMicrosPerUnit        int64
	MaximumCostMicros       int64
	HeldCreditMicros        int64
	HeldOverageMicros       int64
	ClientReference         string
	Status                  string
	ActiveOrganizationID    pgtype.UUID
	ActiveTeamID            pgtype.UUID
	ActiveAccountID         pgtype.UUID
	ActiveServiceIdentityID pgtype.UUID
	ActiveMeterID           pgtype.UUID
	ExpiresAt               pgtype.Timestamptz
	FinalizedAt             pgtype.Timestamptz
	CreatedAt               pgtype.Timestamptz
}

type WebhookInbox struct {
	ID              pgtype.UUID
	Provider        string
	ProviderEventID string
	EventType       string
	PayloadSha256   []byte
	ReceivedAt      pgtype.Timestamptz
	ProcessedAt     pgtype.Timestamptz
	AttemptCount    int32
	NextAttemptAt   pgtype.Timestamptz
	DeadLetteredAt  pgtype.Timestamptz
	SafeErrorClass  pgtype.Text
}
