// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	GetAccountByLogtoSubject(ctx context.Context, logtoSubject string) (Account, error)
	LockOrganizationForMutation(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	Ping(ctx context.Context) (int64, error)
}

var _ Querier = (*Queries)(nil)
