// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, logto_subject, display_name)
VALUES ($1, $2, $3)
RETURNING id, logto_subject, display_name, status, created_at, updated_at
`

type CreateAccountParams struct {
	ID           pgtype.UUID
	LogtoSubject string
	DisplayName  string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.ID, arg.LogtoSubject, arg.DisplayName)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.LogtoSubject,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByLogtoSubject = `-- name: GetAccountByLogtoSubject :one
SELECT id, logto_subject, display_name, status, created_at, updated_at
FROM accounts
WHERE logto_subject = $1
`

func (q *Queries) GetAccountByLogtoSubject(ctx context.Context, logtoSubject string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByLogtoSubject, logtoSubject)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.LogtoSubject,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockOrganizationForMutation = `-- name: LockOrganizationForMutation :one
SELECT id
FROM organizations
WHERE id = $1
  AND deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) LockOrganizationForMutation(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockOrganizationForMutation, id)
	err := row.Scan(&id)
	return id, err
}

const ping = `-- name: Ping :one
SELECT 1::bigint
`

func (q *Queries) Ping(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, ping)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
