// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (id, organization_id, parent_team_id, name)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, organization_id, parent_team_id, name, protected_general, created_at, updated_at
`

type CreateTeamParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	ParentTeamID   pgtype.UUID
	Name           string
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.ID,
		arg.OrganizationID,
		arg.ParentTeamID,
		arg.Name,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ParentTeamID,
		&i.Name,
		&i.ProtectedGeneral,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeamMembership = `-- name: DeleteTeamMembership :execrows
DELETE FROM team_memberships
WHERE organization_id = $1
  AND team_id = $2
  AND account_id = $3
`

type DeleteTeamMembershipParams struct {
	OrganizationID pgtype.UUID
	TeamID         pgtype.UUID
	AccountID      pgtype.UUID
}

func (q *Queries) DeleteTeamMembership(ctx context.Context, arg DeleteTeamMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTeamMembership, arg.OrganizationID, arg.TeamID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTeamSubtree = `-- name: DeleteTeamSubtree :execrows
DELETE FROM teams
WHERE organization_id = $1
  AND id = $2
`

type DeleteTeamSubtreeParams struct {
	OrganizationID pgtype.UUID
	TeamID         pgtype.UUID
}

func (q *Queries) DeleteTeamSubtree(ctx context.Context, arg DeleteTeamSubtreeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTeamSubtree, arg.OrganizationID, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEffectiveTeamAccess = `-- name: GetEffectiveTeamAccess :one
SELECT
    $1::uuid AS team_id,
    $2::uuid AS account_id,
    effective_team_role(
        $3, $1, $2
    ) AS effective_role,
    effective_team_access_source(
        $3, $1, $2
    ) AS access_source,
    effective_team_access_source_team(
        $3, $1, $2
    ) AS source_team_id,
    effective_team_organization_role(
        $3, $1, $2
    ) AS organization_role
WHERE effective_team_role(
    $3, $1, $2
) IS NOT NULL
`

type GetEffectiveTeamAccessParams struct {
	TeamID         pgtype.UUID
	AccountID      pgtype.UUID
	OrganizationID pgtype.UUID
}

type GetEffectiveTeamAccessRow struct {
	TeamID           pgtype.UUID
	AccountID        pgtype.UUID
	EffectiveRole    string
	AccessSource     string
	SourceTeamID     pgtype.UUID
	OrganizationRole string
}

func (q *Queries) GetEffectiveTeamAccess(ctx context.Context, arg GetEffectiveTeamAccessParams) (GetEffectiveTeamAccessRow, error) {
	row := q.db.QueryRow(ctx, getEffectiveTeamAccess, arg.TeamID, arg.AccountID, arg.OrganizationID)
	var i GetEffectiveTeamAccessRow
	err := row.Scan(
		&i.TeamID,
		&i.AccountID,
		&i.EffectiveRole,
		&i.AccessSource,
		&i.SourceTeamID,
		&i.OrganizationRole,
	)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, organization_id, parent_team_id, name, protected_general, created_at, updated_at
FROM teams
WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id pgtype.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ParentTeamID,
		&i.Name,
		&i.ProtectedGeneral,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamInOrganization = `-- name: GetTeamInOrganization :one
SELECT team.id, team.organization_id, team.parent_team_id, team.name, team.protected_general, team.created_at, team.updated_at, team_depth(team.organization_id, team.id) AS depth
FROM teams AS team
WHERE team.organization_id = $1
  AND team.id = $2
`

type GetTeamInOrganizationParams struct {
	OrganizationID pgtype.UUID
	TeamID         pgtype.UUID
}

type GetTeamInOrganizationRow struct {
	ID               pgtype.UUID
	OrganizationID   pgtype.UUID
	ParentTeamID     pgtype.UUID
	Name             string
	ProtectedGeneral bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Depth            int32
}

func (q *Queries) GetTeamInOrganization(ctx context.Context, arg GetTeamInOrganizationParams) (GetTeamInOrganizationRow, error) {
	row := q.db.QueryRow(ctx, getTeamInOrganization, arg.OrganizationID, arg.TeamID)
	var i GetTeamInOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ParentTeamID,
		&i.Name,
		&i.ProtectedGeneral,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Depth,
	)
	return i, err
}

const getTeamMembership = `-- name: GetTeamMembership :one
SELECT
    membership.organization_id,
    membership.team_id,
    membership.account_id,
    account.display_name,
    membership.role,
    membership.created_at,
    membership.updated_at
FROM team_memberships AS membership
JOIN accounts AS account ON account.id = membership.account_id
WHERE membership.organization_id = $1
  AND membership.team_id = $2
  AND membership.account_id = $3
  AND account.status = 'active'
`

type GetTeamMembershipParams struct {
	OrganizationID pgtype.UUID
	TeamID         pgtype.UUID
	AccountID      pgtype.UUID
}

type GetTeamMembershipRow struct {
	OrganizationID pgtype.UUID
	TeamID         pgtype.UUID
	AccountID      pgtype.UUID
	DisplayName    string
	Role           string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetTeamMembership(ctx context.Context, arg GetTeamMembershipParams) (GetTeamMembershipRow, error) {
	row := q.db.QueryRow(ctx, getTeamMembership, arg.OrganizationID, arg.TeamID, arg.AccountID)
	var i GetTeamMembershipRow
	err := row.Scan(
		&i.OrganizationID,
		&i.TeamID,
		&i.AccountID,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasActiveReservationsForTeamSubtree = `-- name: HasActiveReservationsForTeamSubtree :one
SELECT EXISTS (
    SELECT 1
    FROM usage_reservations AS reservation
    WHERE reservation.organization_id = $1
      AND reservation.status = 'held'
      AND team_is_descendant_or_self(
          reservation.organization_id,
          reservation.team_id,
          $2
      )
)
`

type HasActiveReservationsForTeamSubtreeParams struct {
	OrganizationID pgtype.UUID
	TeamID         pgtype.UUID
}

func (q *Queries) HasActiveReservationsForTeamSubtree(ctx context.Context, arg HasActiveReservationsForTeamSubtreeParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveReservationsForTeamSubtree, arg.OrganizationID, arg.TeamID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertTeamMembershipIfAbsent = `-- name: InsertTeamMembershipIfAbsent :execrows
INSERT INTO team_memberships (organization_id, team_id, account_id, role)
VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (team_id, account_id) DO NOTHING
`

type InsertTeamMembershipIfAbsentParams struct {
	OrganizationID pgtype.UUID
	TeamID         pgtype.UUID
	AccountID      pgtype.UUID
	Role           string
}

func (q *Queries) InsertTeamMembershipIfAbsent(ctx context.Context, arg InsertTeamMembershipIfAbsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertTeamMembershipIfAbsent,
		arg.OrganizationID,
		arg.TeamID,
		arg.AccountID,
		arg.Role,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listEffectiveTeamAccess = `-- name: ListEffectiveTeamAccess :many
SELECT
    team.id AS team_id,
    $1::uuid AS account_id,
    effective_team_role(
        team.organization_id, team.id, $1
    ) AS effective_role,
    effective_team_access_source(
        team.organization_id, team.id, $1
    ) AS access_source,
    effective_team_access_source_team(
        team.organization_id, team.id, $1
    ) AS source_team_id,
    effective_team_organization_role(
        team.organization_id, team.id, $1
    ) AS organization_role
FROM teams AS team
WHERE team.organization_id = $2
  AND team.id > $3
  AND effective_team_role(
      team.organization_id, team.id, $1
  ) IS NOT NULL
ORDER BY team.id
LIMIT $4
`

type ListEffectiveTeamAccessParams struct {
	AccountID      pgtype.UUID
	OrganizationID pgtype.UUID
	AfterID        pgtype.UUID
	PageLimit      int32
}

type ListEffectiveTeamAccessRow struct {
	TeamID           pgtype.UUID
	AccountID        pgtype.UUID
	EffectiveRole    string
	AccessSource     string
	SourceTeamID     pgtype.UUID
	OrganizationRole string
}

func (q *Queries) ListEffectiveTeamAccess(ctx context.Context, arg ListEffectiveTeamAccessParams) ([]ListEffectiveTeamAccessRow, error) {
	rows, err := q.db.Query(ctx, listEffectiveTeamAccess,
		arg.AccountID,
		arg.OrganizationID,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEffectiveTeamAccessRow{}
	for rows.Next() {
		var i ListEffectiveTeamAccessRow
		if err := rows.Scan(
			&i.TeamID,
			&i.AccountID,
			&i.EffectiveRole,
			&i.AccessSource,
			&i.SourceTeamID,
			&i.OrganizationRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMemberships = `-- name: ListTeamMemberships :many
SELECT
    membership.organization_id,
    membership.team_id,
    membership.account_id,
    account.display_name,
    membership.role,
    membership.created_at,
    membership.updated_at
FROM team_memberships AS membership
JOIN accounts AS account ON account.id = membership.account_id
WHERE membership.organization_id = $1
  AND membership.team_id = $2
  AND membership.account_id > $3
  AND account.status = 'active'
ORDER BY membership.account_id
LIMIT $4
`

type ListTeamMembershipsParams struct {
	OrganizationID pgtype.UUID
	TeamID         pgtype.UUID
	AfterID        pgtype.UUID
	PageLimit      int32
}

type ListTeamMembershipsRow struct {
	OrganizationID pgtype.UUID
	TeamID         pgtype.UUID
	AccountID      pgtype.UUID
	DisplayName    string
	Role           string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ListTeamMemberships(ctx context.Context, arg ListTeamMembershipsParams) ([]ListTeamMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listTeamMemberships,
		arg.OrganizationID,
		arg.TeamID,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamMembershipsRow{}
	for rows.Next() {
		var i ListTeamMembershipsRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.TeamID,
			&i.AccountID,
			&i.DisplayName,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamSubtree = `-- name: ListTeamSubtree :many
SELECT
    team.id, team.organization_id, team.parent_team_id, team.name, team.protected_general, team.created_at, team.updated_at,
    (
        team_depth(team.organization_id, team.id)
        - team_depth(team.organization_id, $1)
    )::integer AS relative_depth
FROM teams AS team
WHERE team.organization_id = $2
  AND team_is_descendant_or_self(
      team.organization_id,
      team.id,
      $1
  )
ORDER BY relative_depth DESC, team.id
`

type ListTeamSubtreeParams struct {
	TeamID         pgtype.UUID
	OrganizationID pgtype.UUID
}

type ListTeamSubtreeRow struct {
	ID               pgtype.UUID
	OrganizationID   pgtype.UUID
	ParentTeamID     pgtype.UUID
	Name             string
	ProtectedGeneral bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	RelativeDepth    int32
}

func (q *Queries) ListTeamSubtree(ctx context.Context, arg ListTeamSubtreeParams) ([]ListTeamSubtreeRow, error) {
	rows, err := q.db.Query(ctx, listTeamSubtree, arg.TeamID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamSubtreeRow{}
	for rows.Next() {
		var i ListTeamSubtreeRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ParentTeamID,
			&i.Name,
			&i.ProtectedGeneral,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RelativeDepth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsForAccount = `-- name: ListTeamsForAccount :many
SELECT team.id, team.organization_id, team.parent_team_id, team.name, team.protected_general, team.created_at, team.updated_at, team_depth(team.organization_id, team.id) AS depth
FROM teams AS team
JOIN organization_memberships AS caller
  ON caller.organization_id = team.organization_id
 AND caller.account_id = $1
JOIN accounts AS caller_account ON caller_account.id = caller.account_id
JOIN organizations AS organization ON organization.id = team.organization_id
WHERE team.organization_id = $2
  AND team.id > $3
  AND caller_account.status = 'active'
  AND organization.deleted_at IS NULL
  AND (
      (
          $4::uuid IS NULL
          AND (
              $5::boolean
              OR team.parent_team_id IS NULL
          )
      )
      OR
      (
          $4::uuid IS NOT NULL
          AND (
              team.parent_team_id = $4
              OR (
                  $5::boolean
                  AND team.id <> $4
                  AND team_is_descendant_or_self(
                      team.organization_id,
                      team.id,
                      $4
                  )
              )
          )
      )
  )
  AND (
      caller.role IN ('owner', 'admin')
      OR EXISTS (
          SELECT 1
          FROM effective_team_access(
              team.organization_id,
              team.id,
              caller.account_id
          )
      )
  )
ORDER BY team.id
LIMIT $6
`

type ListTeamsForAccountParams struct {
	AccountID          pgtype.UUID
	OrganizationID     pgtype.UUID
	AfterID            pgtype.UUID
	ParentTeamID       pgtype.UUID
	IncludeDescendants bool
	PageLimit          int32
}

type ListTeamsForAccountRow struct {
	ID               pgtype.UUID
	OrganizationID   pgtype.UUID
	ParentTeamID     pgtype.UUID
	Name             string
	ProtectedGeneral bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Depth            int32
}

func (q *Queries) ListTeamsForAccount(ctx context.Context, arg ListTeamsForAccountParams) ([]ListTeamsForAccountRow, error) {
	rows, err := q.db.Query(ctx, listTeamsForAccount,
		arg.AccountID,
		arg.OrganizationID,
		arg.AfterID,
		arg.ParentTeamID,
		arg.IncludeDescendants,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsForAccountRow{}
	for rows.Next() {
		var i ListTeamsForAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ParentTeamID,
			&i.Name,
			&i.ProtectedGeneral,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveTeam = `-- name: MoveTeam :one
UPDATE teams
SET parent_team_id = $1,
    updated_at = transaction_timestamp()
WHERE organization_id = $2
  AND id = $3
RETURNING id, organization_id, parent_team_id, name, protected_general, created_at, updated_at
`

type MoveTeamParams struct {
	ParentTeamID   pgtype.UUID
	OrganizationID pgtype.UUID
	TeamID         pgtype.UUID
}

func (q *Queries) MoveTeam(ctx context.Context, arg MoveTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, moveTeam, arg.ParentTeamID, arg.OrganizationID, arg.TeamID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ParentTeamID,
		&i.Name,
		&i.ProtectedGeneral,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTeamName = `-- name: UpdateTeamName :one
UPDATE teams
SET name = $1,
    updated_at = transaction_timestamp()
WHERE organization_id = $2
  AND id = $3
RETURNING id, organization_id, parent_team_id, name, protected_general, created_at, updated_at
`

type UpdateTeamNameParams struct {
	Name           string
	OrganizationID pgtype.UUID
	TeamID         pgtype.UUID
}

func (q *Queries) UpdateTeamName(ctx context.Context, arg UpdateTeamNameParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeamName, arg.Name, arg.OrganizationID, arg.TeamID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ParentTeamID,
		&i.Name,
		&i.ProtectedGeneral,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTeamMembership = `-- name: UpsertTeamMembership :one
INSERT INTO team_memberships (organization_id, team_id, account_id, role)
VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (team_id, account_id) DO UPDATE
SET role = EXCLUDED.role,
    updated_at = transaction_timestamp()
RETURNING organization_id, team_id, account_id, role, created_at, updated_at
`

type UpsertTeamMembershipParams struct {
	OrganizationID pgtype.UUID
	TeamID         pgtype.UUID
	AccountID      pgtype.UUID
	Role           string
}

func (q *Queries) UpsertTeamMembership(ctx context.Context, arg UpsertTeamMembershipParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, upsertTeamMembership,
		arg.OrganizationID,
		arg.TeamID,
		arg.AccountID,
		arg.Role,
	)
	var i TeamMembership
	err := row.Scan(
		&i.OrganizationID,
		&i.TeamID,
		&i.AccountID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
