// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usage.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const finalizeUsageReservation = `-- name: FinalizeUsageReservation :one
UPDATE usage_reservations
SET status = $1
WHERE organization_id = $2
  AND id = $3
  AND status = 'held'
RETURNING id, organization_id, team_id, team_name_snapshot, meter_id, price_version_id, account_id, service_identity_id, maximum_units, usd_micros_per_unit, maximum_cost_micros, held_credit_micros, held_overage_micros, client_reference, status, active_organization_id, active_team_id, active_account_id, active_service_identity_id, active_meter_id, expires_at, finalized_at, created_at, user_actor_reference_snapshot, service_name_snapshot, meter_name_snapshot, polar_event_name_snapshot, price_effective_from_snapshot, price_effective_until_snapshot, overage_billing_period_id
`

type FinalizeUsageReservationParams struct {
	Status         string
	OrganizationID pgtype.UUID
	ReservationID  pgtype.UUID
}

func (q *Queries) FinalizeUsageReservation(ctx context.Context, arg FinalizeUsageReservationParams) (UsageReservation, error) {
	row := q.db.QueryRow(ctx, finalizeUsageReservation, arg.Status, arg.OrganizationID, arg.ReservationID)
	var i UsageReservation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.TeamNameSnapshot,
		&i.MeterID,
		&i.PriceVersionID,
		&i.AccountID,
		&i.ServiceIdentityID,
		&i.MaximumUnits,
		&i.UsdMicrosPerUnit,
		&i.MaximumCostMicros,
		&i.HeldCreditMicros,
		&i.HeldOverageMicros,
		&i.ClientReference,
		&i.Status,
		&i.ActiveOrganizationID,
		&i.ActiveTeamID,
		&i.ActiveAccountID,
		&i.ActiveServiceIdentityID,
		&i.ActiveMeterID,
		&i.ExpiresAt,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UserActorReferenceSnapshot,
		&i.ServiceNameSnapshot,
		&i.MeterNameSnapshot,
		&i.PolarEventNameSnapshot,
		&i.PriceEffectiveFromSnapshot,
		&i.PriceEffectiveUntilSnapshot,
		&i.OverageBillingPeriodID,
	)
	return i, err
}

const getUsageAccountBySubject = `-- name: GetUsageAccountBySubject :one
SELECT id, logto_subject, display_name, status, created_at, updated_at
FROM accounts
WHERE logto_subject = $1
`

func (q *Queries) GetUsageAccountBySubject(ctx context.Context, logtoSubject string) (Account, error) {
	row := q.db.QueryRow(ctx, getUsageAccountBySubject, logtoSubject)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.LogtoSubject,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsageCapacity = `-- name: GetUsageCapacity :one
WITH settled_credit AS (
    SELECT COALESCE(sum(amount_micros), 0)::bigint AS amount
    FROM ledger_entries
    WHERE organization_id = $2
      AND entry_type IN (
          'credit_grant', 'credit_reversal', 'credit_commit',
          'credit_forfeiture'
      )
), credit_holds AS (
    SELECT COALESCE(sum(held_credit_micros), 0)::bigint AS amount
    FROM usage_reservations
    WHERE organization_id = $2
      AND status = 'held'
), selected_subscription AS (
    SELECT subscription.id, subscription.organization_id, subscription.polar_subscription_id, subscription.status, subscription.current_period_starts_at, subscription.current_period_ends_at, subscription.created_at, subscription.updated_at, subscription.provider_event_at
    FROM subscriptions AS subscription
    WHERE subscription.organization_id = $2
    ORDER BY
        (subscription.status = 'active') DESC,
        subscription.provider_event_at DESC,
        subscription.updated_at DESC,
        subscription.id DESC
    LIMIT 1
), current_period AS (
    SELECT period.id, period.organization_id, period.subscription_id, period.starts_at, period.ends_at, period.overage_limit_micros, period.created_at, period.requested_overage_limit_micros
    FROM billing_periods AS period
    JOIN selected_subscription AS subscription
      ON subscription.organization_id = period.organization_id
     AND subscription.id = period.subscription_id
    WHERE subscription.status = 'active'
      AND subscription.current_period_starts_at = period.starts_at
      AND subscription.current_period_ends_at = period.ends_at
      AND period.starts_at <= statement_timestamp()
      AND period.ends_at > statement_timestamp()
    LIMIT 1
), committed_overage AS (
    SELECT COALESCE(sum(record.overage_applied_micros), 0)::bigint AS amount
    FROM usage_records AS record
    JOIN current_period ON record.billing_period_id = current_period.id
    WHERE record.organization_id = $2
), overage_holds AS (
    SELECT COALESCE(sum(reservation.held_overage_micros), 0)::bigint AS amount
    FROM usage_reservations AS reservation
    JOIN current_period
      ON reservation.overage_billing_period_id = current_period.id
    WHERE reservation.organization_id = $2
      AND reservation.status = 'held'
), refund_shortfall AS (
    SELECT COALESCE(sum(shortfall.amount_micros), 0)::bigint AS amount
    FROM billing_shortfalls AS shortfall
    JOIN current_period ON shortfall.billing_period_id = current_period.id
    WHERE shortfall.organization_id = $2
)
SELECT
    settled_credit.amount AS settled_credit_micros,
    credit_holds.amount AS held_credit_micros,
    GREATEST(settled_credit.amount - credit_holds.amount, 0)::bigint
        AS available_credit_micros,
    COALESCE(selected_subscription.status, 'none')::text
        AS subscription_status,
    organization.overage_limit_configured,
    current_period.id AS billing_period_id,
    current_period.starts_at AS period_starts_at,
    current_period.ends_at AS period_ends_at,
    COALESCE(current_period.requested_overage_limit_micros, 0)::bigint
        AS requested_overage_limit_micros,
    COALESCE(current_period.overage_limit_micros, 0)::bigint
        AS effective_overage_limit_micros,
    committed_overage.amount AS committed_overage_micros,
    overage_holds.amount AS held_overage_micros,
    refund_shortfall.amount AS refund_shortfall_micros,
    COALESCE(
        current_period.ends_at
            >= statement_timestamp()
                + $1::bigint * interval '1 second',
        false
    )::boolean AS overage_ttl_allowed,
    GREATEST(
        COALESCE(current_period.requested_overage_limit_micros, 0)
        - committed_overage.amount
        - overage_holds.amount
        - refund_shortfall.amount,
        0
    )::bigint AS available_overage_micros
FROM organizations AS organization
CROSS JOIN settled_credit
CROSS JOIN credit_holds
LEFT JOIN selected_subscription ON true
LEFT JOIN current_period ON true
CROSS JOIN committed_overage
CROSS JOIN overage_holds
CROSS JOIN refund_shortfall
WHERE organization.id = $2
  AND organization.deleted_at IS NULL
`

type GetUsageCapacityParams struct {
	ReservationTtlSeconds int64
	OrganizationID        pgtype.UUID
}

type GetUsageCapacityRow struct {
	SettledCreditMicros         int64
	HeldCreditMicros            int64
	AvailableCreditMicros       int64
	SubscriptionStatus          string
	OverageLimitConfigured      bool
	BillingPeriodID             pgtype.UUID
	PeriodStartsAt              pgtype.Timestamptz
	PeriodEndsAt                pgtype.Timestamptz
	RequestedOverageLimitMicros int64
	EffectiveOverageLimitMicros int64
	CommittedOverageMicros      int64
	HeldOverageMicros           int64
	RefundShortfallMicros       int64
	OverageTtlAllowed           bool
	AvailableOverageMicros      int64
}

func (q *Queries) GetUsageCapacity(ctx context.Context, arg GetUsageCapacityParams) (GetUsageCapacityRow, error) {
	row := q.db.QueryRow(ctx, getUsageCapacity, arg.ReservationTtlSeconds, arg.OrganizationID)
	var i GetUsageCapacityRow
	err := row.Scan(
		&i.SettledCreditMicros,
		&i.HeldCreditMicros,
		&i.AvailableCreditMicros,
		&i.SubscriptionStatus,
		&i.OverageLimitConfigured,
		&i.BillingPeriodID,
		&i.PeriodStartsAt,
		&i.PeriodEndsAt,
		&i.RequestedOverageLimitMicros,
		&i.EffectiveOverageLimitMicros,
		&i.CommittedOverageMicros,
		&i.HeldOverageMicros,
		&i.RefundShortfallMicros,
		&i.OverageTtlAllowed,
		&i.AvailableOverageMicros,
	)
	return i, err
}

const getUsageMeterAuthorization = `-- name: GetUsageMeterAuthorization :one
SELECT
    meter.id AS meter_id,
    meter.name AS meter_name,
    meter.reservation_ttl_seconds,
    price.id AS price_version_id,
    price.usd_micros_per_unit,
    price.effective_from,
    price.effective_until,
    mapping.polar_meter_id
FROM service_meter_allowlists AS allowlist
JOIN service_identities AS service
  ON service.id = allowlist.service_identity_id
JOIN catalog_meters AS meter ON meter.id = allowlist.meter_id
JOIN catalog_apps AS app ON app.id = meter.app_id
JOIN polar_meter_mappings AS mapping ON mapping.meter_id = meter.id
JOIN LATERAL (
    SELECT version.id, version.usd_micros_per_unit,
           version.effective_from, version.effective_until
    FROM catalog_price_versions AS version
    WHERE version.meter_id = meter.id
      AND version.effective_from <= statement_timestamp()
      AND (
          version.effective_until IS NULL
          OR statement_timestamp() < version.effective_until
      )
    ORDER BY version.effective_from DESC
    LIMIT 1
) AS price ON true
WHERE allowlist.service_identity_id = $1
  AND allowlist.meter_id = $2
  AND allowlist.enabled
  AND service.enabled
  AND meter.enabled
  AND app.enabled
`

type GetUsageMeterAuthorizationParams struct {
	ServiceIdentityID pgtype.UUID
	MeterID           pgtype.UUID
}

type GetUsageMeterAuthorizationRow struct {
	MeterID               pgtype.UUID
	MeterName             string
	ReservationTtlSeconds int64
	PriceVersionID        pgtype.UUID
	UsdMicrosPerUnit      int64
	EffectiveFrom         pgtype.Timestamptz
	EffectiveUntil        pgtype.Timestamptz
	PolarMeterID          string
}

func (q *Queries) GetUsageMeterAuthorization(ctx context.Context, arg GetUsageMeterAuthorizationParams) (GetUsageMeterAuthorizationRow, error) {
	row := q.db.QueryRow(ctx, getUsageMeterAuthorization, arg.ServiceIdentityID, arg.MeterID)
	var i GetUsageMeterAuthorizationRow
	err := row.Scan(
		&i.MeterID,
		&i.MeterName,
		&i.ReservationTtlSeconds,
		&i.PriceVersionID,
		&i.UsdMicrosPerUnit,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.PolarMeterID,
	)
	return i, err
}

const getUsageRecordByReservation = `-- name: GetUsageRecordByReservation :one
SELECT id, reservation_id, organization_id, team_id, team_name_snapshot, meter_id, account_id, service_identity_id, committed_units, total_cost_micros, credit_applied_micros, overage_applied_micros, committed_at, retain_until, price_version_id, usd_micros_per_unit, client_reference, user_actor_reference_snapshot, service_name_snapshot, meter_name_snapshot, polar_event_name_snapshot, price_effective_from_snapshot, price_effective_until_snapshot, billing_period_id, billing_period_starts_at_snapshot, billing_period_ends_at_snapshot
FROM usage_records
WHERE organization_id = $1
  AND reservation_id = $2
`

type GetUsageRecordByReservationParams struct {
	OrganizationID pgtype.UUID
	ReservationID  pgtype.UUID
}

func (q *Queries) GetUsageRecordByReservation(ctx context.Context, arg GetUsageRecordByReservationParams) (UsageRecord, error) {
	row := q.db.QueryRow(ctx, getUsageRecordByReservation, arg.OrganizationID, arg.ReservationID)
	var i UsageRecord
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.OrganizationID,
		&i.TeamID,
		&i.TeamNameSnapshot,
		&i.MeterID,
		&i.AccountID,
		&i.ServiceIdentityID,
		&i.CommittedUnits,
		&i.TotalCostMicros,
		&i.CreditAppliedMicros,
		&i.OverageAppliedMicros,
		&i.CommittedAt,
		&i.RetainUntil,
		&i.PriceVersionID,
		&i.UsdMicrosPerUnit,
		&i.ClientReference,
		&i.UserActorReferenceSnapshot,
		&i.ServiceNameSnapshot,
		&i.MeterNameSnapshot,
		&i.PolarEventNameSnapshot,
		&i.PriceEffectiveFromSnapshot,
		&i.PriceEffectiveUntilSnapshot,
		&i.BillingPeriodID,
		&i.BillingPeriodStartsAtSnapshot,
		&i.BillingPeriodEndsAtSnapshot,
	)
	return i, err
}

const getUsageServiceIdentity = `-- name: GetUsageServiceIdentity :one
SELECT id, logto_client_id, name, enabled, created_at, updated_at
FROM service_identities
WHERE logto_client_id = $1
`

func (q *Queries) GetUsageServiceIdentity(ctx context.Context, logtoClientID string) (ServiceIdentity, error) {
	row := q.db.QueryRow(ctx, getUsageServiceIdentity, logtoClientID)
	var i ServiceIdentity
	err := row.Scan(
		&i.ID,
		&i.LogtoClientID,
		&i.Name,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUsageLedgerEntry = `-- name: InsertUsageLedgerEntry :one
INSERT INTO ledger_entries (
    id, organization_id, billing_period_id, entry_type, amount_micros,
    balance_after_micros, reservation_id, usage_record_id,
    team_id_snapshot, team_name_snapshot, source_reference, actor_reference
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7,
    $8, $9,
    $10, $11,
    $12
)
RETURNING id, organization_id, billing_period_id, billing_period_starts_at_snapshot, billing_period_ends_at_snapshot, entry_type, amount_micros, balance_after_micros, reservation_id, usage_record_id, team_id_snapshot, team_name_snapshot, source_reference, actor_reference, created_at, retain_until
`

type InsertUsageLedgerEntryParams struct {
	ID                 pgtype.UUID
	OrganizationID     pgtype.UUID
	BillingPeriodID    pgtype.UUID
	EntryType          string
	AmountMicros       int64
	BalanceAfterMicros int64
	ReservationID      pgtype.UUID
	UsageRecordID      pgtype.UUID
	TeamIDSnapshot     pgtype.UUID
	TeamNameSnapshot   pgtype.Text
	SourceReference    string
	ActorReference     string
}

func (q *Queries) InsertUsageLedgerEntry(ctx context.Context, arg InsertUsageLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, insertUsageLedgerEntry,
		arg.ID,
		arg.OrganizationID,
		arg.BillingPeriodID,
		arg.EntryType,
		arg.AmountMicros,
		arg.BalanceAfterMicros,
		arg.ReservationID,
		arg.UsageRecordID,
		arg.TeamIDSnapshot,
		arg.TeamNameSnapshot,
		arg.SourceReference,
		arg.ActorReference,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.BillingPeriodID,
		&i.BillingPeriodStartsAtSnapshot,
		&i.BillingPeriodEndsAtSnapshot,
		&i.EntryType,
		&i.AmountMicros,
		&i.BalanceAfterMicros,
		&i.ReservationID,
		&i.UsageRecordID,
		&i.TeamIDSnapshot,
		&i.TeamNameSnapshot,
		&i.SourceReference,
		&i.ActorReference,
		&i.CreatedAt,
		&i.RetainUntil,
	)
	return i, err
}

const insertUsageRecord = `-- name: InsertUsageRecord :one
INSERT INTO usage_records (
    id, reservation_id, organization_id, team_id, team_name_snapshot,
    meter_id, account_id, service_identity_id, committed_units,
    total_cost_micros, credit_applied_micros, overage_applied_micros
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8,
    $9, $10,
    $11, $12
)
RETURNING id, reservation_id, organization_id, team_id, team_name_snapshot, meter_id, account_id, service_identity_id, committed_units, total_cost_micros, credit_applied_micros, overage_applied_micros, committed_at, retain_until, price_version_id, usd_micros_per_unit, client_reference, user_actor_reference_snapshot, service_name_snapshot, meter_name_snapshot, polar_event_name_snapshot, price_effective_from_snapshot, price_effective_until_snapshot, billing_period_id, billing_period_starts_at_snapshot, billing_period_ends_at_snapshot
`

type InsertUsageRecordParams struct {
	ID                   pgtype.UUID
	ReservationID        pgtype.UUID
	OrganizationID       pgtype.UUID
	TeamID               pgtype.UUID
	TeamNameSnapshot     string
	MeterID              pgtype.UUID
	AccountID            pgtype.UUID
	ServiceIdentityID    pgtype.UUID
	CommittedUnits       int64
	TotalCostMicros      int64
	CreditAppliedMicros  int64
	OverageAppliedMicros int64
}

func (q *Queries) InsertUsageRecord(ctx context.Context, arg InsertUsageRecordParams) (UsageRecord, error) {
	row := q.db.QueryRow(ctx, insertUsageRecord,
		arg.ID,
		arg.ReservationID,
		arg.OrganizationID,
		arg.TeamID,
		arg.TeamNameSnapshot,
		arg.MeterID,
		arg.AccountID,
		arg.ServiceIdentityID,
		arg.CommittedUnits,
		arg.TotalCostMicros,
		arg.CreditAppliedMicros,
		arg.OverageAppliedMicros,
	)
	var i UsageRecord
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.OrganizationID,
		&i.TeamID,
		&i.TeamNameSnapshot,
		&i.MeterID,
		&i.AccountID,
		&i.ServiceIdentityID,
		&i.CommittedUnits,
		&i.TotalCostMicros,
		&i.CreditAppliedMicros,
		&i.OverageAppliedMicros,
		&i.CommittedAt,
		&i.RetainUntil,
		&i.PriceVersionID,
		&i.UsdMicrosPerUnit,
		&i.ClientReference,
		&i.UserActorReferenceSnapshot,
		&i.ServiceNameSnapshot,
		&i.MeterNameSnapshot,
		&i.PolarEventNameSnapshot,
		&i.PriceEffectiveFromSnapshot,
		&i.PriceEffectiveUntilSnapshot,
		&i.BillingPeriodID,
		&i.BillingPeriodStartsAtSnapshot,
		&i.BillingPeriodEndsAtSnapshot,
	)
	return i, err
}

const insertUsageReservation = `-- name: InsertUsageReservation :one
INSERT INTO usage_reservations (
    id, organization_id, team_id, team_name_snapshot, meter_id,
    price_version_id, account_id, service_identity_id, maximum_units,
    usd_micros_per_unit, maximum_cost_micros, held_credit_micros,
    held_overage_micros, client_reference, expires_at,
    user_actor_reference_snapshot
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7,
    $8, $9,
    $10, $11,
    $12, $13,
    $14,
    statement_timestamp() + $15::bigint
        * interval '1 second',
    $16
)
RETURNING id, organization_id, team_id, team_name_snapshot, meter_id, price_version_id, account_id, service_identity_id, maximum_units, usd_micros_per_unit, maximum_cost_micros, held_credit_micros, held_overage_micros, client_reference, status, active_organization_id, active_team_id, active_account_id, active_service_identity_id, active_meter_id, expires_at, finalized_at, created_at, user_actor_reference_snapshot, service_name_snapshot, meter_name_snapshot, polar_event_name_snapshot, price_effective_from_snapshot, price_effective_until_snapshot, overage_billing_period_id
`

type InsertUsageReservationParams struct {
	ID                         pgtype.UUID
	OrganizationID             pgtype.UUID
	TeamID                     pgtype.UUID
	TeamNameSnapshot           string
	MeterID                    pgtype.UUID
	PriceVersionID             pgtype.UUID
	AccountID                  pgtype.UUID
	ServiceIdentityID          pgtype.UUID
	MaximumUnits               int64
	UsdMicrosPerUnit           int64
	MaximumCostMicros          int64
	HeldCreditMicros           int64
	HeldOverageMicros          int64
	ClientReference            string
	ReservationTtlSeconds      int64
	UserActorReferenceSnapshot string
}

func (q *Queries) InsertUsageReservation(ctx context.Context, arg InsertUsageReservationParams) (UsageReservation, error) {
	row := q.db.QueryRow(ctx, insertUsageReservation,
		arg.ID,
		arg.OrganizationID,
		arg.TeamID,
		arg.TeamNameSnapshot,
		arg.MeterID,
		arg.PriceVersionID,
		arg.AccountID,
		arg.ServiceIdentityID,
		arg.MaximumUnits,
		arg.UsdMicrosPerUnit,
		arg.MaximumCostMicros,
		arg.HeldCreditMicros,
		arg.HeldOverageMicros,
		arg.ClientReference,
		arg.ReservationTtlSeconds,
		arg.UserActorReferenceSnapshot,
	)
	var i UsageReservation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.TeamNameSnapshot,
		&i.MeterID,
		&i.PriceVersionID,
		&i.AccountID,
		&i.ServiceIdentityID,
		&i.MaximumUnits,
		&i.UsdMicrosPerUnit,
		&i.MaximumCostMicros,
		&i.HeldCreditMicros,
		&i.HeldOverageMicros,
		&i.ClientReference,
		&i.Status,
		&i.ActiveOrganizationID,
		&i.ActiveTeamID,
		&i.ActiveAccountID,
		&i.ActiveServiceIdentityID,
		&i.ActiveMeterID,
		&i.ExpiresAt,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UserActorReferenceSnapshot,
		&i.ServiceNameSnapshot,
		&i.MeterNameSnapshot,
		&i.PolarEventNameSnapshot,
		&i.PriceEffectiveFromSnapshot,
		&i.PriceEffectiveUntilSnapshot,
		&i.OverageBillingPeriodID,
	)
	return i, err
}

const listExpiredUsageReservationCandidates = `-- name: ListExpiredUsageReservationCandidates :many
SELECT id, organization_id
FROM usage_reservations
WHERE status = 'held'
  AND expires_at <= statement_timestamp()
ORDER BY expires_at, id
LIMIT $1
`

type ListExpiredUsageReservationCandidatesRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) ListExpiredUsageReservationCandidates(ctx context.Context, pageLimit int32) ([]ListExpiredUsageReservationCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listExpiredUsageReservationCandidates, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredUsageReservationCandidatesRow{}
	for rows.Next() {
		var i ListExpiredUsageReservationCandidatesRow
		if err := rows.Scan(&i.ID, &i.OrganizationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredUsageReservationsForOrganization = `-- name: ListExpiredUsageReservationsForOrganization :many
SELECT id, organization_id, team_id, team_name_snapshot, meter_id, price_version_id, account_id, service_identity_id, maximum_units, usd_micros_per_unit, maximum_cost_micros, held_credit_micros, held_overage_micros, client_reference, status, active_organization_id, active_team_id, active_account_id, active_service_identity_id, active_meter_id, expires_at, finalized_at, created_at, user_actor_reference_snapshot, service_name_snapshot, meter_name_snapshot, polar_event_name_snapshot, price_effective_from_snapshot, price_effective_until_snapshot, overage_billing_period_id
FROM usage_reservations
WHERE organization_id = $1
  AND status = 'held'
  AND expires_at <= statement_timestamp()
ORDER BY expires_at, id
FOR UPDATE
`

func (q *Queries) ListExpiredUsageReservationsForOrganization(ctx context.Context, organizationID pgtype.UUID) ([]UsageReservation, error) {
	rows, err := q.db.Query(ctx, listExpiredUsageReservationsForOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageReservation{}
	for rows.Next() {
		var i UsageReservation
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.TeamID,
			&i.TeamNameSnapshot,
			&i.MeterID,
			&i.PriceVersionID,
			&i.AccountID,
			&i.ServiceIdentityID,
			&i.MaximumUnits,
			&i.UsdMicrosPerUnit,
			&i.MaximumCostMicros,
			&i.HeldCreditMicros,
			&i.HeldOverageMicros,
			&i.ClientReference,
			&i.Status,
			&i.ActiveOrganizationID,
			&i.ActiveTeamID,
			&i.ActiveAccountID,
			&i.ActiveServiceIdentityID,
			&i.ActiveMeterID,
			&i.ExpiresAt,
			&i.FinalizedAt,
			&i.CreatedAt,
			&i.UserActorReferenceSnapshot,
			&i.ServiceNameSnapshot,
			&i.MeterNameSnapshot,
			&i.PolarEventNameSnapshot,
			&i.PriceEffectiveFromSnapshot,
			&i.PriceEffectiveUntilSnapshot,
			&i.OverageBillingPeriodID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleUsageRecords = `-- name: ListVisibleUsageRecords :many
SELECT
    record.id, record.reservation_id, record.organization_id, record.team_id, record.team_name_snapshot, record.meter_id, record.account_id, record.service_identity_id, record.committed_units, record.total_cost_micros, record.credit_applied_micros, record.overage_applied_micros, record.committed_at, record.retain_until, record.price_version_id, record.usd_micros_per_unit, record.client_reference, record.user_actor_reference_snapshot, record.service_name_snapshot, record.meter_name_snapshot, record.polar_event_name_snapshot, record.price_effective_from_snapshot, record.price_effective_until_snapshot, record.billing_period_id, record.billing_period_starts_at_snapshot, record.billing_period_ends_at_snapshot,
    CASE
        WHEN outbox.delivered_at IS NOT NULL THEN 'polar_reported'
        WHEN outbox.id IS NOT NULL THEN 'polar_pending'
        ELSE 'committed'
    END::text AS delivery_status
FROM usage_records AS record
LEFT JOIN integration_outbox AS outbox
  ON outbox.integration = 'polar'
 AND outbox.operation = 'report_usage'
 AND outbox.aggregate_type = 'usage_record'
 AND outbox.aggregate_id = record.id
WHERE record.organization_id = $1
  AND record.committed_at >= $2
  AND record.committed_at < $3
  AND record.id > $4
  AND (
      $5::uuid IS NULL
      OR record.team_id = $5
  )
  AND (
      $6::uuid IS NULL
      OR record.meter_id = $6
  )
  AND (
      $7::uuid IS NULL
      OR record.account_id = $7
  )
  AND (
      $8::boolean
      OR record.account_id = $9
      OR effective_team_role(
          record.organization_id,
          record.team_id,
          $9
      ) IS NOT NULL
  )
ORDER BY record.id
LIMIT $10
`

type ListVisibleUsageRecordsParams struct {
	OrganizationID         pgtype.UUID
	FromTime               pgtype.Timestamptz
	ToTime                 pgtype.Timestamptz
	AfterID                pgtype.UUID
	TeamID                 pgtype.UUID
	MeterID                pgtype.UUID
	UserAccountID          pgtype.UUID
	FullOrganizationAccess bool
	CallerAccountID        pgtype.UUID
	PageLimit              int32
}

type ListVisibleUsageRecordsRow struct {
	ID                            pgtype.UUID
	ReservationID                 pgtype.UUID
	OrganizationID                pgtype.UUID
	TeamID                        pgtype.UUID
	TeamNameSnapshot              string
	MeterID                       pgtype.UUID
	AccountID                     pgtype.UUID
	ServiceIdentityID             pgtype.UUID
	CommittedUnits                int64
	TotalCostMicros               int64
	CreditAppliedMicros           int64
	OverageAppliedMicros          int64
	CommittedAt                   pgtype.Timestamptz
	RetainUntil                   pgtype.Timestamptz
	PriceVersionID                pgtype.UUID
	UsdMicrosPerUnit              int64
	ClientReference               string
	UserActorReferenceSnapshot    string
	ServiceNameSnapshot           string
	MeterNameSnapshot             string
	PolarEventNameSnapshot        string
	PriceEffectiveFromSnapshot    pgtype.Timestamptz
	PriceEffectiveUntilSnapshot   pgtype.Timestamptz
	BillingPeriodID               pgtype.UUID
	BillingPeriodStartsAtSnapshot pgtype.Timestamptz
	BillingPeriodEndsAtSnapshot   pgtype.Timestamptz
	DeliveryStatus                string
}

func (q *Queries) ListVisibleUsageRecords(ctx context.Context, arg ListVisibleUsageRecordsParams) ([]ListVisibleUsageRecordsRow, error) {
	rows, err := q.db.Query(ctx, listVisibleUsageRecords,
		arg.OrganizationID,
		arg.FromTime,
		arg.ToTime,
		arg.AfterID,
		arg.TeamID,
		arg.MeterID,
		arg.UserAccountID,
		arg.FullOrganizationAccess,
		arg.CallerAccountID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleUsageRecordsRow{}
	for rows.Next() {
		var i ListVisibleUsageRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReservationID,
			&i.OrganizationID,
			&i.TeamID,
			&i.TeamNameSnapshot,
			&i.MeterID,
			&i.AccountID,
			&i.ServiceIdentityID,
			&i.CommittedUnits,
			&i.TotalCostMicros,
			&i.CreditAppliedMicros,
			&i.OverageAppliedMicros,
			&i.CommittedAt,
			&i.RetainUntil,
			&i.PriceVersionID,
			&i.UsdMicrosPerUnit,
			&i.ClientReference,
			&i.UserActorReferenceSnapshot,
			&i.ServiceNameSnapshot,
			&i.MeterNameSnapshot,
			&i.PolarEventNameSnapshot,
			&i.PriceEffectiveFromSnapshot,
			&i.PriceEffectiveUntilSnapshot,
			&i.BillingPeriodID,
			&i.BillingPeriodStartsAtSnapshot,
			&i.BillingPeriodEndsAtSnapshot,
			&i.DeliveryStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUsageReservation = `-- name: LockUsageReservation :one
SELECT id, organization_id, team_id, team_name_snapshot, meter_id, price_version_id, account_id, service_identity_id, maximum_units, usd_micros_per_unit, maximum_cost_micros, held_credit_micros, held_overage_micros, client_reference, status, active_organization_id, active_team_id, active_account_id, active_service_identity_id, active_meter_id, expires_at, finalized_at, created_at, user_actor_reference_snapshot, service_name_snapshot, meter_name_snapshot, polar_event_name_snapshot, price_effective_from_snapshot, price_effective_until_snapshot, overage_billing_period_id
FROM usage_reservations
WHERE organization_id = $1
  AND id = $2
FOR UPDATE
`

type LockUsageReservationParams struct {
	OrganizationID pgtype.UUID
	ReservationID  pgtype.UUID
}

func (q *Queries) LockUsageReservation(ctx context.Context, arg LockUsageReservationParams) (UsageReservation, error) {
	row := q.db.QueryRow(ctx, lockUsageReservation, arg.OrganizationID, arg.ReservationID)
	var i UsageReservation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TeamID,
		&i.TeamNameSnapshot,
		&i.MeterID,
		&i.PriceVersionID,
		&i.AccountID,
		&i.ServiceIdentityID,
		&i.MaximumUnits,
		&i.UsdMicrosPerUnit,
		&i.MaximumCostMicros,
		&i.HeldCreditMicros,
		&i.HeldOverageMicros,
		&i.ClientReference,
		&i.Status,
		&i.ActiveOrganizationID,
		&i.ActiveTeamID,
		&i.ActiveAccountID,
		&i.ActiveServiceIdentityID,
		&i.ActiveMeterID,
		&i.ExpiresAt,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UserActorReferenceSnapshot,
		&i.ServiceNameSnapshot,
		&i.MeterNameSnapshot,
		&i.PolarEventNameSnapshot,
		&i.PriceEffectiveFromSnapshot,
		&i.PriceEffectiveUntilSnapshot,
		&i.OverageBillingPeriodID,
	)
	return i, err
}
