-- +goose Up
ALTER TABLE pr_records
    ADD COLUMN IF NOT EXISTS pr_url TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS unit_task_id TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS auto_fix_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS fix_attempt_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS max_fix_attempts INTEGER NOT NULL DEFAULT 3,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- +goose Down
ALTER TABLE pr_records
    DROP COLUMN IF EXISTS updated_at,
    DROP COLUMN IF EXISTS created_at,
    DROP COLUMN IF EXISTS max_fix_attempts,
    DROP COLUMN IF EXISTS fix_attempt_count,
    DROP COLUMN IF EXISTS auto_fix_enabled,
    DROP COLUMN IF EXISTS unit_task_id,
    DROP COLUMN IF EXISTS pr_url;
