// SPDX-License-Identifier: Apache-2.0
import { StrictMode, useState } from "react";
import { act, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { expect, it, vi, beforeEach } from "vitest";
import { CommandMenu, CommandGroup, applicationCommands, type MenuCommand } from "./command-menu";
import { ShortcutProvider, useShortcuts, useShortcutHelp, useGlobalShortcutAria } from "./shortcut-provider";
import { ShortcutId, ShortcutScope, ShortcutInput, globalShortcutBindings } from "./shortcuts";
import { i18n, useLocale } from "./localization";
import { settingsGroups } from "./settings";
import { settingsSearchTargets } from "./settings-search";
import { editableShortcutCatalog, customizationBindings, validShortcutChord } from "./shortcut-preferences";

beforeEach(()=>{vi.stubGlobal("ResizeObserver",class{observe(){}disconnect(){}unobserve(){}});HTMLElement.prototype.scrollIntoView=()=>{};});
function Fixture({commands,run=()=>{}}:{commands?:MenuCommand[];run?:()=>void}){
 useLocale();
 const [open,setOpen]=useState(false),[draft,setDraft]=useState("original uncertain draft"); const help=useShortcutHelp(),aria=useGlobalShortcutAria(ShortcutId.CommandMenu);
 useShortcuts([{id:ShortcutId.CommandMenu,scope:ShortcutScope.Global,label:"command-menu.title",bindings:globalShortcutBindings[ShortcutId.CommandMenu],input:ShortcutInput.Allow,run:()=>setOpen(value=>!value)},{id:ShortcutId.NewSession,scope:ShortcutScope.Global,label:"shortcuts.newSession",bindings:globalShortcutBindings[ShortcutId.NewSession],input:ShortcutInput.Allow,run}]);
 const catalog=commands??applicationCommands({navigate:run,navigateHeader:run,openSettings:run,newSession:run,newGeneralChat:run,newProject:run,help});
 return <main id="main" tabIndex={-1}><button aria-keyshortcuts={aria} onClick={()=>setOpen(true)}>Menu</button><textarea aria-label="Draft" value={draft} onChange={event=>setDraft(event.target.value)}/><button onClick={help}>Help</button>{open?<CommandMenu commands={catalog} close={()=>setOpen(false)}/>:null}</main>;
}
const mount=(props:Parameters<typeof Fixture>[0]={})=>render(<ShortcutProvider><Fixture {...props}/></ShortcutProvider>);
const open=()=>fireEvent.click(screen.getByRole("button",{name:"Menu"}));
it.each([['MacIntel','metaKey','ctrlKey'],['Win32','ctrlKey','metaKey'],['Linux x86_64','ctrlKey','metaKey']] as const)("uses only the fixed platform chord on %s and dismisses without background dispatch",(platform,primary,wrong)=>{
 Object.defineProperty(navigator,'platform',{configurable:true,value:platform});const run=vi.fn();mount({run});const draft=screen.getByLabelText('Draft');draft.focus();fireEvent.keyDown(draft,{key:'k',[wrong]:true});expect(screen.queryByRole('dialog')).toBeNull();
 fireEvent.keyDown(draft,{key:'k',[primary]:true});const input=screen.getByRole('combobox');expect(document.activeElement).toBe(input);expect(screen.getByRole('button',{name:'Menu'}).getAttribute('aria-keyshortcuts')).toBe(`${primary==='metaKey'?'Meta':'Control'}+K`);
 fireEvent.keyDown(input,{key:'n',shiftKey:true,[primary]:true});expect(run).not.toHaveBeenCalled();fireEvent.keyDown(input,{key:'k',[primary]:true});expect(screen.queryByRole('dialog')).toBeNull();expect(document.activeElement).toBe(draft);expect((draft as HTMLTextAreaElement).value).toBe('original uncertain draft');
});
it.each([{repeat:true},{isComposing:true},{keyCode:229},{altKey:true}])('rejects excluded shortcut events %j',flags=>{Object.defineProperty(navigator,'platform',{configurable:true,value:'Linux'});mount();fireEvent.keyDown(screen.getByLabelText('Draft'),{key:'k',ctrlKey:true,...flags});expect(screen.queryByRole('dialog')).toBeNull();});
it('retains modal and passthrough admission and handled events',()=>{mount();const draft=screen.getByLabelText('Draft');draft.setAttribute('data-shortcuts','passthrough');fireEvent.keyDown(draft,{key:'k',ctrlKey:true});expect(screen.queryByRole('dialog')).toBeNull();draft.removeAttribute('data-shortcuts');const event=new KeyboardEvent('keydown',{key:'k',ctrlKey:true,bubbles:true,cancelable:true});event.preventDefault();fireEvent(draft,event);expect(screen.queryByRole('dialog')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Help'}));fireEvent.keyDown(screen.getByRole('button',{name:'Close keyboard shortcuts'}),{key:'k',ctrlKey:true});expect(screen.queryByRole('dialog',{name:'Command menu'})).toBeNull();});
it('has exact flat catalog order and static unique enum values, with seven editable actions',()=>{
 const commands=applicationCommands({navigate:vi.fn(),navigateHeader:vi.fn(),openSettings:vi.fn(),newSession:vi.fn(),newGeneralChat:vi.fn(),newProject:vi.fn(),help:vi.fn()});expect(commands.slice(0,7).map(item=>item.label)).toEqual(['Sessions','Pull requests','Usage','Schedules','Inbox','Search','Settings']);expect(commands.slice(7,10).map(item=>item.label)).toEqual(['New session','New Chat','New project']);expect(new Set(commands.map(item=>item.value)).size).toBe(commands.length);
 expect(commands.filter(item=>item.group===CommandGroup.Settings)).toHaveLength(settingsGroups.flatMap(group=>group.categories).reduce((count,category)=>count+1+(settingsSearchTargets[category]?.length??0),0));expect(editableShortcutCatalog).toHaveLength(7);expect(validShortcutChord({key:'k',shift:false})).toBe(false);expect(customizationBindings(ShortcutId.CommandMenu,{})).toEqual([{key:'k',primary:true}]);
 mount();open();expect([...document.querySelectorAll('[cmdk-item]')].map(node=>node.getAttribute('data-value'))).toEqual(commands.map(item=>item.value));
});
it('matches current localized labels and breadcrumbs without searchable IDs; whitespace restores order',async()=>{
 mount();open();const input=screen.getByRole('combobox');fireEvent.change(input,{target:{value:'settings:appearance:language'}});await screen.findByText('No commands found.');fireEvent.change(input,{target:{value:'Appearance Language'}});await screen.findByRole('option',{name:'Appearance › Language'});expect([...document.querySelectorAll('[cmdk-item]')].every(node=>!node.getAttribute('data-value')?.includes('appearance:language')||node.textContent==='Appearance › Language')).toBe(true);
 fireEvent.change(input,{target:{value:'theme'}});await screen.findByRole('option',{name:'Appearance › Theme'});await act(()=>i18n.changeLanguage('ko'));expect(document.activeElement).toBe(input);expect((input as HTMLInputElement).value).toBe('theme');await screen.findByText('검색 결과가 없습니다.');fireEvent.change(input,{target:{value:'테마'.normalize('NFD')}});await screen.findByRole('option',{name:'외관 › 테마'});fireEvent.change(input,{target:{value:'   '}});await waitFor(()=>expect(document.querySelector('[cmdk-item]')?.getAttribute('data-value')).toBe('navigate:sessions'));
});
it('closes before one pointer or Enter callback, rejects disabled and IME actions, loops selection',async()=>{
 let closed=false;const run=vi.fn(()=>{closed=!document.querySelector('dialog[open]');screen.getByLabelText('Draft').focus();});const commands:MenuCommand[]=[{value:'one',group:CommandGroup.Create,label:'One',run},{value:'blocked',group:CommandGroup.Create,label:'Blocked',enabled:false,reason:'Original guard',run},{value:'two',group:CommandGroup.Create,label:'Two',run}];mount({commands});open();const input=screen.getByRole('combobox');await waitFor(()=>expect(document.querySelector('[data-selected="true"]')?.getAttribute('data-value')).toBe('one'));
 fireEvent.keyDown(input,{key:'ArrowUp'});await waitFor(()=>expect(document.querySelector('[data-selected="true"]')?.getAttribute('data-value')).toBe('two'));fireEvent.keyDown(input,{key:'Enter',keyCode:229});expect(run).not.toHaveBeenCalled();fireEvent.compositionStart(input);fireEvent.click(screen.getByRole('option',{name:'Two'}));expect(run).not.toHaveBeenCalled();fireEvent.compositionEnd(input);fireEvent.click(screen.getByRole('option',{name:'Blocked Original guard'}));expect(run).not.toHaveBeenCalled();fireEvent.keyDown(input,{key:'Enter'});expect(run).toHaveBeenCalledTimes(1);expect(closed).toBe(true);expect(document.activeElement).toBe(screen.getByLabelText('Draft'));
});
it.each(['Escape','Close','backdrop'])('resets query, restores opener and retains drafts after %s',async dismissal=>{mount();const opener=screen.getByRole('button',{name:'Menu'});opener.focus();open();fireEvent.change(screen.getByRole('combobox'),{target:{value:'Language'}});if(dismissal==='Escape')fireEvent.keyDown(screen.getByRole('combobox'),{key:'Escape'});else if(dismissal==='Close')fireEvent.click(screen.getByRole('button',{name:'Close command menu'}));else fireEvent.click(screen.getByRole('dialog'),{clientX:-1,clientY:-1});expect(screen.queryByRole('dialog')).toBeNull();expect(document.activeElement).toBe(opener);open();expect((screen.getByRole('combobox') as HTMLInputElement).value).toBe('');expect((screen.getByLabelText('Draft') as HTMLTextAreaElement).value).toBe('original uncertain draft');});
it('StrictMode keeps a single dispatch and same identity while replacement disposes the visit',()=>{const view=render(<StrictMode><ShortcutProvider key="a"><Fixture/></ShortcutProvider></StrictMode>);open();const input=screen.getByRole('combobox');fireEvent.change(input,{target:{value:'Language'}});view.rerender(<StrictMode><ShortcutProvider key="a"><Fixture/></ShortcutProvider></StrictMode>);expect(screen.getByRole('combobox')).toBe(input);expect((input as HTMLInputElement).value).toBe('Language');view.rerender(<StrictMode><ShortcutProvider key="b"><Fixture/></ShortcutProvider></StrictMode>);expect(screen.queryByRole('dialog')).toBeNull();});

it('keeps focused Close Enter out of cmdk selection and retains native button activation',async()=>{
 const run=vi.fn();mount({commands:[{value:'one',group:CommandGroup.Create,label:'One',run}]});screen.getByRole('button',{name:'Menu'}).focus();open();await waitFor(()=>expect(document.querySelector('[data-selected="true"]')?.getAttribute('data-value')).toBe('one'));
 const close=screen.getByRole('button',{name:'Close command menu'});close.focus();expect(fireEvent.keyDown(close,{key:'Enter'})).toBe(true);expect(run).not.toHaveBeenCalled();expect(screen.getByRole('dialog')).toBeTruthy();
 // jsdom does not synthesize a button click from keydown. An uncancelled
 // native Enter activates that same click path in the browser.
 fireEvent.click(close);expect(screen.queryByRole('dialog')).toBeNull();expect(run).not.toHaveBeenCalled();expect(document.activeElement).toBe(screen.getByRole('button',{name:'Menu'}));
});
