// SPDX-License-Identifier: Apache-2.0
import { useId, useState } from "react";
import { useQuery } from "@connectrpc/connect-query";
import { EntityKind, isEntityId, supportsResourceSchema, ResourceQuery, SystemQuery, SystemCapability, HarnessInheritance, inheritedHarnessValues, effectiveHarnessSelection, readableHarnessValues, type HarnessValues, type HarnessValueField, type HarnessDefaultEntry } from "@delinoio/delidev-api-client";
import { document, items, object, text, type Document } from "./documents";
import { ResourceChoice, ServiceTierField } from "./configuration-fields";
import { copy, useLocale, type MessageKey } from "./localization";
import { Problem } from "./ui";
import { SettingsActionButton, SettingsActionIcon } from "./settings-action";

export enum HarnessSettingsScope { Server = "server", Project = "project", Agent = "agent" }
const labels:Record<HarnessValueField,MessageKey>={model:"harness-settings.model",effort:"harness-settings.effort",permission:"harness-settings.permission",claude_permission:"harness-settings.permission",approvals_reviewer:"harness-settings.reviewer",subagent_model:"harness-settings.subagentModel",subagent_effort:"harness-settings.subagentEffort",max_concurrency:"harness-settings.concurrency",approval_policy:"harness-settings.approvalPolicy",approval_review_model:"harness-settings.reviewModel",service_tier:"harness-settings.serviceTier"};
const fields:HarnessValueField[]=["model","effort","permission","approval_policy","approvals_reviewer","subagent_model","subagent_effort","max_concurrency","service_tier","approval_review_model"];
const ownerKey={native:"harness-settings.native",server:"harness-settings.server",project:"harness-settings.project",agent:"harness-settings.agent"} as const;
function defaults(data:Document):HarnessDefaultEntry[]{return items(data.harness_defaults).filter(value=>readableHarnessValues(object(value).values)) as HarnessDefaultEntry[];}

function HarnessValueFields({values,change,scope,source={},server=[],project=[],active,disabled=false,modelSelection=true,onlyModel=false}:{values:HarnessValues;change:(v:HarnessValues)=>void;scope:HarnessSettingsScope;source?:Pick<HarnessDefaultEntry,"provider_id"|"subscription_service"|"api_protocol">;server?:HarnessDefaultEntry[];project?:HarnessDefaultEntry[];active:boolean;disabled?:boolean;modelSelection?:boolean;onlyModel?:boolean}) {
 useLocale();const [modelProblem,setModelProblem]=useState(false);const id=useId();const status=useQuery(SystemQuery.getStatus,{},{enabled:active,retry:false});
 const supported=status.data?.capabilities.includes(SystemCapability.HARNESS_DEFAULTS_V1)===true;
 const subagents=status.data?.capabilities.includes(SystemCapability.CODEX_SUBAGENT_CONFIGURATION_V1)===true;
 const reviewer=status.data?.capabilities.includes(SystemCapability.CODEX_APPROVAL_REVIEW_V1)===true;
 return <div className="settings-form-fields"><Problem error={status.error}/>{fields.filter(key=>onlyModel?key==="model":(modelSelection||key!=="model") && (!["subagent_model","subagent_effort","max_concurrency"].includes(key)||subagents||values[key].state===HarnessInheritance.Override) && (key!=="approvals_reviewer"||reviewer||values[key].state===HarnessInheritance.Override) && (key!=="approval_review_model"||values[key].state===HarnessInheritance.Override)).map(key=>{
  const selection=values[key];const available=supported&&key!=="approval_review_model"&&(!["subagent_model","subagent_effort","max_concurrency"].includes(key)||subagents)&&(key!=="approvals_reviewer"||reviewer);
  const effective=effectiveHarnessSelection(key,"codex",source,server,project,values);
  const set=(value:string|number)=>change({...values,[key]:{state:HarnessInheritance.Override,value},...(key==="approvals_reviewer"&&value==="auto_review"?{approval_policy:{state:HarnessInheritance.Override,value:"on-request"}}:{})});
  const choices=key==="permission"?["default","read-only","workspace-write","full-access"]:key==="approvals_reviewer"?["user","auto_review"]:undefined;
  const updateModel=(value:string,model?:Document)=>{if(model&&(source.provider_id&&model.provider_id!==source.provider_id||source.subscription_service&&model.subscription_service!==source.subscription_service||!items(model.harnesses).includes("codex"))){setModelProblem(true);return;}setModelProblem(false);set(value);};
  return <fieldset key={key} data-settings-search-target={`codex-${key}`} aria-describedby={`${id}-${key}-effective`}><legend>{copy(labels[key])}</legend>
   <label>{copy("harness-settings.selection")}<select aria-label={`${copy(labels[key])}: ${copy("harness-settings.selection")}`} value={selection.state} disabled={disabled||!available} onChange={event=>change({...values,[key]:event.target.value===HarnessInheritance.Inherit?{state:HarnessInheritance.Inherit}:{state:HarnessInheritance.Override,value:key==="max_concurrency"?0:key==="permission"?"default":key==="approvals_reviewer"?"user":""}})}><option value="inherit">{copy("harness-settings.inherit")}</option><option value="override">{copy("harness-settings.override")}</option></select></label>
   {selection.state===HarnessInheritance.Override?key==="service_tier"?<fieldset disabled={disabled||!available}><ServiceTierField value={selection.value} unavailable={!available} change={value=>set(value)} clear={()=>set("")}/></fieldset>:key==="model"?<ResourceChoice label={copy(labels[key])} kind={EntityKind.MODEL} value={text(selection.value)} change={updateModel} active={active} disabled={disabled||!available} required/>:choices?<label>{copy(labels[key])}<select aria-label={copy(labels[key])} value={text(selection.value)} disabled={disabled||!available} onChange={event=>set(event.target.value)}>{!choices.includes(text(selection.value))?<option value={text(selection.value)}>{text(selection.value)}</option>:null}{choices.map(value=><option key={value} value={value}>{value}</option>)}</select></label>:<label>{copy(labels[key])}<input aria-label={copy(labels[key])} type={key==="max_concurrency"?"number":"text"} min={0} max={4294967295} step={1} maxLength={key==="effort"||key==="subagent_effort"?64:256} value={selection.value??""} disabled={disabled||!available} onChange={event=>set(key==="max_concurrency"?Number(event.target.value):event.target.value)}/></label>:null}
   {key==="model"&&modelProblem?<p role="alert">{copy("harness-settings.wrongSource")}</p>:null}<p id={`${id}-${key}-effective`}>{copy("harness-settings.effective",{v0:effective.selection.state===HarnessInheritance.Override?String(effective.selection.value):copy("harness-settings.unavailable"),v1:copy(selection.state===HarnessInheritance.Override?ownerKey[scope]:ownerKey[effective.source])})}</p>
   {!available?<p role="status">{copy("harness-settings.unsupported")}</p>:null}
   {selection.state===HarnessInheritance.Override?<SettingsActionButton icon={SettingsActionIcon.Inspect} type="button" disabled={disabled||!supported} onClick={()=>change({...values,[key]:{state:HarnessInheritance.Inherit}})}>{copy("harness-settings.reset",{v0:copy(labels[key])})}</SettingsActionButton>:null}
  </fieldset>;
 })}<p>{copy("harness-settings.nativeBoundary")}</p></div>;
}

export function HarnessDefaultFields({data,change,scope,active,disabled=false}:{data:Document;change:(data:Document)=>void;scope:HarnessSettingsScope.Server|HarnessSettingsScope.Project;active:boolean;disabled?:boolean}) {
 useLocale();const [provider,setProvider]=useState("");const [protocol,setProtocol]=useState("");const [service,setService]=useState(false);
 const settings=useQuery(ResourceQuery.listResources,{filter:{kind:EntityKind.SETTINGS,pageSize:2}},{enabled:active&&scope===HarnessSettingsScope.Project,retry:false});
 const complete=scope===HarnessSettingsScope.Server||Boolean(settings.data&&!settings.error&&!settings.data.nextPageToken&&settings.data.resources.length<=1&&settings.data.resources.every(row=>row.kind===EntityKind.SETTINGS&&isEntityId(row.id)&&row.revision>0n&&supportsResourceSchema(row)));
 const parent=scope===HarnessSettingsScope.Server?[]:complete?defaults(document(settings.data?.resources[0])):[];
 const entries=items(data.harness_defaults);const current=defaults(data);
 const write=(next:unknown[])=>change({...data,harness_defaults_version:1,harness_defaults:next});
 const add=(source:Partial<HarnessDefaultEntry>)=>{const entry={harness:"codex",...source,values:inheritedHarnessValues()};if(entries.length>=256||current.some(v=>v.harness==="codex"&&v.provider_id===entry.provider_id&&v.subscription_service===entry.subscription_service&&v.api_protocol===entry.api_protocol))return;write([...entries,entry]);};
 return <section data-settings-search-target="codex-defaults"><h3>{copy("harness-settings.title")}</h3><p>{copy(scope===HarnessSettingsScope.Server?"harness-settings.serverScope":"harness-settings.projectScope")}</p><Problem error={settings.error}/>{!complete?<p role="status">{copy("harness-settings.parentUnavailable")}</p>:null}
 {entries.map((raw,index)=>{const entry=object(raw);if(entry.harness!=="codex")return null;const values=readableHarnessValues(entry.values)?entry.values:undefined;return <fieldset key={index}><legend>{text(entry.subscription_service)||text(entry.provider_id)||copy("harness-settings.allSources")}{entry.api_protocol?` · ${text(entry.api_protocol)}`:""}</legend>{values?<HarnessValueFields values={values} scope={scope} source={entry} server={scope===HarnessSettingsScope.Server?current:parent} project={scope===HarnessSettingsScope.Project?current:[]} active={active} disabled={disabled} change={values=>write(entries.map((value,i)=>i===index?{...entry,values}:value))}/>:<p role="alert">{copy("harness-settings.unsupported")}</p>}<SettingsActionButton icon={SettingsActionIcon.Delete} type="button" disabled={disabled} onClick={()=>write(entries.filter((_,i)=>i!==index))}>{copy("harness-settings.removeScope")}</SettingsActionButton></fieldset>;})}
 <SettingsActionButton icon={SettingsActionIcon.Add} type="button" disabled={disabled} onClick={()=>add({})}>{copy("harness-settings.addHarness")}</SettingsActionButton>
 <fieldset><legend>{copy("harness-settings.addSource")}</legend><label><input type="checkbox" checked={service} disabled={disabled} onChange={event=>setService(event.target.checked)}/>{copy("harness-settings.chatgpt")}</label>{!service?<><ResourceChoice label={copy("harness-settings.provider")} kind={EntityKind.PROVIDER} value={provider} change={setProvider} active={active} disabled={disabled}/><label>{copy("harness-settings.apiProfile")}<select value={protocol} disabled={disabled} onChange={event=>setProtocol(event.target.value)}><option value="">{copy("harness-settings.allProfiles")}</option><option value="openai-responses">OpenAI Responses</option><option value="openai-chat">OpenAI Chat Completions</option><option value="anthropic-messages">Anthropic Messages</option></select></label></>:null}<SettingsActionButton icon={SettingsActionIcon.Add} type="button" disabled={disabled||!service&&!provider} onClick={()=>add(service?{subscription_service:"chatgpt"}:{provider_id:provider,...(protocol?{api_protocol:protocol}:{})})}>{copy("harness-settings.addSource")}</SettingsActionButton></fieldset>
 </section>;
}

export function AgentHarnessFields({data,change,active,disabled=false,routeCount=1,sources=[]}:{data:Document;change:(data:Document)=>void;active:boolean;disabled?:boolean;routeCount?:number;sources?:Pick<HarnessDefaultEntry,"provider_id"|"subscription_service"|"api_protocol">[]}) {
 useLocale();const [view,setView]=useState(0);const settings=useQuery(ResourceQuery.listResources,{filter:{kind:EntityKind.SETTINGS,pageSize:2}},{enabled:active,retry:false});
 const complete=Boolean(settings.data&&!settings.error&&!settings.data.nextPageToken&&settings.data.resources.length<=1&&settings.data.resources.every(row=>row.kind===EntityKind.SETTINGS&&isEntityId(row.id)&&row.revision>0n&&supportsResourceSchema(row)));
 const raw=object(data.harness_settings);const values=readableHarnessValues(raw.values)?raw.values:inheritedHarnessValues();const models=Array.from({length:routeCount},(_,i)=>object(items(raw.models)[i]).state?object(items(raw.models)[i]):{state:HarnessInheritance.Inherit});
 const write=(nextValues:HarnessValues,nextModels= models)=>change({...data,harness_settings:{...raw,version:1,models:nextModels,values:nextValues}});
 return <section><h3>{copy("harness-settings.title")}</h3><p>{copy("harness-settings.agentScope")}</p><Problem error={settings.error}/>{!complete?<p role="status">{copy("harness-settings.parentUnavailable")}</p>:null}<label>{copy("harness-settings.previewSource")}<select value={view} onChange={event=>setView(Number(event.target.value))}>{models.map((_,i)=><option key={i} value={i}>{copy("harness-settings.sourceModel",{v0:i+1})}</option>)}</select></label><HarnessValueFields source={sources[view]??{}} scope={HarnessSettingsScope.Agent} values={values} change={write} server={complete?defaults(document(settings.data?.resources[0])):[]} active={active} disabled={disabled} modelSelection={false}/>{models.map((selection,index)=><fieldset key={index}><legend>{copy("harness-settings.sourceModel",{v0:index+1})}</legend><HarnessValueFields source={sources[index]??{}} server={complete?defaults(document(settings.data?.resources[0])):[]} scope={HarnessSettingsScope.Agent} values={{...inheritedHarnessValues(),model:selection as HarnessValues["model"]}} change={next=>write(values,models.map((m,i)=>i===index?next.model:m))} active={active} disabled={disabled} onlyModel/></fieldset>)}</section>;
}
