import { Code, ConnectError, createRouterTransport } from "@connectrpc/connect";
import { TransportProvider } from "@connectrpc/connect-query";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { expect, it, vi } from "vitest";
import { SystemService } from "@delinoio/delidev-api-client";
import { LocalServerControls, LocalServerState, type LocalServerStatus } from "./local-server";
import { Modal } from "./ui";
import { MutationIntents } from "./mutation";
import { LocalConnectionHelp, LocalConnectionPresentationProvider } from "./local-connection-presentation";

it("requires an explicit stop, retains its uncertain request, and never restarts from a stopped status", async () => {
  const stop = vi.fn(async (_request: unknown) => ({}));
  stop.mockRejectedValueOnce(new ConnectError("Response lost", Code.Unavailable));
  const restart = vi.fn();
  const transport = createRouterTransport((router) => router.service(SystemService, { stopServer: stop }));
  const client = new QueryClient();
  const view = (state: LocalServerState) => <TransportProvider transport={transport}><QueryClientProvider client={client}><MutationIntents><LocalServerControls status={{ state, attempts: 0, retry_ms: 0 } satisfies LocalServerStatus} restart={restart} busy={false} /></MutationIntents></QueryClientProvider></TransportProvider>;
  const mounted = render(view(LocalServerState.Ready));
  fireEvent.click(screen.getByText("Local server"));
  fireEvent.click(screen.getByRole("button", { name: "Stop local server" }));
  expect(stop).not.toHaveBeenCalled();
  fireEvent.click(screen.getByRole("button", { name: "Confirm server stop" }));
  await screen.findByRole("button", { name: "Retry the same server stop" });
  mounted.rerender(view(LocalServerState.Stopped));
  expect(restart).not.toHaveBeenCalled();
  fireEvent.click(screen.getByRole("button", { name: "Retry the same server stop" }));
  await waitFor(() => expect(stop).toHaveBeenCalledTimes(2));
  expect(stop.mock.calls[1][0]).toEqual(stop.mock.calls[0][0]);
  fireEvent.click(screen.getByRole("button", { name: "Start local server" }));
  expect(restart).toHaveBeenCalledTimes(1);
});

it("reveals the original connection view inline and preserves its confirmation across presentation moves", async () => {
  const stop = vi.fn(async () => ({})), restart = vi.fn();
  const transport = createRouterTransport(router => router.service(SystemService, { stopServer: stop }));
  const client = new QueryClient();
  const target = document.createElement("div");
  document.body.append(target);
  const view = (destination?: HTMLElement) => <TransportProvider transport={transport}><QueryClientProvider client={client}><MutationIntents><LocalConnectionPresentationProvider target={destination} inline={false}><LocalConnectionHelp /><LocalServerControls status={{ state: LocalServerState.Ready, attempts: 0, retry_ms: 0 }} restart={restart} busy={false} /></LocalConnectionPresentationProvider></MutationIntents></QueryClientProvider></TransportProvider>;
  const mounted = render(view());
  expect(screen.queryByRole("button", { name: "Stop local server" })).toBeNull();
  fireEvent.click(screen.getByRole("button", { name: "Connection controls" }));
  fireEvent.click(screen.getByText("Local server"));
  fireEvent.click(screen.getByRole("button", { name: "Stop local server" }));
  mounted.rerender(view(target));
  expect(screen.getAllByRole("button", { name: "Confirm server stop" })).toHaveLength(1);
  mounted.rerender(view());
  expect(screen.getByRole("button", { name: "Confirm server stop" })).toBeTruthy();
  expect(stop).not.toHaveBeenCalled();
  expect(restart).not.toHaveBeenCalled();
  fireEvent.click(screen.getByRole("button", { name: "Confirm server stop" }));
  await waitFor(() => expect(stop).toHaveBeenCalledTimes(1));
  mounted.unmount(); target.remove();
});

it("presents the same guarded controller inside the invoking modal and releases only its view on departure", () => {
  const stop = vi.fn(async () => ({})), restart = vi.fn(), request = vi.fn();
  const transport = createRouterTransport(router => router.service(SystemService, { stopServer: stop }));
  const client = new QueryClient();
  const view = (open: boolean) => <TransportProvider transport={transport}><QueryClientProvider client={client}><MutationIntents><LocalConnectionPresentationProvider inline={false} onRequest={request}>{open ? <Modal title="Original account task" close={() => {}}><LocalConnectionHelp /></Modal> : null}<LocalServerControls status={{ state: LocalServerState.Ready, attempts: 0, retry_ms: 0 }} restart={restart} busy={false} /></LocalConnectionPresentationProvider></MutationIntents></QueryClientProvider></TransportProvider>;
  const mounted = render(view(true));
  const task = screen.getByRole("dialog", { name: "Original account task" });
  fireEvent.click(within(task).getByRole("button", { name: "Connection controls" }));
  fireEvent.click(within(task).getByText("Local server"));
  fireEvent.click(within(task).getByRole("button", { name: "Stop local server" }));
  expect(within(task).getByRole("button", { name: "Confirm server stop" })).toBeTruthy();
  expect(screen.getAllByRole("button", { name: "Confirm server stop" })).toHaveLength(1);
  mounted.rerender(view(false));
  expect(request).toHaveBeenLastCalledWith(undefined);
  expect(screen.queryByRole("button", { name: "Confirm server stop" })).toBeNull();
  expect(stop).not.toHaveBeenCalled(); expect(restart).not.toHaveBeenCalled();
});

it("releases a mounted inactive task slot and retains the original confirmation in diagnostics", () => {
  const stop = vi.fn(async () => ({})), restart = vi.fn(), request = vi.fn();
  const transport = createRouterTransport(router => router.service(SystemService, { stopServer: stop }));
  const client = new QueryClient();
  const target = document.createElement("div"); document.body.append(target);
  const view = (active: boolean) => <TransportProvider transport={transport}><QueryClientProvider client={client}><MutationIntents><LocalConnectionPresentationProvider target={target} inline={false} onRequest={request}><section hidden={!active} aria-label="Original retained task"><LocalConnectionHelp active={active} /></section><LocalServerControls status={{ state: LocalServerState.Ready, attempts: 0, retry_ms: 0 }} restart={restart} busy={false} /></LocalConnectionPresentationProvider></MutationIntents></QueryClientProvider></TransportProvider>;
  const mounted = render(view(true));
  fireEvent.click(screen.getByRole("button", { name: "Connection controls" }));
  fireEvent.click(screen.getByText("Local server"));
  fireEvent.click(screen.getByRole("button", { name: "Stop local server" }));
  mounted.rerender(view(false));
  expect(request).toHaveBeenLastCalledWith(undefined);
  expect(within(target).getByRole("button", { name: "Confirm server stop" })).toBeTruthy();
  expect(stop).not.toHaveBeenCalled(); expect(restart).not.toHaveBeenCalled();
  mounted.unmount(); target.remove();
});
