// SPDX-License-Identifier: Apache-2.0
import { useEffect, useId, useState } from "react";
import { useQuery } from "@connectrpc/connect-query";
import { SystemQuery, SystemCapability, EntityKind, McpAuthentication, McpAuthenticationState, McpMutation, McpTransport, newRequestId, type McpDefinition, type McpServer } from "@delinoio/delidev-api-client";
import { ResourceChoice } from "./configuration-fields";
import { McpPending, useMcpCatalog, useMcpManagement } from "./mcp-management";
import { SettingsActionButton, SettingsActionIcon, SettingsActionPresentation } from "./settings-action";
import { SettingsTaskDialog, SettingsTaskActions, SettingsDialogSize } from "./settings-task";
import { SettingsLoading } from "./settings-presentation";
import { copy, useLocale } from "./localization";
import { Problem } from "./ui";
import "./mcp-settings.css";
export function McpSettings({active}:{active:boolean}) {
 useLocale();const owner=useMcpManagement();const [machine,setMachine]=useState(""),[search,setSearch]=useState(""),[editor,setEditor]=useState<McpServer|null>(),[deleting,setDeleting]=useState<McpServer>();
 const status=useQuery(SystemQuery.getStatus,{}, {enabled:active,retry:false}),supported=status.data?.capabilities.includes(SystemCapability.MCP_MANAGEMENT_V1)===true;
 const catalog=useMcpCatalog(machine,active&&supported),blocked=owner.mutation.busy||owner.mutation.uncertain||owner.oauth?.busy===true||owner.oauth?.state===McpAuthenticationState.PENDING||owner.oauth?.uncertain===true;
 const refresh=()=>void catalog.refetch();
 const rows=(catalog.data?.servers??[]).filter(row=>row.definition?.name.toLocaleLowerCase().includes(search.toLocaleLowerCase()));
 return <div className="mcp-settings" data-settings-search-target="mcp-inventory"><McpPending/><Problem error={status.error}/>{status.data&&!supported?<p role="status">{copy("mcp.serverUnsupported")}</p>:null}<ResourceChoice kind={EntityKind.MACHINE} label={copy("mcp.runner")} value={machine} change={setMachine} active={active} required/>
 <div className="mcp-toolbar"><label>{copy("mcp.search")}<input type="search" maxLength={128} value={search} onChange={event=>setSearch(event.target.value)}/></label><SettingsActionButton icon={SettingsActionIcon.Add} disabled={!machine||blocked||!catalog.data||Boolean(catalog.error)} onClick={()=>setEditor(null)}>{copy("mcp.add")}</SettingsActionButton><SettingsActionButton icon={SettingsActionIcon.Refresh} disabled={!machine||catalog.isFetching} onClick={refresh}>{copy("mcp.refresh")}</SettingsActionButton></div>
 <Problem error={catalog.error}/>{catalog.isLoading&&machine?<SettingsLoading label={copy("mcp.loading")}/>:null}
 {catalog.data&&!catalog.error&&!catalog.isFetching&&!rows.length?<p role="status">{copy("mcp.empty")}</p>:null}
 {rows.map(row=>{const definition=row.definition!;return <article className="mcp-row" key={definition.id}><div><h2>{definition.name}</h2><p>{definition.transport===McpTransport.STDIO?copy("mcp.stdio"):copy("mcp.http")} · {copy(definition.enabled?"mcp.enabled":"mcp.disabled")}</p><p>{copy(row.authenticationState===McpAuthenticationState.READY?"mcp.ready":row.authenticationState===McpAuthenticationState.NOT_REQUIRED?"mcp.notRequired":row.authenticationState===McpAuthenticationState.PENDING?"mcp.pending":row.authenticationState===McpAuthenticationState.UNCERTAIN?"mcp.uncertain":row.authenticationState===McpAuthenticationState.CANCELED?"mcp.canceled":"mcp.required")}</p><p className="scope">{copy("mcp.runtimeUnavailable")}</p><ul className="scope">{["Codex","Claude Code","OpenCode","Grok"].map(harness=><li key={harness}>{harness}: {copy("mcp.unsupported")}</li>)}</ul>{row.agentIds.length?<div><p>{copy("mcp.usedBy",{count:row.agentIds.length})}</p><ul>{row.agentIds.map(id=><li key={id}><code>{id}</code></li>)}</ul></div>:null}</div><div className="actions"><SettingsActionButton icon={SettingsActionIcon.Edit} presentation={SettingsActionPresentation.Icon} targetName={definition.name} disabled={blocked||Boolean(catalog.error)} onClick={()=>setEditor(row)}>{copy("mcp.edit")}</SettingsActionButton><SettingsActionButton icon={SettingsActionIcon.Save} disabled={blocked||Boolean(catalog.error)} onClick={()=>void owner.mutation.send({machineId:machine,operation:McpMutation.ENABLE,mutation:{id:definition.id,expectedRevision:definition.revision,requestId:newRequestId()},enabled:!definition.enabled})}>{copy(definition.enabled?"mcp.disable":"mcp.enable")}</SettingsActionButton>{row.authenticationAttemptId&&row.authenticationState===McpAuthenticationState.PENDING?<SettingsActionButton icon={SettingsActionIcon.Cancel} disabled={owner.mutation.busy||owner.oauth?.busy} onClick={()=>owner.cancelServer(row)}>{copy("mcp.cancelAuthentication")}</SettingsActionButton>:null}{definition.authentication===McpAuthentication.OAUTH?<SettingsActionButton icon={SettingsActionIcon.Connect} disabled={blocked||!owner.nativeAvailable||Boolean(catalog.error)||[McpAuthenticationState.PENDING,McpAuthenticationState.UNCERTAIN].includes(row.authenticationState)} onClick={()=>owner.start(row)}>{copy("mcp.authenticate")}</SettingsActionButton>:null}<SettingsActionButton icon={SettingsActionIcon.Delete} presentation={SettingsActionPresentation.Icon} targetName={definition.name} disabled={blocked||Boolean(catalog.error)||row.agentIds.length>0} onClick={()=>setDeleting(row)}>{copy("mcp.delete")}</SettingsActionButton></div></article>;})}
 {editor!==undefined?<SettingsTaskDialog title={copy(editor?"mcp.edit":"mcp.add")} size={SettingsDialogSize.Form} close={()=>setEditor(undefined)}><McpEditor machine={machine} initial={editor??undefined} done={()=>{setEditor(undefined);refresh();}}/></SettingsTaskDialog>:null}
 {deleting?<SettingsTaskDialog title={copy("mcp.delete")} size={SettingsDialogSize.Form} close={()=>setDeleting(undefined)}><p>{copy("mcp.confirmDelete",{name:deleting.definition!.name})}</p><SettingsTaskActions><SettingsActionButton icon={SettingsActionIcon.Cancel} disabled={blocked} onClick={()=>setDeleting(undefined)}>{copy("mcp.cancel")}</SettingsActionButton><SettingsActionButton icon={SettingsActionIcon.Delete} disabled={blocked||deleting.agentIds.length>0} onClick={()=>{void owner.mutation.send({machineId:deleting.machineId,operation:McpMutation.DELETE,mutation:{id:deleting.definition!.id,expectedRevision:deleting.definition!.revision,requestId:newRequestId()},confirmed:true});setDeleting(undefined);}}>{copy("mcp.confirm")}</SettingsActionButton></SettingsTaskActions></SettingsTaskDialog>:null}
 </div>;
}
function McpEditor({machine,initial,done}:{machine:string;initial?:McpServer;done:()=>void}) {
 useLocale();const owner=useMcpManagement(),formId=useId();const base=initial?.definition;
 const [draft,setDraft]=useState<McpDefinition>(()=>base?{...base,arguments:[...base.arguments],environmentNames:[...base.environmentNames],headerNames:[...base.headerNames]}:{$typeName:"delidev.v1.McpDefinition",id:newRequestId(),name:"",transport:McpTransport.STDIO,executable:"",arguments:[],directory:"",endpoint:"",environmentNames:[],headerNames:[],authentication:McpAuthentication.NONE,enabled:true,revision:0n});
 const [replace,setReplace]=useState(!initial),[environment,setEnvironment]=useState<Record<string,string>>({}),[headers,setHeaders]=useState<Record<string,string>>({});
 const blocked=owner.mutation.busy||owner.mutation.uncertain;const change=<K extends keyof McpDefinition>(key:K,value:McpDefinition[K])=>setDraft(old=>({...old,[key]:value}));
 const [sent,setSent]=useState(false);useEffect(()=>{if(sent&&!owner.mutation.busy&&!owner.mutation.uncertain&&!owner.mutation.error)done();},[sent,owner.mutation.busy,owner.mutation.uncertain,owner.mutation.error,done]);
 const names=(value:string)=>value.split("\n").map(name=>name.trim()).filter(Boolean);
 return <form id={formId} className="mcp-form" onSubmit={event=>{event.preventDefault();if(blocked)return;const secrets=replace&&draft.authentication===McpAuthentication.MANUAL?{environment:draft.environmentNames.map(name=>({name,value:environment[name]??""})),headers:draft.headerNames.map(name=>({name,value:headers[name]??""}))}:undefined;setSent(true);void owner.mutation.send({machineId:machine,operation:McpMutation.SAVE,definition:draft,mutation:{id:draft.id,expectedRevision:base?.revision??0n,requestId:newRequestId()},secrets});}}>
 <p>{copy("mcp.metadataOnly")}</p><fieldset disabled={blocked}><label>{copy("mcp.name")}<input required maxLength={128} value={draft.name} onChange={event=>change("name",event.target.value)}/></label><label>{copy("mcp.transport")}<select value={draft.transport} onChange={event=>setDraft(old=>({...old,transport:Number(event.target.value) as McpTransport,executable:"",directory:"",arguments:[],endpoint:"",environmentNames:[],headerNames:[],authentication:McpAuthentication.NONE}))}><option value={McpTransport.STDIO}>{copy("mcp.stdio")}</option><option value={McpTransport.STREAMABLE_HTTP}>{copy("mcp.http")}</option></select></label>
 {draft.transport===McpTransport.STDIO?<><label>{copy("mcp.executable")}<input required maxLength={4096} value={draft.executable} onChange={event=>change("executable",event.target.value)}/></label><label>{copy("mcp.arguments")}<textarea rows={3} value={draft.arguments.join("\n")} onChange={event=>change("arguments",event.target.value?event.target.value.split("\n"):[])}/></label><label>{copy("mcp.directory")}<input maxLength={4096} value={draft.directory} onChange={event=>change("directory",event.target.value)}/></label></>:<label>{copy("mcp.endpoint")}<input required type="url" maxLength={4096} value={draft.endpoint} onChange={event=>change("endpoint",event.target.value)}/></label>}
 <label>{copy("mcp.authentication")}<select value={draft.authentication} onChange={event=>setDraft(old=>({...old,authentication:Number(event.target.value) as McpAuthentication,environmentNames:[],headerNames:[]}))}><option value={McpAuthentication.NONE}>{copy("mcp.none")}</option><option value={McpAuthentication.MANUAL}>{copy("mcp.manual")}</option>{draft.transport===McpTransport.STREAMABLE_HTTP?<option value={McpAuthentication.OAUTH}>OAuth</option>:null}</select></label>
 {draft.authentication===McpAuthentication.MANUAL?<><label>{copy(draft.transport===McpTransport.STDIO?"mcp.environmentNames":"mcp.headerNames")}<textarea rows={3} value={(draft.transport===McpTransport.STDIO?draft.environmentNames:draft.headerNames).join("\n")} onChange={event=>change(draft.transport===McpTransport.STDIO?"environmentNames":"headerNames",names(event.target.value))}/></label>{initial?<label><input type="checkbox" checked={replace} onChange={event=>setReplace(event.target.checked)}/>{copy("mcp.replaceSecrets")}</label>:null}<p>{copy("mcp.writeOnly")}</p>{replace?(draft.transport===McpTransport.STDIO?draft.environmentNames:draft.headerNames).map((name,index)=><label key={index}>{name}<input type="password" autoComplete="new-password" maxLength={16384} value={(draft.transport===McpTransport.STDIO?environment:headers)[name]??""} onChange={event=>(draft.transport===McpTransport.STDIO?setEnvironment:setHeaders)(old=>({...old,[name]:event.target.value}))}/></label>):null}</>:null}
 <label><input type="checkbox" checked={draft.enabled} onChange={event=>change("enabled",event.target.checked)}/>{copy("mcp.enabled")}</label></fieldset><Problem error={owner.mutation.error}/><SettingsTaskActions form={formId}><SettingsActionButton icon={SettingsActionIcon.Cancel} type="button" onClick={done}>{copy("mcp.cancel")}</SettingsActionButton><SettingsActionButton icon={SettingsActionIcon.Save} type="submit" disabled={blocked}>{copy("mcp.save")}</SettingsActionButton></SettingsTaskActions></form>;
}
