import { render, screen, cleanup, fireEvent } from "@testing-library/react";
import { test, expect, afterEach, vi } from "vitest";
import type { Resource } from "@delinoio/delidev-api-client";
import { NativeGrokInteraction } from "./native-grok-interactions";
import { encode, object, type Document } from "./documents";
const send = vi.fn();vi.mock("./mutation", () => ({useRetainedMutation: () => ({send,busy:false,uncertain:false,error:undefined})}));
afterEach(()=>{cleanup();send.mockClear();});
const id="01900000-0000-7000-8000-000000000001";
function fixture():Document{return {execution_id:id,native_thread_id:id,native_turn_id:"526452fa-1956-42dd-b5f4-60e2b23dfe92",native_item_id:"original",native_request_id:{kind:"text",text:"native-original"},type:"user-question",closure:"open",grok:{version:"1.0.41",observation_id:id,request_digest:"ab".repeat(32),proposal_digest:"cd".repeat(32),event:{method:"_x.ai/ask_user_question",request_id:{kind:"text",text:"native-original"},arrival_id:id,payload:{sessionId:id,toolCallId:"original",questions:[{question:"Original <script>question()</script>?",options:[{label:"One",description:"First"},{label:"Two",description:"Second"}],multiSelect:null}]}}}};}
test("renders nullable native questions and continues cancellation distinctly",()=>{const data=fixture();const resource={id,revision:9007199254740993n,schemaVersion:1,documentJson:encode(data)} as Resource;const {container}=render(<NativeGrokInteraction data={data} resource={resource} accepted={()=>{}}/>);expect(screen.getByText("Native multi-select value is null")).toBeTruthy();expect(container.querySelector("script")).toBeNull();fireEvent.change(screen.getByLabelText("Question response"),{target:{value:"cancelled"}});fireEvent.click(screen.getByText("Send response to Grok"));const input=send.mock.calls[0]![0];expect(input.mutation.expectedRevision).toBe(9007199254740993n);expect(JSON.parse(new TextDecoder().decode(input.responseJson))).toEqual({grok:{outcome:"cancelled"}});});
test("sends exact original answer keys and notes",()=>{const data=fixture(),resource={id,revision:1n,schemaVersion:1,documentJson:encode(data)} as Resource;render(<NativeGrokInteraction data={data} resource={resource} accepted={()=>{}}/>);fireEvent.change(screen.getByLabelText("Exact answer for question 1"),{target:{value:"One, Two"}});fireEvent.change(screen.getByLabelText("Notes for question 1"),{target:{value:"Original notes"}});fireEvent.click(screen.getByText("Send response to Grok"));expect(JSON.parse(new TextDecoder().decode(send.mock.calls[0]![0].responseJson))).toEqual({grok:{outcome:"accepted",answers:{"Original <script>question()</script>?":"One, Two"},annotations:{"Original <script>question()</script>?":{notes:"Original notes"}}}});});
for(const change of ["mixed","request","kind","version","arrival","null"])test(`rejects ${change} before exposing controls`,()=>{const data=fixture(),r=object(data.grok),v=object(r.event);if(change==="mixed")data.claude={};if(change==="request")data.native_request_id={kind:"text",text:"foreign"};if(change==="kind")data.type="native-approval";if(change==="version")r.version="future";if(change==="arrival")v.arrival_id="foreign";if(change==="null")data.grok=null;render(<NativeGrokInteraction data={data}/>);expect(screen.getByLabelText("Grok request unavailable")).toBeTruthy();});
test("shows native revised Plan without inventing another approval",()=>{const data=fixture(),r=object(data.grok),v=object(r.event),p=object(v.payload);data.type="native-approval";v.method="_x.ai/exit_plan_mode";delete p.questions;p.planContent="# Revised native plan";r.plan={origin:{entry_tool_id:"entry",entry_event_id:`${id}-1`,revision:2},write_tool_id:"write-revision",content_digest:"ab".repeat(32)};const {container}=render(<NativeGrokInteraction data={data}/>);expect(screen.getByText("Plan revision 2")).toBeTruthy();expect(screen.getByText("# Revised native plan")).toBeTruthy();expect(container.querySelector("button,a")).toBeNull();});
