// SPDX-License-Identifier: Apache-2.0
import { render, screen } from "@testing-library/react";
import { expect, test, vi } from "vitest";
import { NativeCodexDynamicTool, validCodexDynamicTool } from "./native-codex-dynamic-tool";
const id="01900000-0000-7000-8000-000000000001";
const fixture=()=>({role:"tool",state:"complete",text:"Original",execution_id:id,native_thread_id:id,native_turn_id:id,native_id:"call",first_sequence:3,last_sequence:3,codex_dynamic_tool:{version:1,id,stage:"completed",call_id:"call",namespace:null,tool:"unavailable",arguments:{present:true,type:"object",digest:"a".repeat(64)},status:"failed",success:false,duration_ms:3,content_items:[{type:"inputText",text:"<script>alert(1)</script> ![private](https://private.example/image)"},{type:"inputImage",reference_kind:"image_url",reference_present:true,reference_digest:"b".repeat(64)},{type:"inputAudio",reference_kind:"audio_url",reference_present:true,reference_digest:"c".repeat(64)}]}});
test("renders original ordered dynamic output as inert text without dispatch or media fetch",()=>{const fetch=vi.spyOn(globalThis,"fetch");const {container}=render(<NativeCodexDynamicTool data={fixture()}/>);expect(screen.getByText(/<script>alert/)).toBeTruthy();expect(container.querySelector("script,a,img,audio,iframe,button,input")).toBeNull();expect([...container.querySelectorAll("pre,small")].map(x=>x.textContent)).toEqual([fixture().codex_dynamic_tool.content_items[0].text,"Image output","Audio output"]);expect(fetch).not.toHaveBeenCalled();});
test.each(["arguments","namespace","status","content_items","success","duration_ms"])("rejects omitted original field %s",key=>{const data=fixture();delete (data.codex_dynamic_tool as Record<string,unknown>)[key];expect(validCodexDynamicTool(data)).toBe(false)});
test.each(["image_url","audio_url","arguments_json","native","handler"])("rejects public authority or raw content field %s",key=>{const data=fixture();Object.assign(data.codex_dynamic_tool,{[key]:"private"});expect(validCodexDynamicTool(data)).toBe(false)});
test("retains requested, transmitted and resolved independently without native item completion",()=>{const data=fixture();const base={...data.codex_dynamic_tool,status:null,success:null,duration_ms:null,content_items:null,arrival_id:id,request_id:{kind:"number",value:"7"},delivery:"not-sent",request_resolved:false,stage:"requested"};expect(validCodexDynamicTool({...data,codex_dynamic_tool:base})).toBe(true);const sent={...base,stage:"reply-delivery",delivery:"transmitted",response_id:id,negative_outcome:false};expect(validCodexDynamicTool({...data,codex_dynamic_tool:sent})).toBe(true);expect(validCodexDynamicTool({...data,codex_dynamic_tool:{...sent,stage:"request-resolved",request_resolved:true}})).toBe(true);expect(validCodexDynamicTool({...data,codex_dynamic_tool:{...sent,success:false}})).toBe(false)});

test("preserves large original numeric request identity as decimal text with its number kind",()=>{const data=fixture();const request={...data.codex_dynamic_tool,status:null,success:null,duration_ms:null,content_items:null,arrival_id:id,request_id:{kind:"number",value:"9007199254740993"},delivery:"not-sent",request_resolved:false,stage:"requested"};expect(validCodexDynamicTool({...data,codex_dynamic_tool:request})).toBe(true);for(const value of ["9223372036854775808","7.5","1e3","07","-0"]){expect(validCodexDynamicTool({...data,codex_dynamic_tool:{...request,request_id:{kind:"number",value}}})).toBe(false)}});
