// SPDX-License-Identifier: Apache-2.0
import { copy, type MessageKey } from "./localization";

// Presentation-only mapping. Unknown external identifiers retain their bytes.
const labels: Record<string, MessageKey> = {
  "requested": "status.requested",
  "pending": "status.pending",
  "saved": "status.saved",
  "bound": "status.bound",
  "cancelled": "status.cancelled",
  "finished": "status.finished",
  "exited": "status.exited",
  "interrupted": "status.interrupted",
  "handled": "status.handled",
  "unhandled": "status.unhandled",
  "detected": "status.detected",
  "missing": "status.missing",
  "unchecked": "status.unchecked",
  "success": "status.success",
  "waiting-for-idle": "status.waiting-for-idle",
  "waiting-for-oracle": "status.waiting-for-oracle",
  "restart-required": "status.restart-required",
  "downloading": "status.downloading",
  "validating": "status.validating",
  "applying": "status.applying",
  "installed": "status.installed",
  "rolled-back": "status.rolled-back",
  "streaming": "status.streaming",
  "project-restricted": "status.project-restricted",
  "locally-dismissed": "status.locally-dismissed",
  "non-failing": "status.non-failing",
  "terminal-failure": "status.terminal-failure",
  "not-required": "status.not-required",
  "mergeable": "status.mergeable",
  "conflicting": "status.conflicting",
  "not-applicable": "status.not-applicable",
  "present": "status.present",
  "sending": "status.sending",
  "true": "status.true",
  "false": "status.false",
  "active": "status.active",
  "archived": "status.archived",
  "archiving": "status.archiving",
  "idle": "status.idle",
  "running": "status.running",
  "succeeded": "status.succeeded",
  "failed": "status.failed",
  "stopped": "status.stopped",
  "not-started": "status.not-started",
  "accepted": "status.accepted",
  "queued": "status.queued",
  "waiting": "status.waiting",
  "paused": "status.paused",
  "blocked": "status.blocked",
  "dispatching": "status.dispatching",
  "claimed": "status.claimed",
  "starting": "status.starting",
  "completed": "status.completed",
  "complete": "status.complete",
  "preparing": "status.preparing",
  "ready": "status.ready",
  "canceled": "status.canceled",
  "uncertain": "status.uncertain",
  "required": "status.required",
  "none": "status.none",
  "disconnected": "status.disconnected",
  "connected": "status.connected",
  "unverified": "status.unverified",
  "verified": "status.verified",
  "authorized": "status.authorized",
  "revoked": "status.revoked",
  "removed": "status.removed",
  "expired": "status.expired",
  "offline": "status.offline",
  "exhausted": "status.exhausted",
  "available": "status.available",
  "unavailable": "status.unavailable",
  "unsupported": "status.unsupported",
  "stale": "status.stale",
  "unknown": "status.unknown",
  "observed": "status.observed",
  "transmitted": "status.transmitted",
  "superseded": "status.superseded",
  "healthy": "status.healthy",
  "refresh": "status.refresh",
  "recovery-required": "status.recovery-required"
};
export function statusLabel(value: string): string {
  const canonical = value.toLowerCase().replaceAll("_", "-");
  if (!Object.hasOwn(labels, canonical)) return value;
  const label = copy(labels[canonical]);
  return label === canonical ? value : label;
}
