// SPDX-License-Identifier: Apache-2.0
import { create } from "@bufbuild/protobuf";
import { createRouterTransport } from "@connectrpc/connect";
import { TransportProvider } from "@connectrpc/connect-query";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { act, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, expect, it, vi } from "vitest";
import { EntityKind, ResourceSchema, ResourceService, newRequestId } from "@delinoio/delidev-api-client";
import { ProjectSettingsMenu } from "./project-settings-menu";
import { SessionRowActionsProvider } from "./session-row-actions";
import { encode } from "./documents";
beforeEach(()=>vi.stubGlobal("ResizeObserver",class{observe(){}disconnect(){}unobserve(){}}));
function mount(active=true){const ids=[newRequestId(),newRequestId()],reads:string[]=[],toggle=vi.fn(),createSession=vi.fn();const client=new QueryClient({defaultOptions:{queries:{retry:false}}});const transport=createRouterTransport(router=>router.service(ResourceService,{getResource:request=>{reads.push(request.id);return {resource:create(ResourceSchema,{id:request.id,kind:EntityKind.PROJECT,revision:1n,schemaVersion:1,documentJson:encode({name:"Repeated",repositories:[],defaults:{}})})};},listResources:()=>({resources:[]})}));render(<QueryClientProvider client={client}><TransportProvider transport={transport}><SessionRowActionsProvider active={active}>{ids.map(id=><section key={id} className="sidebar-project-group"><button className="sidebar-project-row" aria-expanded="false" onClick={toggle}>Repeated</button><button onClick={createSession}>+</button><ProjectSettingsMenu projectId={id} label="Repeated" active={active}/></section>)}</SessionRowActionsProvider></TransportProvider></QueryClientProvider>);return {ids,reads,toggle,createSession,client};}
it("menu navigation and dismissal do not read, expand or select projects",()=>{const {reads,toggle,createSession}=mount();const trigger=screen.getAllByRole("button",{name:/Project actions/})[0];fireEvent.click(trigger);expect(screen.getAllByRole("menuitem")).toHaveLength(1);const item=screen.getByRole("menuitem",{name:"Project settings"});expect(document.activeElement).toBe(item);fireEvent.keyDown(item,{key:"End"});expect(document.activeElement).toBe(item);fireEvent.keyDown(item,{key:"Escape"});expect(screen.queryByRole("menu")).toBeNull();expect(document.activeElement).toBe(trigger);fireEvent.click(trigger);fireEvent.pointerDown(document.body);expect(screen.queryByRole("menu")).toBeNull();expect(reads).toEqual([]);expect(toggle).not.toHaveBeenCalled();expect(createSession).not.toHaveBeenCalled();});
it("duplicate labels keep original project identity and durable dialog opener",async()=>{const {ids,reads,client}=mount();const trigger=screen.getAllByRole("button",{name:/Project actions/})[1];fireEvent.click(trigger);fireEvent.click(screen.getByRole("menuitem",{name:"Project settings"}));await waitFor(()=>expect(reads).toEqual([ids[1]]));expect(screen.queryByRole("menu")).toBeNull();const name=await screen.findByRole("textbox",{name:"Name"});fireEvent.change(name,{target:{value:"Retained draft"}});await act(async()=>{await client.invalidateQueries();});expect((name as HTMLInputElement).value).toBe("Retained draft");const dialog=screen.getByRole("dialog",{name:"Project settings"});fireEvent(dialog,new Event("cancel",{bubbles:false,cancelable:true}));await waitFor(()=>expect(screen.queryByRole("dialog")).toBeNull());expect(document.activeElement).toBe(trigger);});
it("inactive triggers cannot open menus or perform reads",()=>{const {reads}=mount(false);const trigger=screen.getAllByRole("button",{name:/Project actions/})[0];expect((trigger as HTMLButtonElement).disabled).toBe(true);fireEvent.click(trigger);expect(screen.queryByRole("menu")).toBeNull();expect(reads).toEqual([]);});
