// SPDX-License-Identifier: Apache-2.0
import { create } from "@bufbuild/protobuf";
import { Code, ConnectError, createRouterTransport } from "@connectrpc/connect";
import { TransportProvider } from "@connectrpc/connect-query";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { expect, it, vi } from "vitest";
import { EntityKind, ResourceSchema, ResourceService, SessionService, newRequestId } from "@delinoio/delidev-api-client";
import { encode } from "./documents";
import { MutationIntents } from "./mutation";
import { SessionNameEditorProvider, useSessionNameEditor, validSessionName } from "./session-name-editor";
function Names({ id }: { id: string }) { const open=useSessionNameEditor();return <><button onDoubleClick={e=>open?.(id,e.currentTarget)}>Sidebar name</button><h2 tabIndex={-1} onDoubleClick={e=>open?.(id,e.currentTarget)}>Header name</h2><main id="main" tabIndex={-1}/></>; }
function fixture(){
 const id=newRequestId();let session=create(ResourceSchema,{id,kind:EntityKind.SESSION,revision:8n,schemaVersion:1,documentJson:encode({name:"Original name"})});
 const read=vi.fn(()=>({resource:session}));const rename=vi.fn(async (request:{mutation?:{requestId:string;expectedRevision:bigint};name:string})=>{session={...session,revision:session.revision+1n,documentJson:encode({name:request.name})};return {change:{session,requestId:request.mutation?.requestId}};});
 const transport=createRouterTransport(router=>{router.service(ResourceService,{getResource:read});router.service(SessionService,{renameSession:rename});});const client=new QueryClient({defaultOptions:{queries:{retry:false}}});
 const view=<TransportProvider transport={transport}><QueryClientProvider client={client}><MutationIntents><SessionNameEditorProvider><Names id={id}/></SessionNameEditorProvider></MutationIntents></QueryClientProvider></TransportProvider>;
 return {id,view,read,rename,client,peer:()=>{session={...session,revision:session.revision+1n};}};
}
it("validates UTF-8 bytes and Unicode without altering the original name",()=>{expect(validSessionName("가".repeat(85))).toBe(true);for(const value of [" ","a\0b","가".repeat(86),"x\uD800","\uDC00x"])expect(validSessionName(value)).toBe(false);expect(validSessionName("😀".repeat(64))).toBe(true);});
it("opens only on double-click and shares a retained draft across both original-session gestures",async()=>{const f=fixture();render(f.view);fireEvent.click(screen.getByText("Sidebar name"));expect(f.read).not.toHaveBeenCalled();fireEvent.doubleClick(screen.getByText("Sidebar name"));const input=await screen.findByLabelText("Session name");await waitFor(()=>expect(input).toHaveProperty("value","Original name"));expect(document.activeElement).toBe(input);expect((input as HTMLInputElement).selectionEnd).toBe("Original name".length);expect(f.rename).not.toHaveBeenCalled();fireEvent.change(input,{target:{value:"Retained draft"}});fireEvent.click(screen.getByRole("button",{name:"Close"}));fireEvent.doubleClick(screen.getByText("Header name"));expect(await screen.findByLabelText("Session name")).toBe(input);expect(input).toHaveProperty("value","Retained draft");fireEvent.click(screen.getByRole("button",{name:"Save"}));await waitFor(()=>expect(screen.queryByRole("dialog")).toBeNull());expect(f.rename.mock.calls[0][0]).toMatchObject({mutation:{id:f.id,expectedRevision:8n},name:"Retained draft"});});
it("blocks peer conflicts until explicit draft discard and preserves original uncertain requests",async()=>{const f=fixture();f.rename.mockRejectedValueOnce(new ConnectError("Original acknowledgment lost",Code.Unavailable));render(f.view);fireEvent.doubleClick(screen.getByText("Sidebar name"));const input=await screen.findByLabelText("Session name");await waitFor(()=>expect(input).toHaveProperty("value","Original name"));fireEvent.change(input,{target:{value:"Draft"}});f.peer();await f.client.invalidateQueries({refetchType:"active"});await waitFor(()=>expect(screen.getByRole("button",{name:"Save"})).toHaveProperty("disabled",true));expect(input).toHaveProperty("value","Draft");fireEvent.click(screen.getByRole("button",{name:"Discard draft and reload"}));await waitFor(()=>expect(input).toHaveProperty("value","Original name"));fireEvent.change(input,{target:{value:"Fresh name"}});fireEvent.click(screen.getByRole("button",{name:"Save"}));await screen.findByRole("button",{name:"Retry original rename"});const original=f.rename.mock.calls[0][0];fireEvent.click(screen.getByRole("button",{name:"Close"}));fireEvent.doubleClick(screen.getByText("Header name"));fireEvent.click(await screen.findByRole("button",{name:"Retry original rename"}));await waitFor(()=>expect(f.rename).toHaveBeenCalledTimes(2));expect(f.rename.mock.calls[1][0]).toEqual(original);});
