import {describe,it,expect} from "vitest";
import {SessionTabsStore,SessionTabKind,sessionTabKey} from "./session-tabs";
import {Comparison} from "./session-diff-model";
describe("connection session tab descriptors",()=>{
 it("pins Conversation and preserves append order with exact resource identities",()=>{const store=new SessionTabsStore();const file={kind:SessionTabKind.File as const,repository:"repo",path:"a"};store.open("s",file);store.open("s",{...file,path:"b"});store.open("s",file);expect(store.snapshot("s").tabs).toHaveLength(3);expect(store.snapshot("s").selected).toBe(sessionTabKey(file));store.close("s",SessionTabKind.Conversation);expect(store.snapshot("s").tabs[0]?.kind).toBe(SessionTabKind.Conversation);store.open("s",{kind:SessionTabKind.Comparison,repository:"repo",comparison:Comparison.Staged,path:"a"});expect(store.snapshot("s").tabs).toHaveLength(4);});
 it("closes presentation with left fallback and keeps inactive selection",()=>{const s=new SessionTabsStore();s.open("s",{kind:SessionTabKind.Terminal,id:"one"});s.open("s",{kind:SessionTabKind.Terminal,id:"two"});s.close("s",JSON.stringify(["terminal","one"]));expect(s.snapshot("s").selected).toBe(JSON.stringify(["terminal","two"]));s.close("s",JSON.stringify(["terminal","two"]));expect(s.snapshot("s").selected).toBe("conversation");});
 it("selects exact positions1 and9 with no last-tab alias or absent selection",()=>{const s=new SessionTabsStore();for(let n=0;n<10;n++)s.open("s",{kind:SessionTabKind.Terminal,id:String(n)});s.position("s",9);expect(s.snapshot("s").selected).toBe(JSON.stringify(["terminal","7"]));s.position("s",1);expect(s.snapshot("s").selected).toBe("conversation");s.position("other",9);expect(s.snapshot("other").selected).toBe("conversation");s.position("s",10);expect(s.snapshot("s").selected).toBe("conversation");});
 it("scopes order to session/connection and retains original Sidechat parent",()=>{const s=new SessionTabsStore();s.open("parent",{kind:SessionTabKind.Sidechat,id:"child",name:"Child"});expect(s.parent("child")).toBe("parent");expect(s.snapshot("other").tabs).toHaveLength(1);expect(new SessionTabsStore().snapshot("parent").tabs).toHaveLength(1);});
});
