// SPDX-License-Identifier: Apache-2.0
import { createClient } from "@connectrpc/connect";
import { TransportProvider } from "@connectrpc/connect-query";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { expect, it } from "vitest";
import { EntityKind, ResourceService } from "@delinoio/delidev-api-client";
import { Settings } from "./settings";
import { MutationIntents } from "./mutation";
import { document } from "./documents";
import { useSettingsFixture } from "./settings-test-fixture";

const fixture = useSettingsFixture();

it("configures a real Go server through the settings forms and explicitly validates a private keyless provider", async () => {
  const { transport, providerOrigin } = fixture;
  const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false, gcTime: 0 } } });
  render(<TransportProvider transport={transport}><QueryClientProvider client={client}><MutationIntents><Settings /></MutationIntents></QueryClientProvider></TransportProvider>);
  const change = (name: string, value: string) => fireEvent.change(screen.getByLabelText(name), { target: { value } });
  fireEvent.click(screen.getByRole("button", { name: "API Providers" }));
  const create = await screen.findByRole("button", { name: "Custom provider" });
  await waitFor(() => expect((create as HTMLButtonElement).disabled).toBe(false));
  fireEvent.click(create);
  change("Name", "Owned local API");
  const responses = screen.getByRole("checkbox", { name: "OpenAI Responses" });
  await waitFor(() => expect(responses.matches(":disabled")).toBe(false));
  fireEvent.click(responses);
  change("API base URL", providerOrigin); change("Authentication", "keyless");
  fireEvent.click(screen.getByRole("checkbox", { name: "Discover models automatically for connected entries" }));
  fireEvent.click(screen.getByRole("button", { name: "Save Provider" }));
  await screen.findByRole("heading", { name: "Owned local API" });
  fireEvent.click(screen.getByRole("button", { name: "AI API Keys" }));
  const addAccount = screen.getByRole("button", { name: "Add AI API key" });
  await waitFor(() => expect((addAccount as HTMLButtonElement).disabled).toBe(false));
  fireEvent.click(addAccount);
  fireEvent.click(await screen.findByRole("button", { name: "Owned local API Local endpoint" }));
  change("Entry name", "Owned keyless account");
  await screen.findByText("OpenAI Responses", { selector: "output" });
  expect(screen.queryByRole("combobox", { name: "API format" })).toBeNull();
  const connect = screen.getByRole("button", { name: "Add and connect" });
  await waitFor(() => expect((connect as HTMLButtonElement).disabled).toBe(false));
  fireEvent.click(connect);
  await screen.findByRole("heading", { name: "Owned keyless account" });
  const manageAccount = await screen.findByRole("button", { name: "Manage connection" });
  await waitFor(() => expect((manageAccount as HTMLButtonElement).disabled).toBe(false));
  fireEvent.click(manageAccount);
  await screen.findByText("Health: unverified · Credential connected");
  fireEvent.click(screen.getByRole("button", { name: "Validate connection" }));
  await screen.findByText("Health: ready · Credential connected");
  fireEvent.click(screen.getByRole("button", { name: "Back to AI API Keys" }));
  fireEvent.click(screen.getByRole("button", { name: "Agent Workers" }));
  fireEvent.click(screen.getByRole("button", { name: "New Agent Worker" }));
  const next = () => fireEvent.click(screen.getByRole("button", { name: "Next" }));
  await waitFor(() => expect((screen.getByRole("radio", { name: "Codex" }) as HTMLButtonElement).disabled).toBe(false));
  fireEvent.click(screen.getByRole("radio", { name: "Codex" }));
  const source = await screen.findByRole("option", { name: "Owned local API" }) as HTMLOptionElement;
  change("Account source", source.value);
  fireEvent.click(await screen.findByRole("checkbox", { name: /Owned keyless account/ }));
  next();
  fireEvent.change(screen.getByRole("combobox", { name: /^Model for / }), { target: { value: "fixture-model" } }); next();
  change("Name", "Configured agent");
  fireEvent.click(screen.getByRole("button", { name: "Save Agent Worker" }));
  await screen.findByRole("heading", { name: "Configured agent" });
  const agents = await createClient(ResourceService, transport).listResources({ filter: { kind: EntityKind.AGENT } });
  expect(agents.resources).toHaveLength(1);
  expect(document(agents.resources[0])).toMatchObject({ name: "Configured agent", harness: "codex", accounts: [{ weight: 1 }], options: { permission: "default" } });
}, 30000);
