// SPDX-License-Identifier: Apache-2.0
import { execFile, spawn } from "node:child_process";
import { readFile, realpath } from "node:fs/promises";
import { join, resolve } from "node:path";
import { promisify } from "node:util";
import { createClient } from "@connectrpc/connect";
import { TransportProvider } from "@connectrpc/connect-query";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { expect, it } from "vitest";
import { BudgetState, SessionService, ConfigurationService, EntityKind, ResourceService, ScheduleService, newRequestId } from "@delinoio/delidev-api-client";
import { SessionBudget } from "./session-budget";
import { Schedules } from "./schedules";
import { NewSession } from "./new-session";
import { Settings } from "./settings";
import { MutationIntents } from "./mutation";
import { document, encode } from "./documents";
import { useSettingsFixture } from "./settings-test-fixture";

const fixture = useSettingsFixture();

it("inspects and saves a real owned Git checkout through a separate Go Worker before creating a project", async () => {
  const { directory, transport, providerOrigin, binary, scope, runCLI } = fixture;
  const pairing = JSON.parse(await runCLI(["device", "create-pairing", "--type", "worker", "--name", "Owned Git Worker"]));
  const grant = await readFile(pairing.result.code_file, "utf8");
  const workerRoot = join(directory, "worker");
  await runCLI(["worker", "pair", "--worker-dir", workerRoot, "--name", "Owned Git Worker", "--code-stdin"], grant);
  fixture.worker = spawn(binary, ["--data-dir", scope, "worker", "start", "--worker-dir", workerRoot], { stdio: ["ignore", "pipe", "ignore"] });
  await new Promise<void>((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error("Owned Worker readiness timed out")), 10000);
    let output = "";
    const fail = () => { clearTimeout(timer); reject(new Error("Owned Worker exited before readiness")); };
    fixture.worker!.once("error", fail); fixture.worker!.once("exit", fail);
    fixture.worker!.stdout!.on("data", (chunk: Buffer) => {
      output += chunk.toString();
      if (output.length > 16384) { fail(); return; }
      if (output.includes('"status":"ready"')) { clearTimeout(timer); fixture.worker!.removeListener("exit", fail); fixture.worker!.removeListener("error", fail); resolve(); }
    });
  });
  const checkout = join(directory, "checkout");
  await promisify(execFile)("git", ["init", "--quiet", checkout], { timeout: 10000 });
  const canonical = await realpath(checkout);
  const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false, gcTime: 0 } } });
  render(<TransportProvider transport={transport}><QueryClientProvider client={client}><MutationIntents><Settings close={() => {}} /></MutationIntents></QueryClientProvider></TransportProvider>);
  const change = (name: string, value: string) => fireEvent.change(screen.getByLabelText(name), { target: { value } });
  fireEvent.click(screen.getByRole("button", { name: "Repositories" }));
  fireEvent.click(screen.getByRole("button", { name: "Add repository" }));
  fireEvent.click(screen.getByRole("button", { name: "Enter a path…" }));
  change("Computer", "remote");
  change("Execution Worker", (await screen.findByRole("option", { name: "Owned Git Worker" }, { timeout: 15000 }) as HTMLOptionElement).value);
  change("Absolute checkout path", checkout);
  fireEvent.click(screen.getByRole("button", { name: "Inspect folder" }));
  await screen.findByRole("region", { name: "Repository detected" }, { timeout: 15000 });
  fireEvent.click(screen.getByRole("button", { name: "Optional settings" }));
  change("Name", "Owned repository");
  fireEvent.click(screen.getByRole("button", { name: "Add repository" }));
  await waitFor(() => expect(screen.queryByRole("region", { name: "Add repository" })).toBeNull(), { timeout: 15000 });
  await screen.findByRole("heading", { name: "Owned repository" });
  const repositories = await createClient(ResourceService, transport).listResources({ filter: { kind: EntityKind.REPOSITORY } });
  expect(document(repositories.resources[0]).checkouts).toEqual([expect.objectContaining({ path: canonical })]);
  fireEvent.click(screen.getByRole("button", { name: "Projects" }));
  fireEvent.click(screen.getByRole("button", { name: "New Project" }));
  change("Name", "Owned project");
  change("Add Repository", (await screen.findByRole("option", { name: "Owned repository" }) as HTMLOptionElement).value);
  fireEvent.click(screen.getByRole("button", { name: "Add selected" }));
  change("Primary repository", repositories.resources[0].id);
  fireEvent.click(screen.getByRole("checkbox", { name: "Restrict ai accounts" }));
  fireEvent.click(screen.getByRole("button", { name: "Save Project" }));
  await screen.findByRole("heading", { name: "Owned project" });
  const projects = await createClient(ResourceService, transport).listResources({ filter: { kind: EntityKind.PROJECT } });
  expect(document(projects.resources[0])).toMatchObject({ primary_repository: repositories.resources[0].id, accounts: { configured: true, ids: [] } });
  fireEvent.click(screen.getByRole("button", { name: "Execution Workers" }));
  fireEvent.click(await screen.findByRole("button", { name: "Inspect installed harnesses" }));
  fireEvent.click(screen.getByRole("button", { name: "Edit executable paths" }));
  for (const harness of ["codex", "claude-code", "opencode", "grok-build"]) change(`${harness} executable path`, join(directory, `missing-${harness}`));
  fireEvent.click(screen.getByRole("button", { name: "Check installed harnesses" }));
  fireEvent.click(await screen.findByRole("button", { name: "Finish inspection" }, { timeout: 15000 }));
  await waitFor(() => expect(screen.getAllByText("missing · Version: Unknown")).toHaveLength(4));
  // An account-less Agent is valid configuration but cannot infer readiness or
  // launch a harness. The real Worker has only explicit missing executables.
  const configurations = createClient(ConfigurationService, transport);
  const save = async (kind: EntityKind, value: Record<string, unknown>) => (await configurations.saveConfiguration({ kind, mutation: { requestId: newRequestId() }, schemaVersion: 1, documentJson: encode(value) })).resource!;
  const providerConfig = await save(EntityKind.PROVIDER, { name: "Schedule fixture provider", endpoint: providerOrigin, protocol: "openai-chat", authentication: "keyless", discovery: false });
  const model = await save(EntityKind.MODEL, { name: "Schedule fixture model", provider_id: providerConfig.id, native_id: "fixture-model", harnesses: ["codex"], manual: true, metadata_source: "unknown" });
  const accountlessAgent = await save(EntityKind.AGENT, { name: "Accountless schedule agent", harness: "codex", model_id: model.id, accounts: [], templates: [], options: { permission: "default" } });
  cleanup();
  const scheduleClient = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false, gcTime: 0 } } });
  const readLocalWorker = async () => {
    const credential = JSON.parse(await readFile(join(workerRoot, "device.json"), "utf8"));
    return { machineId: credential.machine_id as string, token: credential.token as string };
  };
  let createdSessionId = "";
  render(<TransportProvider transport={transport}><QueryClientProvider client={scheduleClient}><MutationIntents><NewSession active ownsActivation activation={1} back={() => {}} openSettings={() => {}} open={(id) => { createdSessionId = id; }} created={() => {}} readLocalWorker={readLocalWorker} /></MutationIntents></QueryClientProvider></TransportProvider>);
  const newSession = within(window.document.querySelector(".new-session-page")!);
  const changeNewSession = (name: string, value: string) => fireEvent.change(newSession.getByLabelText(name), { target: { value } });
  changeNewSession("Project", (await within(newSession.getByLabelText("Project")).findByRole("option", { name: "Owned project" }) as HTMLOptionElement).value);
  fireEvent.click(newSession.getByRole("button", { name: "Options" }));
  fireEvent.click(newSession.getByRole("button", { name: "Use this computer's Local checkouts" }));
  await waitFor(() => expect((newSession.getByLabelText("Execution Worker") as HTMLSelectElement).disabled).toBe(true));
  changeNewSession("Agent Worker", (await newSession.findByRole("option", { name: "Accountless schedule agent" }) as HTMLOptionElement).value);
  changeNewSession("First message", "Local proof fixture without inference");
  fireEvent.click(newSession.getByText("Optional estimated-cost budget"));
  fireEvent.click(newSession.getByRole("checkbox", { name: "Enable estimated-cost budget" }));
  changeNewSession("Budget currency", "USD"); changeNewSession("Estimated-cost threshold", "0.000000000000001");
  fireEvent.click(newSession.getByRole("button", { name: "Create session" }));
  await waitFor(async () => {
    expect(createdSessionId).not.toBe("");
    const sessions = await createClient(ResourceService, transport).listResources({ filter: { kind: EntityKind.SESSION } });
    const created = sessions.resources.find((row) => row.id === createdSessionId);
    expect(created && document(created)).toMatchObject({ workspace: "local", name: "New session", estimated_cost_budget: { currency: "USD", threshold: "0.000000000000001" } });
  });
  cleanup();
  const budgetSession = (await createClient(ResourceService, transport).getResource({ kind: EntityKind.SESSION, id: createdSessionId })).resource!;
  expect(document(budgetSession).estimated_cost_budget).toEqual({ currency: "USD", threshold: "0.000000000000001" });
  const budgetClient = createClient(SessionService, transport);
  expect((await budgetClient.getSessionBudget({ sessionId: budgetSession.id })).view).toMatchObject({ state: BudgetState.ALLOW_INCOMPLETE, selectedCurrency: { knownAmount: "" } });
  render(<TransportProvider transport={transport}><QueryClientProvider client={scheduleClient}><MutationIntents><SessionBudget resource={budgetSession} changed={() => {}} blocked={() => {}} /></MutationIntents></QueryClientProvider></TransportProvider>);
  await screen.findByText(/Known lifetime subtotal: Unavailable/);
  fireEvent.click(screen.getByRole("button", { name: "Edit session budget" }));
  change("Estimated-cost threshold", "12.345678901234567");
  fireEvent.click(screen.getByRole("button", { name: "Save session budget" }));
  await screen.findByText(/Threshold: USD 12.345678901234567/);
  expect((await budgetClient.getSessionBudget({ sessionId: budgetSession.id })).view?.budget?.threshold).toBe("12.345678901234567");
  fireEvent.click(screen.getByRole("button", { name: "Edit session budget" }));
  fireEvent.click(screen.getByRole("checkbox", { name: "Enable estimated-cost budget" }));
  fireEvent.click(screen.getByRole("button", { name: "Save session budget" }));
  await screen.findByText("No estimated-cost budget is configured.");
  expect((await budgetClient.getSessionBudget({ sessionId: budgetSession.id })).view?.state).toBe(BudgetState.DISABLED);
  cleanup();
  render(<TransportProvider transport={transport}><QueryClientProvider client={scheduleClient}><MutationIntents><Schedules active open={() => {}} readLocalWorker={readLocalWorker} /></MutationIntents></QueryClientProvider></TransportProvider>);
  fireEvent.click(screen.getByRole("button", { name: "New schedule" }));
  change("Schedule name", "Owned schedule");
  change("Project", (await within(screen.getByLabelText("Project")).findByRole("option", { name: "Owned project" }) as HTMLOptionElement).value);
  change("Agent Worker", (await screen.findByRole("option", { name: "Accountless schedule agent" }) as HTMLOptionElement).value);
  change("Execution Worker", (await screen.findByRole("option", { name: "Owned Git Worker" }) as HTMLOptionElement).value);
  fireEvent.click(screen.getByRole("radio", { name: "Local computer" }));
  await waitFor(() => expect((screen.getByLabelText("Execution Worker") as HTMLSelectElement).disabled).toBe(true));
  change("Frequency", "custom"); change("Scheduled prompt", "Private schedule fixture prompt"); change("Cron expression", "0 0 1 1 *"); change("IANA timezone", "Asia/Seoul");
  fireEvent.click(screen.getByRole("button", { name: "Create schedule" }));
  fireEvent.click(await screen.findByRole("button", { name: "Resume future runs" }));
  fireEvent.click(await screen.findByRole("button", { name: "Pause future runs" }));
  await screen.findByRole("button", { name: "Resume future runs" });
  fireEvent.click(screen.getByRole("button", { name: "Run now" }));
  fireEvent.click(screen.getByRole("button", { name: "Confirm Run now" }));
  await screen.findByText("Run now accepted");
  const schedules = await createClient(ScheduleService, transport).listSchedules({});
  const scheduleId = schedules.schedules[0].id;
  expect(document(schedules.schedules[0])).toMatchObject({ definition: { workspace: "local" }, local_origin: { machine_id: (await readLocalWorker()).machineId } });
  expect((await createClient(ScheduleService, transport).listScheduleOccurrences({ scheduleId })).occurrences).toHaveLength(1);
  fireEvent.click(screen.getByRole("button", { name: "Delete schedule" }));
  fireEvent.click(screen.getByRole("button", { name: "Confirm schedule deletion" }));
  await screen.findByText("Schedule configuration deleted. Retained occurrences and sessions remain.");
  expect((await createClient(ScheduleService, transport).listScheduleOccurrences({ scheduleId })).occurrences).toHaveLength(1);
  cleanup();
  render(<TransportProvider transport={transport}><QueryClientProvider client={client}><MutationIntents><Settings close={() => {}} /></MutationIntents></QueryClientProvider></TransportProvider>);
  fireEvent.click(screen.getByRole("button", { name: "Projects" }));
  fireEvent.click(await screen.findByRole("button", { name: "Delete Owned project" }));
  fireEvent.click(screen.getByRole("button", { name: "Confirm configuration deletion" }));
  await waitFor(() => expect(screen.queryByRole("heading", { name: "Delete Owned project?" })).toBeNull());
  expect((await createClient(ResourceService, transport).listResources({ filter: { kind: EntityKind.PROJECT } })).resources).toHaveLength(0);
}, 60000);

