// SPDX-License-Identifier: Apache-2.0
import { useRef, useState } from "react";
import { createRouterTransport } from "@connectrpc/connect";
import { TransportProvider } from "@connectrpc/connect-query";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { expect, it, vi } from "vitest";
import { SessionService, SessionQuery, SkillService, SkillProvenance, newRequestId } from "@delinoio/delidev-api-client";
import { skillToken, editedBindings, useSkillCompletion } from "./skill-completion";
import { MutationIntents, useRetainedMutation } from "./mutation";
import { SupportedLanguage, i18n } from "./localization";
const machine = newRequestId(), agent = newRequestId(), inventory = newRequestId(), worker = newRequestId();
const entries = ["add-issue", "add-note"].map(name => ({ name, description: `${name} fixture`, provenance: SkillProvenance.USER, selection: { $typeName: "delidev.v1.SkillSelection" as const, inventoryId: inventory, workerDeviceId: worker, skillId: newRequestId(), contentRevision: "a".repeat(64) } }));
function Composer({ runner = machine, locked = false, send }: { runner?: string; locked?: boolean; send: (value: unknown) => void }) {
 const [value,change]=useState("");const textarea=useRef<HTMLTextAreaElement>(null);const skills=useSkillCompletion({value,change,textarea,machineId:runner,agentId:agent,disabled:locked});
 return <><fieldset disabled={locked}><textarea aria-label="Message" ref={textarea} value={value} onChange={e=>skills.onChange(e.target.value,e.target.selectionStart)} onSelect={skills.onSelect} onKeyDown={skills.onKeyDown} onCompositionStart={skills.onCompositionStart} onCompositionEnd={skills.onCompositionEnd} {...skills.attributes}/>{skills.list}{skills.warning}</fieldset><button disabled={skills.blocked} onClick={()=>send({value,skills:skills.selections})}>Send</button></>;
}
function fixture() {const send=vi.fn(),read=vi.fn(async()=>({skills:entries}));const transport=createRouterTransport(router=>router.service(SkillService,{listSkills:read}));const client=new QueryClient();const view=(runner=machine,locked=false)=><TransportProvider transport={transport}><QueryClientProvider client={client}><Composer runner={runner} locked={locked} send={send}/></QueryClientProvider></TransportProvider>;return{send,read,view};}
it("finds whitespace-delimited caret tokens without consuming surrounding Unicode",()=>{expect(skillToken("한글\n$add-iss trailing",11)).toEqual({start:3,end:11,prefix:"add-iss"});expect(skillToken("email$add",9)).toBeUndefined();});
it("binds keyboard selection separately, replaces only the token and does not send",async()=>{const f=fixture();render(f.view());const input=screen.getByRole("textbox");fireEvent.change(input,{target:{value:"한글\n$add-iss",selectionStart:11}});await screen.findByRole("option");fireEvent.keyDown(input,{key:"Enter"});expect((input as HTMLTextAreaElement).value).toBe("한글\n$add-issue");expect(f.send).not.toHaveBeenCalled();fireEvent.click(screen.getByText("Send"));expect(f.send.mock.calls[0]![0]).toMatchObject({skills:[entries[0]!.selection]});});
it("removes an edited binding and requires reselection on Runner changes",async()=>{const f=fixture();const view=render(f.view());const input=screen.getByRole("textbox");fireEvent.change(input,{target:{value:"$add-iss",selectionStart:8}});await screen.findByRole("option");fireEvent.keyDown(input,{key:"Tab"});view.rerender(f.view(newRequestId()));await screen.findByText("The selected skills need reselection before sending.");expect((screen.getByText("Send") as HTMLButtonElement).disabled).toBe(true);fireEvent.change(input,{target:{value:"manual",selectionStart:6}});await waitFor(()=>expect((screen.getByText("Send") as HTMLButtonElement).disabled).toBe(false));fireEvent.click(screen.getByText("Send"));expect(f.send.mock.calls[0]![0]).toMatchObject({skills:[]});});
it("does not select or submit during IME composition and Escape preserves text",async()=>{const f=fixture();render(f.view());const input=screen.getByRole("textbox");fireEvent.change(input,{target:{value:"$add-iss",selectionStart:8}});await screen.findByRole("option");fireEvent.compositionStart(input);fireEvent.keyDown(input,{key:"Enter",isComposing:true});expect((input as HTMLTextAreaElement).value).toBe("$add-iss");fireEvent.compositionEnd(input);fireEvent.keyDown(input,{key:"Escape"});expect(screen.queryByRole("listbox")).toBeNull();expect(f.send).not.toHaveBeenCalled();});
it("keeps manually typed tokens unbound and supports localized loading states",async()=>{await i18n.changeLanguage(SupportedLanguage.Korean);const f=fixture();render(f.view());const input=screen.getByRole("textbox");fireEvent.change(input,{target:{value:"$unknown",selectionStart:8}});await screen.findByText("일치하는 스킬이 없습니다.");fireEvent.click(screen.getByText("Send"));expect(f.send.mock.calls[0]![0]).toMatchObject({skills:[]});await i18n.changeLanguage(SupportedLanguage.English);});
it("keeps bindings shifted by outside edits but removes changed selected tokens",()=>{const binding={start:2,end:12,token:"$add-issue",selection:entries[0]!.selection,stale:false};expect(editedBindings("a $add-issue","prefix a $add-issue",[binding])[0]?.start).toBe(9);expect(editedBindings("a $add-issue","a $other",[binding])).toEqual([]);});

it("includes the remainder of the caret token without matching it as a prefix",()=>{expect(skillToken("before $add-issue after",15)).toEqual({start:7,end:17,prefix:"add-iss"});});

it("does not accept IME commit Enter, repeated keys or AltGraph",async()=>{const f=fixture();render(f.view());const input=screen.getByRole("textbox");fireEvent.change(input,{target:{value:"$add-iss",selectionStart:8}});await screen.findByRole("option");for(const event of [{key:"Enter",keyCode:229,isComposing:false},{key:"Enter",repeat:true},{key:"Enter",modifierAltGraph:true}]) {fireEvent.keyDown(input,event);expect((input as HTMLTextAreaElement).value).toBe("$add-iss");}expect(f.send).not.toHaveBeenCalled();});

it("drops a binding when typing at either token boundary but preserves whitespace",()=>{const binding={start:2,end:7,token:"$same",selection:entries[0]!.selection,stale:false};for(const value of ["a $samex","a $same한글","a x$same"]){expect(editedBindings("a $same",value,[binding])).toEqual([]);}expect(editedBindings("a $same","a $same ",[binding])).toHaveLength(1);expect(editedBindings("a $same","a  $same",[binding])).toHaveLength(1);});

it("rejects native fieldset-locked completion clicks and keyboard edits before React settlement",async()=>{const f=fixture();const view=render(f.view());const input=screen.getByRole("textbox");fireEvent.change(input,{target:{value:"$ad",selectionStart:3}});const option=await screen.findByRole("option",{name:/add-issue/});view.container.querySelector("fieldset")!.disabled=true;fireEvent.click(option);fireEvent.keyDown(input,{key:"Enter"});fireEvent.change(input,{target:{value:"changed",selectionStart:7}});fireEvent.click(screen.getByRole("button",{name:"Send"}));expect(f.send).toHaveBeenLastCalledWith({value:"$ad",skills:[]});});
it("keeps exact draft and accepted bindings through pending or uncertain composer locks",async()=>{const f=fixture();const view=render(f.view());const input=screen.getByRole("textbox");fireEvent.change(input,{target:{value:"$ad",selectionStart:3}});fireEvent.click(await screen.findByRole("option",{name:/add-issue/}));fireEvent.change(input,{target:{value:"$add-issue $ad",selectionStart:14}});await screen.findByRole("option",{name:/add-note/});view.rerender(f.view(machine,true));expect(screen.queryByRole("listbox")).toBeNull();fireEvent.keyDown(input,{key:"Enter"});fireEvent.change(input,{target:{value:"changed",selectionStart:7}});fireEvent.click(screen.getByRole("button",{name:"Send"}));expect(f.send).toHaveBeenLastCalledWith({value:"$add-issue $ad",skills:[entries[0]!.selection]});view.rerender(f.view());await screen.findByRole("option",{name:/add-note/});expect((input as HTMLTextAreaElement).value).toBe("$add-issue $ad");});

function AcceptedComposer() {const [value,change]=useState("");const textarea=useRef<HTMLTextAreaElement>(null);const mutation=useRetainedMutation("skills-accepted-fixture",SessionQuery.enqueueInput,()=>{change("");skills.clearAccepted();});const skills=useSkillCompletion({value,change,textarea,machineId:machine,agentId:agent,disabled:mutation.busy||mutation.uncertain});return <><textarea aria-label="Accepted message" disabled={mutation.busy||mutation.uncertain} ref={textarea} value={value} onChange={e=>skills.onChange(e.target.value,e.target.selectionStart)}/>{skills.list}<output data-selected>{skills.selections.length}</output><button onClick={()=>void mutation.send({requestId:newRequestId(),sessionId:newRequestId(),documentJson:new Uint8Array()})}>Enqueue fixture</button></>;}
it("clears accepted bindings in the real retained-mutation callback before the pending render unlocks",async()=>{let resolve!:()=>void;const pending=new Promise<void>(done=>{resolve=done;});const transport=createRouterTransport(router=>{router.service(SkillService,{listSkills:async()=>({skills:entries})});router.service(SessionService,{enqueueInput:async()=>{await pending;return {};}});});const view=render(<TransportProvider transport={transport}><QueryClientProvider client={new QueryClient()}><MutationIntents><AcceptedComposer/></MutationIntents></QueryClientProvider></TransportProvider>);const input=screen.getByRole("textbox");fireEvent.change(input,{target:{value:"$ad",selectionStart:3}});fireEvent.click(await screen.findByRole("option",{name:/add-issue/}));expect(view.container.querySelector("[data-selected]")!.textContent).toBe("1");fireEvent.click(screen.getByRole("button",{name:"Enqueue fixture"}));await waitFor(()=>expect((input as HTMLTextAreaElement).disabled).toBe(true));resolve();await waitFor(()=>expect((input as HTMLTextAreaElement).value).toBe(""));fireEvent.change(input,{target:{value:"$add-issue",selectionStart:10}});expect(view.container.querySelector("[data-selected]")!.textContent).toBe("0");});

function RestoredComposer({ runner, reject = false }: { runner: string; reject?: boolean }) {
 const [value,setValue]=useState("$add-issue");const textarea=useRef<HTMLTextAreaElement>(null);
 const skills=useSkillCompletion({value,change:next=>{if(reject)return false;setValue(next);return true;},textarea,machineId:runner,agentId:agent,initialBindings:[{start:0,end:10,token:"$add-issue",selection:entries[0]!.selection,stale:false,context:`${machine}:${agent}::`}]});
 return <><textarea ref={textarea} value={value} onChange={event=>skills.onChange(event.target.value,event.target.selectionStart)}/>{skills.warning}<button disabled={skills.blocked}>Restored send</button><output>{skills.selections.length}</output></>;
}
it("blocks a retained binding during unresolved and changed context until explicit token removal",async()=>{
 const client=new QueryClient();const transport=createRouterTransport(router=>router.service(SkillService,{listSkills:async()=>({skills:entries})}));
 const tree=(runner:string)=><TransportProvider transport={transport}><QueryClientProvider client={client}><RestoredComposer runner={runner}/></QueryClientProvider></TransportProvider>;
 const view=render(tree(""));expect(screen.getByRole("button",{name:"Restored send"})).toHaveProperty("disabled",true);view.rerender(tree(machine));await waitFor(()=>expect(screen.getByRole("button",{name:"Restored send"})).toHaveProperty("disabled",false));
 view.rerender(tree(newRequestId()));await waitFor(()=>expect(screen.getByRole("button",{name:"Restored send"})).toHaveProperty("disabled",true));fireEvent.change(screen.getByRole("textbox"),{target:{value:"$plain",selectionStart:6}});await waitFor(()=>expect(screen.getByRole("button",{name:"Restored send"})).toHaveProperty("disabled",false));expect(screen.queryByText("The selected skills need reselection before sending.")).toBeNull();
});
it("retains text and original bindings atomically when draft growth is rejected",()=>{
 const transport=createRouterTransport(router=>router.service(SkillService,{listSkills:async()=>({skills:entries})}));render(<TransportProvider transport={transport}><QueryClientProvider client={new QueryClient()}><RestoredComposer runner={machine} reject/></QueryClientProvider></TransportProvider>);
 fireEvent.change(screen.getByRole("textbox"),{target:{value:"rejected",selectionStart:8}});expect(screen.getByRole("textbox")).toHaveProperty("value","$add-issue");expect(screen.getByText("1")).toBeDefined();expect(screen.getByRole("button",{name:"Restored send"})).toHaveProperty("disabled",false);
});

function HistorySkillComposer({ locked = false }: { locked?: boolean }) {
 const [value, change] = useState("$add-issue"); const textarea = useRef<HTMLTextAreaElement>(null);
 const skills = useSkillCompletion({ value, change, textarea, machineId: machine, agentId: agent, disabled: locked, initialBindings: [{ start: 0, end: 10, token: "$add-issue", selection: entries[0]!.selection, stale: false, context: `${machine}:${agent}::` }] });
 return <><textarea aria-label="History skill draft" ref={textarea} disabled={locked} value={value} onChange={event => skills.onChange(event.target.value,event.target.selectionStart)}/><output data-history-selections>{skills.selections.length}</output><button onClick={() => skills.replaceUnbound("$add-issue", 0)}>Recall text only</button></>;
}
it("recalling identical text drops typed skill authority and respects the creation lock", () => {
 const transport = createRouterTransport(router => router.service(SkillService, { listSkills: async () => ({ skills: entries }) })); const client = new QueryClient();
 const tree = (locked: boolean) => <TransportProvider transport={transport}><QueryClientProvider client={client}><HistorySkillComposer locked={locked}/></QueryClientProvider></TransportProvider>;
 const view = render(tree(true)); fireEvent.click(screen.getByRole("button", { name: "Recall text only" })); expect(view.container.querySelector("[data-history-selections]")!.textContent).toBe("1");
 view.rerender(tree(false)); fireEvent.click(screen.getByRole("button", { name: "Recall text only" })); expect(screen.getByRole("textbox", { name: "History skill draft" })).toHaveProperty("value", "$add-issue"); expect(view.container.querySelector("[data-history-selections]")!.textContent).toBe("0");
});
