// SPDX-License-Identifier: Apache-2.0
import { useRef, useState } from "react";
import { createRouterTransport } from "@connectrpc/connect";
import { TransportProvider } from "@connectrpc/connect-query";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { expect, it, vi } from "vitest";
import { SkillService, SkillProvenance, newRequestId } from "@delinoio/delidev-api-client";
import { skillToken, editedBindings, useSkillCompletion } from "./skill-completion";
import { SupportedLanguage, i18n } from "./localization";
const machine = newRequestId(), agent = newRequestId(), inventory = newRequestId(), worker = newRequestId();
const entries = ["add-issue", "add-note"].map(name => ({ name, description: `${name} fixture`, provenance: SkillProvenance.USER, selection: { $typeName: "delidev.v1.SkillSelection" as const, inventoryId: inventory, workerDeviceId: worker, skillId: newRequestId(), contentRevision: "a".repeat(64) } }));
function Composer({ runner = machine, locked = false, send }: { runner?: string; locked?: boolean; send: (value: unknown) => void }) {
 const [value,change]=useState("");const textarea=useRef<HTMLTextAreaElement>(null);const skills=useSkillCompletion({value,change,textarea,machineId:runner,agentId:agent,disabled:locked});
 return <><fieldset disabled={locked}><textarea aria-label="Message" ref={textarea} value={value} onChange={e=>skills.onChange(e.target.value,e.target.selectionStart)} onSelect={skills.onSelect} onKeyDown={skills.onKeyDown} onCompositionStart={skills.onCompositionStart} onCompositionEnd={skills.onCompositionEnd} {...skills.attributes}/>{skills.list}{skills.warning}</fieldset><button disabled={skills.blocked} onClick={()=>send({value,skills:skills.selections})}>Send</button></>;
}
function fixture() {const send=vi.fn(),read=vi.fn(async()=>({skills:entries}));const transport=createRouterTransport(router=>router.service(SkillService,{listSkills:read}));const client=new QueryClient();const view=(runner=machine,locked=false)=><TransportProvider transport={transport}><QueryClientProvider client={client}><Composer runner={runner} locked={locked} send={send}/></QueryClientProvider></TransportProvider>;return{send,read,view};}
it("finds whitespace-delimited caret tokens without consuming surrounding Unicode",()=>{expect(skillToken("한글\n$add-iss trailing",11)).toEqual({start:3,end:11,prefix:"add-iss"});expect(skillToken("email$add",9)).toBeUndefined();});
it("binds keyboard selection separately, replaces only the token and does not send",async()=>{const f=fixture();render(f.view());const input=screen.getByRole("textbox");fireEvent.change(input,{target:{value:"한글\n$add-iss",selectionStart:11}});await screen.findByRole("option");fireEvent.keyDown(input,{key:"Enter"});expect((input as HTMLTextAreaElement).value).toBe("한글\n$add-issue");expect(f.send).not.toHaveBeenCalled();fireEvent.click(screen.getByText("Send"));expect(f.send.mock.calls[0]![0]).toMatchObject({skills:[entries[0]!.selection]});});
it("removes an edited binding and requires reselection on Runner changes",async()=>{const f=fixture();const view=render(f.view());const input=screen.getByRole("textbox");fireEvent.change(input,{target:{value:"$add-iss",selectionStart:8}});await screen.findByRole("option");fireEvent.keyDown(input,{key:"Tab"});view.rerender(f.view(newRequestId()));await screen.findByText("The selected skills need reselection before sending.");expect((screen.getByText("Send") as HTMLButtonElement).disabled).toBe(true);fireEvent.change(input,{target:{value:"manual",selectionStart:6}});await waitFor(()=>expect((screen.getByText("Send") as HTMLButtonElement).disabled).toBe(false));fireEvent.click(screen.getByText("Send"));expect(f.send.mock.calls[0]![0]).toMatchObject({skills:[]});});
it("does not select or submit during IME composition and Escape preserves text",async()=>{const f=fixture();render(f.view());const input=screen.getByRole("textbox");fireEvent.change(input,{target:{value:"$add-iss",selectionStart:8}});await screen.findByRole("option");fireEvent.compositionStart(input);fireEvent.keyDown(input,{key:"Enter",isComposing:true});expect((input as HTMLTextAreaElement).value).toBe("$add-iss");fireEvent.compositionEnd(input);fireEvent.keyDown(input,{key:"Escape"});expect(screen.queryByRole("listbox")).toBeNull();expect(f.send).not.toHaveBeenCalled();});
it("keeps manually typed tokens unbound and supports localized loading states",async()=>{await i18n.changeLanguage(SupportedLanguage.Korean);const f=fixture();render(f.view());const input=screen.getByRole("textbox");fireEvent.change(input,{target:{value:"$unknown",selectionStart:8}});await screen.findByText("일치하는 스킬이 없습니다.");fireEvent.click(screen.getByText("Send"));expect(f.send.mock.calls[0]![0]).toMatchObject({skills:[]});await i18n.changeLanguage(SupportedLanguage.English);});
it("keeps bindings shifted by outside edits but removes changed selected tokens",()=>{const binding={start:2,end:12,token:"$add-issue",selection:entries[0]!.selection,stale:false};expect(editedBindings("a $add-issue","prefix a $add-issue",[binding])[0]?.start).toBe(9);expect(editedBindings("a $add-issue","a $other",[binding])).toEqual([]);});

it("includes the remainder of the caret token without matching it as a prefix",()=>{expect(skillToken("before $add-issue after",15)).toEqual({start:7,end:17,prefix:"add-iss"});});

it("does not accept IME commit Enter, repeated keys or AltGraph",async()=>{const f=fixture();render(f.view());const input=screen.getByRole("textbox");fireEvent.change(input,{target:{value:"$add-iss",selectionStart:8}});await screen.findByRole("option");for(const event of [{key:"Enter",keyCode:229,isComposing:false},{key:"Enter",repeat:true},{key:"Enter",modifierAltGraph:true}]) {fireEvent.keyDown(input,event);expect((input as HTMLTextAreaElement).value).toBe("$add-iss");}expect(f.send).not.toHaveBeenCalled();});

it("drops a binding when typing at either token boundary but preserves whitespace",()=>{const binding={start:2,end:7,token:"$same",selection:entries[0]!.selection,stale:false};for(const value of ["a $samex","a $same한글","a x$same"]){expect(editedBindings("a $same",value,[binding])).toEqual([]);}expect(editedBindings("a $same","a $same ",[binding])).toHaveLength(1);expect(editedBindings("a $same","a  $same",[binding])).toHaveLength(1);});

it("rejects native fieldset-locked completion clicks and keyboard edits before React settlement",async()=>{const f=fixture();const view=render(f.view());const input=screen.getByRole("textbox");fireEvent.change(input,{target:{value:"$ad",selectionStart:3}});const option=await screen.findByRole("option",{name:/add-issue/});view.container.querySelector("fieldset")!.disabled=true;fireEvent.click(option);fireEvent.keyDown(input,{key:"Enter"});fireEvent.change(input,{target:{value:"changed",selectionStart:7}});fireEvent.click(screen.getByRole("button",{name:"Send"}));expect(f.send).toHaveBeenLastCalledWith({value:"$ad",skills:[]});});
it("keeps exact draft and accepted bindings through pending or uncertain composer locks",async()=>{const f=fixture();const view=render(f.view());const input=screen.getByRole("textbox");fireEvent.change(input,{target:{value:"$ad",selectionStart:3}});fireEvent.click(await screen.findByRole("option",{name:/add-issue/}));fireEvent.change(input,{target:{value:"$add-issue $ad",selectionStart:14}});await screen.findByRole("option",{name:/add-note/});view.rerender(f.view(machine,true));expect(screen.queryByRole("listbox")).toBeNull();fireEvent.keyDown(input,{key:"Enter"});fireEvent.change(input,{target:{value:"changed",selectionStart:7}});fireEvent.click(screen.getByRole("button",{name:"Send"}));expect(f.send).toHaveBeenLastCalledWith({value:"$add-issue $ad",skills:[entries[0]!.selection]});view.rerender(f.view());await screen.findByRole("option",{name:/add-note/});expect((input as HTMLTextAreaElement).value).toBe("$add-issue $ad");});
