// SPDX-License-Identifier: Apache-2.0
import { createRouterTransport } from "@connectrpc/connect";
import { TransportProvider } from "@connectrpc/connect-query";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { expect, it, vi } from "vitest";
import { DeviceType, SystemCapability, SystemService, TailscaleService, TailscaleDiscoveryState, TailscaleOwnership, TailscalePeerState, TailscaleApprovalState, TailscaleAccessState, newRequestId } from "@delinoio/delidev-api-client";
import { MutationIntents } from "./mutation";
import { TailscaleDevices, TailscaleAccessControls, TailscaleApprovalObserver } from "./tailscale-connections";
function fixture() {
 const serverId=newRequestId();const peer={id:"fixture-peer",name:"Fixture shared desktop",origin:"https://peer.fixture.ts.net:8443",online:true,ownership:TailscaleOwnership.SHARED};
 const read=vi.fn(async()=>({state:TailscaleDiscoveryState.READY,peers:[peer],self:{...peer,id:"self",origin:"https://self.fixture.ts.net:8443"},httpsReady:true}));
 const check=vi.fn(async()=>({state:TailscalePeerState.ACCEPTING,serverId}));
 const start=vi.fn(async(request)=>({connection:{...request,origin:request.targetOrigin,serverId:request.targetServerId,requesterName:"Fixture",confirmationCode:"123456",state:TailscaleApprovalState.PENDING}}));
 const setAccess=vi.fn(async()=>({state:TailscaleAccessState.READY,origin:"https://self.fixture.ts.net:8443",enabled:true}));
 const transport=createRouterTransport(router=>{router.service(SystemService,{getStatus:async()=>({serverId,capabilities:[SystemCapability.TAILSCALE_CONNECTION_APPROVAL_V1]})});router.service(TailscaleService,{readTailscaleDevices:read,checkTailscaleDevice:check,getTailscaleAccess:async()=>({state:TailscaleAccessState.OFF,origin:"https://self.fixture.ts.net:8443",enabled:false}),setTailscaleAccess:setAccess,listTailscalePeerConnections:async()=>({connections:[]}),startTailscalePeerConnection:start});});
 const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});
 const wrap=(child:React.ReactNode)=><TransportProvider transport={transport}><QueryClientProvider client={client}><MutationIntents>{child}</MutationIntents></QueryClientProvider></TransportProvider>;
 return{wrap,peer,read,check,start,setAccess};
}
it("reads shared peers without probes and checks only after explicit action",async()=>{const f=fixture();const view=render(f.wrap(<TailscaleDevices/>));await screen.findByText(f.peer.name);expect(screen.getByText(/Shared device/)).toBeTruthy();expect(f.check).not.toHaveBeenCalled();expect(f.start).not.toHaveBeenCalled();fireEvent.click(screen.getByRole("button",{name:"Refresh devices"}));await waitFor(()=>expect(f.read).toHaveBeenCalledTimes(2));expect(f.check).not.toHaveBeenCalled();fireEvent.click(screen.getByRole("button",{name:"Check DeliDev"}));await screen.findByRole("button",{name:"Connect as client"});expect(f.check).toHaveBeenCalledTimes(1);expect(f.start).not.toHaveBeenCalled();view.unmount();});
it("requires access confirmation before changing the current server",async()=>{const f=fixture();render(f.wrap(<TailscaleAccessControls/>));const enable=await screen.findByRole("button",{name:"Enable access"}) as HTMLButtonElement;await waitFor(()=>expect(enable.disabled).toBe(false));fireEvent.click(enable);await screen.findByRole("dialog");expect(f.setAccess).not.toHaveBeenCalled();fireEvent.click(screen.getByRole("button",{name:"Confirm"}));await waitFor(()=>expect(f.setAccess).toHaveBeenCalledTimes(1));expect(f.setAccess.mock.calls[0][0].origin).toBe("https://self.fixture.ts.net:8443");});
it("requires explicit requester approval initiation after checking the target",async()=>{const f=fixture();render(f.wrap(<TailscaleDevices/>));fireEvent.click(await screen.findByRole("button",{name:"Check DeliDev"}));fireEvent.click(await screen.findByRole("button",{name:"Connect as client"}));await screen.findByRole("dialog");expect(f.start).not.toHaveBeenCalled();fireEvent.click(screen.getByRole("button",{name:"Request approval"}));await screen.findByText("123456");expect(f.start.mock.calls[0][0].role).toBe(DeviceType.CLIENT);expect(f.start.mock.calls[0][0].targetOrigin).toBe(f.peer.origin);expect(screen.queryByRole("button",{name:"Complete approved connection"})).toBeNull();});
it("requires matching code for target Worker approval",async()=>{const id=newRequestId();const decide=vi.fn(async()=>({connection:{requestId:id,state:TailscaleApprovalState.APPROVED}}));const transport=createRouterTransport(router=>{router.service(SystemService,{getStatus:async()=>({capabilities:[SystemCapability.TAILSCALE_CONNECTION_APPROVAL_V1]})});router.service(TailscaleService,{listTailscaleConnections:async()=>({connections:[{requestId:id,requesterName:"Fixture requester",origin:"https://target.fixture.ts.net:8443",workerServerOrigin:"https://chosen.fixture.ts.net:8443",role:DeviceType.WORKER,confirmationCode:"654321",state:TailscaleApprovalState.PENDING}]}),decideTailscaleConnection:decide});});const client=new QueryClient();render(<TransportProvider transport={transport}><QueryClientProvider client={client}><MutationIntents><TailscaleApprovalObserver active/></MutationIntents></QueryClientProvider></TransportProvider>);const input=await screen.findByLabelText("Enter the matching code");expect(document.activeElement).toBe(input);const allow=screen.getByRole("button",{name:"Allow this exact connection"})as HTMLButtonElement;expect(allow.disabled).toBe(true);expect(screen.getByText(/https:\/\/chosen.fixture.ts.net:8443/)).toBeTruthy();fireEvent.change(input,{target:{value:"654321"}});fireEvent.click(allow);await waitFor(()=>expect(decide).toHaveBeenCalledTimes(1));expect(decide.mock.calls[0][0].requestId).toBe(id);expect(decide.mock.calls[0][0].allow).toBe(true);});
