// SPDX-License-Identifier: Apache-2.0
import { ProviderPresetId } from "./gen/delidev/v1/provider_pb.js";

// Presentation identity/order only. Server inventory and saved configuration
// remain the authority for availability, credential evidence and execution.
export const providerPresetNames: ReadonlyMap<ProviderPresetId, string> = new Map([
  [ProviderPresetId.OPENAI, "openai"],
  [ProviderPresetId.ANTHROPIC, "anthropic"],
  [ProviderPresetId.OPENROUTER, "openrouter"],
  [ProviderPresetId.VERCEL_AI_GATEWAY, "vercel-ai-gateway"],
  [ProviderPresetId.XAI, "xai"],
  [ProviderPresetId.DEEPSEEK, "deepseek"],
  [ProviderPresetId.GEMINI, "gemini"],
  [ProviderPresetId.GROQ, "groq"],
  [ProviderPresetId.MISTRAL, "mistral"],
  [ProviderPresetId.TOGETHER_AI, "together-ai"],
  [ProviderPresetId.FIREWORKS_AI, "fireworks-ai"],
  [ProviderPresetId.PERPLEXITY, "perplexity"],
  [ProviderPresetId.COHERE, "cohere"],
  [ProviderPresetId.CEREBRAS, "cerebras"],
  [ProviderPresetId.NEBIUS, "nebius"],
  [ProviderPresetId.NOVITA, "novita"],
  [ProviderPresetId.DEEPINFRA, "deepinfra"],
  [ProviderPresetId.HUGGING_FACE, "hugging-face"],
  [ProviderPresetId.VENICE, "venice"],
  [ProviderPresetId.SCALEWAY, "scaleway"],
  [ProviderPresetId.BASETEN, "baseten"],
  [ProviderPresetId.MOONSHOT, "moonshot"],
  [ProviderPresetId.MOONSHOT_CN, "moonshot-cn"],
  [ProviderPresetId.MINIMAX, "minimax"],
  [ProviderPresetId.MINIMAX_CN, "minimax-cn"],
  [ProviderPresetId.SILICONFLOW, "siliconflow"],
  [ProviderPresetId.SILICONFLOW_CN, "siliconflow-cn"],
  [ProviderPresetId.QIANFAN, "qianfan"],
  [ProviderPresetId.TENCENT_TOKENHUB, "tencent-tokenhub"],
  [ProviderPresetId.TENCENT_TOKENHUB_INTERNATIONAL, "tencent-tokenhub-international"],
  [ProviderPresetId.ALIBABA_MODEL_STUDIO_INTERNATIONAL, "alibaba-model-studio-international"],
  [ProviderPresetId.ALIBABA_MODEL_STUDIO_HONG_KONG, "alibaba-model-studio-hong-kong"],
  [ProviderPresetId.OLLAMA, "ollama"],
  [ProviderPresetId.LM_STUDIO, "lm-studio"],
  [ProviderPresetId.VLLM, "vllm"],
]);

export const hostedProviderPresetOrder: readonly ProviderPresetId[] = [
  ProviderPresetId.OPENAI,
  ProviderPresetId.ANTHROPIC,
  ProviderPresetId.OPENROUTER,
  ProviderPresetId.VERCEL_AI_GATEWAY,
  ProviderPresetId.XAI,
  ProviderPresetId.DEEPSEEK,
  ProviderPresetId.GEMINI,
  ProviderPresetId.GROQ,
  ProviderPresetId.MISTRAL,
  ProviderPresetId.TOGETHER_AI,
  ProviderPresetId.FIREWORKS_AI,
  ProviderPresetId.PERPLEXITY,
  ProviderPresetId.COHERE,
  ProviderPresetId.CEREBRAS,
  ProviderPresetId.NEBIUS,
  ProviderPresetId.NOVITA,
  ProviderPresetId.DEEPINFRA,
  ProviderPresetId.HUGGING_FACE,
  ProviderPresetId.VENICE,
  ProviderPresetId.SCALEWAY,
  ProviderPresetId.BASETEN,
  ProviderPresetId.MOONSHOT,
  ProviderPresetId.MOONSHOT_CN,
  ProviderPresetId.MINIMAX,
  ProviderPresetId.MINIMAX_CN,
  ProviderPresetId.SILICONFLOW,
  ProviderPresetId.SILICONFLOW_CN,
  ProviderPresetId.QIANFAN,
  ProviderPresetId.TENCENT_TOKENHUB,
  ProviderPresetId.TENCENT_TOKENHUB_INTERNATIONAL,
  ProviderPresetId.ALIBABA_MODEL_STUDIO_INTERNATIONAL,
  ProviderPresetId.ALIBABA_MODEL_STUDIO_HONG_KONG,
];
