// SPDX-License-Identifier: Apache-2.0
package providers

import "github.com/delinoio/oss/cmds/delidev-cli/internal/domain"

// Ordinary fixed-region API keys only; these defaults grant no new inference
// protocol, native harness, subscription or account readiness authority.
func additionalHostedPresets() []domain.ProviderPreset {
	return []domain.ProviderPreset{
		{ID: domain.PresetGemini, Provider: domain.Provider{Name: "Google Gemini", Endpoint: "https://generativelanguage.googleapis.com/v1beta/openai", Protocol: domain.OpenAIChat, Authentication: domain.BearerAuth, Enabled: new(true)}, Documentation: "https://ai.google.dev/gemini-api/docs/openai", KeyGuidance: "Create an ordinary inference API key for Google Gemini and connect it with account connect --key-stdin. Validation and discovery are explicit non-inference operations; catalog success does not prove model access or billing availability. Use a Gemini API key from Google AI Studio, separate from Vertex AI/IAM credentials."},
		{ID: domain.PresetGroq, Provider: domain.Provider{Name: "Groq", Endpoint: "https://api.groq.com/openai/v1", Protocol: domain.OpenAIChat, Authentication: domain.BearerAuth, Enabled: new(true)}, Documentation: "https://console.groq.com/docs/models", KeyGuidance: "Create an ordinary inference API key for Groq and connect it with account connect --key-stdin. Validation and discovery are explicit non-inference operations; catalog success does not prove model access or billing availability."},
		{ID: domain.PresetMistral, Provider: domain.Provider{Name: "Mistral", Endpoint: "https://api.mistral.ai/v1", Protocol: domain.OpenAIChat, Authentication: domain.BearerAuth, Enabled: new(true)}, Documentation: "https://docs.mistral.ai/api/endpoint/models", KeyGuidance: "Create an ordinary inference API key for Mistral and connect it with account connect --key-stdin. Validation and discovery are explicit non-inference operations; catalog success does not prove model access or billing availability."},
		{ID: domain.PresetTogetherAI, Provider: domain.Provider{Name: "Together AI", Endpoint: "https://api.together.ai/v1", Protocol: domain.OpenAIChat, Authentication: domain.BearerAuth, Enabled: new(true)}, Documentation: "https://docs.together.ai/reference/models", KeyGuidance: "Create an ordinary inference API key for Together AI and connect it with account connect --key-stdin. Validation and discovery are explicit non-inference operations; catalog success does not prove model access or billing availability."},
		{ID: domain.PresetFireworksAI, Provider: domain.Provider{Name: "Fireworks AI", Endpoint: "https://api.fireworks.ai/inference/v1", Protocol: domain.OpenAIChat, Authentication: domain.BearerAuth, Enabled: new(true)}, Documentation: "https://docs.fireworks.ai/api-reference/list-models", KeyGuidance: "Create an ordinary inference API key for Fireworks AI and connect it with account connect --key-stdin. Validation and discovery are explicit non-inference operations; catalog success does not prove model access or billing availability."},
		{ID: domain.PresetPerplexity, Provider: domain.Provider{Name: "Perplexity Router", Endpoint: "https://api.perplexity.ai/router/v1", Protocol: domain.OpenAIChat, Authentication: domain.BearerAuth, Enabled: new(true)}, Documentation: "https://docs.perplexity.ai/api-reference/gateway-models-get", KeyGuidance: "Create an ordinary inference API key for Perplexity Router and connect it with account connect --key-stdin. Validation and discovery are explicit non-inference operations; catalog success does not prove model access or billing availability."},
		{ID: domain.PresetCohere, Provider: domain.Provider{Name: "Cohere", Endpoint: "https://api.cohere.ai/compatibility/v1", Protocol: domain.OpenAIChat, Authentication: domain.BearerAuth, Enabled: new(true)}, Documentation: "https://docs.cohere.com/docs/compatibility-api", KeyGuidance: "Create an ordinary inference API key for Cohere and connect it with account connect --key-stdin. Validation and discovery are explicit non-inference operations; catalog success does not prove model access or billing availability."},
		{ID: domain.PresetCerebras, Provider: domain.Provider{Name: "Cerebras", Endpoint: "https://api.cerebras.ai/v1", Protocol: domain.OpenAIChat, Authentication: domain.BearerAuth, Enabled: new(true)}, Documentation: "https://inference-docs.cerebras.ai/api-reference/models/list-models", KeyGuidance: "Create an ordinary inference API key for Cerebras and connect it with account connect --key-stdin. Validation and discovery are explicit non-inference operations; catalog success does not prove model access or billing availability."},
		{ID: domain.PresetNebius, Provider: domain.Provider{Name: "Nebius Token Factory", Endpoint: "https://api.tokenfactory.nebius.com/v1", Protocol: domain.OpenAIChat, Authentication: domain.BearerAuth, Enabled: new(true)}, Documentation: "https://docs.tokenfactory.nebius.com/api-reference/models/list-models", KeyGuidance: "Create an ordinary inference API key for Nebius Token Factory and connect it with account connect --key-stdin. Validation and discovery are explicit non-inference operations; catalog success does not prove model access or billing availability."},
		{ID: domain.PresetNovita, Provider: domain.Provider{Name: "Novita", Endpoint: "https://api.novita.ai/openai/v1", Protocol: domain.OpenAIChat, Authentication: domain.BearerAuth, Enabled: new(true)}, Documentation: "https://docs.novita.ai/api-reference/model-apis-llm-list-models", KeyGuidance: "Create an ordinary inference API key for Novita and connect it with account connect --key-stdin. Validation and discovery are explicit non-inference operations; catalog success does not prove model access or billing availability."},
		{ID: domain.PresetDeepInfra, Provider: domain.Provider{Name: "DeepInfra", Endpoint: "https://api.deepinfra.com/v1/openai", Protocol: domain.OpenAIChat, Authentication: domain.BearerAuth, Enabled: new(true)}, Documentation: "https://docs.deepinfra.com/api-reference/models/openai-models", KeyGuidance: "Create an ordinary inference API key for DeepInfra and connect it with account connect --key-stdin. Validation and discovery are explicit non-inference operations; catalog success does not prove model access or billing availability."},
		{ID: domain.PresetHuggingFace, Provider: domain.Provider{Name: "Hugging Face Inference Providers", Endpoint: "https://router.huggingface.co/v1", Protocol: domain.OpenAIChat, Authentication: domain.BearerAuth, Enabled: new(true)}, Documentation: "https://huggingface.co/docs/inference-providers/en/tasks/chat-completion", KeyGuidance: "Create an ordinary inference API key for Hugging Face Inference Providers and connect it with account connect --key-stdin. Validation and discovery are explicit non-inference operations; catalog success does not prove model access or billing availability. Create a Hugging Face token with inference-provider permission for your intended resources; Hub identity verification alone does not establish inference permission."},
		{ID: domain.PresetVenice, Provider: domain.Provider{Name: "Venice", Endpoint: "https://api.venice.ai/api/v1", Protocol: domain.OpenAIChat, Authentication: domain.BearerAuth, Enabled: new(true)}, Documentation: "https://docs.venice.ai/api-reference/endpoint/api_keys/rate_limits", KeyGuidance: "Create an ordinary inference API key for Venice and connect it with account connect --key-stdin. Validation and discovery are explicit non-inference operations; catalog success does not prove model access or billing availability."},
		{ID: domain.PresetScaleway, Provider: domain.Provider{Name: "Scaleway", Endpoint: "https://api.scaleway.ai/v1", Protocol: domain.OpenAIChat, Authentication: domain.BearerAuth, Enabled: new(true)}, Documentation: "https://www.scaleway.com/en/developers/api/generative-apis/models", KeyGuidance: "Create an ordinary inference API key for Scaleway and connect it with account connect --key-stdin. Validation and discovery are explicit non-inference operations; catalog success does not prove model access or billing availability."},
		{ID: domain.PresetBaseten, Provider: domain.Provider{Name: "Baseten", Endpoint: "https://inference.baseten.co/v1", Protocol: domain.OpenAIChat, Authentication: domain.BearerAuth, Enabled: new(true)}, Documentation: "https://docs.baseten.co/reference/management-api/model-apis/gets-all-model-apis", KeyGuidance: "Create an ordinary inference API key for Baseten and connect it with account connect --key-stdin. Validation and discovery are explicit non-inference operations; catalog success does not prove model access or billing availability. Use a Baseten personal API key for the intended workspace; catalog/management access and inference authorization remain separate."},
		{ID: domain.PresetMoonshot, Provider: domain.Provider{Name: "Moonshot / Kimi — Global", Endpoint: "https://api.moonshot.ai/v1", Protocol: domain.OpenAIChat, Authentication: domain.BearerAuth, Enabled: new(true)}, Documentation: "https://platform.kimi.ai/docs/api/list-models", KeyGuidance: "Create an ordinary inference API key for Moonshot / Kimi — Global and connect it with account connect --key-stdin. Validation and discovery are explicit non-inference operations; catalog success does not prove model access or billing availability. Use a key issued for this exact region and endpoint; keys from another region or a subscription/coding/token plan are not interchangeable. DeliDev cannot detect a key type from a model catalog."},
		{ID: domain.PresetMoonshotCN, Provider: domain.Provider{Name: "Moonshot / Kimi — China", Endpoint: "https://api.moonshot.cn/v1", Protocol: domain.OpenAIChat, Authentication: domain.BearerAuth, Enabled: new(true)}, Documentation: "https://platform.kimi.com/docs/api/list-models", KeyGuidance: "Create an ordinary inference API key for Moonshot / Kimi — China and connect it with account connect --key-stdin. Validation and discovery are explicit non-inference operations; catalog success does not prove model access or billing availability. Use a key issued for this exact region and endpoint; keys from another region or a subscription/coding/token plan are not interchangeable. DeliDev cannot detect a key type from a model catalog."},
		{ID: domain.PresetMiniMax, Provider: domain.Provider{Name: "MiniMax — Global", Endpoint: "https://api.minimax.io/v1", Protocol: domain.OpenAIChat, Authentication: domain.BearerAuth, Enabled: new(true)}, Documentation: "https://platform.minimax.io/docs/api-reference/models/openai/list-models", KeyGuidance: "Create an ordinary inference API key for MiniMax — Global and connect it with account connect --key-stdin. Validation and discovery are explicit non-inference operations; catalog success does not prove model access or billing availability. Use a key issued for this exact region and endpoint; keys from another region or a subscription/coding/token plan are not interchangeable. DeliDev cannot detect a key type from a model catalog."},
		{ID: domain.PresetMiniMaxCN, Provider: domain.Provider{Name: "MiniMax — China", Endpoint: "https://api.minimax.cn/v1", Protocol: domain.OpenAIChat, Authentication: domain.BearerAuth, Enabled: new(true)}, Documentation: "https://platform.minimax.cn/docs/api-reference/models/openai/list-models", KeyGuidance: "Create an ordinary inference API key for MiniMax — China and connect it with account connect --key-stdin. Validation and discovery are explicit non-inference operations; catalog success does not prove model access or billing availability. Use a key issued for this exact region and endpoint; keys from another region or a subscription/coding/token plan are not interchangeable. DeliDev cannot detect a key type from a model catalog."},
		{ID: domain.PresetSiliconFlow, Provider: domain.Provider{Name: "SiliconFlow — Global", Endpoint: "https://api.siliconflow.com/v1", Protocol: domain.OpenAIChat, Authentication: domain.BearerAuth, Enabled: new(true)}, Documentation: "https://docs.siliconflow.com/cn/api-reference/models/get-model-list", KeyGuidance: "Create an ordinary inference API key for SiliconFlow — Global and connect it with account connect --key-stdin. Validation and discovery are explicit non-inference operations; catalog success does not prove model access or billing availability. Use a key issued for this exact region and endpoint; keys from another region or a subscription/coding/token plan are not interchangeable. DeliDev cannot detect a key type from a model catalog."},
		{ID: domain.PresetSiliconFlowCN, Provider: domain.Provider{Name: "SiliconFlow — China", Endpoint: "https://api.siliconflow.cn/v1", Protocol: domain.OpenAIChat, Authentication: domain.BearerAuth, Enabled: new(true)}, Documentation: "https://api-docs.siliconflow.cn/docs/api/models-get", KeyGuidance: "Create an ordinary inference API key for SiliconFlow — China and connect it with account connect --key-stdin. Validation and discovery are explicit non-inference operations; catalog success does not prove model access or billing availability. Use a key issued for this exact region and endpoint; keys from another region or a subscription/coding/token plan are not interchangeable. DeliDev cannot detect a key type from a model catalog."},
		{ID: domain.PresetQianfan, Provider: domain.Provider{Name: "Baidu Qianfan", Endpoint: "https://qianfan.baidubce.com/v2", Protocol: domain.OpenAIChat, Authentication: domain.BearerAuth, Enabled: new(true)}, Documentation: "https://cloud.baidu.com/doc/qianfan-api/s/Dmba8k71y", KeyGuidance: "Create an ordinary inference API key for Baidu Qianfan and connect it with account connect --key-stdin. Validation and discovery are explicit non-inference operations; catalog success does not prove model access or billing availability. Use the Qianfan v2 ordinary API key, separate from an IAM access-key/secret-key pair."},
		{ID: domain.PresetTencentTokenHub, Provider: domain.Provider{Name: "Tencent TokenHub — China", Endpoint: "https://tokenhub.tencentmaas.com/v1", Protocol: domain.OpenAIChat, Authentication: domain.BearerAuth, Enabled: new(true)}, Documentation: "https://cloud.tencent.com/document/product/1823/130078", KeyGuidance: "Create an ordinary inference API key for Tencent TokenHub — China and connect it with account connect --key-stdin. Validation and discovery are explicit non-inference operations; catalog success does not prove model access or billing availability. Use a key issued for this exact region and endpoint; keys from another region or a subscription/coding/token plan are not interchangeable. DeliDev cannot detect a key type from a model catalog."},
		{ID: domain.PresetTencentTokenHubInternational, Provider: domain.Provider{Name: "Tencent TokenHub — International", Endpoint: "https://tokenhub-intl.tencentmaas.com/v1", Protocol: domain.OpenAIChat, Authentication: domain.BearerAuth, Enabled: new(true)}, Documentation: "https://cloud.tencent.com/document/product/1823/130078", KeyGuidance: "Create an ordinary inference API key for Tencent TokenHub — International and connect it with account connect --key-stdin. Validation and discovery are explicit non-inference operations; catalog success does not prove model access or billing availability. Use a key issued for this exact region and endpoint; keys from another region or a subscription/coding/token plan are not interchangeable. DeliDev cannot detect a key type from a model catalog."},
		{ID: domain.PresetAlibabaModelStudioInternational, Provider: domain.Provider{Name: "Alibaba Model Studio — International", Endpoint: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1", Protocol: domain.OpenAIChat, Authentication: domain.BearerAuth, Enabled: new(true)}, Documentation: "https://help.aliyun.com/en/model-studio/list-models", KeyGuidance: "Create an ordinary inference API key for Alibaba Model Studio — International and connect it with account connect --key-stdin. Validation and discovery are explicit non-inference operations; catalog success does not prove model access or billing availability. Use a key issued for this exact region and endpoint; keys from another region or a subscription/coding/token plan are not interchangeable. DeliDev cannot detect a key type from a model catalog."},
		{ID: domain.PresetAlibabaModelStudioHongKong, Provider: domain.Provider{Name: "Alibaba Model Studio — Hong Kong", Endpoint: "https://cn-hongkong.dashscope.aliyuncs.com/compatible-mode/v1", Protocol: domain.OpenAIChat, Authentication: domain.BearerAuth, Enabled: new(true)}, Documentation: "https://help.aliyun.com/en/model-studio/list-models", KeyGuidance: "Create an ordinary inference API key for Alibaba Model Studio — Hong Kong and connect it with account connect --key-stdin. Validation and discovery are explicit non-inference operations; catalog success does not prove model access or billing availability. Use a key issued for this exact region and endpoint; keys from another region or a subscription/coding/token plan are not interchangeable. DeliDev cannot detect a key type from a model catalog."},
	}
}
