// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbquery

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Notification struct {
	NotificationID string             `json:"notification_id"`
	WorkspaceID    string             `json:"workspace_id"`
	Type           int32              `json:"type"`
	Title          string             `json:"title"`
	Body           string             `json:"body"`
	ReferenceID    string             `json:"reference_id"`
	Read           bool               `json:"read"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type PrRecord struct {
	PrTrackingID    string             `json:"pr_tracking_id"`
	WorkspaceID     string             `json:"workspace_id"`
	Status          int32              `json:"status"`
	PrUrl           string             `json:"pr_url"`
	UnitTaskID      string             `json:"unit_task_id"`
	AutoFixEnabled  bool               `json:"auto_fix_enabled"`
	FixAttemptCount int32              `json:"fix_attempt_count"`
	MaxFixAttempts  int32              `json:"max_fix_attempts"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Repository struct {
	RepositoryID  string             `json:"repository_id"`
	WorkspaceID   string             `json:"workspace_id"`
	RepositoryUrl string             `json:"repository_url"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type RepositoryGroup struct {
	RepositoryGroupID string             `json:"repository_group_id"`
	WorkspaceID       string             `json:"workspace_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type RepositoryGroupMember struct {
	WorkspaceID       string             `json:"workspace_id"`
	RepositoryGroupID string             `json:"repository_group_id"`
	RepositoryID      string             `json:"repository_id"`
	BranchRef         string             `json:"branch_ref"`
	DisplayOrder      int32              `json:"display_order"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type ReviewAssistItem struct {
	ID             int32  `json:"id"`
	WorkspaceID    string `json:"workspace_id"`
	UnitTaskID     string `json:"unit_task_id"`
	ReviewAssistID string `json:"review_assist_id"`
	Body           string `json:"body"`
}

type ReviewComment struct {
	ID              int32  `json:"id"`
	WorkspaceID     string `json:"workspace_id"`
	PrTrackingID    string `json:"pr_tracking_id"`
	ReviewCommentID string `json:"review_comment_id"`
	Body            string `json:"body"`
}

type SessionSummary struct {
	SessionID          string             `json:"session_id"`
	WorkspaceID        string             `json:"workspace_id"`
	ParentSessionID    string             `json:"parent_session_id"`
	RootSessionID      string             `json:"root_session_id"`
	ForkStatus         int32              `json:"fork_status"`
	ForkedFromSequence int64              `json:"forked_from_sequence"`
	AgentSessionStatus int32              `json:"agent_session_status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type SubTask struct {
	SubTaskID        string             `json:"sub_task_id"`
	UnitTaskID       string             `json:"unit_task_id"`
	WorkspaceID      string             `json:"workspace_id"`
	Type             int32              `json:"type"`
	Status           int32              `json:"status"`
	CompletionReason int32              `json:"completion_reason"`
	Title            string             `json:"title"`
	SessionID        string             `json:"session_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type UnitTask struct {
	UnitTaskID        string             `json:"unit_task_id"`
	WorkspaceID       string             `json:"workspace_id"`
	Status            int32              `json:"status"`
	ActionRequired    int32              `json:"action_required"`
	Prompt            string             `json:"prompt"`
	RepositoryGroupID string             `json:"repository_group_id"`
	AgentCliType      int32              `json:"agent_cli_type"`
	UsePlanMode       bool               `json:"use_plan_mode"`
	SubTaskCount      int32              `json:"sub_task_count"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Workspace struct {
	WorkspaceID string             `json:"workspace_id"`
	Name        string             `json:"name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Type        int32              `json:"type"`
}

type WorkspaceSetting struct {
	WorkspaceID         string             `json:"workspace_id"`
	DefaultAgentCliType int32              `json:"default_agent_cli_type"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}
