// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package dbquery

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (notification_id, workspace_id, type, title, body, reference_id, read, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING notification_id, workspace_id, type, title, body, reference_id, read, created_at
`

type CreateNotificationParams struct {
	NotificationID string             `json:"notification_id"`
	WorkspaceID    string             `json:"workspace_id"`
	Type           int32              `json:"type"`
	Title          string             `json:"title"`
	Body           string             `json:"body"`
	ReferenceID    string             `json:"reference_id"`
	Read           bool               `json:"read"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.NotificationID,
		arg.WorkspaceID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.ReferenceID,
		arg.Read,
		arg.CreatedAt,
	)
	var i Notification
	err := row.Scan(
		&i.NotificationID,
		&i.WorkspaceID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.ReferenceID,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT notification_id, workspace_id, type, title, body, reference_id, read, created_at FROM notifications WHERE workspace_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListNotifications(ctx context.Context, workspaceID string) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.NotificationID,
			&i.WorkspaceID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.ReferenceID,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications SET read = TRUE
WHERE workspace_id = $1 AND notification_id = $2
RETURNING notification_id, workspace_id, type, title, body, reference_id, read, created_at
`

type MarkNotificationReadParams struct {
	WorkspaceID    string `json:"workspace_id"`
	NotificationID string `json:"notification_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.WorkspaceID, arg.NotificationID)
	var i Notification
	err := row.Scan(
		&i.NotificationID,
		&i.WorkspaceID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.ReferenceID,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}
