// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pr_records.sql

package dbquery

import (
	"context"
)

const createPullRequest = `-- name: CreatePullRequest :one
INSERT INTO pr_records (pr_tracking_id, workspace_id, status)
VALUES ($1, $2, $3)
RETURNING pr_tracking_id, workspace_id, status
`

type CreatePullRequestParams struct {
	PrTrackingID string `json:"pr_tracking_id"`
	WorkspaceID  string `json:"workspace_id"`
	Status       int32  `json:"status"`
}

func (q *Queries) CreatePullRequest(ctx context.Context, arg CreatePullRequestParams) (PrRecord, error) {
	row := q.db.QueryRow(ctx, createPullRequest, arg.PrTrackingID, arg.WorkspaceID, arg.Status)
	var i PrRecord
	err := row.Scan(&i.PrTrackingID, &i.WorkspaceID, &i.Status)
	return i, err
}

const getPullRequest = `-- name: GetPullRequest :one
SELECT pr_tracking_id, workspace_id, status FROM pr_records WHERE workspace_id = $1 AND pr_tracking_id = $2
`

type GetPullRequestParams struct {
	WorkspaceID  string `json:"workspace_id"`
	PrTrackingID string `json:"pr_tracking_id"`
}

func (q *Queries) GetPullRequest(ctx context.Context, arg GetPullRequestParams) (PrRecord, error) {
	row := q.db.QueryRow(ctx, getPullRequest, arg.WorkspaceID, arg.PrTrackingID)
	var i PrRecord
	err := row.Scan(&i.PrTrackingID, &i.WorkspaceID, &i.Status)
	return i, err
}

const listPullRequests = `-- name: ListPullRequests :many
SELECT pr_tracking_id, workspace_id, status FROM pr_records WHERE workspace_id = $1
`

func (q *Queries) ListPullRequests(ctx context.Context, workspaceID string) ([]PrRecord, error) {
	rows, err := q.db.Query(ctx, listPullRequests, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrRecord
	for rows.Next() {
		var i PrRecord
		if err := rows.Scan(&i.PrTrackingID, &i.WorkspaceID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePullRequestStatus = `-- name: UpdatePullRequestStatus :one
UPDATE pr_records
SET status = $3
WHERE workspace_id = $1 AND pr_tracking_id = $2
RETURNING pr_tracking_id, workspace_id, status
`

type UpdatePullRequestStatusParams struct {
	WorkspaceID  string `json:"workspace_id"`
	PrTrackingID string `json:"pr_tracking_id"`
	Status       int32  `json:"status"`
}

func (q *Queries) UpdatePullRequestStatus(ctx context.Context, arg UpdatePullRequestStatusParams) (PrRecord, error) {
	row := q.db.QueryRow(ctx, updatePullRequestStatus, arg.WorkspaceID, arg.PrTrackingID, arg.Status)
	var i PrRecord
	err := row.Scan(&i.PrTrackingID, &i.WorkspaceID, &i.Status)
	return i, err
}
