// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbquery

import (
	"context"
)

type Querier interface {
	ArchiveSession(ctx context.Context, arg ArchiveSessionParams) error
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreatePullRequest(ctx context.Context, arg CreatePullRequestParams) (PrRecord, error)
	CreateRepositoryGroup(ctx context.Context, arg CreateRepositoryGroupParams) (RepositoryGroup, error)
	CreateReviewAssistItem(ctx context.Context, arg CreateReviewAssistItemParams) (ReviewAssistItem, error)
	CreateReviewComment(ctx context.Context, arg CreateReviewCommentParams) (ReviewComment, error)
	CreateSessionSummary(ctx context.Context, arg CreateSessionSummaryParams) (SessionSummary, error)
	CreateUnitTask(ctx context.Context, arg CreateUnitTaskParams) (UnitTask, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	GetLatestWaitingSession(ctx context.Context, arg GetLatestWaitingSessionParams) (SessionSummary, error)
	GetPullRequest(ctx context.Context, arg GetPullRequestParams) (PrRecord, error)
	GetRepositoryGroup(ctx context.Context, arg GetRepositoryGroupParams) (RepositoryGroup, error)
	GetSessionSummary(ctx context.Context, arg GetSessionSummaryParams) (SessionSummary, error)
	GetSubTask(ctx context.Context, arg GetSubTaskParams) (SubTask, error)
	GetUnitTask(ctx context.Context, arg GetUnitTaskParams) (UnitTask, error)
	GetWorkspace(ctx context.Context, workspaceID string) (Workspace, error)
	ListForkedSessions(ctx context.Context, arg ListForkedSessionsParams) ([]SessionSummary, error)
	ListNotifications(ctx context.Context, workspaceID string) ([]Notification, error)
	ListPullRequests(ctx context.Context, workspaceID string) ([]PrRecord, error)
	ListRepositoryGroups(ctx context.Context, workspaceID string) ([]RepositoryGroup, error)
	ListReviewAssistItems(ctx context.Context, arg ListReviewAssistItemsParams) ([]ReviewAssistItem, error)
	ListReviewComments(ctx context.Context, arg ListReviewCommentsParams) ([]ReviewComment, error)
	ListSubTasks(ctx context.Context, arg ListSubTasksParams) ([]SubTask, error)
	ListUnitTasks(ctx context.Context, workspaceID string) ([]UnitTask, error)
	ListWorkspaces(ctx context.Context) ([]Workspace, error)
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error)
	UpdateUnitTaskStatus(ctx context.Context, arg UpdateUnitTaskStatusParams) (UnitTask, error)
	UpsertSubTask(ctx context.Context, arg UpsertSubTaskParams) (SubTask, error)
}

var _ Querier = (*Queries)(nil)
