// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repositories.sql

package dbquery

import (
	"context"
)

const createRepository = `-- name: CreateRepository :one
INSERT INTO repositories (
    repository_id,
    workspace_id,
    repository_url,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, NOW(), NOW())
RETURNING repository_id, workspace_id, repository_url, created_at, updated_at
`

type CreateRepositoryParams struct {
	RepositoryID  string `json:"repository_id"`
	WorkspaceID   string `json:"workspace_id"`
	RepositoryUrl string `json:"repository_url"`
}

func (q *Queries) CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, createRepository, arg.RepositoryID, arg.WorkspaceID, arg.RepositoryUrl)
	var i Repository
	err := row.Scan(
		&i.RepositoryID,
		&i.WorkspaceID,
		&i.RepositoryUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRepository = `-- name: DeleteRepository :exec
DELETE FROM repositories WHERE workspace_id = $1 AND repository_id = $2
`

type DeleteRepositoryParams struct {
	WorkspaceID  string `json:"workspace_id"`
	RepositoryID string `json:"repository_id"`
}

func (q *Queries) DeleteRepository(ctx context.Context, arg DeleteRepositoryParams) error {
	_, err := q.db.Exec(ctx, deleteRepository, arg.WorkspaceID, arg.RepositoryID)
	return err
}

const getRepository = `-- name: GetRepository :one
SELECT repository_id, workspace_id, repository_url, created_at, updated_at FROM repositories WHERE workspace_id = $1 AND repository_id = $2
`

type GetRepositoryParams struct {
	WorkspaceID  string `json:"workspace_id"`
	RepositoryID string `json:"repository_id"`
}

func (q *Queries) GetRepository(ctx context.Context, arg GetRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepository, arg.WorkspaceID, arg.RepositoryID)
	var i Repository
	err := row.Scan(
		&i.RepositoryID,
		&i.WorkspaceID,
		&i.RepositoryUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRepositories = `-- name: ListRepositories :many
SELECT repository_id, workspace_id, repository_url, created_at, updated_at FROM repositories WHERE workspace_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListRepositories(ctx context.Context, workspaceID string) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listRepositories, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.RepositoryID,
			&i.WorkspaceID,
			&i.RepositoryUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRepository = `-- name: UpdateRepository :one
UPDATE repositories
SET repository_url = $3, updated_at = NOW()
WHERE workspace_id = $1 AND repository_id = $2
RETURNING repository_id, workspace_id, repository_url, created_at, updated_at
`

type UpdateRepositoryParams struct {
	WorkspaceID   string `json:"workspace_id"`
	RepositoryID  string `json:"repository_id"`
	RepositoryUrl string `json:"repository_url"`
}

func (q *Queries) UpdateRepository(ctx context.Context, arg UpdateRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, updateRepository, arg.WorkspaceID, arg.RepositoryID, arg.RepositoryUrl)
	var i Repository
	err := row.Scan(
		&i.RepositoryID,
		&i.WorkspaceID,
		&i.RepositoryUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
