// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sub_tasks.sql

package dbquery

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSubTask = `-- name: GetSubTask :one
SELECT sub_task_id, unit_task_id, workspace_id, type, status, completion_reason, title, session_id, created_at, updated_at FROM sub_tasks WHERE workspace_id = $1 AND sub_task_id = $2
`

type GetSubTaskParams struct {
	WorkspaceID string `json:"workspace_id"`
	SubTaskID   string `json:"sub_task_id"`
}

func (q *Queries) GetSubTask(ctx context.Context, arg GetSubTaskParams) (SubTask, error) {
	row := q.db.QueryRow(ctx, getSubTask, arg.WorkspaceID, arg.SubTaskID)
	var i SubTask
	err := row.Scan(
		&i.SubTaskID,
		&i.UnitTaskID,
		&i.WorkspaceID,
		&i.Type,
		&i.Status,
		&i.CompletionReason,
		&i.Title,
		&i.SessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubTasks = `-- name: ListSubTasks :many
SELECT sub_task_id, unit_task_id, workspace_id, type, status, completion_reason, title, session_id, created_at, updated_at FROM sub_tasks WHERE workspace_id = $1 AND unit_task_id = $2 ORDER BY created_at
`

type ListSubTasksParams struct {
	WorkspaceID string `json:"workspace_id"`
	UnitTaskID  string `json:"unit_task_id"`
}

func (q *Queries) ListSubTasks(ctx context.Context, arg ListSubTasksParams) ([]SubTask, error) {
	rows, err := q.db.Query(ctx, listSubTasks, arg.WorkspaceID, arg.UnitTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubTask
	for rows.Next() {
		var i SubTask
		if err := rows.Scan(
			&i.SubTaskID,
			&i.UnitTaskID,
			&i.WorkspaceID,
			&i.Type,
			&i.Status,
			&i.CompletionReason,
			&i.Title,
			&i.SessionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSubTask = `-- name: UpsertSubTask :one
INSERT INTO sub_tasks (sub_task_id, unit_task_id, workspace_id, type, status, completion_reason, title, session_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (sub_task_id) DO UPDATE SET
    type = EXCLUDED.type,
    status = EXCLUDED.status,
    completion_reason = EXCLUDED.completion_reason,
    title = EXCLUDED.title,
    session_id = EXCLUDED.session_id,
    updated_at = EXCLUDED.updated_at
RETURNING sub_task_id, unit_task_id, workspace_id, type, status, completion_reason, title, session_id, created_at, updated_at
`

type UpsertSubTaskParams struct {
	SubTaskID        string             `json:"sub_task_id"`
	UnitTaskID       string             `json:"unit_task_id"`
	WorkspaceID      string             `json:"workspace_id"`
	Type             int32              `json:"type"`
	Status           int32              `json:"status"`
	CompletionReason int32              `json:"completion_reason"`
	Title            string             `json:"title"`
	SessionID        string             `json:"session_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertSubTask(ctx context.Context, arg UpsertSubTaskParams) (SubTask, error) {
	row := q.db.QueryRow(ctx, upsertSubTask,
		arg.SubTaskID,
		arg.UnitTaskID,
		arg.WorkspaceID,
		arg.Type,
		arg.Status,
		arg.CompletionReason,
		arg.Title,
		arg.SessionID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SubTask
	err := row.Scan(
		&i.SubTaskID,
		&i.UnitTaskID,
		&i.WorkspaceID,
		&i.Type,
		&i.Status,
		&i.CompletionReason,
		&i.Title,
		&i.SessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
