// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: unit_tasks.sql

package dbquery

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUnitTask = `-- name: CreateUnitTask :one
INSERT INTO unit_tasks (
    unit_task_id,
    workspace_id,
    status,
    prompt,
    repository_group_id,
    agent_cli_type,
    use_plan_mode,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING unit_task_id, workspace_id, status, action_required, prompt, repository_group_id, agent_cli_type, use_plan_mode, sub_task_count, created_at, updated_at
`

type CreateUnitTaskParams struct {
	UnitTaskID        string             `json:"unit_task_id"`
	WorkspaceID       string             `json:"workspace_id"`
	Status            int32              `json:"status"`
	Prompt            string             `json:"prompt"`
	RepositoryGroupID string             `json:"repository_group_id"`
	AgentCliType      int32              `json:"agent_cli_type"`
	UsePlanMode       bool               `json:"use_plan_mode"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUnitTask(ctx context.Context, arg CreateUnitTaskParams) (UnitTask, error) {
	row := q.db.QueryRow(ctx, createUnitTask,
		arg.UnitTaskID,
		arg.WorkspaceID,
		arg.Status,
		arg.Prompt,
		arg.RepositoryGroupID,
		arg.AgentCliType,
		arg.UsePlanMode,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UnitTask
	err := row.Scan(
		&i.UnitTaskID,
		&i.WorkspaceID,
		&i.Status,
		&i.ActionRequired,
		&i.Prompt,
		&i.RepositoryGroupID,
		&i.AgentCliType,
		&i.UsePlanMode,
		&i.SubTaskCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnitTask = `-- name: GetUnitTask :one
SELECT unit_task_id, workspace_id, status, action_required, prompt, repository_group_id, agent_cli_type, use_plan_mode, sub_task_count, created_at, updated_at FROM unit_tasks WHERE workspace_id = $1 AND unit_task_id = $2
`

type GetUnitTaskParams struct {
	WorkspaceID string `json:"workspace_id"`
	UnitTaskID  string `json:"unit_task_id"`
}

func (q *Queries) GetUnitTask(ctx context.Context, arg GetUnitTaskParams) (UnitTask, error) {
	row := q.db.QueryRow(ctx, getUnitTask, arg.WorkspaceID, arg.UnitTaskID)
	var i UnitTask
	err := row.Scan(
		&i.UnitTaskID,
		&i.WorkspaceID,
		&i.Status,
		&i.ActionRequired,
		&i.Prompt,
		&i.RepositoryGroupID,
		&i.AgentCliType,
		&i.UsePlanMode,
		&i.SubTaskCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUnitTasks = `-- name: ListUnitTasks :many
SELECT unit_task_id, workspace_id, status, action_required, prompt, repository_group_id, agent_cli_type, use_plan_mode, sub_task_count, created_at, updated_at FROM unit_tasks WHERE workspace_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListUnitTasks(ctx context.Context, workspaceID string) ([]UnitTask, error) {
	rows, err := q.db.Query(ctx, listUnitTasks, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnitTask
	for rows.Next() {
		var i UnitTask
		if err := rows.Scan(
			&i.UnitTaskID,
			&i.WorkspaceID,
			&i.Status,
			&i.ActionRequired,
			&i.Prompt,
			&i.RepositoryGroupID,
			&i.AgentCliType,
			&i.UsePlanMode,
			&i.SubTaskCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUnitTaskStatus = `-- name: UpdateUnitTaskStatus :one
UPDATE unit_tasks SET status = $3, updated_at = NOW()
WHERE workspace_id = $1 AND unit_task_id = $2
RETURNING unit_task_id, workspace_id, status, action_required, prompt, repository_group_id, agent_cli_type, use_plan_mode, sub_task_count, created_at, updated_at
`

type UpdateUnitTaskStatusParams struct {
	WorkspaceID string `json:"workspace_id"`
	UnitTaskID  string `json:"unit_task_id"`
	Status      int32  `json:"status"`
}

func (q *Queries) UpdateUnitTaskStatus(ctx context.Context, arg UpdateUnitTaskStatusParams) (UnitTask, error) {
	row := q.db.QueryRow(ctx, updateUnitTaskStatus, arg.WorkspaceID, arg.UnitTaskID, arg.Status)
	var i UnitTask
	err := row.Scan(
		&i.UnitTaskID,
		&i.WorkspaceID,
		&i.Status,
		&i.ActionRequired,
		&i.Prompt,
		&i.RepositoryGroupID,
		&i.AgentCliType,
		&i.UsePlanMode,
		&i.SubTaskCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
