[package]
name = "clibox-fspy"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
file-id = "0.2.3"
globset = "0.4.18"
notify = "8.1.0"
pathdiff = "0.2.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sha2 = "0.10.9"
tempfile = "3.25.0"
tracing = "0.1.44"
uuid = { version = "1.18.1", features = ["serde", "v7"] }
walkdir = "2.5.0"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2.182"
signal-hook = "0.3.18"

[target.'cfg(target_os = "macos")'.dependencies]
fspy = { path = "../fspy" }
futures-util = "0.3.31"
libc = "0.2.182"
signal-hook = "0.3.18"
tokio = { version = "1.49.0", features = ["rt", "time"] }
tokio-util = "0.7.18"

[target.'cfg(target_os = "windows")'.dependencies]
fspy = { path = "../fspy" }
futures-util = "0.3.31"
tokio = { version = "1.49.0", features = ["rt", "time"] }
tokio-util = "0.7.18"
winapi = { version = "0.3.9", features = ["consoleapi", "fileapi", "handleapi", "jobapi2", "namedpipeapi", "stringapiset", "synchapi", "winbase", "wincon", "winnls", "winnt"] }
