// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveShortcutsForAccount = `-- name: CountActiveShortcutsForAccount :one
SELECT count(*)::bigint
FROM realqa_shortcuts AS shortcut
JOIN realqa_presets AS preset ON preset.id = shortcut.preset_id
WHERE preset.created_by_account_id = $1
  AND shortcut.active
`

func (q *Queries) CountActiveShortcutsForAccount(ctx context.Context, accountID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveShortcutsForAccount, accountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getIdentityBySubjectDigest = `-- name: GetIdentityBySubjectDigest :one
SELECT account_id, subject_digest, deleted_at, created_at
FROM realqa_identities
WHERE subject_digest = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetIdentityBySubjectDigest(ctx context.Context, subjectDigest []byte) (RealqaIdentity, error) {
	row := q.db.QueryRow(ctx, getIdentityBySubjectDigest, subjectDigest)
	var i RealqaIdentity
	err := row.Scan(
		&i.AccountID,
		&i.SubjectDigest,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOwnerAccess = `-- name: GetOwnerAccess :one
SELECT binding.account_id, binding.owner_kind, binding.owner_id, binding.role, binding.payer_organization_id, binding.payer_team_id, binding.created_at, binding.updated_at
FROM realqa_owner_bindings AS binding
JOIN realqa_identities AS identity ON identity.account_id = binding.account_id
LEFT JOIN realqa_scope_tombstones AS tombstone
  ON tombstone.owner_kind = binding.owner_kind
 AND tombstone.owner_id = binding.owner_id
WHERE binding.account_id = $1
  AND binding.owner_kind = $2
  AND binding.owner_id = $3
  AND identity.deleted_at IS NULL
  AND tombstone.owner_id IS NULL
`

type GetOwnerAccessParams struct {
	AccountID pgtype.UUID
	OwnerKind string
	OwnerID   pgtype.UUID
}

func (q *Queries) GetOwnerAccess(ctx context.Context, arg GetOwnerAccessParams) (RealqaOwnerBinding, error) {
	row := q.db.QueryRow(ctx, getOwnerAccess, arg.AccountID, arg.OwnerKind, arg.OwnerID)
	var i RealqaOwnerBinding
	err := row.Scan(
		&i.AccountID,
		&i.OwnerKind,
		&i.OwnerID,
		&i.Role,
		&i.PayerOrganizationID,
		&i.PayerTeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasPayerTeamAccess = `-- name: HasPayerTeamAccess :one
SELECT EXISTS (
    SELECT 1
    FROM realqa_payer_team_bindings
    WHERE account_id = $1
      AND organization_id = $2
      AND team_id = $3
)
`

type HasPayerTeamAccessParams struct {
	AccountID      pgtype.UUID
	OrganizationID pgtype.UUID
	TeamID         pgtype.UUID
}

func (q *Queries) HasPayerTeamAccess(ctx context.Context, arg HasPayerTeamAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPayerTeamAccess, arg.AccountID, arg.OrganizationID, arg.TeamID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasRepositorySubmitAccess = `-- name: HasRepositorySubmitAccess :one
SELECT EXISTS (
    SELECT 1
    FROM realqa_repository_access AS access
    JOIN realqa_github_installations AS installation
      ON installation.id = access.installation_id
    JOIN realqa_github_connections AS connection
      ON connection.id = installation.connection_id
     AND connection.state = 'connected'
    WHERE access.installation_id = $1
      AND access.account_id = $2
      AND access.repository_id = $3
      AND access.issues_enabled
      AND access.can_submit
      AND access.checked_at >= statement_timestamp() - interval '5 minutes'
)
`

type HasRepositorySubmitAccessParams struct {
	InstallationID pgtype.UUID
	AccountID      pgtype.UUID
	RepositoryID   string
}

func (q *Queries) HasRepositorySubmitAccess(ctx context.Context, arg HasRepositorySubmitAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasRepositorySubmitAccess, arg.InstallationID, arg.AccountID, arg.RepositoryID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
