// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github_provider.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateGitHubInstallation = `-- name: ActivateGitHubInstallation :execrows
UPDATE realqa_github_installations
SET provider_account_id = $1,
    account_login = $2,
    account_kind = $3,
    state = 'active',
    permissions = $4,
    revision = revision + 1,
    updated_at = transaction_timestamp()
WHERE provider_installation_id = $5
  AND state <> 'deleted'
`

type ActivateGitHubInstallationParams struct {
	ProviderAccountID      pgtype.Int8
	AccountLogin           string
	AccountKind            pgtype.Text
	Permissions            []byte
	ProviderInstallationID int64
}

func (q *Queries) ActivateGitHubInstallation(ctx context.Context, arg ActivateGitHubInstallationParams) (int64, error) {
	result, err := q.db.Exec(ctx, activateGitHubInstallation,
		arg.ProviderAccountID,
		arg.AccountLogin,
		arg.AccountKind,
		arg.Permissions,
		arg.ProviderInstallationID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const connectGitHubUser = `-- name: ConnectGitHubUser :execrows
UPDATE realqa_github_connections
SET state = 'connected',
    github_login = $1,
    github_user_id = $2,
    credential_ciphertext = $3,
    wrapped_data_key = $4,
    key_id = $5,
    oauth_state_digest = NULL,
    oauth_state_expires_at = NULL,
    connected_at = transaction_timestamp(),
    revision = revision + 1,
    updated_at = transaction_timestamp()
WHERE owner_kind = $6
  AND owner_id = $7
`

type ConnectGitHubUserParams struct {
	GithubLogin          string
	GithubUserID         pgtype.Int8
	CredentialCiphertext []byte
	WrappedDataKey       []byte
	KeyID                pgtype.Text
	OwnerKind            string
	OwnerID              pgtype.UUID
}

func (q *Queries) ConnectGitHubUser(ctx context.Context, arg ConnectGitHubUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, connectGitHubUser,
		arg.GithubLogin,
		arg.GithubUserID,
		arg.CredentialCiphertext,
		arg.WrappedDataKey,
		arg.KeyID,
		arg.OwnerKind,
		arg.OwnerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeGitHubCallbackState = `-- name: ConsumeGitHubCallbackState :execrows
INSERT INTO realqa_github_callback_states (nonce)
VALUES ($1)
ON CONFLICT (nonce) DO NOTHING
`

func (q *Queries) ConsumeGitHubCallbackState(ctx context.Context, nonce string) (int64, error) {
	result, err := q.db.Exec(ctx, consumeGitHubCallbackState, nonce)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createPendingGitHubInstallation = `-- name: CreatePendingGitHubInstallation :execrows
INSERT INTO realqa_github_installations (
    id, connection_id, owner_kind, owner_id, provider_installation_id,
    account_login, state
)
SELECT
    $1, connection.id, connection.owner_kind, connection.owner_id,
    $2, 'pending', 'pending'
FROM realqa_github_connections AS connection
WHERE connection.owner_kind = $3
  AND connection.owner_id = $4
ON CONFLICT (provider_installation_id) DO NOTHING
`

type CreatePendingGitHubInstallationParams struct {
	ID                     pgtype.UUID
	ProviderInstallationID int64
	OwnerKind              string
	OwnerID                pgtype.UUID
}

func (q *Queries) CreatePendingGitHubInstallation(ctx context.Context, arg CreatePendingGitHubInstallationParams) (int64, error) {
	result, err := q.db.Exec(ctx, createPendingGitHubInstallation,
		arg.ID,
		arg.ProviderInstallationID,
		arg.OwnerKind,
		arg.OwnerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disconnectGitHubUserCredentials = `-- name: DisconnectGitHubUserCredentials :execrows
UPDATE realqa_github_connections
SET state = 'disconnected',
    credential_ciphertext = NULL,
    wrapped_data_key = NULL,
    key_id = NULL,
    oauth_state_digest = NULL,
    oauth_state_expires_at = NULL,
    revision = revision + 1,
    updated_at = transaction_timestamp()
WHERE github_user_id = $1
  AND credential_ciphertext IS NOT NULL
`

func (q *Queries) DisconnectGitHubUserCredentials(ctx context.Context, githubUserID pgtype.Int8) (int64, error) {
	result, err := q.db.Exec(ctx, disconnectGitHubUserCredentials, githubUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGitHubInstallationBinding = `-- name: GetGitHubInstallationBinding :one
SELECT owner_kind, owner_id
FROM realqa_github_installations
WHERE provider_installation_id = $1
`

type GetGitHubInstallationBindingRow struct {
	OwnerKind string
	OwnerID   pgtype.UUID
}

func (q *Queries) GetGitHubInstallationBinding(ctx context.Context, providerInstallationID int64) (GetGitHubInstallationBindingRow, error) {
	row := q.db.QueryRow(ctx, getGitHubInstallationBinding, providerInstallationID)
	var i GetGitHubInstallationBindingRow
	err := row.Scan(&i.OwnerKind, &i.OwnerID)
	return i, err
}

const getGitHubUserCredentialForInstallation = `-- name: GetGitHubUserCredentialForInstallation :one
SELECT
    installation.provider_installation_id,
    installation.owner_kind,
    installation.owner_id,
    connection.credential_ciphertext,
    connection.wrapped_data_key,
    connection.key_id
FROM realqa_github_installations AS installation
JOIN realqa_github_connections AS connection
  ON connection.id = installation.connection_id
 AND connection.state = 'connected'
WHERE installation.id = $1
  AND installation.state = 'active'
`

type GetGitHubUserCredentialForInstallationRow struct {
	ProviderInstallationID int64
	OwnerKind              string
	OwnerID                pgtype.UUID
	CredentialCiphertext   []byte
	WrappedDataKey         []byte
	KeyID                  pgtype.Text
}

func (q *Queries) GetGitHubUserCredentialForInstallation(ctx context.Context, installationID pgtype.UUID) (GetGitHubUserCredentialForInstallationRow, error) {
	row := q.db.QueryRow(ctx, getGitHubUserCredentialForInstallation, installationID)
	var i GetGitHubUserCredentialForInstallationRow
	err := row.Scan(
		&i.ProviderInstallationID,
		&i.OwnerKind,
		&i.OwnerID,
		&i.CredentialCiphertext,
		&i.WrappedDataKey,
		&i.KeyID,
	)
	return i, err
}

const markAssetsRemovedForDeletedGitHubIssue = `-- name: MarkAssetsRemovedForDeletedGitHubIssue :execrows
UPDATE realqa_assets AS asset
SET state = 'removed_placeholder',
    object_key_ciphertext = NULL,
    removed_at = COALESCE(asset.removed_at, transaction_timestamp()),
    revision = asset.revision + 1
FROM realqa_submissions AS submission
JOIN realqa_destinations AS destination
  ON destination.id = submission.destination_id
JOIN realqa_github_installations AS installation
  ON installation.id = destination.installation_id
WHERE asset.submission_id = submission.id
  AND installation.provider_installation_id = $1
  AND destination.repository_id = $2
  AND submission.provider_issue_id = $3
  AND asset.state IN ('private_staging', 'verified_unlinked', 'public_retained')
`

type MarkAssetsRemovedForDeletedGitHubIssueParams struct {
	ProviderInstallationID int64
	RepositoryID           string
	ProviderIssueID        pgtype.Text
}

func (q *Queries) MarkAssetsRemovedForDeletedGitHubIssue(ctx context.Context, arg MarkAssetsRemovedForDeletedGitHubIssueParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAssetsRemovedForDeletedGitHubIssue, arg.ProviderInstallationID, arg.RepositoryID, arg.ProviderIssueID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordGitHubWebhookDelivery = `-- name: RecordGitHubWebhookDelivery :execrows
INSERT INTO realqa_github_webhook_deliveries (delivery_id)
VALUES ($1)
ON CONFLICT (delivery_id) DO NOTHING
`

func (q *Queries) RecordGitHubWebhookDelivery(ctx context.Context, deliveryID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, recordGitHubWebhookDelivery, deliveryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeGitHubRepositoryAccess = `-- name: RemoveGitHubRepositoryAccess :execrows
DELETE FROM realqa_repository_access
WHERE installation_id = (
    SELECT id
    FROM realqa_github_installations
    WHERE provider_installation_id = $1
)
AND repository_id = $2
`

type RemoveGitHubRepositoryAccessParams struct {
	ProviderInstallationID int64
	RepositoryID           string
}

func (q *Queries) RemoveGitHubRepositoryAccess(ctx context.Context, arg RemoveGitHubRepositoryAccessParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeGitHubRepositoryAccess, arg.ProviderInstallationID, arg.RepositoryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeGitHubRepositoryDefinitions = `-- name: RemoveGitHubRepositoryDefinitions :execrows
DELETE FROM realqa_repository_definitions
WHERE installation_id = (
    SELECT id
    FROM realqa_github_installations
    WHERE provider_installation_id = $1
)
AND repository_id = $2
`

type RemoveGitHubRepositoryDefinitionsParams struct {
	ProviderInstallationID int64
	RepositoryID           string
}

func (q *Queries) RemoveGitHubRepositoryDefinitions(ctx context.Context, arg RemoveGitHubRepositoryDefinitionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeGitHubRepositoryDefinitions, arg.ProviderInstallationID, arg.RepositoryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setGitHubInstallationState = `-- name: SetGitHubInstallationState :execrows
UPDATE realqa_github_installations
SET state = $1,
    revision = revision + 1,
    updated_at = transaction_timestamp()
WHERE provider_installation_id = $2
`

type SetGitHubInstallationStateParams struct {
	State                  string
	ProviderInstallationID int64
}

func (q *Queries) SetGitHubInstallationState(ctx context.Context, arg SetGitHubInstallationStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, setGitHubInstallationState, arg.State, arg.ProviderInstallationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
