// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: preset.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPresetsForOwner = `-- name: CountPresetsForOwner :one
SELECT count(*)::bigint
FROM realqa_presets
WHERE owner_kind = $1
  AND owner_id = $2
`

type CountPresetsForOwnerParams struct {
	OwnerKind string
	OwnerID   pgtype.UUID
}

func (q *Queries) CountPresetsForOwner(ctx context.Context, arg CountPresetsForOwnerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPresetsForOwner, arg.OwnerKind, arg.OwnerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createIdempotencyRecord = `-- name: CreateIdempotencyRecord :one
INSERT INTO realqa_idempotency_records (
    id, caller_kind, caller_digest, operation,
    idempotency_key, request_digest, resource_id, response_payload
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, $8
)
RETURNING id, caller_kind, caller_digest, operation, idempotency_key, request_digest, resource_id, response_payload, completed_at
`

type CreateIdempotencyRecordParams struct {
	ID              pgtype.UUID
	CallerKind      string
	CallerDigest    []byte
	Operation       string
	IdempotencyKey  pgtype.UUID
	RequestDigest   []byte
	ResourceID      pgtype.UUID
	ResponsePayload []byte
}

func (q *Queries) CreateIdempotencyRecord(ctx context.Context, arg CreateIdempotencyRecordParams) (RealqaIdempotencyRecord, error) {
	row := q.db.QueryRow(ctx, createIdempotencyRecord,
		arg.ID,
		arg.CallerKind,
		arg.CallerDigest,
		arg.Operation,
		arg.IdempotencyKey,
		arg.RequestDigest,
		arg.ResourceID,
		arg.ResponsePayload,
	)
	var i RealqaIdempotencyRecord
	err := row.Scan(
		&i.ID,
		&i.CallerKind,
		&i.CallerDigest,
		&i.Operation,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.ResourceID,
		&i.ResponsePayload,
		&i.CompletedAt,
	)
	return i, err
}

const createPreset = `-- name: CreatePreset :one
INSERT INTO realqa_presets (
    id, owner_kind, owner_id, created_by_account_id,
    payer_organization_id, payer_team_id, destination_id,
    name, capture_mode, include_pointer, selector_mode,
    issue_definition_kind, issue_definition_id, issue_definition_name,
    issue_definition_path, issue_definition_etag,
    default_labels, default_assignees, milestone_number, project_node_ids
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, $8,
    $9, $10, $11,
    $12, $13,
    $14, $15,
    $16, $17,
    $18, $19,
    $20
)
RETURNING id, owner_kind, owner_id, created_by_account_id, payer_organization_id, payer_team_id, destination_id, name, capture_mode, include_pointer, selector_mode, issue_definition_kind, issue_definition_id, issue_definition_name, issue_definition_path, issue_definition_etag, default_labels, default_assignees, milestone_number, project_node_ids, revision, created_at, updated_at
`

type CreatePresetParams struct {
	ID                  pgtype.UUID
	OwnerKind           string
	OwnerID             pgtype.UUID
	CreatedByAccountID  pgtype.UUID
	PayerOrganizationID pgtype.UUID
	PayerTeamID         pgtype.UUID
	DestinationID       pgtype.UUID
	Name                string
	CaptureMode         string
	IncludePointer      bool
	SelectorMode        string
	IssueDefinitionKind string
	IssueDefinitionID   string
	IssueDefinitionName string
	IssueDefinitionPath string
	IssueDefinitionEtag string
	DefaultLabels       []string
	DefaultAssignees    []string
	MilestoneNumber     pgtype.Int8
	ProjectNodeIds      []string
}

func (q *Queries) CreatePreset(ctx context.Context, arg CreatePresetParams) (RealqaPreset, error) {
	row := q.db.QueryRow(ctx, createPreset,
		arg.ID,
		arg.OwnerKind,
		arg.OwnerID,
		arg.CreatedByAccountID,
		arg.PayerOrganizationID,
		arg.PayerTeamID,
		arg.DestinationID,
		arg.Name,
		arg.CaptureMode,
		arg.IncludePointer,
		arg.SelectorMode,
		arg.IssueDefinitionKind,
		arg.IssueDefinitionID,
		arg.IssueDefinitionName,
		arg.IssueDefinitionPath,
		arg.IssueDefinitionEtag,
		arg.DefaultLabels,
		arg.DefaultAssignees,
		arg.MilestoneNumber,
		arg.ProjectNodeIds,
	)
	var i RealqaPreset
	err := row.Scan(
		&i.ID,
		&i.OwnerKind,
		&i.OwnerID,
		&i.CreatedByAccountID,
		&i.PayerOrganizationID,
		&i.PayerTeamID,
		&i.DestinationID,
		&i.Name,
		&i.CaptureMode,
		&i.IncludePointer,
		&i.SelectorMode,
		&i.IssueDefinitionKind,
		&i.IssueDefinitionID,
		&i.IssueDefinitionName,
		&i.IssueDefinitionPath,
		&i.IssueDefinitionEtag,
		&i.DefaultLabels,
		&i.DefaultAssignees,
		&i.MilestoneNumber,
		&i.ProjectNodeIds,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProcessURLRule = `-- name: CreateProcessURLRule :exec
INSERT INTO realqa_process_url_rules (
    id, preset_id, ordinal, exact_process_name,
    safe_window_title_pattern, url_template, enabled
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7
)
`

type CreateProcessURLRuleParams struct {
	ID                     pgtype.UUID
	PresetID               pgtype.UUID
	Ordinal                int32
	ExactProcessName       string
	SafeWindowTitlePattern string
	UrlTemplate            string
	Enabled                bool
}

func (q *Queries) CreateProcessURLRule(ctx context.Context, arg CreateProcessURLRuleParams) error {
	_, err := q.db.Exec(ctx, createProcessURLRule,
		arg.ID,
		arg.PresetID,
		arg.Ordinal,
		arg.ExactProcessName,
		arg.SafeWindowTitlePattern,
		arg.UrlTemplate,
		arg.Enabled,
	)
	return err
}

const createShortcut = `-- name: CreateShortcut :exec
INSERT INTO realqa_shortcuts (id, preset_id, accelerator, active)
VALUES (
    $1, $2,
    $3, $4
)
`

type CreateShortcutParams struct {
	ID          pgtype.UUID
	PresetID    pgtype.UUID
	Accelerator string
	Active      bool
}

func (q *Queries) CreateShortcut(ctx context.Context, arg CreateShortcutParams) error {
	_, err := q.db.Exec(ctx, createShortcut,
		arg.ID,
		arg.PresetID,
		arg.Accelerator,
		arg.Active,
	)
	return err
}

const deletePresetAtRevision = `-- name: DeletePresetAtRevision :one
DELETE FROM realqa_presets
WHERE id = $1
  AND revision = $2
RETURNING (revision + 1)::bigint AS deleted_revision
`

type DeletePresetAtRevisionParams struct {
	ID               pgtype.UUID
	ExpectedRevision int64
}

func (q *Queries) DeletePresetAtRevision(ctx context.Context, arg DeletePresetAtRevisionParams) (int64, error) {
	row := q.db.QueryRow(ctx, deletePresetAtRevision, arg.ID, arg.ExpectedRevision)
	var deleted_revision int64
	err := row.Scan(&deleted_revision)
	return deleted_revision, err
}

const deleteProcessURLRules = `-- name: DeleteProcessURLRules :exec
DELETE FROM realqa_process_url_rules WHERE preset_id = $1
`

func (q *Queries) DeleteProcessURLRules(ctx context.Context, presetID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProcessURLRules, presetID)
	return err
}

const deleteShortcut = `-- name: DeleteShortcut :exec
DELETE FROM realqa_shortcuts WHERE preset_id = $1
`

func (q *Queries) DeleteShortcut(ctx context.Context, presetID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteShortcut, presetID)
	return err
}

const getIdempotencyRecord = `-- name: GetIdempotencyRecord :one
SELECT id, caller_kind, caller_digest, operation, idempotency_key, request_digest, resource_id, response_payload, completed_at
FROM realqa_idempotency_records
WHERE caller_kind = $1
  AND caller_digest = $2
  AND operation = $3
  AND idempotency_key = $4
`

type GetIdempotencyRecordParams struct {
	CallerKind     string
	CallerDigest   []byte
	Operation      string
	IdempotencyKey pgtype.UUID
}

func (q *Queries) GetIdempotencyRecord(ctx context.Context, arg GetIdempotencyRecordParams) (RealqaIdempotencyRecord, error) {
	row := q.db.QueryRow(ctx, getIdempotencyRecord,
		arg.CallerKind,
		arg.CallerDigest,
		arg.Operation,
		arg.IdempotencyKey,
	)
	var i RealqaIdempotencyRecord
	err := row.Scan(
		&i.ID,
		&i.CallerKind,
		&i.CallerDigest,
		&i.Operation,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.ResourceID,
		&i.ResponsePayload,
		&i.CompletedAt,
	)
	return i, err
}

const getPresetRecord = `-- name: GetPresetRecord :one
SELECT
    preset.id, preset.owner_kind, preset.owner_id, preset.created_by_account_id, preset.payer_organization_id, preset.payer_team_id, preset.destination_id, preset.name, preset.capture_mode, preset.include_pointer, preset.selector_mode, preset.issue_definition_kind, preset.issue_definition_id, preset.issue_definition_name, preset.issue_definition_path, preset.issue_definition_etag, preset.default_labels, preset.default_assignees, preset.milestone_number, preset.project_node_ids, preset.revision, preset.created_at, preset.updated_at,
    destination.installation_id,
    destination.repository_id,
    destination.repository_owner,
    destination.repository_name,
    shortcut.id AS shortcut_id,
    shortcut.accelerator,
    shortcut.active AS shortcut_active
FROM realqa_presets AS preset
JOIN realqa_destinations AS destination ON destination.id = preset.destination_id
LEFT JOIN realqa_shortcuts AS shortcut ON shortcut.preset_id = preset.id
WHERE preset.id = $1
`

type GetPresetRecordRow struct {
	ID                  pgtype.UUID
	OwnerKind           string
	OwnerID             pgtype.UUID
	CreatedByAccountID  pgtype.UUID
	PayerOrganizationID pgtype.UUID
	PayerTeamID         pgtype.UUID
	DestinationID       pgtype.UUID
	Name                string
	CaptureMode         string
	IncludePointer      bool
	SelectorMode        string
	IssueDefinitionKind string
	IssueDefinitionID   string
	IssueDefinitionName string
	IssueDefinitionPath string
	IssueDefinitionEtag string
	DefaultLabels       []string
	DefaultAssignees    []string
	MilestoneNumber     pgtype.Int8
	ProjectNodeIds      []string
	Revision            int64
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	InstallationID      pgtype.UUID
	RepositoryID        string
	RepositoryOwner     string
	RepositoryName      string
	ShortcutID          pgtype.UUID
	Accelerator         pgtype.Text
	ShortcutActive      pgtype.Bool
}

func (q *Queries) GetPresetRecord(ctx context.Context, id pgtype.UUID) (GetPresetRecordRow, error) {
	row := q.db.QueryRow(ctx, getPresetRecord, id)
	var i GetPresetRecordRow
	err := row.Scan(
		&i.ID,
		&i.OwnerKind,
		&i.OwnerID,
		&i.CreatedByAccountID,
		&i.PayerOrganizationID,
		&i.PayerTeamID,
		&i.DestinationID,
		&i.Name,
		&i.CaptureMode,
		&i.IncludePointer,
		&i.SelectorMode,
		&i.IssueDefinitionKind,
		&i.IssueDefinitionID,
		&i.IssueDefinitionName,
		&i.IssueDefinitionPath,
		&i.IssueDefinitionEtag,
		&i.DefaultLabels,
		&i.DefaultAssignees,
		&i.MilestoneNumber,
		&i.ProjectNodeIds,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstallationID,
		&i.RepositoryID,
		&i.RepositoryOwner,
		&i.RepositoryName,
		&i.ShortcutID,
		&i.Accelerator,
		&i.ShortcutActive,
	)
	return i, err
}

const listPresetRecords = `-- name: ListPresetRecords :many
SELECT
    preset.id, preset.owner_kind, preset.owner_id, preset.created_by_account_id, preset.payer_organization_id, preset.payer_team_id, preset.destination_id, preset.name, preset.capture_mode, preset.include_pointer, preset.selector_mode, preset.issue_definition_kind, preset.issue_definition_id, preset.issue_definition_name, preset.issue_definition_path, preset.issue_definition_etag, preset.default_labels, preset.default_assignees, preset.milestone_number, preset.project_node_ids, preset.revision, preset.created_at, preset.updated_at,
    destination.installation_id,
    destination.repository_id,
    destination.repository_owner,
    destination.repository_name,
    shortcut.id AS shortcut_id,
    shortcut.accelerator,
    shortcut.active AS shortcut_active
FROM realqa_presets AS preset
JOIN realqa_destinations AS destination ON destination.id = preset.destination_id
LEFT JOIN realqa_shortcuts AS shortcut ON shortcut.preset_id = preset.id
WHERE preset.owner_kind = $1
  AND preset.owner_id = $2
  AND preset.id > $3
ORDER BY preset.id
LIMIT $4
`

type ListPresetRecordsParams struct {
	OwnerKind string
	OwnerID   pgtype.UUID
	AfterID   pgtype.UUID
	PageLimit int32
}

type ListPresetRecordsRow struct {
	ID                  pgtype.UUID
	OwnerKind           string
	OwnerID             pgtype.UUID
	CreatedByAccountID  pgtype.UUID
	PayerOrganizationID pgtype.UUID
	PayerTeamID         pgtype.UUID
	DestinationID       pgtype.UUID
	Name                string
	CaptureMode         string
	IncludePointer      bool
	SelectorMode        string
	IssueDefinitionKind string
	IssueDefinitionID   string
	IssueDefinitionName string
	IssueDefinitionPath string
	IssueDefinitionEtag string
	DefaultLabels       []string
	DefaultAssignees    []string
	MilestoneNumber     pgtype.Int8
	ProjectNodeIds      []string
	Revision            int64
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	InstallationID      pgtype.UUID
	RepositoryID        string
	RepositoryOwner     string
	RepositoryName      string
	ShortcutID          pgtype.UUID
	Accelerator         pgtype.Text
	ShortcutActive      pgtype.Bool
}

func (q *Queries) ListPresetRecords(ctx context.Context, arg ListPresetRecordsParams) ([]ListPresetRecordsRow, error) {
	rows, err := q.db.Query(ctx, listPresetRecords,
		arg.OwnerKind,
		arg.OwnerID,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPresetRecordsRow{}
	for rows.Next() {
		var i ListPresetRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerKind,
			&i.OwnerID,
			&i.CreatedByAccountID,
			&i.PayerOrganizationID,
			&i.PayerTeamID,
			&i.DestinationID,
			&i.Name,
			&i.CaptureMode,
			&i.IncludePointer,
			&i.SelectorMode,
			&i.IssueDefinitionKind,
			&i.IssueDefinitionID,
			&i.IssueDefinitionName,
			&i.IssueDefinitionPath,
			&i.IssueDefinitionEtag,
			&i.DefaultLabels,
			&i.DefaultAssignees,
			&i.MilestoneNumber,
			&i.ProjectNodeIds,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InstallationID,
			&i.RepositoryID,
			&i.RepositoryOwner,
			&i.RepositoryName,
			&i.ShortcutID,
			&i.Accelerator,
			&i.ShortcutActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProcessURLRules = `-- name: ListProcessURLRules :many
SELECT id, preset_id, ordinal, exact_process_name, safe_window_title_pattern, url_template, enabled
FROM realqa_process_url_rules
WHERE preset_id = $1
ORDER BY ordinal
`

func (q *Queries) ListProcessURLRules(ctx context.Context, presetID pgtype.UUID) ([]RealqaProcessUrlRule, error) {
	rows, err := q.db.Query(ctx, listProcessURLRules, presetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RealqaProcessUrlRule{}
	for rows.Next() {
		var i RealqaProcessUrlRule
		if err := rows.Scan(
			&i.ID,
			&i.PresetID,
			&i.Ordinal,
			&i.ExactProcessName,
			&i.SafeWindowTitlePattern,
			&i.UrlTemplate,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPreset = `-- name: LockPreset :one
SELECT id, owner_kind, owner_id, created_by_account_id, payer_organization_id, payer_team_id, destination_id, name, capture_mode, include_pointer, selector_mode, issue_definition_kind, issue_definition_id, issue_definition_name, issue_definition_path, issue_definition_etag, default_labels, default_assignees, milestone_number, project_node_ids, revision, created_at, updated_at
FROM realqa_presets
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockPreset(ctx context.Context, id pgtype.UUID) (RealqaPreset, error) {
	row := q.db.QueryRow(ctx, lockPreset, id)
	var i RealqaPreset
	err := row.Scan(
		&i.ID,
		&i.OwnerKind,
		&i.OwnerID,
		&i.CreatedByAccountID,
		&i.PayerOrganizationID,
		&i.PayerTeamID,
		&i.DestinationID,
		&i.Name,
		&i.CaptureMode,
		&i.IncludePointer,
		&i.SelectorMode,
		&i.IssueDefinitionKind,
		&i.IssueDefinitionID,
		&i.IssueDefinitionName,
		&i.IssueDefinitionPath,
		&i.IssueDefinitionEtag,
		&i.DefaultLabels,
		&i.DefaultAssignees,
		&i.MilestoneNumber,
		&i.ProjectNodeIds,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockPresetOwner = `-- name: LockPresetOwner :exec
SELECT pg_advisory_xact_lock(
    hashtextextended(
        $1::text || ':' || $2::uuid::text,
        757
    )
)
`

type LockPresetOwnerParams struct {
	OwnerKind string
	OwnerID   pgtype.UUID
}

func (q *Queries) LockPresetOwner(ctx context.Context, arg LockPresetOwnerParams) error {
	_, err := q.db.Exec(ctx, lockPresetOwner, arg.OwnerKind, arg.OwnerID)
	return err
}

const updatePreset = `-- name: UpdatePreset :one
UPDATE realqa_presets
SET payer_organization_id = $1,
    payer_team_id = $2,
    destination_id = $3,
    name = $4,
    capture_mode = $5,
    include_pointer = $6,
    selector_mode = $7,
    issue_definition_kind = $8,
    issue_definition_id = $9,
    issue_definition_name = $10,
    issue_definition_path = $11,
    issue_definition_etag = $12,
    default_labels = $13,
    default_assignees = $14,
    milestone_number = $15,
    project_node_ids = $16,
    revision = revision + 1,
    updated_at = transaction_timestamp()
WHERE id = $17
  AND revision = $18
RETURNING id, owner_kind, owner_id, created_by_account_id, payer_organization_id, payer_team_id, destination_id, name, capture_mode, include_pointer, selector_mode, issue_definition_kind, issue_definition_id, issue_definition_name, issue_definition_path, issue_definition_etag, default_labels, default_assignees, milestone_number, project_node_ids, revision, created_at, updated_at
`

type UpdatePresetParams struct {
	PayerOrganizationID pgtype.UUID
	PayerTeamID         pgtype.UUID
	DestinationID       pgtype.UUID
	Name                string
	CaptureMode         string
	IncludePointer      bool
	SelectorMode        string
	IssueDefinitionKind string
	IssueDefinitionID   string
	IssueDefinitionName string
	IssueDefinitionPath string
	IssueDefinitionEtag string
	DefaultLabels       []string
	DefaultAssignees    []string
	MilestoneNumber     pgtype.Int8
	ProjectNodeIds      []string
	ID                  pgtype.UUID
	ExpectedRevision    int64
}

func (q *Queries) UpdatePreset(ctx context.Context, arg UpdatePresetParams) (RealqaPreset, error) {
	row := q.db.QueryRow(ctx, updatePreset,
		arg.PayerOrganizationID,
		arg.PayerTeamID,
		arg.DestinationID,
		arg.Name,
		arg.CaptureMode,
		arg.IncludePointer,
		arg.SelectorMode,
		arg.IssueDefinitionKind,
		arg.IssueDefinitionID,
		arg.IssueDefinitionName,
		arg.IssueDefinitionPath,
		arg.IssueDefinitionEtag,
		arg.DefaultLabels,
		arg.DefaultAssignees,
		arg.MilestoneNumber,
		arg.ProjectNodeIds,
		arg.ID,
		arg.ExpectedRevision,
	)
	var i RealqaPreset
	err := row.Scan(
		&i.ID,
		&i.OwnerKind,
		&i.OwnerID,
		&i.CreatedByAccountID,
		&i.PayerOrganizationID,
		&i.PayerTeamID,
		&i.DestinationID,
		&i.Name,
		&i.CaptureMode,
		&i.IncludePointer,
		&i.SelectorMode,
		&i.IssueDefinitionKind,
		&i.IssueDefinitionID,
		&i.IssueDefinitionName,
		&i.IssueDefinitionPath,
		&i.IssueDefinitionEtag,
		&i.DefaultLabels,
		&i.DefaultAssignees,
		&i.MilestoneNumber,
		&i.ProjectNodeIds,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDestination = `-- name: UpsertDestination :one
INSERT INTO realqa_destinations (
    id, owner_kind, owner_id, installation_id,
    repository_id, repository_owner, repository_name
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7
)
ON CONFLICT (owner_kind, owner_id, installation_id, repository_id)
DO UPDATE SET repository_owner = EXCLUDED.repository_owner,
              repository_name = EXCLUDED.repository_name
RETURNING id, owner_kind, owner_id, installation_id, repository_id, repository_owner, repository_name, created_at
`

type UpsertDestinationParams struct {
	ID              pgtype.UUID
	OwnerKind       string
	OwnerID         pgtype.UUID
	InstallationID  pgtype.UUID
	RepositoryID    string
	RepositoryOwner string
	RepositoryName  string
}

func (q *Queries) UpsertDestination(ctx context.Context, arg UpsertDestinationParams) (RealqaDestination, error) {
	row := q.db.QueryRow(ctx, upsertDestination,
		arg.ID,
		arg.OwnerKind,
		arg.OwnerID,
		arg.InstallationID,
		arg.RepositoryID,
		arg.RepositoryOwner,
		arg.RepositoryName,
	)
	var i RealqaDestination
	err := row.Scan(
		&i.ID,
		&i.OwnerKind,
		&i.OwnerID,
		&i.InstallationID,
		&i.RepositoryID,
		&i.RepositoryOwner,
		&i.RepositoryName,
		&i.CreatedAt,
	)
	return i, err
}

const upsertShortcut = `-- name: UpsertShortcut :exec
INSERT INTO realqa_shortcuts (id, preset_id, accelerator, active)
VALUES ($1, $2, $3, $4)
ON CONFLICT (preset_id)
DO UPDATE SET id = EXCLUDED.id,
              accelerator = EXCLUDED.accelerator,
              active = EXCLUDED.active
`

type UpsertShortcutParams struct {
	ID          pgtype.UUID
	PresetID    pgtype.UUID
	Accelerator string
	Active      bool
}

func (q *Queries) UpsertShortcut(ctx context.Context, arg UpsertShortcutParams) error {
	_, err := q.db.Exec(ctx, upsertShortcut,
		arg.ID,
		arg.PresetID,
		arg.Accelerator,
		arg.Active,
	)
	return err
}
