// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountActiveShortcutsForAccount(ctx context.Context, accountID pgtype.UUID) (int64, error)
	CountOtherActiveShortcutsForAccount(ctx context.Context, arg CountOtherActiveShortcutsForAccountParams) (int64, error)
	CountPresetsForOwner(ctx context.Context, arg CountPresetsForOwnerParams) (int64, error)
	CreateIdempotencyRecord(ctx context.Context, arg CreateIdempotencyRecordParams) (RealqaIdempotencyRecord, error)
	CreatePreset(ctx context.Context, arg CreatePresetParams) (RealqaPreset, error)
	CreateProcessURLRule(ctx context.Context, arg CreateProcessURLRuleParams) error
	CreateShortcut(ctx context.Context, arg CreateShortcutParams) error
	DeleteLifecycleAccountIdentity(ctx context.Context, accountID pgtype.UUID) (int64, error)
	DeletePresetAtRevision(ctx context.Context, arg DeletePresetAtRevisionParams) (int64, error)
	DeleteProcessURLRules(ctx context.Context, presetID pgtype.UUID) error
	DeleteScopeConnections(ctx context.Context, arg DeleteScopeConnectionsParams) (int64, error)
	DeleteScopeDestinations(ctx context.Context, arg DeleteScopeDestinationsParams) (int64, error)
	DeleteScopeIdempotencySnapshots(ctx context.Context, arg DeleteScopeIdempotencySnapshotsParams) (int64, error)
	DeleteScopePresets(ctx context.Context, arg DeleteScopePresetsParams) (int64, error)
	DeleteScopeSubmissions(ctx context.Context, arg DeleteScopeSubmissionsParams) (int64, error)
	DeleteShortcut(ctx context.Context, presetID pgtype.UUID) error
	DisconnectGitHubConnection(ctx context.Context, arg DisconnectGitHubConnectionParams) (RealqaGithubConnection, error)
	GetDeletionJob(ctx context.Context, arg GetDeletionJobParams) (RealqaDeletionJob, error)
	GetGitHubConnectionForOwner(ctx context.Context, arg GetGitHubConnectionForOwnerParams) (RealqaGithubConnection, error)
	GetGitHubInstallation(ctx context.Context, id pgtype.UUID) (RealqaGithubInstallation, error)
	GetIdempotencyRecord(ctx context.Context, arg GetIdempotencyRecordParams) (RealqaIdempotencyRecord, error)
	GetIdentityBySubjectDigest(ctx context.Context, subjectDigest []byte) (RealqaIdentity, error)
	GetOwnerAccess(ctx context.Context, arg GetOwnerAccessParams) (RealqaOwnerBinding, error)
	GetPresetRecord(ctx context.Context, id pgtype.UUID) (GetPresetRecordRow, error)
	GetRepositorySubmitAccessForOwner(ctx context.Context, arg GetRepositorySubmitAccessForOwnerParams) (RealqaRepositoryAccess, error)
	HasPayerTeamAccess(ctx context.Context, arg HasPayerTeamAccessParams) (bool, error)
	HasRepositorySubmitAccess(ctx context.Context, arg HasRepositorySubmitAccessParams) (bool, error)
	InsertAudit(ctx context.Context, arg InsertAuditParams) error
	InsertDeletionJob(ctx context.Context, arg InsertDeletionJobParams) (RealqaDeletionJob, error)
	InsertScopeTombstone(ctx context.Context, arg InsertScopeTombstoneParams) error
	ListAccessibleRepositories(ctx context.Context, arg ListAccessibleRepositoriesParams) ([]RealqaRepositoryAccess, error)
	ListGitHubInstallations(ctx context.Context, arg ListGitHubInstallationsParams) ([]RealqaGithubInstallation, error)
	ListPresetRecords(ctx context.Context, arg ListPresetRecordsParams) ([]ListPresetRecordsRow, error)
	ListProcessURLRules(ctx context.Context, presetID pgtype.UUID) ([]RealqaProcessUrlRule, error)
	ListRepositoryDefinitions(ctx context.Context, arg ListRepositoryDefinitionsParams) ([]RealqaRepositoryDefinition, error)
	LockPreset(ctx context.Context, id pgtype.UUID) (RealqaPreset, error)
	LockPresetOwner(ctx context.Context, arg LockPresetOwnerParams) error
	LockShortcutAccount(ctx context.Context, accountID pgtype.UUID) error
	Ping(ctx context.Context) (int64, error)
	StartGitHubConnection(ctx context.Context, arg StartGitHubConnectionParams) (RealqaGithubConnection, error)
	TombstoneLifecycleAccountIdentity(ctx context.Context, accountID pgtype.UUID) (int64, error)
	UpdatePreset(ctx context.Context, arg UpdatePresetParams) (RealqaPreset, error)
	UpsertDestination(ctx context.Context, arg UpsertDestinationParams) (RealqaDestination, error)
	UpsertShortcut(ctx context.Context, arg UpsertShortcutParams) error
}

var _ Querier = (*Queries)(nil)
