// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: submission.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const authorizeAssetUpload = `-- name: AuthorizeAssetUpload :one
UPDATE realqa_assets
SET upload_state = 'put_authorized',
    upload_token_digest = $1,
    upload_expires_at = $2,
    revision = revision + 1
WHERE id = $3
  AND submission_id = $4
  AND revision = $5
  AND upload_state IN ('declared', 'put_authorized')
RETURNING id, submission_id, public_id, object_key_ciphertext, state, encoded_bytes, revision, created_at, removed_at, client_image_id, media_type, declared_encoded_bytes, pixel_width, pixel_height, source_sha256, sanitized_sha256, upload_state, upload_token_digest, upload_expires_at, uploaded_at, verified_at
`

type AuthorizeAssetUploadParams struct {
	UploadTokenDigest []byte
	UploadExpiresAt   pgtype.Timestamptz
	ID                pgtype.UUID
	SubmissionID      pgtype.UUID
	ExpectedRevision  int64
}

func (q *Queries) AuthorizeAssetUpload(ctx context.Context, arg AuthorizeAssetUploadParams) (RealqaAsset, error) {
	row := q.db.QueryRow(ctx, authorizeAssetUpload,
		arg.UploadTokenDigest,
		arg.UploadExpiresAt,
		arg.ID,
		arg.SubmissionID,
		arg.ExpectedRevision,
	)
	var i RealqaAsset
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.PublicID,
		&i.ObjectKeyCiphertext,
		&i.State,
		&i.EncodedBytes,
		&i.Revision,
		&i.CreatedAt,
		&i.RemovedAt,
		&i.ClientImageID,
		&i.MediaType,
		&i.DeclaredEncodedBytes,
		&i.PixelWidth,
		&i.PixelHeight,
		&i.SourceSha256,
		&i.SanitizedSha256,
		&i.UploadState,
		&i.UploadTokenDigest,
		&i.UploadExpiresAt,
		&i.UploadedAt,
		&i.VerifiedAt,
	)
	return i, err
}

const completeObjectDeletion = `-- name: CompleteObjectDeletion :exec
DELETE FROM realqa_object_deletion_jobs
WHERE asset_id = $1
  AND object_kind = $2
  AND public_id IS NOT DISTINCT FROM $3
`

type CompleteObjectDeletionParams struct {
	AssetID    pgtype.UUID
	ObjectKind string
	PublicID   pgtype.Text
}

func (q *Queries) CompleteObjectDeletion(ctx context.Context, arg CompleteObjectDeletionParams) error {
	_, err := q.db.Exec(ctx, completeObjectDeletion, arg.AssetID, arg.ObjectKind, arg.PublicID)
	return err
}

const countOpenSubmissionsForAccount = `-- name: CountOpenSubmissionsForAccount :one
SELECT count(*)::bigint
FROM realqa_submissions
WHERE created_by_account_id = $1
  AND state IN ('draft', 'uploading', 'ready')
  AND upload_expires_at > transaction_timestamp()
`

func (q *Queries) CountOpenSubmissionsForAccount(ctx context.Context, accountID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenSubmissionsForAccount, accountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countRecentSubmissionsForAccount = `-- name: CountRecentSubmissionsForAccount :one
SELECT count(*)::bigint
FROM realqa_submissions
WHERE created_by_account_id = $1
  AND created_at >= transaction_timestamp() - interval '1 hour'
`

func (q *Queries) CountRecentSubmissionsForAccount(ctx context.Context, accountID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentSubmissionsForAccount, accountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createAssetRecord = `-- name: CreateAssetRecord :one
INSERT INTO realqa_assets (
    id, submission_id, client_image_id, media_type,
    declared_encoded_bytes, pixel_width, pixel_height, source_sha256,
    upload_state, state, encoded_bytes
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, $8,
    'declared', 'private_staging', 0
)
RETURNING id, submission_id, public_id, object_key_ciphertext, state, encoded_bytes, revision, created_at, removed_at, client_image_id, media_type, declared_encoded_bytes, pixel_width, pixel_height, source_sha256, sanitized_sha256, upload_state, upload_token_digest, upload_expires_at, uploaded_at, verified_at
`

type CreateAssetRecordParams struct {
	ID                   pgtype.UUID
	SubmissionID         pgtype.UUID
	ClientImageID        pgtype.UUID
	MediaType            string
	DeclaredEncodedBytes int64
	PixelWidth           int32
	PixelHeight          int32
	SourceSha256         []byte
}

func (q *Queries) CreateAssetRecord(ctx context.Context, arg CreateAssetRecordParams) (RealqaAsset, error) {
	row := q.db.QueryRow(ctx, createAssetRecord,
		arg.ID,
		arg.SubmissionID,
		arg.ClientImageID,
		arg.MediaType,
		arg.DeclaredEncodedBytes,
		arg.PixelWidth,
		arg.PixelHeight,
		arg.SourceSha256,
	)
	var i RealqaAsset
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.PublicID,
		&i.ObjectKeyCiphertext,
		&i.State,
		&i.EncodedBytes,
		&i.Revision,
		&i.CreatedAt,
		&i.RemovedAt,
		&i.ClientImageID,
		&i.MediaType,
		&i.DeclaredEncodedBytes,
		&i.PixelWidth,
		&i.PixelHeight,
		&i.SourceSha256,
		&i.SanitizedSha256,
		&i.UploadState,
		&i.UploadTokenDigest,
		&i.UploadExpiresAt,
		&i.UploadedAt,
		&i.VerifiedAt,
	)
	return i, err
}

const createSubmissionRecord = `-- name: CreateSubmissionRecord :one
INSERT INTO realqa_submissions (
    id, owner_kind, owner_id, created_by_account_id, preset_id,
    destination_id, state, idempotency_digest, payer_organization_id,
    payer_team_id, preset_revision, declared_encoded_bytes,
    upload_deadline, upload_expires_at
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, 'draft', $7,
    $8, $9,
    $10, $11,
    $12, $13
)
RETURNING id, owner_kind, owner_id, created_by_account_id, preset_id, destination_id, state, provider_issue_id, provider_issue_url, idempotency_digest, revision, created_at, updated_at, submitted_at, payer_organization_id, payer_team_id, preset_revision, declared_encoded_bytes, verified_encoded_bytes, upload_deadline, upload_expires_at
`

type CreateSubmissionRecordParams struct {
	ID                   pgtype.UUID
	OwnerKind            string
	OwnerID              pgtype.UUID
	CreatedByAccountID   pgtype.UUID
	PresetID             pgtype.UUID
	DestinationID        pgtype.UUID
	IdempotencyDigest    []byte
	PayerOrganizationID  pgtype.UUID
	PayerTeamID          pgtype.UUID
	PresetRevision       int64
	DeclaredEncodedBytes int64
	UploadDeadline       pgtype.Timestamptz
	UploadExpiresAt      pgtype.Timestamptz
}

func (q *Queries) CreateSubmissionRecord(ctx context.Context, arg CreateSubmissionRecordParams) (RealqaSubmission, error) {
	row := q.db.QueryRow(ctx, createSubmissionRecord,
		arg.ID,
		arg.OwnerKind,
		arg.OwnerID,
		arg.CreatedByAccountID,
		arg.PresetID,
		arg.DestinationID,
		arg.IdempotencyDigest,
		arg.PayerOrganizationID,
		arg.PayerTeamID,
		arg.PresetRevision,
		arg.DeclaredEncodedBytes,
		arg.UploadDeadline,
		arg.UploadExpiresAt,
	)
	var i RealqaSubmission
	err := row.Scan(
		&i.ID,
		&i.OwnerKind,
		&i.OwnerID,
		&i.CreatedByAccountID,
		&i.PresetID,
		&i.DestinationID,
		&i.State,
		&i.ProviderIssueID,
		&i.ProviderIssueUrl,
		&i.IdempotencyDigest,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.PayerOrganizationID,
		&i.PayerTeamID,
		&i.PresetRevision,
		&i.DeclaredEncodedBytes,
		&i.VerifiedEncodedBytes,
		&i.UploadDeadline,
		&i.UploadExpiresAt,
	)
	return i, err
}

const enqueueObjectDeletion = `-- name: EnqueueObjectDeletion :exec
INSERT INTO realqa_object_deletion_jobs (
    asset_id, object_kind, public_id
) VALUES (
    $1, $2, $3
)
ON CONFLICT DO NOTHING
`

type EnqueueObjectDeletionParams struct {
	AssetID    pgtype.UUID
	ObjectKind string
	PublicID   pgtype.Text
}

func (q *Queries) EnqueueObjectDeletion(ctx context.Context, arg EnqueueObjectDeletionParams) error {
	_, err := q.db.Exec(ctx, enqueueObjectDeletion, arg.AssetID, arg.ObjectKind, arg.PublicID)
	return err
}

const expireAsset = `-- name: ExpireAsset :one
UPDATE realqa_assets
SET upload_state = 'expired',
    state = 'expired',
    removed_at = COALESCE(removed_at, transaction_timestamp()),
    upload_token_digest = NULL,
    upload_expires_at = NULL,
    revision = revision + 1
WHERE id = $1
  AND state IN ('private_staging', 'verified_unlinked')
RETURNING id, submission_id, public_id, object_key_ciphertext, state, encoded_bytes, revision, created_at, removed_at, client_image_id, media_type, declared_encoded_bytes, pixel_width, pixel_height, source_sha256, sanitized_sha256, upload_state, upload_token_digest, upload_expires_at, uploaded_at, verified_at
`

func (q *Queries) ExpireAsset(ctx context.Context, id pgtype.UUID) (RealqaAsset, error) {
	row := q.db.QueryRow(ctx, expireAsset, id)
	var i RealqaAsset
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.PublicID,
		&i.ObjectKeyCiphertext,
		&i.State,
		&i.EncodedBytes,
		&i.Revision,
		&i.CreatedAt,
		&i.RemovedAt,
		&i.ClientImageID,
		&i.MediaType,
		&i.DeclaredEncodedBytes,
		&i.PixelWidth,
		&i.PixelHeight,
		&i.SourceSha256,
		&i.SanitizedSha256,
		&i.UploadState,
		&i.UploadTokenDigest,
		&i.UploadExpiresAt,
		&i.UploadedAt,
		&i.VerifiedAt,
	)
	return i, err
}

const getAssetRecord = `-- name: GetAssetRecord :one
SELECT id, submission_id, public_id, object_key_ciphertext, state, encoded_bytes, revision, created_at, removed_at, client_image_id, media_type, declared_encoded_bytes, pixel_width, pixel_height, source_sha256, sanitized_sha256, upload_state, upload_token_digest, upload_expires_at, uploaded_at, verified_at
FROM realqa_assets
WHERE id = $1
  AND submission_id = $2
`

type GetAssetRecordParams struct {
	ID           pgtype.UUID
	SubmissionID pgtype.UUID
}

func (q *Queries) GetAssetRecord(ctx context.Context, arg GetAssetRecordParams) (RealqaAsset, error) {
	row := q.db.QueryRow(ctx, getAssetRecord, arg.ID, arg.SubmissionID)
	var i RealqaAsset
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.PublicID,
		&i.ObjectKeyCiphertext,
		&i.State,
		&i.EncodedBytes,
		&i.Revision,
		&i.CreatedAt,
		&i.RemovedAt,
		&i.ClientImageID,
		&i.MediaType,
		&i.DeclaredEncodedBytes,
		&i.PixelWidth,
		&i.PixelHeight,
		&i.SourceSha256,
		&i.SanitizedSha256,
		&i.UploadState,
		&i.UploadTokenDigest,
		&i.UploadExpiresAt,
		&i.UploadedAt,
		&i.VerifiedAt,
	)
	return i, err
}

const getAssetUploadGrant = `-- name: GetAssetUploadGrant :one
SELECT asset.id, asset.submission_id, asset.public_id, asset.object_key_ciphertext, asset.state, asset.encoded_bytes, asset.revision, asset.created_at, asset.removed_at, asset.client_image_id, asset.media_type, asset.declared_encoded_bytes, asset.pixel_width, asset.pixel_height, asset.source_sha256, asset.sanitized_sha256, asset.upload_state, asset.upload_token_digest, asset.upload_expires_at, asset.uploaded_at, asset.verified_at, submission.upload_deadline
FROM realqa_assets AS asset
JOIN realqa_submissions AS submission ON submission.id = asset.submission_id
WHERE asset.upload_token_digest = $1
  AND asset.upload_state IN ('put_authorized', 'uploaded')
`

type GetAssetUploadGrantRow struct {
	ID                   pgtype.UUID
	SubmissionID         pgtype.UUID
	PublicID             pgtype.Text
	ObjectKeyCiphertext  []byte
	State                string
	EncodedBytes         int64
	Revision             int64
	CreatedAt            pgtype.Timestamptz
	RemovedAt            pgtype.Timestamptz
	ClientImageID        pgtype.UUID
	MediaType            string
	DeclaredEncodedBytes int64
	PixelWidth           int32
	PixelHeight          int32
	SourceSha256         []byte
	SanitizedSha256      []byte
	UploadState          string
	UploadTokenDigest    []byte
	UploadExpiresAt      pgtype.Timestamptz
	UploadedAt           pgtype.Timestamptz
	VerifiedAt           pgtype.Timestamptz
	UploadDeadline       pgtype.Timestamptz
}

func (q *Queries) GetAssetUploadGrant(ctx context.Context, uploadTokenDigest []byte) (GetAssetUploadGrantRow, error) {
	row := q.db.QueryRow(ctx, getAssetUploadGrant, uploadTokenDigest)
	var i GetAssetUploadGrantRow
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.PublicID,
		&i.ObjectKeyCiphertext,
		&i.State,
		&i.EncodedBytes,
		&i.Revision,
		&i.CreatedAt,
		&i.RemovedAt,
		&i.ClientImageID,
		&i.MediaType,
		&i.DeclaredEncodedBytes,
		&i.PixelWidth,
		&i.PixelHeight,
		&i.SourceSha256,
		&i.SanitizedSha256,
		&i.UploadState,
		&i.UploadTokenDigest,
		&i.UploadExpiresAt,
		&i.UploadedAt,
		&i.VerifiedAt,
		&i.UploadDeadline,
	)
	return i, err
}

const getPublicAsset = `-- name: GetPublicAsset :one
SELECT asset.public_id, asset.media_type, asset.state
FROM realqa_assets AS asset
WHERE asset.public_id = $1
UNION ALL
SELECT tombstone.public_id, ''::text AS media_type,
       'removed_placeholder'::text AS state
FROM realqa_public_asset_tombstones AS tombstone
WHERE tombstone.public_id = $1
LIMIT 1
`

type GetPublicAssetRow struct {
	PublicID  pgtype.Text
	MediaType string
	State     string
}

func (q *Queries) GetPublicAsset(ctx context.Context, publicLookupID pgtype.Text) (GetPublicAssetRow, error) {
	row := q.db.QueryRow(ctx, getPublicAsset, publicLookupID)
	var i GetPublicAssetRow
	err := row.Scan(&i.PublicID, &i.MediaType, &i.State)
	return i, err
}

const getSubmissionRecord = `-- name: GetSubmissionRecord :one
SELECT id, owner_kind, owner_id, created_by_account_id, preset_id, destination_id, state, provider_issue_id, provider_issue_url, idempotency_digest, revision, created_at, updated_at, submitted_at, payer_organization_id, payer_team_id, preset_revision, declared_encoded_bytes, verified_encoded_bytes, upload_deadline, upload_expires_at
FROM realqa_submissions
WHERE id = $1
`

func (q *Queries) GetSubmissionRecord(ctx context.Context, id pgtype.UUID) (RealqaSubmission, error) {
	row := q.db.QueryRow(ctx, getSubmissionRecord, id)
	var i RealqaSubmission
	err := row.Scan(
		&i.ID,
		&i.OwnerKind,
		&i.OwnerID,
		&i.CreatedByAccountID,
		&i.PresetID,
		&i.DestinationID,
		&i.State,
		&i.ProviderIssueID,
		&i.ProviderIssueUrl,
		&i.IdempotencyDigest,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.PayerOrganizationID,
		&i.PayerTeamID,
		&i.PresetRevision,
		&i.DeclaredEncodedBytes,
		&i.VerifiedEncodedBytes,
		&i.UploadDeadline,
		&i.UploadExpiresAt,
	)
	return i, err
}

const listExpiredSubmissionAssets = `-- name: ListExpiredSubmissionAssets :many
SELECT asset.id, asset.submission_id, asset.public_id, asset.object_key_ciphertext, asset.state, asset.encoded_bytes, asset.revision, asset.created_at, asset.removed_at, asset.client_image_id, asset.media_type, asset.declared_encoded_bytes, asset.pixel_width, asset.pixel_height, asset.source_sha256, asset.sanitized_sha256, asset.upload_state, asset.upload_token_digest, asset.upload_expires_at, asset.uploaded_at, asset.verified_at
FROM realqa_assets AS asset
JOIN realqa_submissions AS submission ON submission.id = asset.submission_id
WHERE submission.upload_expires_at <= $1
  AND (
    asset.state IN ('private_staging', 'verified_unlinked')
    OR (
      asset.state = 'public_retained'
      AND submission.submitted_at IS NULL
    )
  )
ORDER BY asset.created_at
LIMIT $2
`

type ListExpiredSubmissionAssetsParams struct {
	Cutoff     pgtype.Timestamptz
	BatchLimit int32
}

func (q *Queries) ListExpiredSubmissionAssets(ctx context.Context, arg ListExpiredSubmissionAssetsParams) ([]RealqaAsset, error) {
	rows, err := q.db.Query(ctx, listExpiredSubmissionAssets, arg.Cutoff, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RealqaAsset{}
	for rows.Next() {
		var i RealqaAsset
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.PublicID,
			&i.ObjectKeyCiphertext,
			&i.State,
			&i.EncodedBytes,
			&i.Revision,
			&i.CreatedAt,
			&i.RemovedAt,
			&i.ClientImageID,
			&i.MediaType,
			&i.DeclaredEncodedBytes,
			&i.PixelWidth,
			&i.PixelHeight,
			&i.SourceSha256,
			&i.SanitizedSha256,
			&i.UploadState,
			&i.UploadTokenDigest,
			&i.UploadExpiresAt,
			&i.UploadedAt,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueAssets = `-- name: ListIssueAssets :many
SELECT asset.id, asset.submission_id, asset.public_id, asset.object_key_ciphertext, asset.state, asset.encoded_bytes, asset.revision, asset.created_at, asset.removed_at, asset.client_image_id, asset.media_type, asset.declared_encoded_bytes, asset.pixel_width, asset.pixel_height, asset.source_sha256, asset.sanitized_sha256, asset.upload_state, asset.upload_token_digest, asset.upload_expires_at, asset.uploaded_at, asset.verified_at
FROM realqa_assets AS asset
JOIN realqa_submissions AS submission ON submission.id = asset.submission_id
WHERE submission.provider_issue_id = $1
  AND asset.state NOT IN ('removed_placeholder', 'deleted', 'expired')
FOR UPDATE OF asset
`

func (q *Queries) ListIssueAssets(ctx context.Context, providerIssueID pgtype.Text) ([]RealqaAsset, error) {
	rows, err := q.db.Query(ctx, listIssueAssets, providerIssueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RealqaAsset{}
	for rows.Next() {
		var i RealqaAsset
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.PublicID,
			&i.ObjectKeyCiphertext,
			&i.State,
			&i.EncodedBytes,
			&i.Revision,
			&i.CreatedAt,
			&i.RemovedAt,
			&i.ClientImageID,
			&i.MediaType,
			&i.DeclaredEncodedBytes,
			&i.PixelWidth,
			&i.PixelHeight,
			&i.SourceSha256,
			&i.SanitizedSha256,
			&i.UploadState,
			&i.UploadTokenDigest,
			&i.UploadExpiresAt,
			&i.UploadedAt,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingObjectDeletions = `-- name: ListPendingObjectDeletions :many
SELECT asset_id, object_kind, public_id, attempt_count, next_attempt_at, last_attempted_at, created_at
FROM realqa_object_deletion_jobs
WHERE next_attempt_at <= $1
ORDER BY
    CASE object_kind WHEN 'public' THEN 0 ELSE 1 END,
    next_attempt_at,
    created_at
LIMIT $2
`

type ListPendingObjectDeletionsParams struct {
	Cutoff     pgtype.Timestamptz
	BatchLimit int32
}

func (q *Queries) ListPendingObjectDeletions(ctx context.Context, arg ListPendingObjectDeletionsParams) ([]RealqaObjectDeletionJob, error) {
	rows, err := q.db.Query(ctx, listPendingObjectDeletions, arg.Cutoff, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RealqaObjectDeletionJob{}
	for rows.Next() {
		var i RealqaObjectDeletionJob
		if err := rows.Scan(
			&i.AssetID,
			&i.ObjectKind,
			&i.PublicID,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.LastAttemptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemovableSubmissionAssets = `-- name: ListRemovableSubmissionAssets :many
SELECT id, submission_id, public_id, object_key_ciphertext, state, encoded_bytes, revision, created_at, removed_at, client_image_id, media_type, declared_encoded_bytes, pixel_width, pixel_height, source_sha256, sanitized_sha256, upload_state, upload_token_digest, upload_expires_at, uploaded_at, verified_at
FROM realqa_assets
WHERE submission_id = $1
  AND state NOT IN ('removed_placeholder', 'deleted', 'expired')
ORDER BY id
FOR UPDATE
`

func (q *Queries) ListRemovableSubmissionAssets(ctx context.Context, submissionID pgtype.UUID) ([]RealqaAsset, error) {
	rows, err := q.db.Query(ctx, listRemovableSubmissionAssets, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RealqaAsset{}
	for rows.Next() {
		var i RealqaAsset
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.PublicID,
			&i.ObjectKeyCiphertext,
			&i.State,
			&i.EncodedBytes,
			&i.Revision,
			&i.CreatedAt,
			&i.RemovedAt,
			&i.ClientImageID,
			&i.MediaType,
			&i.DeclaredEncodedBytes,
			&i.PixelWidth,
			&i.PixelHeight,
			&i.SourceSha256,
			&i.SanitizedSha256,
			&i.UploadState,
			&i.UploadTokenDigest,
			&i.UploadExpiresAt,
			&i.UploadedAt,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScopeObjectAssets = `-- name: ListScopeObjectAssets :many
SELECT asset.id, asset.submission_id, asset.public_id, asset.object_key_ciphertext, asset.state, asset.encoded_bytes, asset.revision, asset.created_at, asset.removed_at, asset.client_image_id, asset.media_type, asset.declared_encoded_bytes, asset.pixel_width, asset.pixel_height, asset.source_sha256, asset.sanitized_sha256, asset.upload_state, asset.upload_token_digest, asset.upload_expires_at, asset.uploaded_at, asset.verified_at
FROM realqa_assets AS asset
JOIN realqa_submissions AS submission ON submission.id = asset.submission_id
WHERE submission.owner_kind = $1
  AND submission.owner_id = $2
FOR UPDATE OF asset
`

type ListScopeObjectAssetsParams struct {
	OwnerKind string
	OwnerID   pgtype.UUID
}

func (q *Queries) ListScopeObjectAssets(ctx context.Context, arg ListScopeObjectAssetsParams) ([]RealqaAsset, error) {
	rows, err := q.db.Query(ctx, listScopeObjectAssets, arg.OwnerKind, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RealqaAsset{}
	for rows.Next() {
		var i RealqaAsset
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.PublicID,
			&i.ObjectKeyCiphertext,
			&i.State,
			&i.EncodedBytes,
			&i.Revision,
			&i.CreatedAt,
			&i.RemovedAt,
			&i.ClientImageID,
			&i.MediaType,
			&i.DeclaredEncodedBytes,
			&i.PixelWidth,
			&i.PixelHeight,
			&i.SourceSha256,
			&i.SanitizedSha256,
			&i.UploadState,
			&i.UploadTokenDigest,
			&i.UploadExpiresAt,
			&i.UploadedAt,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionAssets = `-- name: ListSubmissionAssets :many
SELECT id, submission_id, public_id, object_key_ciphertext, state, encoded_bytes, revision, created_at, removed_at, client_image_id, media_type, declared_encoded_bytes, pixel_width, pixel_height, source_sha256, sanitized_sha256, upload_state, upload_token_digest, upload_expires_at, uploaded_at, verified_at
FROM realqa_assets
WHERE submission_id = $1
ORDER BY id
`

func (q *Queries) ListSubmissionAssets(ctx context.Context, submissionID pgtype.UUID) ([]RealqaAsset, error) {
	rows, err := q.db.Query(ctx, listSubmissionAssets, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RealqaAsset{}
	for rows.Next() {
		var i RealqaAsset
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.PublicID,
			&i.ObjectKeyCiphertext,
			&i.State,
			&i.EncodedBytes,
			&i.Revision,
			&i.CreatedAt,
			&i.RemovedAt,
			&i.ClientImageID,
			&i.MediaType,
			&i.DeclaredEncodedBytes,
			&i.PixelWidth,
			&i.PixelHeight,
			&i.SourceSha256,
			&i.SanitizedSha256,
			&i.UploadState,
			&i.UploadTokenDigest,
			&i.UploadExpiresAt,
			&i.UploadedAt,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionRecords = `-- name: ListSubmissionRecords :many
SELECT submission.id, submission.owner_kind, submission.owner_id, submission.created_by_account_id, submission.preset_id, submission.destination_id, submission.state, submission.provider_issue_id, submission.provider_issue_url, submission.idempotency_digest, submission.revision, submission.created_at, submission.updated_at, submission.submitted_at, submission.payer_organization_id, submission.payer_team_id, submission.preset_revision, submission.declared_encoded_bytes, submission.verified_encoded_bytes, submission.upload_deadline, submission.upload_expires_at
FROM realqa_submissions AS submission
WHERE submission.owner_kind = $1
  AND submission.owner_id = $2
  AND submission.id > $3
  AND submission.submitted_at IS NOT NULL
  AND submission.state IN (
      'submitted', 'storage_billing_grace', 'assets_deleted'
  )
  AND (
      submission.created_by_account_id = $4
      OR EXISTS (
          SELECT 1
          FROM realqa_destinations AS destination
          JOIN realqa_github_installations AS installation
            ON installation.id = destination.installation_id
           AND installation.owner_kind = submission.owner_kind
           AND installation.owner_id = submission.owner_id
          JOIN realqa_github_connections AS connection
            ON connection.id = installation.connection_id
           AND connection.state = 'connected'
          JOIN realqa_repository_access AS access
            ON access.installation_id = destination.installation_id
           AND access.account_id = $4
           AND access.repository_id = destination.repository_id
           AND access.issues_enabled
           AND access.can_submit
           AND access.checked_at >=
               statement_timestamp() - interval '5 minutes'
          WHERE destination.id = submission.destination_id
            AND destination.owner_kind = submission.owner_kind
            AND destination.owner_id = submission.owner_id
      )
  )
ORDER BY submission.id
LIMIT $5
`

type ListSubmissionRecordsParams struct {
	OwnerKind string
	OwnerID   pgtype.UUID
	AfterID   pgtype.UUID
	AccountID pgtype.UUID
	PageLimit int32
}

func (q *Queries) ListSubmissionRecords(ctx context.Context, arg ListSubmissionRecordsParams) ([]RealqaSubmission, error) {
	rows, err := q.db.Query(ctx, listSubmissionRecords,
		arg.OwnerKind,
		arg.OwnerID,
		arg.AfterID,
		arg.AccountID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RealqaSubmission{}
	for rows.Next() {
		var i RealqaSubmission
		if err := rows.Scan(
			&i.ID,
			&i.OwnerKind,
			&i.OwnerID,
			&i.CreatedByAccountID,
			&i.PresetID,
			&i.DestinationID,
			&i.State,
			&i.ProviderIssueID,
			&i.ProviderIssueUrl,
			&i.IdempotencyDigest,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubmittedAt,
			&i.PayerOrganizationID,
			&i.PayerTeamID,
			&i.PresetRevision,
			&i.DeclaredEncodedBytes,
			&i.VerifiedEncodedBytes,
			&i.UploadDeadline,
			&i.UploadExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAssetRecord = `-- name: LockAssetRecord :one
SELECT id, submission_id, public_id, object_key_ciphertext, state, encoded_bytes, revision, created_at, removed_at, client_image_id, media_type, declared_encoded_bytes, pixel_width, pixel_height, source_sha256, sanitized_sha256, upload_state, upload_token_digest, upload_expires_at, uploaded_at, verified_at
FROM realqa_assets
WHERE id = $1
  AND submission_id = $2
FOR UPDATE
`

type LockAssetRecordParams struct {
	ID           pgtype.UUID
	SubmissionID pgtype.UUID
}

func (q *Queries) LockAssetRecord(ctx context.Context, arg LockAssetRecordParams) (RealqaAsset, error) {
	row := q.db.QueryRow(ctx, lockAssetRecord, arg.ID, arg.SubmissionID)
	var i RealqaAsset
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.PublicID,
		&i.ObjectKeyCiphertext,
		&i.State,
		&i.EncodedBytes,
		&i.Revision,
		&i.CreatedAt,
		&i.RemovedAt,
		&i.ClientImageID,
		&i.MediaType,
		&i.DeclaredEncodedBytes,
		&i.PixelWidth,
		&i.PixelHeight,
		&i.SourceSha256,
		&i.SanitizedSha256,
		&i.UploadState,
		&i.UploadTokenDigest,
		&i.UploadExpiresAt,
		&i.UploadedAt,
		&i.VerifiedAt,
	)
	return i, err
}

const lockExpiredSubmissionAsset = `-- name: LockExpiredSubmissionAsset :one
SELECT asset.id, asset.submission_id, asset.public_id, asset.object_key_ciphertext, asset.state, asset.encoded_bytes, asset.revision, asset.created_at, asset.removed_at, asset.client_image_id, asset.media_type, asset.declared_encoded_bytes, asset.pixel_width, asset.pixel_height, asset.source_sha256, asset.sanitized_sha256, asset.upload_state, asset.upload_token_digest, asset.upload_expires_at, asset.uploaded_at, asset.verified_at
FROM realqa_assets AS asset
JOIN realqa_submissions AS submission ON submission.id = asset.submission_id
WHERE asset.id = $1
  AND asset.submission_id = $2
  AND submission.upload_expires_at <= $3
  AND (
    asset.state IN ('private_staging', 'verified_unlinked')
    OR (
      asset.state = 'public_retained'
      AND submission.submitted_at IS NULL
    )
  )
FOR UPDATE OF asset
`

type LockExpiredSubmissionAssetParams struct {
	ID           pgtype.UUID
	SubmissionID pgtype.UUID
	Cutoff       pgtype.Timestamptz
}

func (q *Queries) LockExpiredSubmissionAsset(ctx context.Context, arg LockExpiredSubmissionAssetParams) (RealqaAsset, error) {
	row := q.db.QueryRow(ctx, lockExpiredSubmissionAsset, arg.ID, arg.SubmissionID, arg.Cutoff)
	var i RealqaAsset
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.PublicID,
		&i.ObjectKeyCiphertext,
		&i.State,
		&i.EncodedBytes,
		&i.Revision,
		&i.CreatedAt,
		&i.RemovedAt,
		&i.ClientImageID,
		&i.MediaType,
		&i.DeclaredEncodedBytes,
		&i.PixelWidth,
		&i.PixelHeight,
		&i.SourceSha256,
		&i.SanitizedSha256,
		&i.UploadState,
		&i.UploadTokenDigest,
		&i.UploadExpiresAt,
		&i.UploadedAt,
		&i.VerifiedAt,
	)
	return i, err
}

const lockExpiredSubmissionRecord = `-- name: LockExpiredSubmissionRecord :one
SELECT id, owner_kind, owner_id, created_by_account_id, preset_id, destination_id, state, provider_issue_id, provider_issue_url, idempotency_digest, revision, created_at, updated_at, submitted_at, payer_organization_id, payer_team_id, preset_revision, declared_encoded_bytes, verified_encoded_bytes, upload_deadline, upload_expires_at
FROM realqa_submissions
WHERE id = $1
  AND upload_expires_at <= $2
FOR UPDATE
`

type LockExpiredSubmissionRecordParams struct {
	ID     pgtype.UUID
	Cutoff pgtype.Timestamptz
}

func (q *Queries) LockExpiredSubmissionRecord(ctx context.Context, arg LockExpiredSubmissionRecordParams) (RealqaSubmission, error) {
	row := q.db.QueryRow(ctx, lockExpiredSubmissionRecord, arg.ID, arg.Cutoff)
	var i RealqaSubmission
	err := row.Scan(
		&i.ID,
		&i.OwnerKind,
		&i.OwnerID,
		&i.CreatedByAccountID,
		&i.PresetID,
		&i.DestinationID,
		&i.State,
		&i.ProviderIssueID,
		&i.ProviderIssueUrl,
		&i.IdempotencyDigest,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.PayerOrganizationID,
		&i.PayerTeamID,
		&i.PresetRevision,
		&i.DeclaredEncodedBytes,
		&i.VerifiedEncodedBytes,
		&i.UploadDeadline,
		&i.UploadExpiresAt,
	)
	return i, err
}

const lockIssueSubmissionRecords = `-- name: LockIssueSubmissionRecords :many
SELECT submission.id, submission.owner_kind, submission.owner_id, submission.created_by_account_id, submission.preset_id, submission.destination_id, submission.state, submission.provider_issue_id, submission.provider_issue_url, submission.idempotency_digest, submission.revision, submission.created_at, submission.updated_at, submission.submitted_at, submission.payer_organization_id, submission.payer_team_id, submission.preset_revision, submission.declared_encoded_bytes, submission.verified_encoded_bytes, submission.upload_deadline, submission.upload_expires_at
FROM realqa_submissions AS submission
WHERE submission.provider_issue_id = $1
ORDER BY submission.id
FOR UPDATE
`

func (q *Queries) LockIssueSubmissionRecords(ctx context.Context, providerIssueID pgtype.Text) ([]RealqaSubmission, error) {
	rows, err := q.db.Query(ctx, lockIssueSubmissionRecords, providerIssueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RealqaSubmission{}
	for rows.Next() {
		var i RealqaSubmission
		if err := rows.Scan(
			&i.ID,
			&i.OwnerKind,
			&i.OwnerID,
			&i.CreatedByAccountID,
			&i.PresetID,
			&i.DestinationID,
			&i.State,
			&i.ProviderIssueID,
			&i.ProviderIssueUrl,
			&i.IdempotencyDigest,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubmittedAt,
			&i.PayerOrganizationID,
			&i.PayerTeamID,
			&i.PresetRevision,
			&i.DeclaredEncodedBytes,
			&i.VerifiedEncodedBytes,
			&i.UploadDeadline,
			&i.UploadExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockObjectDeletion = `-- name: LockObjectDeletion :one
SELECT asset_id, object_kind, public_id, attempt_count, next_attempt_at, last_attempted_at, created_at
FROM realqa_object_deletion_jobs
WHERE asset_id = $1
  AND object_kind = $2
  AND public_id IS NOT DISTINCT FROM $3
  AND next_attempt_at <= $4
FOR UPDATE
`

type LockObjectDeletionParams struct {
	AssetID    pgtype.UUID
	ObjectKind string
	PublicID   pgtype.Text
	Cutoff     pgtype.Timestamptz
}

func (q *Queries) LockObjectDeletion(ctx context.Context, arg LockObjectDeletionParams) (RealqaObjectDeletionJob, error) {
	row := q.db.QueryRow(ctx, lockObjectDeletion,
		arg.AssetID,
		arg.ObjectKind,
		arg.PublicID,
		arg.Cutoff,
	)
	var i RealqaObjectDeletionJob
	err := row.Scan(
		&i.AssetID,
		&i.ObjectKind,
		&i.PublicID,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastAttemptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const lockScopeSubmissionRecords = `-- name: LockScopeSubmissionRecords :many
SELECT submission.id
FROM realqa_submissions AS submission
WHERE submission.owner_kind = $1
  AND submission.owner_id = $2
ORDER BY submission.id
FOR UPDATE
`

type LockScopeSubmissionRecordsParams struct {
	OwnerKind string
	OwnerID   pgtype.UUID
}

func (q *Queries) LockScopeSubmissionRecords(ctx context.Context, arg LockScopeSubmissionRecordsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, lockScopeSubmissionRecords, arg.OwnerKind, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSubmissionRecord = `-- name: LockSubmissionRecord :one
SELECT id, owner_kind, owner_id, created_by_account_id, preset_id, destination_id, state, provider_issue_id, provider_issue_url, idempotency_digest, revision, created_at, updated_at, submitted_at, payer_organization_id, payer_team_id, preset_revision, declared_encoded_bytes, verified_encoded_bytes, upload_deadline, upload_expires_at
FROM realqa_submissions
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockSubmissionRecord(ctx context.Context, submissionRecordID pgtype.UUID) (RealqaSubmission, error) {
	row := q.db.QueryRow(ctx, lockSubmissionRecord, submissionRecordID)
	var i RealqaSubmission
	err := row.Scan(
		&i.ID,
		&i.OwnerKind,
		&i.OwnerID,
		&i.CreatedByAccountID,
		&i.PresetID,
		&i.DestinationID,
		&i.State,
		&i.ProviderIssueID,
		&i.ProviderIssueUrl,
		&i.IdempotencyDigest,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.PayerOrganizationID,
		&i.PayerTeamID,
		&i.PresetRevision,
		&i.DeclaredEncodedBytes,
		&i.VerifiedEncodedBytes,
		&i.UploadDeadline,
		&i.UploadExpiresAt,
	)
	return i, err
}

const lockUploadSessionAccount = `-- name: LockUploadSessionAccount :exec
SELECT pg_advisory_xact_lock(
    hashtextextended(
        'upload-session:' || $1::uuid::text,
        757
    )
)
`

func (q *Queries) LockUploadSessionAccount(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, lockUploadSessionAccount, accountID)
	return err
}

const markAssetRejected = `-- name: MarkAssetRejected :one
UPDATE realqa_assets
SET upload_state = 'rejected',
    revision = revision + 1
WHERE id = $1
  AND submission_id = $2
  AND upload_state IN ('uploaded', 'verifying')
RETURNING id, submission_id, public_id, object_key_ciphertext, state, encoded_bytes, revision, created_at, removed_at, client_image_id, media_type, declared_encoded_bytes, pixel_width, pixel_height, source_sha256, sanitized_sha256, upload_state, upload_token_digest, upload_expires_at, uploaded_at, verified_at
`

type MarkAssetRejectedParams struct {
	ID           pgtype.UUID
	SubmissionID pgtype.UUID
}

func (q *Queries) MarkAssetRejected(ctx context.Context, arg MarkAssetRejectedParams) (RealqaAsset, error) {
	row := q.db.QueryRow(ctx, markAssetRejected, arg.ID, arg.SubmissionID)
	var i RealqaAsset
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.PublicID,
		&i.ObjectKeyCiphertext,
		&i.State,
		&i.EncodedBytes,
		&i.Revision,
		&i.CreatedAt,
		&i.RemovedAt,
		&i.ClientImageID,
		&i.MediaType,
		&i.DeclaredEncodedBytes,
		&i.PixelWidth,
		&i.PixelHeight,
		&i.SourceSha256,
		&i.SanitizedSha256,
		&i.UploadState,
		&i.UploadTokenDigest,
		&i.UploadExpiresAt,
		&i.UploadedAt,
		&i.VerifiedAt,
	)
	return i, err
}

const markAssetUploaded = `-- name: MarkAssetUploaded :one
UPDATE realqa_assets
SET upload_state = 'uploaded',
    uploaded_at = transaction_timestamp()
WHERE id = $1
  AND submission_id = $2
  AND upload_token_digest = $3
  AND upload_state = 'put_authorized'
RETURNING id, submission_id, public_id, object_key_ciphertext, state, encoded_bytes, revision, created_at, removed_at, client_image_id, media_type, declared_encoded_bytes, pixel_width, pixel_height, source_sha256, sanitized_sha256, upload_state, upload_token_digest, upload_expires_at, uploaded_at, verified_at
`

type MarkAssetUploadedParams struct {
	ID                pgtype.UUID
	SubmissionID      pgtype.UUID
	UploadTokenDigest []byte
}

func (q *Queries) MarkAssetUploaded(ctx context.Context, arg MarkAssetUploadedParams) (RealqaAsset, error) {
	row := q.db.QueryRow(ctx, markAssetUploaded, arg.ID, arg.SubmissionID, arg.UploadTokenDigest)
	var i RealqaAsset
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.PublicID,
		&i.ObjectKeyCiphertext,
		&i.State,
		&i.EncodedBytes,
		&i.Revision,
		&i.CreatedAt,
		&i.RemovedAt,
		&i.ClientImageID,
		&i.MediaType,
		&i.DeclaredEncodedBytes,
		&i.PixelWidth,
		&i.PixelHeight,
		&i.SourceSha256,
		&i.SanitizedSha256,
		&i.UploadState,
		&i.UploadTokenDigest,
		&i.UploadExpiresAt,
		&i.UploadedAt,
		&i.VerifiedAt,
	)
	return i, err
}

const markAssetVerified = `-- name: MarkAssetVerified :one
UPDATE realqa_assets
SET upload_state = 'verified',
    state = 'verified_unlinked',
    encoded_bytes = $1,
    sanitized_sha256 = $2,
    verified_at = transaction_timestamp(),
    upload_token_digest = NULL,
    upload_expires_at = NULL,
    revision = revision + 1
WHERE id = $3
  AND submission_id = $4
  AND upload_state = 'verifying'
RETURNING id, submission_id, public_id, object_key_ciphertext, state, encoded_bytes, revision, created_at, removed_at, client_image_id, media_type, declared_encoded_bytes, pixel_width, pixel_height, source_sha256, sanitized_sha256, upload_state, upload_token_digest, upload_expires_at, uploaded_at, verified_at
`

type MarkAssetVerifiedParams struct {
	EncodedBytes    int64
	SanitizedSha256 []byte
	ID              pgtype.UUID
	SubmissionID    pgtype.UUID
}

func (q *Queries) MarkAssetVerified(ctx context.Context, arg MarkAssetVerifiedParams) (RealqaAsset, error) {
	row := q.db.QueryRow(ctx, markAssetVerified,
		arg.EncodedBytes,
		arg.SanitizedSha256,
		arg.ID,
		arg.SubmissionID,
	)
	var i RealqaAsset
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.PublicID,
		&i.ObjectKeyCiphertext,
		&i.State,
		&i.EncodedBytes,
		&i.Revision,
		&i.CreatedAt,
		&i.RemovedAt,
		&i.ClientImageID,
		&i.MediaType,
		&i.DeclaredEncodedBytes,
		&i.PixelWidth,
		&i.PixelHeight,
		&i.SourceSha256,
		&i.SanitizedSha256,
		&i.UploadState,
		&i.UploadTokenDigest,
		&i.UploadExpiresAt,
		&i.UploadedAt,
		&i.VerifiedAt,
	)
	return i, err
}

const markAssetVerifying = `-- name: MarkAssetVerifying :one
UPDATE realqa_assets
SET upload_state = 'verifying',
    revision = revision + 1
WHERE id = $1
  AND submission_id = $2
  AND revision = $3
  AND upload_state = 'uploaded'
RETURNING id, submission_id, public_id, object_key_ciphertext, state, encoded_bytes, revision, created_at, removed_at, client_image_id, media_type, declared_encoded_bytes, pixel_width, pixel_height, source_sha256, sanitized_sha256, upload_state, upload_token_digest, upload_expires_at, uploaded_at, verified_at
`

type MarkAssetVerifyingParams struct {
	ID               pgtype.UUID
	SubmissionID     pgtype.UUID
	ExpectedRevision int64
}

func (q *Queries) MarkAssetVerifying(ctx context.Context, arg MarkAssetVerifyingParams) (RealqaAsset, error) {
	row := q.db.QueryRow(ctx, markAssetVerifying, arg.ID, arg.SubmissionID, arg.ExpectedRevision)
	var i RealqaAsset
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.PublicID,
		&i.ObjectKeyCiphertext,
		&i.State,
		&i.EncodedBytes,
		&i.Revision,
		&i.CreatedAt,
		&i.RemovedAt,
		&i.ClientImageID,
		&i.MediaType,
		&i.DeclaredEncodedBytes,
		&i.PixelWidth,
		&i.PixelHeight,
		&i.SourceSha256,
		&i.SanitizedSha256,
		&i.UploadState,
		&i.UploadTokenDigest,
		&i.UploadExpiresAt,
		&i.UploadedAt,
		&i.VerifiedAt,
	)
	return i, err
}

const markSubmissionAssetsDeleted = `-- name: MarkSubmissionAssetsDeleted :one
UPDATE realqa_submissions
SET state = 'assets_deleted',
    verified_encoded_bytes = 0,
    revision = revision + 1,
    updated_at = transaction_timestamp()
WHERE id = $1
  AND revision = $2
RETURNING id, owner_kind, owner_id, created_by_account_id, preset_id, destination_id, state, provider_issue_id, provider_issue_url, idempotency_digest, revision, created_at, updated_at, submitted_at, payer_organization_id, payer_team_id, preset_revision, declared_encoded_bytes, verified_encoded_bytes, upload_deadline, upload_expires_at
`

type MarkSubmissionAssetsDeletedParams struct {
	ID               pgtype.UUID
	ExpectedRevision int64
}

func (q *Queries) MarkSubmissionAssetsDeleted(ctx context.Context, arg MarkSubmissionAssetsDeletedParams) (RealqaSubmission, error) {
	row := q.db.QueryRow(ctx, markSubmissionAssetsDeleted, arg.ID, arg.ExpectedRevision)
	var i RealqaSubmission
	err := row.Scan(
		&i.ID,
		&i.OwnerKind,
		&i.OwnerID,
		&i.CreatedByAccountID,
		&i.PresetID,
		&i.DestinationID,
		&i.State,
		&i.ProviderIssueID,
		&i.ProviderIssueUrl,
		&i.IdempotencyDigest,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.PayerOrganizationID,
		&i.PayerTeamID,
		&i.PresetRevision,
		&i.DeclaredEncodedBytes,
		&i.VerifiedEncodedBytes,
		&i.UploadDeadline,
		&i.UploadExpiresAt,
	)
	return i, err
}

const markSubmissionSubmitted = `-- name: MarkSubmissionSubmitted :one
UPDATE realqa_submissions
SET state = 'submitted',
    submitted_at = COALESCE(submitted_at, transaction_timestamp()),
    updated_at = transaction_timestamp(),
    revision = revision + 1
WHERE id = $1
  AND state IN ('ready', 'submitting', 'reconciling')
RETURNING id, owner_kind, owner_id, created_by_account_id, preset_id, destination_id, state, provider_issue_id, provider_issue_url, idempotency_digest, revision, created_at, updated_at, submitted_at, payer_organization_id, payer_team_id, preset_revision, declared_encoded_bytes, verified_encoded_bytes, upload_deadline, upload_expires_at
`

func (q *Queries) MarkSubmissionSubmitted(ctx context.Context, id pgtype.UUID) (RealqaSubmission, error) {
	row := q.db.QueryRow(ctx, markSubmissionSubmitted, id)
	var i RealqaSubmission
	err := row.Scan(
		&i.ID,
		&i.OwnerKind,
		&i.OwnerID,
		&i.CreatedByAccountID,
		&i.PresetID,
		&i.DestinationID,
		&i.State,
		&i.ProviderIssueID,
		&i.ProviderIssueUrl,
		&i.IdempotencyDigest,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.PayerOrganizationID,
		&i.PayerTeamID,
		&i.PresetRevision,
		&i.DeclaredEncodedBytes,
		&i.VerifiedEncodedBytes,
		&i.UploadDeadline,
		&i.UploadExpiresAt,
	)
	return i, err
}

const promoteAsset = `-- name: PromoteAsset :one
UPDATE realqa_assets
SET public_id = $1,
    state = 'public_retained',
    revision = revision + 1
WHERE id = $2
  AND submission_id = $3
  AND upload_state = 'verified'
  AND state = 'verified_unlinked'
RETURNING id, submission_id, public_id, object_key_ciphertext, state, encoded_bytes, revision, created_at, removed_at, client_image_id, media_type, declared_encoded_bytes, pixel_width, pixel_height, source_sha256, sanitized_sha256, upload_state, upload_token_digest, upload_expires_at, uploaded_at, verified_at
`

type PromoteAssetParams struct {
	PublicID     pgtype.Text
	ID           pgtype.UUID
	SubmissionID pgtype.UUID
}

func (q *Queries) PromoteAsset(ctx context.Context, arg PromoteAssetParams) (RealqaAsset, error) {
	row := q.db.QueryRow(ctx, promoteAsset, arg.PublicID, arg.ID, arg.SubmissionID)
	var i RealqaAsset
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.PublicID,
		&i.ObjectKeyCiphertext,
		&i.State,
		&i.EncodedBytes,
		&i.Revision,
		&i.CreatedAt,
		&i.RemovedAt,
		&i.ClientImageID,
		&i.MediaType,
		&i.DeclaredEncodedBytes,
		&i.PixelWidth,
		&i.PixelHeight,
		&i.SourceSha256,
		&i.SanitizedSha256,
		&i.UploadState,
		&i.UploadTokenDigest,
		&i.UploadExpiresAt,
		&i.UploadedAt,
		&i.VerifiedAt,
	)
	return i, err
}

const refreshSubmissionAssetState = `-- name: RefreshSubmissionAssetState :one
UPDATE realqa_submissions AS submission
SET verified_encoded_bytes = (
        SELECT COALESCE(sum(encoded_bytes), 0)::bigint
        FROM realqa_assets
        WHERE submission_id = submission.id
          AND upload_state = 'verified'
          AND state IN ('verified_unlinked', 'public_retained')
    ),
    state = CASE
        WHEN NOT EXISTS (
                 SELECT 1 FROM realqa_assets
                 WHERE submission_id = submission.id
                   AND upload_state NOT IN (
                       'rejected', 'expired', 'deleted'
                   )
             ) THEN 'assets_deleted'
        WHEN EXISTS (
                 SELECT 1 FROM realqa_assets
                 WHERE submission_id = submission.id
                   AND upload_state = 'verified'
             )
             AND NOT EXISTS (
                 SELECT 1 FROM realqa_assets
                 WHERE submission_id = submission.id
                   AND upload_state NOT IN (
                       'verified', 'rejected', 'expired', 'deleted'
                   )
             ) THEN 'ready'
        ELSE 'uploading'
    END,
    revision = revision + 1,
    updated_at = transaction_timestamp()
WHERE submission.id = $1
  AND submission.state IN ('draft', 'uploading', 'ready')
RETURNING id, owner_kind, owner_id, created_by_account_id, preset_id, destination_id, state, provider_issue_id, provider_issue_url, idempotency_digest, revision, created_at, updated_at, submitted_at, payer_organization_id, payer_team_id, preset_revision, declared_encoded_bytes, verified_encoded_bytes, upload_deadline, upload_expires_at
`

func (q *Queries) RefreshSubmissionAssetState(ctx context.Context, id pgtype.UUID) (RealqaSubmission, error) {
	row := q.db.QueryRow(ctx, refreshSubmissionAssetState, id)
	var i RealqaSubmission
	err := row.Scan(
		&i.ID,
		&i.OwnerKind,
		&i.OwnerID,
		&i.CreatedByAccountID,
		&i.PresetID,
		&i.DestinationID,
		&i.State,
		&i.ProviderIssueID,
		&i.ProviderIssueUrl,
		&i.IdempotencyDigest,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.PayerOrganizationID,
		&i.PayerTeamID,
		&i.PresetRevision,
		&i.DeclaredEncodedBytes,
		&i.VerifiedEncodedBytes,
		&i.UploadDeadline,
		&i.UploadExpiresAt,
	)
	return i, err
}

const reserveAssetPublicID = `-- name: ReserveAssetPublicID :one
UPDATE realqa_assets
SET public_id = COALESCE(public_id, $1)
WHERE id = $2
  AND submission_id = $3
  AND upload_state = 'verified'
  AND state = 'verified_unlinked'
RETURNING id, submission_id, public_id, object_key_ciphertext, state, encoded_bytes, revision, created_at, removed_at, client_image_id, media_type, declared_encoded_bytes, pixel_width, pixel_height, source_sha256, sanitized_sha256, upload_state, upload_token_digest, upload_expires_at, uploaded_at, verified_at
`

type ReserveAssetPublicIDParams struct {
	PublicID     pgtype.Text
	ID           pgtype.UUID
	SubmissionID pgtype.UUID
}

func (q *Queries) ReserveAssetPublicID(ctx context.Context, arg ReserveAssetPublicIDParams) (RealqaAsset, error) {
	row := q.db.QueryRow(ctx, reserveAssetPublicID, arg.PublicID, arg.ID, arg.SubmissionID)
	var i RealqaAsset
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.PublicID,
		&i.ObjectKeyCiphertext,
		&i.State,
		&i.EncodedBytes,
		&i.Revision,
		&i.CreatedAt,
		&i.RemovedAt,
		&i.ClientImageID,
		&i.MediaType,
		&i.DeclaredEncodedBytes,
		&i.PixelWidth,
		&i.PixelHeight,
		&i.SourceSha256,
		&i.SanitizedSha256,
		&i.UploadState,
		&i.UploadTokenDigest,
		&i.UploadExpiresAt,
		&i.UploadedAt,
		&i.VerifiedAt,
	)
	return i, err
}

const retryObjectDeletion = `-- name: RetryObjectDeletion :exec
UPDATE realqa_object_deletion_jobs
SET attempt_count = attempt_count + 1,
    last_attempted_at = transaction_timestamp(),
    next_attempt_at = transaction_timestamp() + interval '5 minutes'
WHERE asset_id = $1
  AND object_kind = $2
  AND public_id IS NOT DISTINCT FROM $3
`

type RetryObjectDeletionParams struct {
	AssetID    pgtype.UUID
	ObjectKind string
	PublicID   pgtype.Text
}

func (q *Queries) RetryObjectDeletion(ctx context.Context, arg RetryObjectDeletionParams) error {
	_, err := q.db.Exec(ctx, retryObjectDeletion, arg.AssetID, arg.ObjectKind, arg.PublicID)
	return err
}

const sumOtherVerifiedAssetBytes = `-- name: SumOtherVerifiedAssetBytes :one
SELECT COALESCE(sum(encoded_bytes), 0)::bigint
FROM realqa_assets
WHERE submission_id = $1
  AND id <> $2
  AND upload_state = 'verified'
  AND state IN ('verified_unlinked', 'public_retained')
`

type SumOtherVerifiedAssetBytesParams struct {
	SubmissionID pgtype.UUID
	AssetID      pgtype.UUID
}

func (q *Queries) SumOtherVerifiedAssetBytes(ctx context.Context, arg SumOtherVerifiedAssetBytesParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumOtherVerifiedAssetBytes, arg.SubmissionID, arg.AssetID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const tombstoneAsset = `-- name: TombstoneAsset :one
WITH selected AS (
    SELECT selected_asset.public_id
    FROM realqa_assets AS selected_asset
    WHERE selected_asset.id = $1
      AND selected_asset.submission_id = $2
      AND selected_asset.revision = $3
      AND selected_asset.state NOT IN (
          'removed_placeholder', 'deleted', 'expired'
      )
    FOR UPDATE
), tombstone AS (
    INSERT INTO realqa_public_asset_tombstones (public_id)
    SELECT public_id FROM selected WHERE public_id IS NOT NULL
    ON CONFLICT (public_id) DO NOTHING
)
UPDATE realqa_assets AS asset
SET upload_state = 'deleted',
    state = CASE
        WHEN asset.public_id IS NULL THEN 'deleted'
        ELSE 'removed_placeholder'
    END,
    removed_at = COALESCE(asset.removed_at, transaction_timestamp()),
    revision = asset.revision + 1
WHERE asset.id = $1
  AND asset.submission_id = $2
  AND asset.revision = $3
  AND asset.state NOT IN ('removed_placeholder', 'deleted', 'expired')
RETURNING asset.id, asset.submission_id, asset.public_id, asset.object_key_ciphertext, asset.state, asset.encoded_bytes, asset.revision, asset.created_at, asset.removed_at, asset.client_image_id, asset.media_type, asset.declared_encoded_bytes, asset.pixel_width, asset.pixel_height, asset.source_sha256, asset.sanitized_sha256, asset.upload_state, asset.upload_token_digest, asset.upload_expires_at, asset.uploaded_at, asset.verified_at
`

type TombstoneAssetParams struct {
	AssetRecordID     pgtype.UUID
	AssetSubmissionID pgtype.UUID
	ExpectedRevision  int64
}

func (q *Queries) TombstoneAsset(ctx context.Context, arg TombstoneAssetParams) (RealqaAsset, error) {
	row := q.db.QueryRow(ctx, tombstoneAsset, arg.AssetRecordID, arg.AssetSubmissionID, arg.ExpectedRevision)
	var i RealqaAsset
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.PublicID,
		&i.ObjectKeyCiphertext,
		&i.State,
		&i.EncodedBytes,
		&i.Revision,
		&i.CreatedAt,
		&i.RemovedAt,
		&i.ClientImageID,
		&i.MediaType,
		&i.DeclaredEncodedBytes,
		&i.PixelWidth,
		&i.PixelHeight,
		&i.SourceSha256,
		&i.SanitizedSha256,
		&i.UploadState,
		&i.UploadTokenDigest,
		&i.UploadExpiresAt,
		&i.UploadedAt,
		&i.VerifiedAt,
	)
	return i, err
}

const tombstoneScopePublicAssets = `-- name: TombstoneScopePublicAssets :exec
INSERT INTO realqa_public_asset_tombstones (public_id)
SELECT asset.public_id
FROM realqa_assets AS asset
JOIN realqa_submissions AS submission ON submission.id = asset.submission_id
WHERE submission.owner_kind = $1
  AND submission.owner_id = $2
  AND asset.public_id IS NOT NULL
ON CONFLICT (public_id) DO NOTHING
`

type TombstoneScopePublicAssetsParams struct {
	OwnerKind string
	OwnerID   pgtype.UUID
}

func (q *Queries) TombstoneScopePublicAssets(ctx context.Context, arg TombstoneScopePublicAssetsParams) error {
	_, err := q.db.Exec(ctx, tombstoneScopePublicAssets, arg.OwnerKind, arg.OwnerID)
	return err
}

const tombstoneSubmissionAssets = `-- name: TombstoneSubmissionAssets :many
WITH selected AS (
    SELECT selected_asset.id, selected_asset.public_id
    FROM realqa_assets AS selected_asset
    WHERE selected_asset.submission_id = $1
      AND selected_asset.state NOT IN ('removed_placeholder', 'deleted', 'expired')
    FOR UPDATE
), tombstones AS (
    INSERT INTO realqa_public_asset_tombstones (public_id)
    SELECT public_id FROM selected WHERE public_id IS NOT NULL
    ON CONFLICT (public_id) DO NOTHING
)
UPDATE realqa_assets AS asset
SET upload_state = 'deleted',
    state = CASE
        WHEN asset.public_id IS NULL THEN 'deleted'
        ELSE 'removed_placeholder'
    END,
    removed_at = COALESCE(asset.removed_at, transaction_timestamp()),
    revision = asset.revision + 1
FROM selected
WHERE asset.id = selected.id
RETURNING asset.id, asset.submission_id, asset.public_id, asset.object_key_ciphertext, asset.state, asset.encoded_bytes, asset.revision, asset.created_at, asset.removed_at, asset.client_image_id, asset.media_type, asset.declared_encoded_bytes, asset.pixel_width, asset.pixel_height, asset.source_sha256, asset.sanitized_sha256, asset.upload_state, asset.upload_token_digest, asset.upload_expires_at, asset.uploaded_at, asset.verified_at
`

func (q *Queries) TombstoneSubmissionAssets(ctx context.Context, assetSubmissionID pgtype.UUID) ([]RealqaAsset, error) {
	rows, err := q.db.Query(ctx, tombstoneSubmissionAssets, assetSubmissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RealqaAsset{}
	for rows.Next() {
		var i RealqaAsset
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.PublicID,
			&i.ObjectKeyCiphertext,
			&i.State,
			&i.EncodedBytes,
			&i.Revision,
			&i.CreatedAt,
			&i.RemovedAt,
			&i.ClientImageID,
			&i.MediaType,
			&i.DeclaredEncodedBytes,
			&i.PixelWidth,
			&i.PixelHeight,
			&i.SourceSha256,
			&i.SanitizedSha256,
			&i.UploadState,
			&i.UploadTokenDigest,
			&i.UploadExpiresAt,
			&i.UploadedAt,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchSubmissionAfterAssetDeletion = `-- name: TouchSubmissionAfterAssetDeletion :one
UPDATE realqa_submissions AS submission
SET verified_encoded_bytes = (
        SELECT COALESCE(sum(encoded_bytes), 0)::bigint
        FROM realqa_assets
        WHERE submission_id = submission.id
          AND upload_state = 'verified'
          AND state IN ('verified_unlinked', 'public_retained')
    ),
    state = CASE
        WHEN submission.state IN ('draft', 'uploading', 'ready')
             AND NOT EXISTS (
                 SELECT 1 FROM realqa_assets
                 WHERE submission_id = submission.id
                   AND upload_state NOT IN (
                       'rejected', 'expired', 'deleted'
                   )
             ) THEN 'assets_deleted'
        WHEN submission.state IN ('draft', 'uploading', 'ready')
             AND EXISTS (
                 SELECT 1 FROM realqa_assets
                 WHERE submission_id = submission.id
                   AND upload_state = 'verified'
             )
             AND NOT EXISTS (
                 SELECT 1 FROM realqa_assets
                 WHERE submission_id = submission.id
                   AND upload_state NOT IN (
                       'verified', 'rejected', 'expired', 'deleted'
                   )
             ) THEN 'ready'
        WHEN submission.state IN ('draft', 'uploading', 'ready')
            THEN 'uploading'
        ELSE submission.state
    END,
    revision = revision + 1,
    updated_at = transaction_timestamp()
WHERE submission.id = $1
  AND submission.revision = $2
RETURNING id, owner_kind, owner_id, created_by_account_id, preset_id, destination_id, state, provider_issue_id, provider_issue_url, idempotency_digest, revision, created_at, updated_at, submitted_at, payer_organization_id, payer_team_id, preset_revision, declared_encoded_bytes, verified_encoded_bytes, upload_deadline, upload_expires_at
`

type TouchSubmissionAfterAssetDeletionParams struct {
	ID               pgtype.UUID
	ExpectedRevision int64
}

func (q *Queries) TouchSubmissionAfterAssetDeletion(ctx context.Context, arg TouchSubmissionAfterAssetDeletionParams) (RealqaSubmission, error) {
	row := q.db.QueryRow(ctx, touchSubmissionAfterAssetDeletion, arg.ID, arg.ExpectedRevision)
	var i RealqaSubmission
	err := row.Scan(
		&i.ID,
		&i.OwnerKind,
		&i.OwnerID,
		&i.CreatedByAccountID,
		&i.PresetID,
		&i.DestinationID,
		&i.State,
		&i.ProviderIssueID,
		&i.ProviderIssueUrl,
		&i.IdempotencyDigest,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.PayerOrganizationID,
		&i.PayerTeamID,
		&i.PresetRevision,
		&i.DeclaredEncodedBytes,
		&i.VerifiedEncodedBytes,
		&i.UploadDeadline,
		&i.UploadExpiresAt,
	)
	return i, err
}

const updateSubmissionVerifiedBytes = `-- name: UpdateSubmissionVerifiedBytes :one
UPDATE realqa_submissions AS submission
SET verified_encoded_bytes = $1,
    state = CASE
        WHEN EXISTS (
            SELECT 1 FROM realqa_assets
            WHERE submission_id = submission.id
              AND upload_state = 'verified'
        ) AND NOT EXISTS (
            SELECT 1 FROM realqa_assets
            WHERE submission_id = submission.id
              AND upload_state NOT IN (
                  'verified', 'rejected', 'expired', 'deleted'
              )
        ) THEN 'ready'
        ELSE 'uploading'
    END,
    revision = revision + 1,
    updated_at = transaction_timestamp()
WHERE submission.id = $2
  AND submission.state IN ('draft', 'uploading', 'ready')
RETURNING id, owner_kind, owner_id, created_by_account_id, preset_id, destination_id, state, provider_issue_id, provider_issue_url, idempotency_digest, revision, created_at, updated_at, submitted_at, payer_organization_id, payer_team_id, preset_revision, declared_encoded_bytes, verified_encoded_bytes, upload_deadline, upload_expires_at
`

type UpdateSubmissionVerifiedBytesParams struct {
	VerifiedEncodedBytes int64
	SubmissionRecordID   pgtype.UUID
}

func (q *Queries) UpdateSubmissionVerifiedBytes(ctx context.Context, arg UpdateSubmissionVerifiedBytesParams) (RealqaSubmission, error) {
	row := q.db.QueryRow(ctx, updateSubmissionVerifiedBytes, arg.VerifiedEncodedBytes, arg.SubmissionRecordID)
	var i RealqaSubmission
	err := row.Scan(
		&i.ID,
		&i.OwnerKind,
		&i.OwnerID,
		&i.CreatedByAccountID,
		&i.PresetID,
		&i.DestinationID,
		&i.State,
		&i.ProviderIssueID,
		&i.ProviderIssueUrl,
		&i.IdempotencyDigest,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.PayerOrganizationID,
		&i.PayerTeamID,
		&i.PresetRevision,
		&i.DeclaredEncodedBytes,
		&i.VerifiedEncodedBytes,
		&i.UploadDeadline,
		&i.UploadExpiresAt,
	)
	return i, err
}
