// SPDX-License-Identifier: Apache-2.0
export const en = {
  stale:
    "The server state changed. Inspect the current original target before retrying.",
  outcome: "Outcome",
  dispatch: "Dispatch",
  recovery: "Recovery",
  "not-started": "Not started",
  running: "Running",
  succeeded: "Completed",
  failed: "Failed",
  stopped: "Stopped",
  none: "Not required",
  required: "Required",
  reconciling: "Reconciling",
  ready: "Ready",
  paused: "Paused",
  blocked: "Blocked",
  claimed: "Claimed",
  question: "Question",
  "approval-request": "Approval request",
  terminal: "Session outcome",

  serverNotifications: "This server’s notification categories",
  interactions: "Requests",
  terminals: "Session outcomes",
  pairingExpired:
    "The pairing code is expired or invalid. Keep the original pending identity until you explicitly forget this profile.",
  permissionDenied:
    "The server denied this action. Review its original session and account permissions.",
  recoveryRequired:
    "This session requires recovery in its original desktop client.",
  certificate: "The HTTPS certificate is invalid or untrusted.",
  sessions: "Sessions",
  inbox: "Inbox",
  settings: "Settings",
  profile: "Server profile",
  disconnected: "Not connected",
  live: "Connected",
  connecting: "Connecting",
  unavailable:
    "Connection unavailable. Check the server and its HTTPS certificate.",
  add: "Add server",
  name: "Profile name",
  origin: "HTTPS server origin",
  pairing: "Pairing code document",
  pair: "Pair",
  retryPair: "Retry original pairing",
  forget: "Forget on this device",
  revoke: "Revoke remote client",
  confirmForget:
    "Forget this profile and its protected requests on this device?",
  confirmRevoke: "Revoke this client on the selected server?",
  cancel: "Cancel",
  confirm: "Confirm",
  back: "Back",
  close: "Close",
  loading: "Loading…",
  refresh: "Refresh",
  more: "Load more",
  empty: "No items",
  newSession: "New session",
  project: "Project",
  all: "All projects",
  agent: "Agent",
  runner: "Runner",
  workspace: "Workspace",
  worktree: "Worktree",
  general: "General Chat",
  title: "Session name",
  prompt: "Message",
  send: "Send",
  steer: "Steer queued input",
  stop: "Stop",
  resume: "Resume",
  information: "Session information",
  state: "State",
  mode: "Input mode",
  execute: "Execute",
  plan: "Plan",
  pending:
    "The original request has an unresolved outcome. Inspect current server state before retrying the same request.",
  inspect: "Inspect original target",
  retry: "Retry the same request",
  inspected: "Current server state inspected",
  suspended: "Synchronization paused while the app is in the background.",
  error:
    "The operation could not be confirmed. Your original request is retained.",
  revoked: "This client is revoked. Pair a new profile explicitly.",
  version: "The selected server protocol is unsupported.",
  read: "Mark read",
  unread: "Mark unread",
  open: "Open original request",
  answer: "Answer",
  approval: "Approval",
  submit: "Submit response",
  allow: "Allow once",
  sessionAllow: "Allow for this session",
  decline: "Decline",
  leave: "Leave unanswered",
  custom: "Another answer",
  original: "Original request",
  closed: "This original request is closed or already answered.",
  secret: "Answer this protected question in its original desktop client.",
  unsupported: "This native request is not supported by this client version.",
  language: "Language",
  theme: "Theme",
  system: "System",
  light: "Light",
  dark: "Dark",
  notifications: "Foreground notifications",
  diagnostics: "Connection diagnostics",
  export: "Copy safe diagnostics",
  copied: "Safe diagnostics copied",
  safe: "Diagnostics contain only operation names and opaque correlation identifiers.",
  notificationNote:
    "OS submission is not proof that you saw a notification. Inbox read state is separate.",
  localNote:
    "Forgetting removes only this device’s profile. Remote sessions continue running.",
  noChoices:
    "No eligible saved choices. Configure projects, Agents and Runners in the desktop client.",
  inspectNote: "Inspecting never retries a request or resumes execution.",
  queue: "Queued messages",
  choose: "Choose",
  sessionGone: "The original session is unavailable.",
  stopConfirm: "Stop this remote session?",
  resumeConfirm:
    "Resume this remote session with its current saved selections?",
  selectProfile: "Select a paired server in Settings.",
  pairingNote:
    "Use the complete existing client pairing document from your server. The origin must match its HTTPS endpoint.",
  saved: "Saved",
  readOnly: "Read only",
  notificationDenied: "Notification permission is unavailable or denied.",
  requestTooLarge: "Keep input within the server’s 256 KiB text limit.",
  pairingInvalid: "The pairing document or HTTPS origin is invalid.",
  notificationPermission: "Allow foreground notifications",
  inboxOriginal: "Open the current original request before responding.",
  network: "Requested network access",
  permissions: "Permissions",
  turn: "This turn",
  requestScope: "Original native scope",
  revokeInspect: "Inspect client before revocation",
  identity: "Server identity",
  diagnosticFailure: "Diagnostics unavailable",
  confirmRetry: "Retry the exact protected original request?",
  pendingPair:
    "Original pairing is retained. Retry it without generating another credential.",
} as const;
export const ko: Record<keyof typeof en, string> = {
  stale:
    "서버 상태가 변경되었습니다. 재시도하기 전에 현재 원래 대상을 확인하세요.",
  outcome: "실행 결과",
  dispatch: "진행 상태",
  recovery: "복구",
  "not-started": "시작 전",
  running: "실행 중",
  succeeded: "완료",
  failed: "실패",
  stopped: "중지됨",
  none: "필요 없음",
  required: "필요함",
  reconciling: "확인 중",
  ready: "준비됨",
  paused: "일시 중지",
  blocked: "차단됨",
  claimed: "할당됨",
  question: "질문",
  "approval-request": "승인 요청",
  terminal: "세션 결과",

  serverNotifications: "이 서버의 알림 유형",
  interactions: "요청",
  terminals: "세션 결과",
  pairingExpired:
    "페어링 코드가 만료되었거나 유효하지 않습니다. 이 프로필을 명시적으로 삭제할 때까지 원래 요청을 유지합니다.",
  permissionDenied:
    "서버가 이 작업을 거부했습니다. 원래 세션과 계정 권한을 확인하세요.",
  recoveryRequired: "원래 데스크톱 클라이언트에서 이 세션을 복구해야 합니다.",
  certificate: "HTTPS 인증서가 유효하지 않거나 신뢰되지 않습니다.",
  sessions: "세션",
  inbox: "받은 편지함",
  settings: "설정",
  profile: "서버 프로필",
  disconnected: "연결 안 됨",
  live: "연결됨",
  connecting: "연결 중",
  unavailable: "연결할 수 없습니다. 서버와 HTTPS 인증서를 확인하세요.",
  add: "서버 추가",
  name: "프로필 이름",
  origin: "HTTPS 서버 주소",
  pairing: "페어링 코드 문서",
  pair: "페어링",
  retryPair: "원래 페어링 재시도",
  forget: "이 기기에서 삭제",
  revoke: "원격 클라이언트 해제",
  confirmForget: "이 기기에서 프로필과 보호된 요청을 삭제할까요?",
  confirmRevoke: "선택한 서버에서 이 클라이언트를 해제할까요?",
  cancel: "취소",
  confirm: "확인",
  back: "뒤로",
  close: "닫기",
  loading: "불러오는 중…",
  refresh: "새로 고침",
  more: "더 불러오기",
  empty: "항목 없음",
  newSession: "새 세션",
  project: "프로젝트",
  all: "모든 프로젝트",
  agent: "Agent",
  runner: "Runner",
  workspace: "작업 공간",
  worktree: "Worktree",
  general: "일반 채팅",
  title: "세션 이름",
  prompt: "메시지",
  send: "보내기",
  steer: "대기 입력으로 방향 조정",
  stop: "중지",
  resume: "재개",
  information: "세션 정보",
  state: "상태",
  mode: "입력 모드",
  execute: "실행",
  plan: "계획",
  pending:
    "원래 요청의 결과가 확인되지 않았습니다. 같은 요청을 재시도하기 전에 현재 서버 상태를 확인하세요.",
  inspect: "원래 대상 확인",
  retry: "같은 요청 재시도",
  inspected: "현재 서버 상태 확인됨",
  suspended: "앱이 백그라운드에 있는 동안 동기화가 일시 중지됩니다.",
  error: "작업 결과를 확인할 수 없습니다. 원래 요청은 유지됩니다.",
  revoked:
    "이 클라이언트가 해제되었습니다. 새 프로필을 명시적으로 페어링하세요.",
  version: "선택한 서버 프로토콜이 지원되지 않습니다.",
  read: "읽음으로 표시",
  unread: "읽지 않음으로 표시",
  open: "원래 요청 열기",
  answer: "답변",
  approval: "승인",
  submit: "응답 제출",
  allow: "한 번 허용",
  sessionAllow: "이 세션에서 허용",
  decline: "거부",
  leave: "답변하지 않기",
  custom: "다른 답변",
  original: "원래 요청",
  closed: "원래 요청이 닫혔거나 이미 응답되었습니다.",
  secret: "보호된 질문은 원래 데스크톱 클라이언트에서 답변하세요.",
  unsupported: "이 클라이언트 버전에서 지원하지 않는 네이티브 요청입니다.",
  language: "언어",
  theme: "테마",
  system: "시스템",
  light: "밝게",
  dark: "어둡게",
  notifications: "포그라운드 알림",
  diagnostics: "연결 진단",
  export: "안전한 진단 복사",
  copied: "안전한 진단 복사됨",
  safe: "진단에는 작업 이름과 불투명한 상관 식별자만 포함됩니다.",
  notificationNote:
    "OS에 제출되었다고 알림을 보았다는 뜻은 아닙니다. 받은 편지함 읽음 상태는 별개입니다.",
  localNote:
    "삭제는 이 기기의 프로필만 제거합니다. 원격 세션은 계속 실행됩니다.",
  noChoices:
    "사용 가능한 저장된 항목이 없습니다. 데스크톱에서 프로젝트, Agent, Runner를 설정하세요.",
  inspectNote: "확인은 요청을 재시도하거나 실행을 재개하지 않습니다.",
  queue: "대기 메시지",
  choose: "선택",
  sessionGone: "원래 세션을 사용할 수 없습니다.",
  stopConfirm: "원격 세션을 중지할까요?",
  resumeConfirm: "현재 저장된 선택으로 원격 세션을 재개할까요?",
  selectProfile: "설정에서 페어링된 서버를 선택하세요.",
  pairingNote:
    "서버에서 받은 클라이언트 페어링 문서 전체를 사용하세요. 주소는 HTTPS 엔드포인트와 일치해야 합니다.",
  saved: "저장됨",
  readOnly: "읽기 전용",
  notificationDenied: "알림 권한이 없거나 거부되었습니다.",
  requestTooLarge: "서버의 텍스트 제한인 256 KiB 이내로 입력하세요.",
  pairingInvalid: "페어링 문서 또는 HTTPS 주소가 올바르지 않습니다.",
  notificationPermission: "포그라운드 알림 허용",
  inboxOriginal: "응답하기 전에 현재 원래 요청을 열어 확인하세요.",
  network: "요청된 네트워크 접근",
  permissions: "권한",
  turn: "이번 턴",
  requestScope: "원래 네이티브 범위",
  revokeInspect: "해제 전에 클라이언트 확인",
  identity: "서버 식별자",
  diagnosticFailure: "진단 사용 불가",
  confirmRetry: "보호된 원래 요청을 정확히 재시도할까요?",
  pendingPair:
    "원래 페어링을 유지합니다. 새 자격 증명을 만들지 않고 재시도하세요.",
};
export type Copy = typeof en;
export type Labels = Record<keyof Copy, string>;
